import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

test('invitation-code entry source covers validation states before onboarding handoff', () => {
  const codeEntrySource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/invitation-code-entry-view.js'), 'utf8')
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')

  assert.match(codeEntrySource, /const INVITATION_CODE_LENGTH = 6/)
  assert.match(codeEntrySource, /const INVITATION_CODE_VALIDATION_STATES = Object\.freeze\(\{[\s\S]*EMPTY: 'empty',[\s\S]*INCOMPLETE: 'incomplete',[\s\S]*READY: 'ready',[\s\S]*SUBMITTING: 'submitting',[\s\S]*ERROR: 'error',[\s\S]*\}\)/)
  assert.match(codeEntrySource, /function getInvitationCodeValidationState\(\{ code = '', errorMessage = '', isSubmitting = false \} = \{\}\) \{[\s\S]*if \(isSubmitting\) \{[\s\S]*return INVITATION_CODE_VALIDATION_STATES\.SUBMITTING[\s\S]*\}[\s\S]*if \(errorMessage\) \{[\s\S]*return INVITATION_CODE_VALIDATION_STATES\.ERROR[\s\S]*\}[\s\S]*if \(!normalizedCode\.length\) \{[\s\S]*return INVITATION_CODE_VALIDATION_STATES\.EMPTY[\s\S]*\}[\s\S]*if \(normalizedCode\.length < INVITATION_CODE_LENGTH\) \{[\s\S]*return INVITATION_CODE_VALIDATION_STATES\.INCOMPLETE[\s\S]*\}[\s\S]*return INVITATION_CODE_VALIDATION_STATES\.READY[\s\S]*\}/)
  assert.match(codeEntrySource, /const validationState = getInvitationCodeValidationState\(\{ code: normalizedCode, errorMessage, isSubmitting \}\)/)
  assert.match(codeEntrySource, /const isCodeReady = validationState === INVITATION_CODE_VALIDATION_STATES\.READY/)
  assert.match(codeEntrySource, /const shouldShowValidationError = validationState === INVITATION_CODE_VALIDATION_STATES\.ERROR/)
  assert.match(codeEntrySource, /maxLength=\{INVITATION_CODE_LENGTH\}/)
  assert.match(codeEntrySource, /disabled=\{validationState !== INVITATION_CODE_VALIDATION_STATES\.READY\}/)
  assert.match(codeEntrySource, /label=\{validationState === INVITATION_CODE_VALIDATION_STATES\.SUBMITTING \? 'Checking code\.\.\.' : 'Continue'\}/)
  assert.match(codeEntrySource, /\{shouldShowValidationError \? \(/)
  assert.match(codeEntrySource, /replace\(\/\[\^a-zA-Z0-9\]\/g, ''\)\.toUpperCase\(\)/)

  assert.match(appSource, /const normalizedCode = String\(authInvitationCode \|\| ''\)\.trim\(\)\.toUpperCase\(\);/)
  assert.match(appSource, /if \(normalizedCode\.length !== 6\) \{[\s\S]*setAuthInvitationCodeErrorMessage\('Enter the full 6-character invitation code before continuing\.'\);[\s\S]*return;[\s\S]*\}/)
  assert.match(appSource, /setAuthInvitationCode\(normalizedCode\);[\s\S]*setAuthInvitationOnboardingStep\(0\);[\s\S]*setAuthMode\('invitation_onboarding'\);/)
})

test('invitation-code entry form is keyboard-safe and safe-area padded so Continue stays reachable', () => {
  const codeEntrySource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/invitation-code-entry-view.js'), 'utf8')

  assert.match(codeEntrySource, /import \{ KeyboardAvoidingView, Modal, Platform, ScrollView, Text, TextInput, View \} from 'react-native'/)
  assert.match(codeEntrySource, /const insets = useSafeAreaInsets\(\)/)
  assert.match(codeEntrySource, /paddingTop: Math\.max\(insets\.top, 16\)/)
  assert.match(codeEntrySource, /paddingBottom: Math\.max\(insets\.bottom, 20\)/)
  assert.match(codeEntrySource, /<KeyboardAvoidingView[\s\S]*behavior=\{Platform\.OS === 'ios' \? 'padding' : undefined\}[\s\S]*keyboardVerticalOffset=\{insets\.top\}/)
  assert.match(codeEntrySource, /<ScrollView[\s\S]*keyboardShouldPersistTaps="handled"[\s\S]*showsVerticalScrollIndicator=\{false\}/)
  assert.match(codeEntrySource, /contentContainerStyle=\{\{[\s\S]*flexGrow: 1,[\s\S]*justifyContent: 'center',[\s\S]*paddingBottom: 32,[\s\S]*\}\}/)
  assert.match(codeEntrySource, /testID="athlete-invitation-code-input"/)
  assert.match(codeEntrySource, /label=\{validationState === INVITATION_CODE_VALIDATION_STATES\.SUBMITTING \? 'Checking code\.\.\.' : 'Continue'\}/)
})

test('invited-athlete completion source covers final completion states', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const onboardingSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/athlete-invite-onboarding-view.js'), 'utf8')

  assert.match(appSource, /const INVITED_ATHLETE_COMPLETION_STATES = Object\.freeze\(\{[\s\S]*IDLE: 'idle',[\s\S]*SUBMITTING: 'submitting',[\s\S]*UNAVAILABLE: 'unavailable',[\s\S]*SUCCEEDED: 'succeeded',[\s\S]*FAILED: 'failed',[\s\S]*\}\);/)
  assert.match(appSource, /const \[invitedAthleteCompletionState, setInvitedAthleteCompletionState\] = useState\(INVITED_ATHLETE_COMPLETION_STATES\.IDLE\);/)
  assert.match(appSource, /function handleOpenInvitationCodeFlow\(\) \{[\s\S]*setInvitedAthleteCompletionState\(INVITED_ATHLETE_COMPLETION_STATES\.IDLE\);[\s\S]*\}/)
  assert.match(appSource, /function handleInvitationOnboardingChange\(fieldId, nextValue\) \{[\s\S]*setInvitedAthleteCompletionState\(INVITED_ATHLETE_COMPLETION_STATES\.IDLE\);[\s\S]*\}/)
  assert.match(appSource, /async function handleInvitationOnboardingNext\(\) \{[\s\S]*if \(!invitationCompletionClient\?\.completeAthleteInvitation\) \{[\s\S]*setInvitedAthleteCompletionState\(INVITED_ATHLETE_COMPLETION_STATES\.UNAVAILABLE\);[\s\S]*throw new Error\('Athlete invitation completion is not available right now\.'\);[\s\S]*\}[\s\S]*setInvitedAthleteCompletionState\(INVITED_ATHLETE_COMPLETION_STATES\.SUBMITTING\);[\s\S]*const completionResult = await invitationCompletionClient\.completeAthleteInvitation\([\s\S]*setInvitedAthleteCompletionState\(INVITED_ATHLETE_COMPLETION_STATES\.SUCCEEDED\);[\s\S]*\} catch \(error\) \{[\s\S]*setInvitedAthleteCompletionState\(\(current\) => current === INVITED_ATHLETE_COMPLETION_STATES\.UNAVAILABLE \? current : INVITED_ATHLETE_COMPLETION_STATES\.FAILED\);[\s\S]*\}/)
  assert.match(appSource, /<AthleteInviteOnboardingView[\s\S]*completionState=\{invitedAthleteCompletionState\}/)
  assert.match(onboardingSource, /completionState = 'idle'/)
  assert.match(onboardingSource, /const isCompletionSubmitting = isSubmitting \|\| completionState === 'submitting'/)
  assert.match(onboardingSource, /label=\{isCompletionSubmitting && currentStep === 5 \? 'Getting started\.\.\.' : currentStep === 5 \? 'Get started' : 'Next'\}/)
  assert.match(onboardingSource, /disabled=\{isCompletionSubmitting\}/)
})

test('mobile auth gate exposes an athlete invitation-code path that hands off into a screenshot-matched multi-step onboarding flow', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const authSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/auth-view.js'), 'utf8')
  const codeEntrySource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/invitation-code-entry-view.js'), 'utf8')
  const onboardingSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/athlete-invite-onboarding-view.js'), 'utf8')

  assert.match(appSource, /import \{ InvitationCodeEntryView \} from '\.\/src\/screens\/invitation-code-entry-view\.js';/)
  assert.match(appSource, /import \{ AthleteInviteOnboardingView \} from '\.\/src\/screens\/athlete-invite-onboarding-view\.js';/)
  assert.match(appSource, /const \[authInvitationCode, setAuthInvitationCode\] = useState\(''\);/)
  assert.match(appSource, /const \[authInvitationCodeErrorMessage, setAuthInvitationCodeErrorMessage\] = useState\(''\);/)
  assert.match(appSource, /const \[authInvitationOnboardingStep, setAuthInvitationOnboardingStep\] = useState\(0\);/)
  assert.match(appSource, /const initialInvitationOnboardingValues = \{[\s\S]*avatarUrl: ''[\s\S]*avatarAsset: null[\s\S]*dateOfBirth: ''[\s\S]*gender: ''[\s\S]*position: ''[\s\S]*weightUnit: 'lb'[\s\S]*weight: '70'[\s\S]*heightUnit: 'ft'[\s\S]*heightFeet: '5'[\s\S]*heightInches: '9'[\s\S]*heightCm: '175'[\s\S]*\};/)
  assert.match(appSource, /const \[authInvitationOnboardingValues, setAuthInvitationOnboardingValues\] = useState\(initialInvitationOnboardingValues\);/)
  assert.match(appSource, /function handleOpenInvitationCodeFlow\(\) \{[\s\S]*setAuthMode\('invitation_code'\);[\s\S]*setAuthInvitationOnboardingStep\(0\);[\s\S]*\}/)
  assert.match(appSource, /const \{ authSession, bootstrapState, sessionStore, signInWithPassword, signUpWithPassword, resetPasswordForEmail, signOut, refreshAuthSession, updateAuthSession, updateAthleteProfile, updateCoachProfile, createCoachBodyMetricLog, getLatestCoachBodyMetricLog \} = useMobileAuthSession\(\);/)
  assert.match(appSource, /const invitationClient = useMemo\(\(\) => createMobileInvitationClient\(\{[\s\S]*\}\), \[authSession\.accessToken\]\);/)
  assert.match(appSource, /const invitationCompletionClient = useMemo\(\(\) => createMobileInvitationClient\(\{[\s\S]*accessToken: null[\s\S]*\}\), \[\]\);/)
  assert.match(appSource, /function handleContinueInvitationCodeFlow\(\) \{[\s\S]*setAuthInvitationOnboardingStep\(0\);[\s\S]*setAuthMode\('invitation_onboarding'\);[\s\S]*\}/)
  assert.match(appSource, /function handleInvitationOnboardingChange\(fieldId, nextValue\) \{[\s\S]*setAuthInvitationOnboardingValues\(\(current\) => \(\{ \.\.\.current, \[fieldId\]: nextValue \}\)\);[\s\S]*\}/)
  assert.match(appSource, /async function handleInvitationAvatarUpload\(\)/)
  assert.match(appSource, /ImagePicker\.requestMediaLibraryPermissionsAsync\(\)/)
  assert.match(appSource, /ImagePicker\.launchImageLibraryAsync\(\{[\s\S]*mediaTypes: \['images'\][\s\S]*allowsEditing: true[\s\S]*aspect: \[1, 1\][\s\S]*quality: 0\.7[\s\S]*\}\)/)
  assert.match(appSource, /const nextAvatarUrl = asset\.uri/)
  assert.match(appSource, /avatarUrl: nextAvatarUrl/)
  assert.match(appSource, /avatarAsset: \{[\s\S]*uri: asset\.uri[\s\S]*mimeType: asset\.mimeType \|\| 'image\/jpeg'[\s\S]*fileName: asset\.fileName \|\| `athlete-avatar-\$\{Date\.now\(\)\}\.jpg`[\s\S]*\}/)
  assert.match(appSource, /setAuthErrorMessage\('Photo library access is required to update the profile image\.'\)/)
  assert.match(appSource, /setAuthErrorMessage\('Could not read that photo\. Try another image\.'\)/)
  assert.match(appSource, /setAuthInvitationOnboardingValues\(\(current\) => \(\{[\s\S]*avatarUrl: nextAvatarUrl[\s\S]*avatarAsset:/)
  assert.match(appSource, /function handleInvitationOnboardingPrevious\(\) \{[\s\S]*setAuthInvitationOnboardingStep\(\(current\) => Math\.max\(0, current - 1\)\);[\s\S]*\}/)
  assert.match(appSource, /async function handleInvitationOnboardingNext\(\) \{[\s\S]*if \(isAuthSubmitting\) \{[\s\S]*return;[\s\S]*\}[\s\S]*authInvitationOnboardingStep === 0[\s\S]*authInvitationOnboardingValues\.password\.length < 6[\s\S]*at least 6 characters[\s\S]*authInvitationOnboardingStep === 1[\s\S]*authInvitationOnboardingValues\.dateOfBirth[\s\S]*date of birth[\s\S]*authInvitationOnboardingStep === 2[\s\S]*authInvitationOnboardingStep === 3[\s\S]*authInvitationOnboardingStep === 4[\s\S]*await invitationCompletionClient\.completeAthleteInvitation\(\{[\s\S]*inviteCode: authInvitationCode,[\s\S]*dateOfBirth: authInvitationOnboardingValues\.dateOfBirth,[\s\S]*gender: authInvitationOnboardingValues\.gender,[\s\S]*position: authInvitationOnboardingValues\.position,[\s\S]*weight: authInvitationOnboardingValues\.weight,[\s\S]*weightUnit: authInvitationOnboardingValues\.weightUnit,[\s\S]*heightUnit: authInvitationOnboardingValues\.heightUnit,[\s\S]*\}\)[\s\S]*await updateAuthSession\(\{[\s\S]*accessToken: completionResult\.accessToken,[\s\S]*refreshToken: completionResult\.refreshToken,[\s\S]*currentUserId: completionResult\.currentUserId,[\s\S]*currentAthleteId: completionResult\.currentAthleteId,[\s\S]*\}\)[\s\S]*setActiveTab\('progress'\);[\s\S]*await updateAthleteProfile\(\{ avatarAsset: authInvitationOnboardingValues\.avatarAsset \}\)[\s\S]*setAuthInvitationCode\(''\);[\s\S]*setAuthInvitationOnboardingStep\(0\);[\s\S]*setAuthNoticeMessage\('Welcome to PPLUS\.'\);[\s\S]*\}/)
  assert.doesNotMatch(appSource, /async function handleInvitationOnboardingNext\(\)[\s\S]*setAuthMode\('sign_in'\);/)
  assert.match(appSource, /function handleCloseInvitationOnboardingView\(\) \{[\s\S]*setAuthMode\('invitation_code'\);[\s\S]*setAuthInvitationOnboardingStep\(0\);[\s\S]*\}/)
  assert.match(appSource, /<AuthView[\s\S]*onInvitationCodePress=\{handleOpenInvitationCodeFlow\}[\s\S]*theme=\{appTheme\}/)
  assert.match(appSource, /authMode === 'invitation_code' \? \([\s\S]*<InvitationCodeEntryView[\s\S]*onContinue=\{handleContinueInvitationCodeFlow\}[\s\S]*\) : authMode === 'invitation_onboarding' \? \([\s\S]*<AthleteInviteOnboardingView[\s\S]*currentStep=\{authInvitationOnboardingStep\}[\s\S]*values=\{authInvitationOnboardingValues\}[\s\S]*onChangeField=\{handleInvitationOnboardingChange\}[\s\S]*onAvatarPress=\{handleInvitationAvatarUpload\}[\s\S]*onNext=\{handleInvitationOnboardingNext\}[\s\S]*onPrevious=\{handleInvitationOnboardingPrevious\}[\s\S]*onClose=\{handleCloseInvitationOnboardingView\}[\s\S]*theme=\{appTheme\}/)
  assert.match(onboardingSource, /currentStep === 0 \? <DetailsStep[\s\S]*currentStep === 1 \? <DateOfBirthStep[\s\S]*currentStep === 2 \? <GenderStep[\s\S]*currentStep === 3 \? <PositionStep[\s\S]*currentStep === 4 \? <WeightStep[\s\S]*currentStep === 5 \? <HeightStep/)

  assert.match(authSource, /onInvitationCodePress/)
  assert.match(authSource, /Sign up with invitation code/)
  assert.match(authSource, /mode === 'sign_in' && values\.role === 'athlete' && onInvitationCodePress/)
  assert.match(authSource, /textAlign: 'left'/)
  assert.match(authSource, /letterSpacing: 0/)

  assert.match(codeEntrySource, /AppSheetHeader/)
  assert.match(codeEntrySource, /title="Invitation code"/)
  assert.match(codeEntrySource, /testID="athlete-invitation-code-input"/)
  assert.match(codeEntrySource, /text-center text-\[24px\] font-semibold tracking-\[8px\]/)
  assert.match(codeEntrySource, /autoCapitalize="characters"/)
  assert.match(codeEntrySource, /maxLength=\{INVITATION_CODE_LENGTH\}/)
  assert.match(codeEntrySource, /label=\{validationState === INVITATION_CODE_VALIDATION_STATES\.SUBMITTING \? 'Checking code\.\.\.' : 'Continue'\}/)
  assert.doesNotMatch(codeEntrySource, /Coach-led athlete signup/)
  assert.doesNotMatch(codeEntrySource, /Enter the 6-character code your coach sent you\./)
  assert.doesNotMatch(codeEntrySource, /Backend invite claim is the next live seam/)

  assert.match(appSource, /import \* as ImagePicker from 'expo-image-picker';/)
  assert.match(onboardingSource, /import \{ useState \} from 'react'/)
  assert.match(onboardingSource, /import \{ Image, Modal, Platform, Pressable, ScrollView, Text, TextInput, View \} from 'react-native'/)
  assert.match(onboardingSource, /Camera/)
  assert.match(onboardingSource, /const hasAvatar = Boolean\(values\.avatarUrl\)/)
  assert.match(onboardingSource, /onPress=\{onAvatarPress\}/)
  assert.match(onboardingSource, /\{hasAvatar \? \(/)
  assert.match(onboardingSource, /<Image source=\{\{ uri: values\.avatarUrl \}\}/)
  assert.match(onboardingSource, /Eye/)
  assert.match(onboardingSource, /EyeOff/)
  assert.match(onboardingSource, /const \[isPasswordVisible, setIsPasswordVisible\] = useState\(false\)/)
  assert.match(onboardingSource, /const isPasswordField = fieldId === 'password' \|\| fieldId === 'confirmPassword'/)
  assert.match(onboardingSource, /const isSecureEntryEnabled = secureTextEntry && !isPasswordVisible/)
  assert.match(onboardingSource, /trailing=\{trailing\}/)
  assert.match(onboardingSource, /onPress=\{\(\) => setIsPasswordVisible\(\(current\) => !current\)\}/)
  assert.match(onboardingSource, /Enter your details/)
  assert.match(onboardingSource, /What is your date of birth\?/)
  assert.match(onboardingSource, /Select date/)
  assert.match(onboardingSource, /DateTimePicker/)
  assert.match(onboardingSource, /CalendarDays/)
  assert.match(onboardingSource, /What is your gender\?/)
  assert.match(onboardingSource, /What is your position\?/)
  assert.match(onboardingSource, /const WEIGHT_INPUT_MAX_LENGTH_BY_UNIT = \{[\s\S]*lb: 5[\s\S]*kg: 5[\s\S]*\}/)
  assert.match(onboardingSource, /function normalizeWeightInput\(nextValue, maxLength = 5\)/)
  assert.match(onboardingSource, /const hasTrailingDecimal = sanitizedWeightValue\.endsWith\('\.'\)/)
  assert.match(onboardingSource, /const normalizedWeightValue = hasTrailingDecimal \? `\$\{weightWholePart\}\.` : weightDecimalPart\.length > 0 \? `\$\{weightWholePart\}\.\$\{weightDecimalPart\}` : weightWholePart/)
  assert.match(onboardingSource, /const HEIGHT_INPUT_MAX_LENGTH_BY_UNIT = \{[\s\S]*ft: 4[\s\S]*cm: 3[\s\S]*\}/)
  assert.match(onboardingSource, /const weightUnit = values\.weightUnit \|\| 'lb'/)
  assert.match(onboardingSource, /const normalizedWeightValue = String\(values\.weight \|\| ''\)/)
  assert.match(onboardingSource, /const weightInputSuffix = weightUnit === 'kg' \? 'kg' : 'lb'/)
  assert.match(onboardingSource, /onChangeField\('weightUnit', nextUnit\)/)
  assert.match(onboardingSource, /const convertedWeight = nextUnit === 'kg'/)
  assert.match(onboardingSource, /normalizeWeightInput\(String\(convertedWeight \|\| ''\), WEIGHT_INPUT_MAX_LENGTH_BY_UNIT\[nextUnit\] \|\| 5\)/)
  assert.match(onboardingSource, /normalizeWeightInput\(nextValue, WEIGHT_INPUT_MAX_LENGTH_BY_UNIT\[weightUnit\] \|\| 5\)/)
  assert.match(onboardingSource, /placeholder="170"/)
  assert.match(onboardingSource, /value=\{normalizedWeightValue\}/)
  assert.match(onboardingSource, /keyboardType="decimal-pad"/)
  assert.match(onboardingSource, /weightInputSuffix/)
  assert.match(onboardingSource, /const heightUnit = values\.heightUnit \|\| 'ft'/)
  assert.match(onboardingSource, /const normalizedHeightValue = heightUnit === 'cm' \? String\(values\.heightCm \|\| ''\) : `\$\{String\(values\.heightFeet \|\| ''\)\}'\$\{String\(values\.heightInches \|\| ''\)\}`/)
  assert.match(onboardingSource, /const heightInputSuffix = heightUnit === 'cm' \? 'cm' : 'ft'/)
  assert.match(onboardingSource, /onChangeField\('heightUnit', nextUnit\)/)
  assert.match(onboardingSource, /if \(heightUnit === 'cm'\) \{[\s\S]*onChangeField\('heightCm', digitsOnly\.slice\(0, HEIGHT_INPUT_MAX_LENGTH_BY_UNIT\.cm\)\)/)
  assert.match(onboardingSource, /const nextFeet = digitsOnly\.slice\(0, 1\)/)
  assert.match(onboardingSource, /const nextInches = digitsOnly\.slice\(1, 3\)/)
  assert.match(onboardingSource, /placeholder=\{heightUnit === 'cm' \? '180' : "5'09"\}/)
  assert.match(onboardingSource, /value=\{normalizedHeightValue\}/)
  assert.match(onboardingSource, /heightInputSuffix/)
  assert.match(onboardingSource, /className="mt-8 self-center w-full max-w-\[336px\] rounded-\[24px\] px-5 py-4"/)
  assert.match(onboardingSource, /text-\[24px\] font-semibold/)
  assert.match(onboardingSource, /className="text-\[20px\] font-semibold lowercase"/)
  assert.doesNotMatch(onboardingSource, /snapToInterval=\{WEIGHT_SELECTOR_TICK_SPACING\}/)
  assert.doesNotMatch(onboardingSource, /onMomentumScrollEnd=\{handleWeightScrollCommit\}/)
  assert.match(onboardingSource, /170/)
  assert.match(onboardingSource, /180/)
  assert.match(onboardingSource, /What is your height\?/)
  assert.match(onboardingSource, /FIRST NAME/)
  assert.match(onboardingSource, /LAST NAME/)
  assert.match(onboardingSource, /PASSWORD/)
  assert.match(onboardingSource, /CONFIRM PASSWORD/)
  assert.match(onboardingSource, /Male/)
  assert.match(onboardingSource, /Female/)
  assert.match(onboardingSource, /Forward/)
  assert.match(onboardingSource, /Defense/)
  assert.match(onboardingSource, /Goalie/)
  assert.match(onboardingSource, /Lb/)
  assert.match(onboardingSource, /kg/)
  assert.match(onboardingSource, /ft/)
  assert.match(onboardingSource, /cm/)
  assert.match(onboardingSource, /Get started/)
  assert.match(onboardingSource, /Previous/)
  assert.match(onboardingSource, /label=\{isCompletionSubmitting && currentStep === 5 \? 'Getting started\.\.\.' : currentStep === 5 \? 'Get started' : 'Next'\}/)
  assert.match(onboardingSource, /disabled=\{isCompletionSubmitting\}/)
  assert.match(onboardingSource, /Array\.from\(\{ length: 6 \}/)
  assert.match(onboardingSource, /PPLUS/)
  assert.match(onboardingSource, /textAlign: 'left'/)
  assert.match(onboardingSource, /letterSpacing: 0/)
  assert.doesNotMatch(onboardingSource, /testID="athlete-invite-onboarding-email-input"/)
  assert.doesNotMatch(onboardingSource, /fieldId="email"/)
  assert.doesNotMatch(onboardingSource, /placeholder="athlete@pplus\.app"/)
  assert.doesNotMatch(onboardingSource, /Invitation accepted visually/)
  assert.doesNotMatch(onboardingSource, /Backend claim \+ account creation is the next seam to wire live\./)
  assert.doesNotMatch(appSource, /Backend claim \+ final signup submission is the next live seam\./)
  assert.doesNotMatch(appSource, /Athlete onboarding UI now follows the invitation flow\./)
  assert.doesNotMatch(onboardingSource, /Continue athlete signup/)
})
