import test from 'node:test'
import assert from 'node:assert/strict'
import { styles, statusStyles } from '../apps/mobile/src/screens/styles.js'

test('mobile screen styles exports the shared shell and renderer style keys', () => {
  assert.ok(styles.container)
  assert.ok(styles.appShell)
  assert.ok(styles.brandHeader)
  assert.ok(styles.brandHeaderSide)
  assert.ok(styles.brandLogoWrap)
  assert.ok(styles.brandIconButton)
  assert.ok(styles.topHeader)
  assert.ok(styles.previewBar)
  assert.ok(styles.previewHeaderTopRow)
  assert.ok(styles.trainTabsRow)
  assert.ok(styles.trainTabsPill)
  assert.ok(styles.sectionCard)
  assert.ok(styles.tabBar)
  assert.ok(styles.calendarStripCard)
  assert.ok(styles.calendarStripRow)
  assert.ok(styles.calendarDayButton)
  assert.ok(styles.calendarDaySelected)
  assert.ok(styles.calendarDayWeekLabel)
  assert.ok(styles.calendarDayWeekLabelSelected)
  assert.ok(styles.calendarDayNumber)
  assert.ok(styles.calendarDayNumberSelected)
  assert.ok(styles.calendarIndicator)
  assert.ok(styles.calendarIndicatorActive)
  assert.ok(styles.calendarIndicatorMuted)
  assert.ok(styles.sectionHeading)
  assert.ok(styles.workoutListCard)
  assert.ok(styles.workoutListAccentRail)
  assert.ok(styles.todayCardContent)
  assert.ok(styles.todayCardCheckWrap)
  assert.equal(styles.container.backgroundColor, '#0b1220')
  assert.equal(styles.previewButtonActive.backgroundColor, '#06D6A0')
  assert.equal(styles.trainTabButtonActive.backgroundColor, '#06D6A0')
  assert.equal(styles.progressFill.backgroundColor, '#06D6A0')
  assert.equal(styles.programAccentRail.backgroundColor, '#06D6A0')
  assert.equal(styles.calendarDaySelected.borderColor, '#06D6A0')
  assert.equal(styles.calendarDayNumberSelected.color, '#06D6A0')
  assert.equal(styles.calendarIndicatorActive.backgroundColor, '#06D6A0')
  assert.equal(styles.todayCard.backgroundColor, '#111827')
  assert.equal(styles.todayCard.borderRadius, 18)
  assert.equal(styles.todayCard.padding, 14)
  assert.equal(styles.todayCard.flexDirection, 'row')
  assert.equal(styles.todayCard.alignItems, 'center')
  assert.equal(styles.todayCardWorkoutName.fontSize, 18)
  assert.equal(styles.todayCardSummary.fontSize, 12)
  assert.equal(styles.todayCardCheckWrap.width, 28)
  assert.equal(styles.todayCardCheckWrap.borderRadius, 8)
  assert.equal(styles.programCard.backgroundColor, '#111827')
  assert.equal(styles.workoutListCard.backgroundColor, '#111827')
  assert.equal(styles.sectionHeading.fontSize, 22)
  assert.equal(styles.workoutListAccentRail.backgroundColor, '#06D6A0')
})

test('mobile status styles preserves exercise status colors', () => {
  assert.equal(statusStyles.not_started.backgroundColor, '#06D6A0')
  assert.equal(statusStyles.active.backgroundColor, '#7c3aed')
  assert.equal(statusStyles.completed.backgroundColor, '#059669')
  assert.equal(statusStyles.skipped.backgroundColor, '#b45309')
})
