import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

test('mobile active workout view matches the initial live workout shell from the start workout flow', () => {
 const viewSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/active-workout-view.js'), 'utf8')

 assert.match(viewSource, /export function ActiveWorkoutView\(/)
 assert.match(viewSource, /SafeAreaProvider/)
 assert.match(viewSource, /SafeAreaView/)
 assert.match(viewSource, /Modal/)
 assert.match(viewSource, /TextInput/)
 assert.match(viewSource, /Swipeable/)
 assert.match(viewSource, /Trash2/)
 assert.match(viewSource, /function ActiveWorkoutCellInput\(/)
 assert.match(viewSource, /import \{ Image, Modal, Pressable, ScrollView, Text, TextInput, View \} from 'react-native'/)
 assert.match(viewSource, /function SwipeableActiveWorkoutExerciseRow\(/)
 assert.match(viewSource, /<Swipeable[\s\S]*overshootRight=\{false\}[\s\S]*renderRightActions=\{renderRightActions\}[\s\S]*rightThreshold=\{48\}/)
 assert.match(viewSource, /<View className="w-full">/)

 assert.match(viewSource, /onSetValueChange/)

 assert.match(viewSource, /Settings/)
 assert.match(viewSource, /Mic/)
 assert.match(viewSource, /Clock3/)
 assert.match(viewSource, /className=/)
 assert.match(viewSource, /model\.header\.workoutTimerLabel/)
 assert.match(viewSource, /model\.header\.finishLabel/)
 assert.match(viewSource, /model\.title/)
  assert.match(viewSource, /model\.notesPlaceholder/)
  assert.match(viewSource, /model\.notesValue/)
assert.match(viewSource, /model\.addSetLabel/)
 assert.match(viewSource, /buildActiveWorkoutExerciseRenderGroups\(model\.exercises\)\.map\(/)
  assert.match(viewSource, /onWorkoutNotesChange/)
  assert.match(viewSource, /Add Set/)
assert.match(viewSource, /import \{ useEffect, useRef, useState \} from 'react'/)
 assert.match(viewSource, /const previousRestTimerClockLabelRef = useRef\(null\)/)
 assert.match(viewSource, /const previousPostSetEffortTargetRef = useRef\(null\)/)
 assert.match(viewSource, /if \(model\?\.restTimer\?\.clockLabel && !previousRestTimerClockLabelRef\.current\) \{[\s\S]*setIsRestTimerSheetOpen\(false\)/)
 assert.match(viewSource, /const \[restTimerMode, setRestTimerMode\] = useState\('timer'\)/)
 assert.match(viewSource, /const \[isStopwatchRunning, setIsStopwatchRunning\] = useState\(false\)/)
 assert.match(viewSource, /const \[stopwatchElapsedSeconds, setStopwatchElapsedSeconds\] = useState\(0\)/)
 assert.match(viewSource, /const \[isPostSetEffortSheetOpen, setIsPostSetEffortSheetOpen\] = useState\(false\)/)
 assert.match(viewSource, /useEffect\(\(\) => \{[\s\S]*if \(!model\?\.restTimer && !isStopwatchRunning\) \{[\s\S]*setIsRestTimerSheetOpen\(false\)/)
 assert.match(viewSource, /useEffect\(\(\) => \{[\s\S]*const nextPostSetEffortKey = postSetEffortAdjustment \? `\$\{postSetEffortAdjustment\.exerciseId\}:\$\{postSetEffortAdjustment\.setId\}` : null[\s\S]*if \(nextPostSetEffortKey && nextPostSetEffortKey !== previousPostSetEffortTargetRef\.current\) \{[\s\S]*setIsPostSetEffortSheetOpen\(true\)[\s\S]*\}[\s\S]*if \(!nextPostSetEffortKey\) \{[\s\S]*setIsPostSetEffortSheetOpen\(false\)[\s\S]*\}[\s\S]*previousPostSetEffortTargetRef\.current = nextPostSetEffortKey[\s\S]*\}, \[postSetEffortAdjustment\]\)/)
 assert.match(viewSource, /useEffect\(\(\) => \{[\s\S]*if \(!isStopwatchRunning\) return undefined[\s\S]*setInterval/)
 assert.match(viewSource, /import \{ Swipeable \} from 'react-native-gesture-handler'/)
 assert.match(viewSource, /function SwipeableActiveWorkoutSetRow\(/)
 assert.match(viewSource, /<Swipeable[\s\S]*overshootRight=\{false\}[\s\S]*renderRightActions=\{renderRightActions\}[\s\S]*rightThreshold=\{48\}/)
 assert.match(viewSource, /function renderRightActions\(\) \{[\s\S]*<Pressable[\s\S]*onPress=\{onDelete\}[\s\S]*theme\.dangerSurface[\s\S]*theme\.dangerBorder[\s\S]*Trash2/)
 assert.match(viewSource, /<View className="w-full overflow-hidden rounded-\[16px\]">/)
 assert.match(viewSource, /<SwipeableActiveWorkoutSetRow key=\{set\.id\}[\s\S]*onDelete=\{\(\) => onDeleteSet\?\.\(exercise\.id, set\.id\)\}[\s\S]*<ActiveWorkoutSetRow/)
 assert.match(viewSource, /function ActiveWorkoutExerciseBlock\(\{ exercise, exerciseIndex, totalExercises, theme, addSetLabel, onAddSet, onDeleteSet, onDeleteExercise, onMoveExercise, onOpenExerciseDetail, onCompleteSet, onSetValueChange, onOpenSupersetPicker, onOpenExerciseRestTimer, isSupersetLinked, supersetTargetOptions \}\)/)
 assert.match(viewSource, /function buildActiveWorkoutExerciseRenderGroups\(exercises\)[\s\S]*previousGroup\?\.supersetGroupId === currentGroupId[\s\S]*previousGroup\.exercises\.push\(exercise\)/)
 assert.match(viewSource, /buildActiveWorkoutExerciseRenderGroups\(model\.exercises\)\.map\(\(group\) => \{/)
 assert.match(viewSource, /const isSupersetGroup = Boolean\(group\.supersetGroupId && group\.exercises\.length > 1\)/)
 assert.match(viewSource, /<View key=\{`superset-\$\{group\.supersetGroupId\}`\} className="relative gap-5">[\s\S]*className="absolute left-0 top-0 bottom-0 w-\[4px\] rounded-full"[\s\S]*backgroundColor: resolvedTheme\.accentText/)
 assert.match(viewSource, /containerClassName=\{`\$\{isSupersetLinked \? 'ml-3 ' : ''\}rounded-\[24px\] overflow-hidden`\.trim\(\)\}/)
 assert.doesNotMatch(viewSource, /supersetRailPosition=\{getSupersetRailPosition\(model\.exercises, exerciseIndex\)\}/)
 assert.doesNotMatch(viewSource, /className="absolute left-0 w-\[4px\]"[\s\S]*backgroundColor: theme\.accentText/)
 assert.doesNotMatch(viewSource, /absolute bottom-0 left-0 top-0 w-\[4px\] rounded-full/)
 assert.match(viewSource, /<SwipeableActiveWorkoutExerciseRow onDelete=\{\(\) => onDeleteExercise\?\.\(exercise\.id\)\} theme=\{theme\}>[\s\S]*<AppSurfaceCard/)
 assert.match(viewSource, /testID=\{`active-workout-exercise-\$\{exerciseIndex \+ 1\}-card`\}/)
 assert.match(viewSource, /testID=\{`active-workout-exercise-\$\{exerciseIndex \+ 1\}-header`\}/)
 assert.match(viewSource, /testID=\{`active-workout-exercise-\$\{exerciseIndex \+ 1\}-thumbnail`\}/)
 assert.match(viewSource, /testID=\{`active-workout-exercise-\$\{exerciseIndex \+ 1\}-title`\}/)
 assert.match(viewSource, /testID=\{`active-workout-exercise-\$\{exerciseIndex \+ 1\}-reorder-controls`\}/)
 assert.match(viewSource, /testID=\{`active-workout-exercise-\$\{exerciseIndex \+ 1\}-set-header-row`\}/)
 assert.match(viewSource, /const canMoveExerciseUp = exerciseIndex > 0/)
 assert.match(viewSource, /const canMoveExerciseDown = exerciseIndex < totalExercises - 1/)
 assert.match(viewSource, /<AppSurfaceCard[\s\S]*containerClassName="h-14 w-14 rounded-\[18px\] overflow-hidden"[\s\S]*\{exercise\.thumbnailUrl \? \([\s\S]*<Image source=\{\{ uri: exercise\.thumbnailUrl \}\} className="h-full w-full" resizeMode="cover" \/>[\s\S]*: \([\s\S]*<Dumbbell color=\{theme\.iconMuted\} size=\{22\} strokeWidth=\{2\.2\} \/>/)
 assert.match(viewSource, /<Pressable onPress=\{\(\) => onOpenExerciseDetail\?\.\(exercise\)\}>[\s\S]*<Text className="text-\[22px\] font-semibold leading-\[28px\]" style=\{\{ color: theme\.text \}\} testID=\{`active-workout-exercise-\$\{exerciseIndex \+ 1\}-title`\}>\{exercise\.title\}<\/Text>/)
 assert.doesNotMatch(viewSource, /<View className="flex-row items-center justify-end gap-1\.5">[\s\S]*<Clock3 color=\{theme\.iconMuted\} size=\{14\} strokeWidth=\{2\.2\} \/>[\s\S]*exercise\.restLabel/)
 assert.match(viewSource, /<Pressable className="h-10 w-10 items-center justify-center" disabled=\{!canMoveExerciseUp\} onPress=\{\(\) => onMoveExercise\?\.\(exercise\.id, 'up'\)\}>[\s\S]*<ArrowUp color=\{canMoveExerciseUp \? theme\.accentText : theme\.iconMuted\}/)
 assert.match(viewSource, /<Pressable className="h-10 w-10 items-center justify-center" disabled=\{!canMoveExerciseDown\} onPress=\{\(\) => onMoveExercise\?\.\(exercise\.id, 'down'\)\}>[\s\S]*<ArrowDown color=\{canMoveExerciseDown \? theme\.accentText : theme\.iconMuted\}/)
 assert.match(viewSource, /function ActiveWorkoutRestTimerSheet\(/)
 assert.match(viewSource, /function ActiveWorkoutEffortAdjustmentSheet\(/)
 assert.match(viewSource, /function ActiveWorkoutSettingsSheet\(/)
 assert.match(viewSource, /function ActiveWorkoutExerciseRestTimerSheet\(/)
 assert.match(viewSource, /function ActiveWorkoutDiscardWorkoutSheet\(/)
 assert.match(viewSource, /function ActiveWorkoutAddExerciseSheet\(/)
  assert.match(viewSource, /Workout Settings/)
  assert.match(viewSource, /Edit Rest Timer/)
  assert.match(viewSource, /Finish Workout/)
  assert.match(viewSource, /Session Difficulty/)
  assert.match(viewSource, /Complete Workout/)
  assert.match(viewSource, /Empty Workout/)
  assert.match(viewSource, /Complete sets to finish a workout/)
  assert.match(viewSource, /Continue/)
  assert.match(viewSource, /Discard Workout/)
assert.match(viewSource, /Add Exercise/)
  assert.match(viewSource, /AppOutlinedActionButton/)
  assert.match(viewSource, /AppDangerPillButton/)
  assert.doesNotMatch(viewSource, /className="absolute inset-x-0 top-0 h-\[1px\]"/)
  assert.doesNotMatch(viewSource, /style=\{\{ backgroundColor: theme\.buttonHighlight \}\}/)
  assert.match(viewSource, /Search or create/)
 assert.match(viewSource, /Exercises/)
 assert.match(viewSource, /Chat/)
 assert.match(viewSource, /This action cannot be undone\./)
 assert.match(viewSource, /Remove/)
 assert.match(viewSource, /Default Rest Time/)
 assert.match(viewSource, /Keep Awake/)
assert.match(viewSource, /Adjust Effort After Set/)
 assert.match(viewSource, /Adjust Effort/)
 const workoutSettingsSheetBlock = viewSource.match(/function ActiveWorkoutSettingsSheet\([\s\S]*?function ActiveWorkoutDefaultRestTimeSheet\(/)?.[0] || ''
 assert.match(workoutSettingsSheetBlock, /Default Rest Time/)
 assert.match(workoutSettingsSheetBlock, /Auto-Progress/)
 assert.match(workoutSettingsSheetBlock, /Keep Awake/)
 assert.match(workoutSettingsSheetBlock, /Adjust Effort After Set/)
 assert.match(workoutSettingsSheetBlock, /ChevronRight/)
 assert.match(workoutSettingsSheetBlock, /Move to the next set automatically after the rest timer ends\./)
 assert.match(workoutSettingsSheetBlock, /Keep your screen on while this workout is active\./)
 assert.match(workoutSettingsSheetBlock, /Ask for effort after each completed set\./)
 assert.match(workoutSettingsSheetBlock, /containerClassName="w-full rounded-b-none rounded-t-\[28px\] overflow-hidden"/)
 assert.match(workoutSettingsSheetBlock, /contentClassName="px-5 pb-8 pt-5"/)
 assert.match(workoutSettingsSheetBlock, /settings\.autoProgressEnabled/)
 assert.match(workoutSettingsSheetBlock, /settings\.keepAwake/)
 assert.match(viewSource, /function ActiveWorkoutDefaultRestTimeSheet/)
 assert.match(viewSource, /isDefaultRestTimeSheetOpen/)
 assert.match(viewSource, /onOpenDefaultRestTime=\{onOpenDefaultRestTime\}/)
 assert.doesNotMatch(viewSource, /onOpenDefaultRestTime=\{\(\) => \{\}\}/)
 assert.match(viewSource, /defaultRestSeconds: Math\.max\(0, currentSeconds \+ delta\)/)
 assert.match(viewSource, /\[60, 90, 120, 180\]\.map/)
 assert.match(viewSource, /activateKeepAwakeAsync\(ACTIVE_WORKOUT_KEEP_AWAKE_TAG\)/)
 assert.match(viewSource, /deactivateKeepAwake\(ACTIVE_WORKOUT_KEEP_AWAKE_TAG\)/)
 assert.match(viewSource, /set\.isActiveTarget/)
 assert.match(viewSource, /isCompleted \|\| isActiveTarget \? theme\.accentBorder/)
 assert.doesNotMatch(workoutSettingsSheetBlock, /-15s/)
 assert.doesNotMatch(workoutSettingsSheetBlock, /\+15s/)
 assert.doesNotMatch(workoutSettingsSheetBlock, /<View className="px-5 pb-6"/)

 assert.match(viewSource, /settingsButtonLabel/)
 assert.match(viewSource, /onOpenWorkoutSettings/)
 assert.match(viewSource, /onCloseWorkoutSettings/)
 assert.match(viewSource, /onUpdateWorkoutSettings/)
 assert.match(viewSource, /onOpenExerciseRestTimer/)
 assert.match(viewSource, /onAdjustExerciseRestTimer/)
 assert.match(viewSource, /onRemoveExerciseRestTimer/)
  assert.match(viewSource, /onOpenFinishWorkoutSheet/)
  assert.match(viewSource, /onCloseFinishWorkoutSheet/)
  assert.match(viewSource, /onConfirmFinishWorkout/)
  assert.match(viewSource, /setFinishWorkoutPerceivedDifficulty/)
  assert.match(viewSource, /onOpenEmptyWorkoutSheet/)
  assert.match(viewSource, /onCloseEmptyWorkoutSheet/)
  assert.match(viewSource, /onConfirmEmptyWorkoutDiscard/)
assert.match(viewSource, /onOpenDiscardWorkout/)
 assert.match(viewSource, /onCloseDiscardWorkout/)
 assert.match(viewSource, /onConfirmDiscardWorkout/)
 assert.match(viewSource, /onOpenAddExercise/)
 assert.match(viewSource, /onToggleAddExercise/)
 assert.match(viewSource, /onConfirmAddExercises/)
 assert.match(viewSource, /onDecreaseEffort/)
 assert.match(viewSource, /onIncreaseEffort/)
 assert.match(viewSource, /onClosePostSetEffortAdjustment/)
 assert.match(viewSource, /<ActiveWorkoutSettingsSheet[\s\S]*isVisible=\{isWorkoutSettingsSheetOpen\}/)
 assert.match(viewSource, /<ActiveWorkoutExerciseRestTimerSheet[\s\S]*isVisible=\{isExerciseRestTimerSheetOpen\}/)
  assert.match(viewSource, /const \[isFinishWorkoutSheetOpen, setIsFinishWorkoutSheetOpen\] = useState\(false\)/)
  assert.match(viewSource, /const \[finishWorkoutPerceivedDifficulty, setFinishWorkoutPerceivedDifficulty\] = useState\(sessionDifficultyDefault\)/)
  assert.match(viewSource, /<ActiveWorkoutFinishWorkoutSheet[\s\S]*isVisible=\{isFinishWorkoutSheetOpen\}/)
  assert.match(viewSource, /const \[isEmptyWorkoutSheetOpen, setIsEmptyWorkoutSheetOpen\] = useState\(false\)/)
  assert.match(viewSource, /<ActiveWorkoutEmptyWorkoutSheet[\s\S]*isVisible=\{isEmptyWorkoutSheetOpen\}/)
assert.match(viewSource, /<ActiveWorkoutDiscardWorkoutSheet[\s\S]*isVisible=\{isDiscardWorkoutSheetOpen\}/)
 assert.match(viewSource, /<ActiveWorkoutAddExerciseSheet[\s\S]*isVisible=\{isAddExerciseSheetOpen\}/)
 assert.match(viewSource, /<AppOutlinedActionButton[\s\S]*label="Add Exercise"[\s\S]*onPress=\{onOpenAddExercise\}/)
 assert.match(viewSource, /leftIcon=\{<Dumbbell color=\{resolvedTheme\.accentText\} size=\{18\} strokeWidth=\{2\.2\} \/>\}/)
 assert.match(viewSource, /<AppDangerPillButton[\s\S]*label="Discard Workout"[\s\S]*onPress=\{onOpenDiscardWorkout\}/)
 assert.match(viewSource, /leftIcon=\{<Trash2 color=\{resolvedTheme\.dangerText\} size=\{16\} strokeWidth=\{2\.2\} \/>\}/)
 assert.match(viewSource, /<ActiveWorkoutViewContent model=\{model\} theme=\{theme\} onClose=\{onClose\} onFinish=\{onFinish\} onDiscard=\{onDiscard\} canFinishWorkout=\{canFinishWorkout\} onAddSet=\{onAddSet\} onDeleteSet=\{onDeleteSet\} onDeleteExercise=\{onDeleteExercise\} onMoveExercise=\{onMoveExercise\} onOpenExerciseDetail=\{onOpenExerciseDetail\}/)
 assert.match(viewSource, /<ActiveWorkoutEffortAdjustmentSheet[\s\S]*isVisible=\{isPostSetEffortSheetOpen\}/)
 assert.match(viewSource, /function ActiveWorkoutRestTimerChip\(/)
 assert.match(viewSource, /function formatUtilityClock\(/)
 assert.match(viewSource, /Timer/)
 assert.match(viewSource, /Stopwatch/)
 assert.match(viewSource, /Start/)
 assert.match(viewSource, /Cancel/)
 assert.match(viewSource, /restTimerMode === 'timer'/)
 assert.match(viewSource, /restTimerMode === 'stopwatch'/)
 assert.match(viewSource, /onAdjustRestTimer/)
 assert.match(viewSource, /onDismissRestTimer/)
 assert.match(viewSource, /onOpenRestTimer/)
 assert.match(viewSource, /onCloseRestTimer/)
 assert.match(viewSource, /onToggleStopwatch/)
 assert.match(viewSource, /isVisible=\{isRestTimerSheetOpen\}/)
 assert.match(viewSource, /className="h-\[58px\] min-w-\[112px\] rounded-\[24px\]"/)
 assert.match(viewSource, /<Pressable className="flex-row items-center gap-1\.5 px-3 py-3" onPress=\{\(\) => onOpenExerciseRestTimer\?\.\(exercise\.id\)\}/)
 assert.match(viewSource, /function getSupersetGroupTargetOptions\(exercises, exerciseId\)/)
 assert.doesNotMatch(viewSource, /getAdjacentSupersetTargetOptions/)
 assert.match(viewSource, /const linkedTargetIds = selectedSupersetSourceExercise\?\.supersetGroupId/)
 assert.match(viewSource, /model\.exercises[\s\S]*exercise\.supersetGroupId === selectedSupersetSourceExercise\.supersetGroupId[\s\S]*\.map\(\(exercise\) => exercise\.id\)/)
 assert.match(viewSource, /emptySelectionLabel: 'Remove link'/)
 assert.match(viewSource, /import \{ ExerciseMultiSelectView \} from '\.\/exercise-multi-select-view\.js'/)
 assert.doesNotMatch(viewSource, /function ActiveWorkoutSupersetPickerSheet\(/)
 assert.match(viewSource, /const \[selectedSupersetTargetExerciseIds, setSelectedSupersetTargetExerciseIds\] = useState\(\[\]\)/)
 assert.match(viewSource, /const \[supersetSearchQuery, setSupersetSearchQuery\] = useState\(''\)/)
 assert.match(viewSource, /const supersetTargetSheet = selectedSupersetSourceExercise \? \{[\s\S]*title: 'Superset With',[\s\S]*addButtonLabel: 'Link',[\s\S]*emptySelectionLabel: 'Remove link',[\s\S]*exercises: selectedSupersetTargetOptions\.map/)
 assert.match(viewSource, /thumbnailUrl: targetOption\.thumbnailUrl \?\? null/)
 assert.match(viewSource, /function onCloseSupersetPicker\(\) \{[\s\S]*setSupersetSearchQuery\(''\)/)
 assert.match(viewSource, /<ExerciseMultiSelectView[\s\S]*isVisible=\{Boolean\(selectedSupersetSourceExercise\)\}[\s\S]*sheet=\{supersetTargetSheet\}[\s\S]*selectedExerciseIds=\{selectedSupersetTargetExerciseIds\}[\s\S]*onToggleExercise=\{onToggleSupersetTarget\}[\s\S]*searchQuery=\{supersetSearchQuery\}[\s\S]*onSearchChange=\{setSupersetSearchQuery\}[\s\S]*onAddExercises=\{onConfirmSupersetTarget\}[\s\S]*onClose=\{onCloseSupersetPicker\}/)
 assert.doesNotMatch(viewSource, /<ActiveWorkoutSupersetPickerSheet/)
 assert.match(viewSource, /Superset With/)
 assert.match(viewSource, /onOpenSupersetPicker\?\.\(exercise\.id\)/)
 assert.match(viewSource, /onCreateSuperset\?\.\(selectedSupersetSourceExercise\.id, targetExerciseId\)/)
 assert.match(viewSource, /onRemoveSuperset\?\.\(selectedSupersetSourceExercise\.id\)/)
 assert.doesNotMatch(viewSource, /<Pressable className="h-11 w-11 items-center justify-center" onPress=\{\(\) => \{\}\}>[\s\S]*<Link2/)
 assert.match(viewSource, /<ActiveWorkoutViewContent[\s\S]*onCreateSuperset=\{onCreateSuperset\}[\s\S]*onRemoveSuperset=\{onRemoveSuperset\}/)
 assert.match(viewSource, /<ActiveWorkoutExerciseBlock[\s\S]*onOpenSupersetPicker=\{onOpenSupersetPicker\}/)
 assert.match(viewSource, /Discard Workout/)
 assert.match(viewSource, /Add Exercise/)
 assert.match(viewSource, /className=\{`h-\[58px\] flex-row items-center px-5 \$\{isIconOnly \? 'justify-center' : 'justify-start gap-2'\}`\}/)
 assert.match(viewSource, /\{!isIconOnly \? \(/)
  assert.match(viewSource, /canFinishWorkout/)
  assert.match(viewSource, /if \(!canFinishWorkout\) \{[\s\S]*onOpenEmptyWorkoutSheet\(\)[\s\S]*return[\s\S]*\}/)
  assert.match(viewSource, /onOpenFinishWorkoutSheet\(\)/)
  assert.match(viewSource, /onFinish\?\.\(\{ perceivedDifficulty: finishWorkoutPerceivedDifficulty \}\)/)
  assert.match(viewSource, /<AppButton theme=\{resolvedTheme\} label=\{model\.header\.finishLabel\} onPress=\{handleFinishPress\} \/>/)
assert.match(viewSource, /<Pressable className="h-10 w-10 items-center justify-center" onPress=\{onOpenWorkoutSettings\}>[\s\S]*<Settings color=\{resolvedTheme\.accentText\} size=\{20\} strokeWidth=\{2\.2\} \/>/)
 assert.match(viewSource, /function ActiveWorkoutFloatingTools\(\{ theme, timerChipLabel, onOpenRestTimer \}\)/)
 assert.match(viewSource, /const defaultTimerClockLabel = model\.defaultRestTimerLabel \|\| '00:00'/)
 assert.match(viewSource, /isVisible=\{isRestTimerSheetOpen\}/)
 assert.match(viewSource, /const clockLabel = restTimerMode === 'timer' \? \(restTimer\?\.clockLabel \|\| defaultTimerClockLabel\) : stopwatchClockLabel/)
 assert.doesNotMatch(viewSource, /<AppSurfaceCard theme=\{resolvedTheme\} containerClassName="rounded-\[24px\] overflow-hidden" contentClassName="gap-4 px-5 py-5">[\s\S]*Rest Timer[\s\S]*model\.restTimer\.plusLabel/)
 assert.match(viewSource, /from '\.\.\/theme\/app-theme\.js'/)
 assert.match(viewSource, /from '\.\.\/ui\/primitives\.js'/)
 assert.doesNotMatch(viewSource, /#34D399|#243041|#111827|text-white|text-slate-400|text-slate-300/)
})
