import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

test('mobile app shell threads the shared app theme into the remaining modal surfaces', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')

  assert.match(appSource, /\bappTheme\b/)
  assert.match(appSource, /renderProgramSheet\([\s\S]*theme:\s*appTheme/)
  assert.match(appSource, /<ProgramEditView[\s\S]*theme=\{appTheme\}/)
  assert.match(appSource, /<WorkoutEditView[\s\S]*theme=\{appTheme\}/)
  assert.match(appSource, /<ExerciseDetailView[\s\S]*theme=\{appTheme\}/)
  assert.match(appSource, /<ProfileView[\s\S]*theme=\{appTheme\}/)
  assert.match(appSource, /AnalyticsView[\s\S]*theme=\{appTheme\}/)
  assert.match(appSource, /<CoachAthletesSheet[\s\S]*theme=\{appTheme\}/)
  assert.match(appSource, /<CoachAthleteWorkspaceSheet[\s\S]*theme=\{appTheme\}/)
})

test('mobile profile surfaces resolve colors from the shared theme instead of fixed dark literals', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /import \{ getAppTheme \} from '\.\.\/theme\/app-theme\.js'/)
  assert.match(profileSource, /from '\.\.\/ui\/primitives\.js'/)
  assert.match(profileSource, /AppSheetHeader/)
  assert.match(profileSource, /AppSegmentedControl/)
  assert.match(profileSource, /AppSearchInput/)
  assert.match(profileSource, /AppNoticeCard/)
  assert.match(profileSource, /AppListRow/)
  assert.match(profileSource, /AppButton/)
  assert.match(profileSource, /AppFieldShell/)
  assert.match(profileSource, /ProfileOptionIcon/)
  assert.match(profileSource, /ProfileOptionRow/)
  assert.match(profileSource, /ProfileSection/)
  assert.match(profileSource, /ProfileViewContent/)
  assert.match(profileSource, /const resolvedTheme = theme \|\| getAppTheme\(themePreference\)/)
  assert.match(profileSource, /theme=\{resolvedTheme\}/)
  assert.match(profileSource, /export function ProfileView\(/)
  assert.match(profileSource, /theme=\{theme\}/)
})

test('mobile exercise detail, workout edit, and program sheet accept the shared theme prop', () => {
  const exerciseDetailSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/exercise-detail-view.js'), 'utf8')
  const workoutEditSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-edit-view.js'), 'utf8')
  const workoutSheetSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-sheet.js'), 'utf8')
  const programSheetSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/program-sheet.js'), 'utf8')
  const primitivesSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/ui/primitives.js'), 'utf8')

  assert.match(exerciseDetailSource, /import \{ getAppTheme \} from '\.\.\/theme\/app-theme\.js'/)
  assert.match(exerciseDetailSource, /from '\.\.\/ui\/primitives\.js'/)
  assert.match(exerciseDetailSource, /AppSegmentedControl/)
  assert.match(exerciseDetailSource, /ExerciseDetailViewContent/)
  assert.match(exerciseDetailSource, /const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(workoutEditSource, /export function WorkoutEditView\(/)
  assert.match(workoutEditSource, /theme=\{theme\}/)
  assert.match(workoutEditSource, /function WorkoutEditDeleteConfirmationModal\(\{ isVisible, onClose, onConfirm, isDeleting = false, errorMessage = '', theme \}\)/)
  assert.match(workoutEditSource, /Are you sure you want to delete this workout\? This action cannot be undone\./)
  assert.match(workoutEditSource, /<Pressable className=\"px-1 py-2\" onPress=\{onClose\}/)
  assert.match(workoutEditSource, /<Text className=\"text-\[15px\] font-semibold\" style=\{\{ color: theme\.dangerText \}\}>\{isDeleting \? 'Deleting…' : 'Delete'\}<\/Text>/)
  assert.match(workoutEditSource, /<Pressable className=\"mt-4 items-center justify-center px-4 py-2\" disabled=\{isDeleting\} onPress=\{onClose\}>/)

  assert.match(workoutEditSource, /import \{ getAppTheme \} from '\.\.\/theme\/app-theme\.js'/)
  assert.match(workoutEditSource, /from '\.\.\/ui\/primitives\.js'/)
  assert.match(workoutEditSource, /export function WorkoutEditView\(/)
  assert.match(workoutEditSource, /const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.doesNotMatch(workoutEditSource, /#34D399|#243041|#111827|text-white|text-slate-400|text-slate-300/)

  assert.match(workoutSheetSource, /SafeAreaProvider/)
  assert.match(workoutSheetSource, /SafeAreaView/)
  assert.match(workoutSheetSource, /useSafeAreaInsets/)
  assert.match(workoutSheetSource, /AppButton/)
  assert.match(workoutSheetSource, /AppSurfaceCard/)

  assert.match(programSheetSource, /import \{ SafeAreaProvider, SafeAreaView, useSafeAreaInsets \} from 'react-native-safe-area-context';/)
  assert.match(programSheetSource, /from '\.\.\/theme\/app-theme\.js'/)
  assert.match(programSheetSource, /from '\.\.\/ui\/primitives\.js'/)
  assert.match(programSheetSource, /AppSurfaceCard/)
  assert.match(programSheetSource, /AppStatusIconBadge/)
  assert.match(programSheetSource, /ProgramSheetContent/)
  assert.match(programSheetSource, /const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(programSheetSource, /SafeAreaView/)
  assert.match(programSheetSource, /useSafeAreaInsets/)
  assert.match(programSheetSource, /<Modal visible=\{isVisible\} animationType="slide" onRequestClose=\{onClose\}>/)
  assert.doesNotMatch(programSheetSource, /transparent animationType="slide"/)
  assert.doesNotMatch(programSheetSource, /rounded-t-\[28px\]/)
  assert.match(programSheetSource, /theme\.accent|resolvedTheme\.accent/)
  assert.match(primitivesSource, /size === 'sm'/)
  assert.match(primitivesSource, /h-8 w-8 rounded-\[10px\]/)
  assert.match(programSheetSource, /size="sm"/)
  assert.match(programSheetSource, /resolvedTheme\.accentSoft/)
  assert.match(programSheetSource, /export function renderProgramSheet\(/)
})

test('mobile analytics and coach sheets accept the shared theme prop', () => {
  const analyticsSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/analytics-view.js'), 'utf8')
  const coachAthletesSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/coach-athletes-sheet.js'), 'utf8')
  const coachWorkspaceSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/coach-athlete-workspace-sheet.js'), 'utf8')

  assert.match(analyticsSource, /import \{ getAppTheme \} from '\.\.\/theme\/app-theme\.js'/)
  assert.match(analyticsSource, /resolvedTheme/)
  assert.match(analyticsSource, /theme=\{resolvedTheme\}/)
  assert.doesNotMatch(analyticsSource, /#243041|#111827|#0f172a|#64748b|#94a3b8|#ffffff|rgba\(5, 46, 43, 0\.9\)|rgba\(52, 211, 153, 0\.5\)/)

  assert.match(coachAthletesSource, /import \{ getAppTheme \} from '\.\.\/theme\/app-theme\.js'/)
  assert.match(coachAthletesSource, /AppSheetHeader/)
  assert.match(coachAthletesSource, /AppButton/)
  assert.match(coachAthletesSource, /AppSearchInput/)
  assert.match(coachAthletesSource, /AppListRow/)
  assert.match(coachAthletesSource, /CoachAthleteRow/)
  assert.match(coachAthletesSource, /label="Invite athlete"/)
  assert.match(coachAthletesSource, /theme=\{resolvedTheme\}[\s\S]*label="Invite athlete"/)
  assert.match(coachAthletesSource, /backgroundColor: resolvedTheme\.accentSurface/)
  assert.match(coachAthletesSource, /borderColor: resolvedTheme\.accentBorder/)
  assert.match(coachAthletesSource, /const trailing = isSelected[\s\S]*theme\.accent/)
  assert.match(coachAthletesSource, /CoachAthletesSheetContent/)
  assert.match(coachAthletesSource, /const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(coachAthletesSource, /theme=\{resolvedTheme\}/)
  assert.match(coachAthletesSource, /title="Athletes"/)
  assert.match(coachAthletesSource, /export function CoachAthletesSheet\(/)

  assert.match(coachWorkspaceSource, /import \{ getAppTheme \} from '\.\.\/theme\/app-theme\.js'/)
  assert.match(coachWorkspaceSource, /from '\.\.\/ui\/primitives\.js'/)
  assert.match(coachWorkspaceSource, /AppSheetHeader/)
  assert.match(coachWorkspaceSource, /AppButton/)
  assert.match(coachWorkspaceSource, /AppSurfaceCard/)
  assert.match(coachWorkspaceSource, /WorkspaceCard/)
  assert.match(coachWorkspaceSource, /CoachAthleteWorkspaceSheetContent/)
  assert.match(coachWorkspaceSource, /const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(coachWorkspaceSource, /theme=\{resolvedTheme\}|theme=\{theme\}/)
  assert.match(coachWorkspaceSource, /export function CoachAthleteWorkspaceSheet\(/)
})

test('mobile shared renderers and app styles are theme-driven instead of fixed dark literals', () => {
  const renderersSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/renderers.js'), 'utf8')
  const stylesSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/styles.js'), 'utf8')
  const cardsSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/ui/cards.js'), 'utf8')
  const primitivesSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/ui/primitives.js'), 'utf8')

  assert.match(primitivesSource, /export function AppSurfaceCard\(/)
  assert.match(primitivesSource, /export function AppButton\(/)
  assert.match(primitivesSource, /export function AppSheetHeader\(/)
  assert.match(primitivesSource, /export function AppSegmentedControl\(/)
  assert.match(primitivesSource, /export function AppListRow\(/)
  assert.match(primitivesSource, /export function AppSearchInput\(/)
  assert.match(primitivesSource, /export function AppStatusBadge\(/)
  assert.match(primitivesSource, /theme\./)

  assert.match(cardsSource, /from '\.\/primitives\.js'/)
  assert.match(cardsSource, /AppSurfaceCard/)
  assert.match(cardsSource, /AppButton/)
  assert.doesNotMatch(cardsSource, /bg-slate-/)
  assert.doesNotMatch(cardsSource, /text-white/)
  assert.doesNotMatch(cardsSource, /text-slate-/)

  assert.match(renderersSource, /styles\.theme\./)
  assert.match(renderersSource, /styles\.theme\.text/)
  assert.match(renderersSource, /styles\.theme\.textMuted|styles\.theme\.textSoft/)
  assert.match(renderersSource, /styles\.theme\.accentText|styles\.theme\.accent/)
  assert.doesNotMatch(renderersSource, /text-white/)
  assert.doesNotMatch(renderersSource, /text-slate-/)
  assert.doesNotMatch(renderersSource, /bg-slate-/)
  assert.doesNotMatch(renderersSource, /bg-emerald-/)

  assert.match(stylesSource, /theme\.surface/)
  assert.match(stylesSource, /theme\.border/)
  assert.match(stylesSource, /theme\.text/)
  assert.match(stylesSource, /theme\.accentText|theme\.accent/)
})

test('mobile shared renderers and cards support a reusable EmptyCard separate from populated SurfaceCard variants and list rows', () => {
  const renderersSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/renderers.js'), 'utf8')
  const cardsSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/ui/cards.js'), 'utf8')
  const renderPlansSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/render-plans.js'), 'utf8')
  const emptyCardBlock = cardsSource.match(/export function EmptyCard\([\s\S]*?\n\}/)?.[0] || ''
  const createWorkoutCardBlock = cardsSource.match(/export function CreateWorkoutCard\([\s\S]*?\n\}/)?.[0] || ''

  assert.match(renderersSource, /section\.type === 'empty-state-card'/)
  assert.match(renderersSource, /<EmptyCard/)
  assert.match(renderersSource, /section\.type === 'create-workout-card'/)
  assert.match(renderersSource, /<CreateWorkoutCard/)
  assert.doesNotMatch(renderersSource, /variant="empty-state"/)
  assert.match(renderPlansSource, /section\.type === 'empty-state-card'/)
  assert.match(renderPlansSource, /section\.type === 'create-workout-card'/)
  assert.match(cardsSource, /export function EmptyCard\(/)
  assert.match(cardsSource, /export function CreateWorkoutCard\(/)
  assert.doesNotMatch(cardsSource, /variant === 'empty-state'/)
  assert.doesNotMatch(emptyCardBlock, /AppButton/)
  assert.doesNotMatch(emptyCardBlock, /actionLabel/)
  assert.match(emptyCardBlock, /text-\[16px\] font-normal/)
  assert.match(emptyCardBlock, /text-\[13px\][^\n]*font-normal|font-normal[^\n]*text-\[13px\]/)
  assert.doesNotMatch(emptyCardBlock, /text-\[18px\] font-semibold/)
  assert.doesNotMatch(emptyCardBlock, /text-\[15px\] leading-\[22px\]/)
  assert.match(createWorkoutCardBlock, /\{title\}/)
  assert.match(createWorkoutCardBlock, /\{subtitle\}/)
  assert.match(createWorkoutCardBlock, /<Plus/)
  assert.doesNotMatch(createWorkoutCardBlock, /AppButton/)
})
