import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

test('mobile app shell keeps workout-sheet state but delegates workout-open and start-workout orchestration to the extracted helpers', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const trainScreenSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/train/train-screen-models.js'), 'utf8')
  const trainIndexSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/train/index.js'), 'utf8')

  assert.match(appSource, /const \[isWorkoutSheetOpen, setIsWorkoutSheetOpen\] = useState\(false\);/)
  assert.match(appSource, /const \[selectedProgramWorkoutPreview, setSelectedProgramWorkoutPreview\] = useState\(null\);/)
  assert.match(appSource, /const \[selectedWorkoutSessionPreview, setSelectedWorkoutSessionPreview\] = useState\(null\);/)
  assert.match(appSource, /const \[isStartingWorkout, setIsStartingWorkout\] = useState\(false\);/)
  assert.match(appSource, /const \[isActiveWorkoutViewOpen, setIsActiveWorkoutViewOpen\] = useState\(false\);/)
 assert.match(appSource, /const workoutSheetSession = selectedWorkoutSessionPreview \|\| session;/)
 assert.match(appSource, /const resolvedWorkoutSheetProgramWorkout = selectedProgramWorkoutPreview \|\| trainState\.programWorkout;/)
 assert.match(appSource, /const effectiveWorkoutSheetModel = useMemo\([\s\S]*selectedProgramWorkoutPreview[\s\S]*workoutName: selectedProgramWorkoutPreview\.nameSnapshot \?\? ''[\s\S]*programWorkoutId: selectedProgramWorkoutPreview\.id \|\| selectedProgramWorkoutPreview\.programWorkoutId \|\| null[\s\S]*: workoutModel,[\s\S]*\[selectedProgramWorkoutPreview, workoutModel\]\n\s*\);/)
 assert.match(appSource, /const workoutSheetModel = useMemo\(\(\) => getWorkoutSheetModel\(\{ workoutModel: effectiveWorkoutSheetModel, session: workoutSheetSession, programWorkout: resolvedWorkoutSheetProgramWorkout, selectedDayId: selectedCalendarDayId \}\), \[effectiveWorkoutSheetModel, resolvedWorkoutSheetProgramWorkout, selectedCalendarDayId, workoutSheetSession\]\);/)

  assert.match(appSource, /import \{ orchestrateStartWorkoutFromSheet \} from '\.\/src\/train\/start-workout-selection\.js';/)
  assert.match(appSource, /if \(targetKey === 'workout'\) \{[\s\S]*requestedCalendarDayId[\s\S]*requestedProgramWorkoutId/)
  assert.match(appSource, /const \{[\s\S]*requestedCalendarDayId,[\s\S]*requestedDayWorkoutPreview,[\s\S]*requestedProgramWorkoutId,[\s\S]*immediateProgramWorkout,[\s\S]*workoutOpenRequestContext,[\s\S]*\} = deriveWorkoutOpenRequestContext\(\{[\s\S]*payload,[\s\S]*selectedCalendarDayId,[\s\S]*selectedProgramWorkoutId,[\s\S]*trainState,[\s\S]*\}\);/)
  assert.match(appSource, /await orchestrateWorkoutOpen\(\{[\s\S]*targetKey,[\s\S]*payload,[\s\S]*selectedCalendarDayId,[\s\S]*selectedProgramWorkoutId,[\s\S]*workoutOpenRequestContext: \{[\s\S]*requestedCalendarDayId,[\s\S]*requestedDayWorkoutPreview,[\s\S]*requestedProgramWorkoutId,[\s\S]*\.\.\.workoutOpenRequestContext,[\s\S]*\},[\s\S]*requestedProgramWorkoutId,[\s\S]*immediateProgramWorkout,[\s\S]*effectiveSessionStore,[\s\S]*workoutClient: createMobileWorkoutClient\(\{ accessToken: authSession\.accessToken \}\),[\s\S]*session,[\s\S]*trainState,[\s\S]*selectedWorkoutSessionPreview,[\s\S]*setIsWorkoutSheetOpen,[\s\S]*setSelectedProgramWorkoutPreview,[\s\S]*setSelectedWorkoutSessionPreview,[\s\S]*\}\);/)
  assert.doesNotMatch(appSource, /if \(targetKey === 'workout'\) \{[\s\S]*applyWorkoutOpenStateTransition\(/)
  assert.doesNotMatch(appSource, /if \(targetKey === 'workout'\) \{[\s\S]*settleWorkoutOpenSelection\(/)
  assert.doesNotMatch(appSource, /if \(targetKey === 'workout'\) \{[\s\S]*resolveWorkoutOpenPreview\(/)

  assert.match(appSource, /<WorkoutSheet[\s\S]*isVisible=\{isWorkoutSheetOpen\}/)
  assert.match(appSource, /<WorkoutSheet[\s\S]*isStartingWorkout=\{isStartingWorkout\}/)
  assert.match(appSource, /<WorkoutSheet[\s\S]*onStartWorkout=\{handleStartWorkoutFromSheet\}/)
  assert.match(appSource, /async function handleStartWorkoutFromSheet\(payload = null\) \{[\s\S]*await orchestrateStartWorkoutFromSheet\(\{[\s\S]*effectiveSessionStore,[\s\S]*selectedProgramWorkoutId: payload\?\.programWorkoutId \|\| selectedProgramWorkoutId,[\s\S]*session,[\s\S]*selectedWorkoutSessionPreview,[\s\S]*workoutSheetModel,[\s\S]*startedAt: new Date\(\)\.toISOString\(\),[\s\S]*setIsStartingWorkout,[\s\S]*setSession,[\s\S]*setIsWorkoutSheetOpen,[\s\S]*setIsActiveWorkoutViewOpen,[\s\S]*\}\);[\s\S]*\}/)
  assert.doesNotMatch(appSource, /async function handleStartWorkoutFromSheet\(payload = null\) \{[\s\S]*runAfterInteractions: InteractionManager\.runAfterInteractions/)
  assert.doesNotMatch(appSource, /async function handleStartWorkoutFromSheet\(payload = null\) \{[\s\S]*buildStartWorkoutPlan\(/)
  assert.doesNotMatch(appSource, /async function handleStartWorkoutFromSheet\(payload = null\) \{[\s\S]*effectiveSessionStore\.startSession\(/)
  assert.doesNotMatch(appSource, /async function handleStartWorkoutFromSheet\(payload = null\) \{[\s\S]*InteractionManager\.runAfterInteractions\(\(\) => \{/)

  assert.match(trainScreenSource, /targetKey: 'workout'/)
  assert.match(trainScreenSource, /actionPayload: \{ selectedDayId: day.id, programWorkoutId: primaryWorkout\?\.id \|\| null \}/)
  assert.match(trainScreenSource, /calendarStripDays: calendarModel\.days\.map\(\(day\) => \(\{[\s\S]*targetKey: day\.targetKey,[\s\S]*actionPayload: day\.actionPayload,[\s\S]*\}\)\)/)
  assert.match(trainIndexSource, /function getCalendarDayTarget\(\{ trainState, day \}\) \{[\s\S]*return 'calendar-day-select'[\s\S]*\}/)
})

test('mobile workout sheet matches the workout preview reference structure and uses NativeWind plus Lucide', () => {
  const sheetSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-sheet.js'), 'utf8')
  const modelSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/train/workout-sheet-models.js'), 'utf8')

  assert.match(sheetSource, /Start Workout/)
  assert.match(modelSource, /Resume Workout/)
  assert.match(modelSource, /Workout in progress/)
  assert.match(sheetSource, /model\.resumeNotice/)
  assert.match(sheetSource, /WorkoutSheetExerciseBlock/)
  assert.match(sheetSource, /import \{ Image, Modal, Pressable, ScrollView, Text, View \} from 'react-native';/)
  assert.match(sheetSource, /exercise\.thumbnailUrl \? \([\s\S]*<Image source=\{\{ uri: exercise\.thumbnailUrl \}\}/)
  assert.match(sheetSource, /\) : \([\s\S]*<WorkoutThumbnailIcon icon=\{exercise\.thumbnailIcon \|\| 'dumbbell'\} theme=\{theme\} \/>/)

  assert.match(sheetSource, /from '\.\.\/theme\/app-theme\.js'/)
  assert.match(sheetSource, /from '\.\.\/ui\/primitives\.js'/)
  assert.match(sheetSource, /getAppTheme\('dark'\)/)
  assert.match(sheetSource, /AppButton/)
  assert.match(sheetSource, /AppSurfaceCard/)
  assert.match(sheetSource, /<Text className=\"text-\[26px\] font-bold leading-\[30px\]\" style=\{\{ color: resolvedTheme\.text \}\}>\{model\.title\}<\/Text>/)
  assert.match(sheetSource, /<Text className=\"flex-1 text-\[22px\] font-semibold leading-\[28px\]\" style=\{\{ color: theme\.text \}\}>\{exercise\.name\}<\/Text>/)
  assert.doesNotMatch(sheetSource, /<Text className=\"text-\[34px\] font-bold\" style=\{\{ color: resolvedTheme\.text \}\}>\{model\.title\}<\/Text>/)
  assert.doesNotMatch(sheetSource, /<Text className=\"text-\[30px\] font-bold\" style=\{\{ color: resolvedTheme\.text \}\}>\{model\.title\}<\/Text>/)
  assert.match(sheetSource, /w-24 text-center text-\[11px\]/)
  assert.match(sheetSource, /flex-1 text-center text-\[11px\]/)
  assert.match(sheetSource, /flex-1 flex-row items-center justify-center gap-1/)
  assert.match(sheetSource, /<View key=\{set\.id\} className="min-h-\[50px\] flex-row items-center">/)
  assert.match(sheetSource, /Clock3/)
  assert.match(sheetSource, /ArrowUpDown/)
  assert.match(sheetSource, /X/)
  assert.match(sheetSource, /className=/)
  assert.match(sheetSource, /SafeAreaProvider/)
  assert.match(sheetSource, /useSafeAreaInsets/)
  assert.doesNotMatch(sheetSource, /#34D399|#243041|#111827|text-white|text-slate-400|text-slate-300/)

  assert.match(modelSource, /getWorkoutSheetModel/)
  assert.match(modelSource, /summaryItems/)
  assert.match(modelSource, /Start Workout/)
  assert.match(modelSource, /programWorkoutId/)
  assert.match(modelSource, /session\.exercises/)
  assert.match(modelSource, /nameSnapshot \|\| exercise\.name/)
  assert.match(modelSource, /actualLoad \?\? set\.prescribedLoad/)
  assert.match(modelSource, /actualReps \?\? set\.prescribedReps/)
  assert.match(modelSource, /actualRpe \?\? set\.prescribedRpe/)
  assert.match(modelSource, /weightHeader/)
  assert.match(modelSource, /sets: getExerciseSets/)
})
