import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

test('mobile app shell owns a dedicated profile view opened from the top header user icon', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const shellSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/shell-renderers.js'), 'utf8')

  assert.match(appSource, /const \[isProfileViewOpen, setIsProfileViewOpen\] = useState\(false\);/)
  assert.match(appSource, /<ProfileView[\s\S]*isVisible=\{isProfileViewOpen\}/)
  assert.match(appSource, /onProfileHeaderPress: \(\) => \{[\s\S]*setIsProfileViewOpen\(true\);[\s\S]*\}/)
  assert.doesNotMatch(appSource, /onProfileHeaderPress: \(\) => \{[\s\S]*if \(isAthleteLimitedState\) return;[\s\S]*setIsProfileViewOpen\(true\);[\s\S]*\}/)
  assert.match(shellSource, /onProfileHeaderPress/)
  assert.match(shellSource, /<Pressable style=\{styles\.brandIconButton\} onPress=\{onProfileHeaderPress\}>/)
})

test('mobile profile view uses the requested simple section structure and related icons', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /ProfileView/)
  assert.match(profileSource, /function getProfileIdentityModel\(profile, role = 'athlete'\)/)
  assert.match(profileSource, /displayName: fullName \|\| profile\?\.firstName \|\| 'Athlete'/)
  assert.match(profileSource, /metaLabel: ''/)
  assert.match(profileSource, /UserCircle2/)
  assert.match(profileSource, /text-\[32px\] font-bold\" style=\{\{ color: resolvedTheme\.text \}\}/)
  assert.match(profileSource, /profileIdentity\.metaLabel \? \(/)
  assert.match(profileSource, /TRAINING/)
  assert.match(profileSource, /PREFERENCES/)
  assert.match(profileSource, /Connected Apps/)

  assert.match(profileSource, /Profile/)
  assert.match(profileSource, /Athletes/)
  assert.match(profileSource, /Exercises/)
  assert.match(profileSource, /Programs/)
  assert.match(profileSource, /Theme/)
  assert.match(profileSource, /Units/)
  assert.match(profileSource, /Week Start/)
  assert.match(profileSource, /Reminder/)
  assert.match(profileSource, /Languages/)
  assert.match(profileSource, /Apple Health/)
  assert.doesNotMatch(profileSource, /label: 'Language'/)
  assert.doesNotMatch(profileSource, /label: 'Wearables'/)

  assert.match(profileSource, /ChevronLeft/)
  assert.match(profileSource, /ChevronRight/)
  assert.match(profileSource, /User/)
  assert.match(profileSource, /Users/)
  assert.match(profileSource, /Dumbbell/)
  assert.match(profileSource, /CalendarRange/)
  assert.match(profileSource, /Palette/)
  assert.match(profileSource, /Ruler/)
  assert.match(profileSource, /CalendarDays/)
  assert.match(profileSource, /Bell/)
  assert.match(profileSource, /Languages/)
  assert.match(profileSource, /HeartPulse/)
  assert.doesNotMatch(profileSource, /Watch/)
})

test('mobile profile view can open a dedicated profile details form from the Profile option', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')
  const skeletonSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/ui/skeleton.js'), 'utf8')

  assert.match(skeletonSource, /export function Skeleton\(/)
  assert.match(skeletonSource, /className: `rounded-md \$\{className\}`\.trim\(\)/)
  assert.doesNotMatch(skeletonSource, /animate-pulse/)
  assert.match(profileSource, /import \{ Skeleton \} from '\.\.\/ui\/skeleton\.js';/)
  assert.match(profileSource, /const \[activeScreen, setActiveScreen\] = useState\('menu'\)/)
  assert.match(profileSource, /function ProfileDetailsView\(/)
  assert.match(profileSource, /title: 'Profile'/)
  assert.match(profileSource, /label: 'First name'/)
  assert.match(profileSource, /label: 'Last name'/)
  assert.match(profileSource, /label: 'Date of birth'/)
  assert.match(profileSource, /label: 'Gender'/)
  assert.match(profileSource, /label: 'Position'/)
  assert.match(profileSource, /label: 'Height'/)
  assert.match(profileSource, /label: 'Weight'/)
  assert.match(profileSource, /Photo Upload/)
  assert.match(profileSource, /ImagePlus/)
  assert.match(profileSource, /const \[isAvatarImageLoading, setIsAvatarImageLoading\] = useState\(false\)/)
  assert.match(profileSource, /setIsAvatarImageLoading\(Boolean\(safeDraftAvatarUri\)\)/)
  assert.match(profileSource, /onLoadStart=\{\(\) => setIsAvatarImageLoading\(true\)\}/)
  assert.match(profileSource, /onLoadEnd=\{\(\) => setIsAvatarImageLoading\(false\)\}/)
  assert.match(profileSource, /isAvatarImageLoading \? \([\s\S]*<Skeleton[\s\S]*className="absolute inset-0 rounded-full"[\s\S]*theme=\{resolvedTheme\}/)
  assert.match(profileSource, /onPress=\{\(\) => onSelect\?\.\(item\)\}/)
  assert.match(profileSource, /if \(activeScreen === 'profile-details'\)/)
})

test('mobile profile view can open a dedicated exercises list from the Exercises option and hand pressed exercises to the shared exercise detail sheet', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const sharedExerciseLibrarySource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/exercise-library-view.js'), 'utf8')

  assert.match(sharedExerciseLibrarySource, /import \{ Skeleton \} from '\.\.\/ui\/skeleton\.js'/)
  assert.match(sharedExerciseLibrarySource, /function ExerciseLibrarySkeletonRows\({ theme, selectable = false }\)/)
  assert.match(sharedExerciseLibrarySource, /Array\.from\(\{ length: 6 \}\)/)
  assert.match(sharedExerciseLibrarySource, /<Skeleton[\s\S]*className="mr-3 h-14 w-14 rounded-\[14px\]"[\s\S]*theme=\{theme\}/)
  assert.match(sharedExerciseLibrarySource, /<Skeleton[\s\S]*className="h-5 flex-1 rounded-full"[\s\S]*theme=\{theme\}/)
  assert.match(sharedExerciseLibrarySource, /<Skeleton[\s\S]*className="h-8 w-8 rounded-full"[\s\S]*theme=\{theme\}/)
  assert.match(sharedExerciseLibrarySource, /isLoading \? \([\s\S]*<ExerciseLibrarySkeletonRows theme=\{resolvedTheme\} selectable=\{selectable\} \/>/)
  assert.doesNotMatch(sharedExerciseLibrarySource, /Loading exercises\.\.\./)
  assert.match(profileSource, /function ExercisesView\({ onBack, exercises, isLoading = false, error = '', searchQuery = '', onSearchChange, onOpenExerciseDetail, theme }\)/)
  assert.match(profileSource, /import \{ ExerciseLibraryView \} from '\.\/exercise-library-view\.js'/)
  assert.match(profileSource, /title: 'Exercises'/)
  assert.match(profileSource, /Search or Create Exercises/)
  assert.match(profileSource, /<ExerciseLibraryView[\s\S]*title=\{EXERCISES_VIEW_MODEL\.title\}[\s\S]*searchPlaceholder=\{EXERCISES_VIEW_MODEL\.searchLabel\}[\s\S]*exercises=\{exercises\}[\s\S]*searchQuery=\{searchQuery\}[\s\S]*onSearchChange=\{onSearchChange\}[\s\S]*onPressExercise=\{onOpenExerciseDetail\}/)
  assert.match(profileSource, /import \* as data from '.*packages\/data\/src\/index\.js'/)
  assert.match(profileSource, /function createMobileExerciseLibraryClient\(\{ env = process\.env, fetchImpl = globalThis\.fetch \} = \{\}\)/)
  assert.match(profileSource, /data\.exercises\.createSupabaseRestExerciseRepository\(/)
  assert.match(profileSource, /const \[exerciseLibraryState, setExerciseLibraryState\] = useState\(\{ items: \[], isLoading: false, error: '' \}\)/)
  assert.match(profileSource, /const \[exerciseSearchQuery, setExerciseSearchQuery\] = useState\(''\)/)
  assert.match(profileSource, /useEffect\(\(\) => \{[\s\S]*if \(activeScreen !== 'exercises'\) return[\s\S]*exerciseClient\.listExercises\(\)/)
  assert.match(profileSource, /const filteredExercises = exerciseLibraryState\.items\.filter\(/)
  assert.match(sharedExerciseLibrarySource, /<Image source=\{\{ uri: exercise\.thumbnailUrl \}\} className="h-full w-full" resizeMode="cover" \/>/)
  assert.match(sharedExerciseLibrarySource, /exercise\.thumbnailUrl \? \(/)
  assert.match(sharedExerciseLibrarySource, /AppSheetHeader/)
  assert.match(sharedExerciseLibrarySource, /AppNoticeCard/)
  assert.match(sharedExerciseLibrarySource, /AppSearchInput/)
  assert.match(sharedExerciseLibrarySource, /placeholder=\{searchPlaceholder\}/)
  assert.match(sharedExerciseLibrarySource, /<Pressable key=\{exercise\.id\} className="flex-row items-center py-3" style=\{styles\.exerciseRow\} onPress=\{\(\) => handleExercisePress\(exercise\)\}>/)
  assert.match(profileSource, /if \(activeScreen === 'exercises'\) \{[\s\S]*onOpenExerciseDetail=\{onOpenExerciseDetail\}/)
  assert.doesNotMatch(profileSource, /exercise-demo-1/)
  assert.doesNotMatch(profileSource, /Barbell Deadlift/)

  assert.match(profileSource, /if \(item\?\.id === 'exercises'\) \{[\s\S]*setActiveScreen\('exercises'\)/)
  assert.match(appSource, /<ProfileView isVisible=\{isProfileViewOpen\}[\s\S]*onOpenExerciseDetail=\{\(exercise\) => handleOpenExerciseDetail\(exercise, 'profile-view'\)\}/)
})

test('mobile profile view can open a dedicated programs list backed by the live program repository and hand selected programs to the shared program sheet', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')

  assert.match(profileSource, /function createMobileProgramLibraryClient\(\{ env = process\.env, fetchImpl = globalThis\.fetch \} = \{\}\)/)
  assert.match(profileSource, /AppSheetHeader/)
  assert.match(profileSource, /AppNoticeCard/)
  assert.match(profileSource, /data\.programs\.createSupabaseRestProgramRepository\(/)
  assert.match(profileSource, /function ProgramsView\({ onBack, programs, isLoading = false, error = '', onOpenProgramDetail, theme }\)/)
  assert.match(profileSource, /title: 'Programs'/)
  assert.doesNotMatch(profileSource, /title: 'All Programs'/)
  assert.match(profileSource, /activeSectionTitle: 'ACTIVE PROGRAMS'/)
  assert.match(profileSource, /completedSectionTitle: 'COMPLETED PROGRAMS'/)
  assert.doesNotMatch(profileSource, /activeSectionTitle: 'Active Program'/)
  assert.match(profileSource, /PROGRAMS_VIEW_MODEL\.activeSectionTitle/)
  assert.match(profileSource, /PROGRAMS_VIEW_MODEL\.completedSectionTitle/)
  assert.match(profileSource, /className="text-\[12px\] font-semibold uppercase tracking-\[1\.2px\]" style=\{\{ color: resolvedTheme\.textSoft \}\}/)
  assert.match(profileSource, /No Active Programs/)
  assert.match(profileSource, /No Completed Programs/)
  assert.match(profileSource, /const \[programLibraryState, setProgramLibraryState\] = useState\(\{ items: \[], isLoading: false, error: '' \}\)/)
  assert.match(profileSource, /useEffect\(\(\) => \{[\s\S]*if \(activeScreen !== 'programs'\) return/)
  assert.match(profileSource, /const loadPrograms = role === 'coach'/)
  assert.match(profileSource, /\? \(\) => programClient\.listPrograms\(\)/)
  assert.match(profileSource, /: \(\) => athleteProfile\?\.id[\s\S]*programClient\.listProgramsForAthlete\(athleteProfile\.id\)[\s\S]*Promise\.resolve\(\[\]\)/)
  assert.match(profileSource, /loadPrograms\(\)/)
  assert.match(profileSource, /const activePrograms = programs\.filter\(/)
  assert.match(profileSource, /const completedPrograms = programs\.filter\(/)
  assert.match(profileSource, /program\.name/)
  assert.match(profileSource, /function ProgramsView\([\s\S]*function ProgramListIcon\(\{ theme \}\)/)
  assert.match(profileSource, /function ProgramsView\([\s\S]*<CalendarRange color=\{theme\.iconMuted\} size=\{24\} strokeWidth=\{2\.1\} \/>/)
  assert.match(profileSource, /function ProgramsView\([\s\S]*function renderProgramRows\([\s\S]*<AppListRow[\s\S]*title=\{program\.name\}[\s\S]*leading=\{<ProgramListIcon theme=\{resolvedTheme\} \/>\}[\s\S]*trailing=\{<ChevronRight color=\{resolvedTheme\.iconMuted\} size=\{20\} strokeWidth=\{2\.2\} \/>\}/)
  assert.doesNotMatch(profileSource, /function ProgramsView\([\s\S]*renderProgramRows\([\s\S]*AppSurfaceCard/)
  assert.doesNotMatch(profileSource, /function ProgramsView\([\s\S]*renderProgramRows\([\s\S]*program\.weeksCount/)
  assert.doesNotMatch(profileSource, /function ProgramsView\([\s\S]*renderProgramRows\([\s\S]*program\.workoutsCount/)
  assert.match(profileSource, /onPress=\{\(\) => onOpenProgramDetail\?\.\(program\)\}/)
  assert.doesNotMatch(profileSource, /<AppSurfaceCard theme=\{resolvedTheme\} contentClassName="px-5 py-5">/)
  assert.doesNotMatch(profileSource, /function ProgramsView\([\s\S]*renderProgramRows\([\s\S]*formatProgramSummary\(program\)/)
  assert.doesNotMatch(profileSource, /10 weeks • 40 workouts/)
  assert.doesNotMatch(profileSource, /Spring '26 Hypertrophy/)
  assert.doesNotMatch(profileSource, /Create New Program/)
  assert.match(profileSource, /if \(activeScreen === 'programs'\) \{[\s\S]*programs=\{programLibraryState\.items\}[\s\S]*onOpenProgramDetail=\{onOpenProgramDetail\}/)
  assert.match(profileSource, /if \(item\?\.id === 'programs'\) \{[\s\S]*setActiveScreen\('programs'\)/)
  assert.match(appSource, /<ProfileView isVisible=\{isProfileViewOpen\}[\s\S]*onOpenProgramDetail=\{\(program\) => handleOpenProgramDetail\(program, 'profile-view'\)\}/)
})

test('mobile profile view can open a dedicated theme view from the Theme option and persist a real theme preference', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')

  assert.match(profileSource, /function ReminderFallbackPicker\({ value, theme }\) \{[\s\S]*const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(profileSource, /function ProfileOptionRow\({ item, onSelect, theme }\) \{[\s\S]*const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(profileSource, /function ProfileSection\({ section, onSelect, theme }\) \{[\s\S]*const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(profileSource, /function ProfileDropdownField\({ field, selectedValue, onOpen, theme }\) \{[\s\S]*const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(profileSource, /AppFieldShell/)
  assert.match(profileSource, /function ProfileDropdownSheet\({ visible, title, options, selectedValue, onSelect, onClose, theme }\) \{[\s\S]*const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(profileSource, /function ProfileField\({ field, onChange, onOpenDatePicker, onOpenDropdown, unitsPreference, theme }\) \{[\s\S]*const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(profileSource, /AppFieldShell/)
  assert.match(profileSource, /function ExercisesView\({ onBack, exercises, isLoading = false, error = '', searchQuery = '', onSearchChange, onOpenExerciseDetail, theme }\) \{[\s\S]*const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(profileSource, /function ThemeView\({ onBack, themePreference = 'dark', onChangeThemePreference, theme }\) \{[\s\S]*const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(profileSource, /function ThemeView\(/)
  assert.match(profileSource, /title: 'Theme'/)
  assert.match(profileSource, /Light/)
  assert.match(profileSource, /Dark/)
  assert.match(profileSource, /themePreference/)
  assert.match(profileSource, /onChangeThemePreference/)
  assert.match(profileSource, /function handleThemeSelection\(nextThemePreference\) \{[\s\S]*onChangeThemePreference\?\.\(nextThemePreference\)[\s\S]*setActiveScreen\(\(current\) => \(current === 'theme' \? 'theme' : current\)\)/)
  assert.match(profileSource, /Dark mode reduces eye strain in low-light/)
  assert.match(profileSource, /resolvedTheme\.accentText|theme\.accentText/)
  assert.match(profileSource, /resolvedTheme\.accentSurface|theme\.accentSurface/)
  assert.match(profileSource, /resolvedTheme\.accentBorder|theme\.accentBorder/)
  assert.doesNotMatch(profileSource, /text-\[#A78BFA\]/)
  assert.doesNotMatch(profileSource, /bg-\[#312E81\]/)
  assert.match(profileSource, /if \(activeScreen === 'theme'\)/)
  assert.match(profileSource, /if \(activeScreen === 'theme'\) \{[\s\S]*onChangeThemePreference=\{handleThemeSelection\}/)
  assert.match(profileSource, /if \(item\?\.id === 'theme'\) \{[\s\S]*setActiveScreen\('theme'\)/)

  assert.match(appSource, /import \{[\s\S]*orchestrateThemePreferenceChange,[\s\S]*\} from '\.\/src\/auth\/auth-profile-actions\.js';/)
  assert.match(appSource, /async function handleThemePreferenceChange\(nextThemePreference\) \{[\s\S]*await orchestrateThemePreferenceChange\(\{[\s\S]*nextThemePreference,[\s\S]*isCoachBootstrapState,[\s\S]*updateCoachProfile,[\s\S]*updateAthleteProfile,[\s\S]*setAuthErrorMessage,[\s\S]*setAuthNoticeMessage,[\s\S]*setProfileSaveNotice,[\s\S]*logger: console,[\s\S]*\}\);[\s\S]*\}/)
  assert.match(appSource, /<ProfileView isVisible=\{isProfileViewOpen\}[\s\S]*themePreference=\{appThemePreference\}[\s\S]*onChangeThemePreference=\{handleThemePreferenceChange\}/)
  assert.match(appSource, /<StatusBar style=\{appThemePreference === 'light' \? 'dark' : 'light'\} \/>/)
  assert.doesNotMatch(appSource, /useEffect\(\(\) => \{[\s\S]*setIsProfileViewOpen\(false\);[\s\S]*\}, \[bootstrapState, coachAthleteOptions, fallbackTrainState\]\);/)
})

test('mobile profile view can open a dedicated units view from the Units option', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')

  assert.match(profileSource, /function UnitsView\({ onBack, weightUnitPreference = 'lb', distanceUnitPreference = 'km', onChangeWeightUnitPreference, onChangeDistanceUnitPreference, theme }\)/)
  assert.match(profileSource, /title: 'Units'/)
  assert.match(profileSource, /Weight Unit/)
  assert.match(profileSource, /Distance Unit/)
  assert.match(profileSource, /These units will be used throughout the app for logging and displaying your workout data\./)
  assert.match(profileSource, /weightUnitPreference/)
  assert.match(profileSource, /distanceUnitPreference/)
  assert.match(profileSource, /onChangeWeightUnitPreference/)
  assert.match(profileSource, /onChangeDistanceUnitPreference/)
  assert.match(profileSource, /row\.id === 'weight-unit'/)
  assert.match(profileSource, /onChangeWeightUnitPreference\?\.\(option\.id\)/)
  assert.match(profileSource, /onChangeDistanceUnitPreference\?\.\(option\.id\)/)
  assert.match(profileSource, /AppSegmentedControl/)
  assert.match(profileSource, /const unitsSegmentedControlWidth = 132/)
  assert.match(profileSource, /className="w-\[132px\] flex-row rounded-\[18px\] p-1"/)
  assert.match(profileSource, /style=\{\{ width: unitsSegmentedControlWidth, borderWidth: 1, borderColor: resolvedTheme\.border, backgroundColor: resolvedTheme\.surface \}\}/)
  assert.match(profileSource, /className="flex-1 items-center justify-center rounded-\[14px\] px-5 py-2\.5"/)
  assert.match(profileSource, /className="text-center text-\[15px\] font-semibold"/)
  assert.match(profileSource, /theme\.accentText|resolvedTheme\.accentText/)
  assert.match(profileSource, /if \(activeScreen === 'units'\)/)
  assert.match(profileSource, /if \(activeScreen === 'units'\) \{[\s\S]*weightUnitPreference=\{weightUnitPreference\}[\s\S]*distanceUnitPreference=\{distanceUnitPreference\}[\s\S]*onChangeWeightUnitPreference=\{onChangeWeightUnitPreference\}[\s\S]*onChangeDistanceUnitPreference=\{onChangeDistanceUnitPreference\}/)
  assert.match(profileSource, /if \(item\?\.id === 'units'\) \{[\s\S]*setActiveScreen\('units'\)/)

  assert.match(appSource, /import \{[\s\S]*orchestrateUnitsPreferenceChange,[\s\S]*\} from '\.\/src\/auth\/auth-profile-actions\.js';/)
  assert.match(appSource, /async function handleUnitsPreferenceChange\(updates = \{\}\) \{[\s\S]*await orchestrateUnitsPreferenceChange\(\{[\s\S]*updates,[\s\S]*profileViewProfile,[\s\S]*isCoachBootstrapState,[\s\S]*updateCoachProfile,[\s\S]*updateAthleteProfile,[\s\S]*logger: console,[\s\S]*\}\);[\s\S]*\}/)
  assert.match(appSource, /<ProfileView isVisible=\{isProfileViewOpen\}[\s\S]*weightUnitPreference=\{profileViewProfile\?\.weightUnitPreference \|\| 'lb'\}[\s\S]*distanceUnitPreference=\{profileViewProfile\?\.distanceUnitPreference \|\| 'km'\}[\s\S]*onChangeWeightUnitPreference=\{\(nextWeightUnitPreference\) => handleUnitsPreferenceChange\(\{ weightUnitPreference: nextWeightUnitPreference \}\)\}[\s\S]*onChangeDistanceUnitPreference=\{\(nextDistanceUnitPreference\) => handleUnitsPreferenceChange\(\{ distanceUnitPreference: nextDistanceUnitPreference \}\)\}/)
})

test('mobile profile view can open a dedicated week start view from the Week Start option', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /function WeekStartView\(/)
  assert.match(profileSource, /title: 'Week Start'/)
  assert.match(profileSource, /Week starts on/)
  assert.match(profileSource, /Sunday/)
  assert.match(profileSource, /Monday/)
  assert.match(profileSource, /Choose which day your calendar week begins\./)
  assert.match(profileSource, /AppSegmentedControl/)
  assert.match(profileSource, /theme\.accentText|resolvedTheme\.accentText/)
  assert.match(profileSource, /if \(activeScreen === 'week-start'\)/)
  assert.match(profileSource, /if \(item\?\.id === 'week-start'\) \{[\s\S]*setActiveScreen\('week-start'\)/)
})

test('mobile profile view can open a dedicated reminder view from the Reminder option', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /function ReminderView\(/)
  assert.match(profileSource, /title: 'Workout Reminder'/)
  assert.match(profileSource, /YOUR TIMEZONE/)
  assert.match(profileSource, /America\/Toronto/)
  assert.match(profileSource, /REMINDER TIME/)
  assert.match(profileSource, /Update Reminder Time/)
  assert.match(profileSource, /We’ll send you a reminder at this time on days you have a workout scheduled\./)
  assert.match(profileSource, /theme\.accentSurface|resolvedTheme\.accentSurface/)
  assert.match(profileSource, /theme\.accentBorder|resolvedTheme\.accentBorder/)
  assert.match(profileSource, /theme\.accentText|resolvedTheme\.accentText/)
  assert.match(profileSource, /DateTimePicker/)
  assert.match(profileSource, /mode="time"/)
  assert.match(profileSource, /if \(activeScreen === 'reminder'\)/)
  assert.match(profileSource, /if \(item\?\.id === 'reminder'\) \{[\s\S]*setActiveScreen\('reminder'\)/)
})

test('mobile profile view can open a dedicated languages view from the Languages option under Reminder', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /\{ id: 'reminder', label: 'Reminder', icon: 'bell' \},\n\s*\{ id: 'languages', label: 'Languages', icon: 'languages' \}/)
  assert.match(profileSource, /function getLanguageViewModel\(languagePreference = 'en'\)/)
  assert.match(profileSource, /title: 'Languages'/)
  assert.match(profileSource, /label: languagePreference === 'fr' \? 'Langue de l’app' : 'App Language'/)
  assert.match(profileSource, /languagePreference === 'fr'[\s\S]*\{ id: 'en', label: 'Anglais' \}[\s\S]*\{ id: 'fr', label: 'Français' \}/)
  assert.match(profileSource, /\{ id: 'en', label: 'English' \}[\s\S]*\{ id: 'fr', label: 'French' \}/)
  assert.match(profileSource, /Choose the language used by the app\. Full app translation will be completed later\./)
  assert.match(profileSource, /function LanguagesView\(\{ onBack, languagePreference = 'en', onChangeLanguagePreference, theme \}\)/)
  assert.match(profileSource, /languageViewModel\.options\.map\(\(option\) =>/)
  assert.match(profileSource, /option\.id === languagePreference/)
  assert.match(profileSource, /onChangeLanguagePreference\?\.\(option\.id\)/)
  assert.match(profileSource, /if \(activeScreen === 'languages'\)/)
  assert.match(profileSource, /<LanguagesView onBack=\{\(\) => setActiveScreen\('menu'\)\} languagePreference=\{languagePreference\} onChangeLanguagePreference=\{onChangeLanguagePreference\} theme=\{resolvedTheme\} \/>/)
  assert.match(profileSource, /if \(item\?\.id === 'languages'\) \{[\s\S]*setActiveScreen\('languages'\)/)
  assert.match(profileSource, /ProfileViewContent\(\{[\s\S]*languagePreference = 'en',[\s\S]*onChangeLanguagePreference,[\s\S]*theme \}\)/)
  assert.match(profileSource, /export function ProfileView\(\{[\s\S]*languagePreference = 'en',[\s\S]*onChangeLanguagePreference,[\s\S]*theme \}\)/)
})

test('mobile profile view can open a dedicated Apple Health view from the Apple Health option', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /function AppleHealthView\(/)
  assert.match(profileSource, /title: 'Apple Health'/)
  assert.match(profileSource, /label: 'Apple Health'/)
  assert.match(profileSource, /buttonLabel: 'Manage'/)
  assert.match(profileSource, /Manage the data shared between Spotr on Apple Health app or Settings › Health\./)
  assert.match(profileSource, /Note: Wearable data must be synced with Apple Health before it is available in Spotr\./)
  assert.match(profileSource, /theme\.accentBorder|resolvedTheme\.accentBorder/)
  assert.match(profileSource, /theme\.accentText|resolvedTheme\.accentText/)
  assert.match(profileSource, /if \(activeScreen === 'apple-health'\)/)
  assert.match(profileSource, /if \(item\?\.id === 'apple-health'\) \{[\s\S]*setActiveScreen\('apple-health'\)/)
})

test('mobile profile view exposes a coach Athletes option inside the same profile shell', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const sheetSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/coach-athletes-sheet.js'), 'utf8')

  assert.match(sheetSource, /import \{ Skeleton \} from '\.\.\/ui\/skeleton\.js'/)
  assert.match(sheetSource, /function CoachAthleteSkeletonRows\({ theme }\)/)
  assert.match(sheetSource, /Array\.from\(\{ length: 6 \}\)/)
  assert.match(sheetSource, /<Skeleton[\s\S]*className="h-12 w-12 rounded-full"[\s\S]*theme=\{theme\}/)
  assert.match(sheetSource, /<Skeleton[\s\S]*className="h-5 flex-1 rounded-full"[\s\S]*theme=\{theme\}/)
  assert.match(sheetSource, /<Skeleton[\s\S]*className="h-8 w-8 rounded-full"[\s\S]*theme=\{theme\}/)
  assert.match(sheetSource, /isLoading = false/)
  assert.match(sheetSource, /const shouldShowSkeleton = isLoading \|\| isInitialSkeletonVisible/)
  assert.match(sheetSource, /shouldShowSkeleton \? \([\s\S]*<CoachAthleteSkeletonRows theme=\{resolvedTheme\} \/>/)
  assert.match(appSource, /const isCoachAthletesLoading = bootstrapState\.status === 'loading'/)
  assert.match(appSource, /<ProfileView[\s\S]*isAthletesLoading=\{isCoachAthletesLoading\}/)
  assert.match(appSource, /<CoachAthletesSheet[\s\S]*isLoading=\{isCoachAthletesLoading\}/)
  assert.match(profileSource, /\{ id: 'athletes', label: 'Athletes', icon: 'users', roles: \['coach'\] \}/)
  assert.match(profileSource, /function getVisibleProfileSections\({ role }\)/)
  assert.match(profileSource, /section\.items\.filter\(\(item\) => !item\.roles \|\| item\.roles\.includes\(role\)\)/)
  assert.match(profileSource, /import \{ CoachAthletesSheetContent \} from '\.\/coach-athletes-sheet\.js';/)
  assert.match(profileSource, /function ProfileViewContent\({ onClose, onSignOut, athleteProfile, onSaveProfile, isSavingProfile = false, saveNotice = '', role = 'athlete', athletes = \[\], selectedAthleteId = null, isAthletesLoading = false, onAthleteActionTarget, onOpenExerciseDetail, onOpenProgramDetail, themePreference = 'dark', onChangeThemePreference, weightUnitPreference = 'lb', distanceUnitPreference = 'km', onChangeWeightUnitPreference, onChangeDistanceUnitPreference, languagePreference = 'en', onChangeLanguagePreference, theme }\)/)
  assert.match(profileSource, /if \(activeScreen === 'athletes'\) \{[\s\S]*<CoachAthletesSheetContent[\s\S]*onClose=\{\(\) => setActiveScreen\('menu'\)\}[\s\S]*athletes=\{athletes\}[\s\S]*selectedAthleteId=\{selectedAthleteId\}[\s\S]*isLoading=\{isAthletesLoading\}[\s\S]*onActionTarget=\{handleProfileAthleteAction\}[\s\S]*theme=\{resolvedTheme\}/)
  assert.match(profileSource, /function handleProfileAthleteAction\(targetKey, payload\) \{[\s\S]*onAthleteActionTarget\?\.\(targetKey, payload\)[\s\S]*if \(targetKey === 'coach-athlete-select' \|\| targetKey === 'coach-athlete-invite'\) \{[\s\S]*onClose\?\.\(\)/)
  assert.match(profileSource, /if \(item\?\.id === 'athletes'\) \{[\s\S]*setActiveScreen\('athletes'\)[\s\S]*return/)
  assert.doesNotMatch(profileSource, /onOpenAthletes\?\.\(\)[\s\S]*onClose\?\.\(\)/)
  assert.match(profileSource, /function ProfileOptionIcon\({ icon, theme }\) \{[\s\S]*if \(icon === 'users'\) return <Users color=\{theme\.iconMuted\} size=\{20\} strokeWidth=\{2\.2\} \/>/)
  assert.match(profileSource, /AppListRow/)
  assert.match(appSource, /onProfileHeaderPress: \(\) => \{[\s\S]*setIsProfileViewOpen\(true\);[\s\S]*\}/)
  assert.doesNotMatch(appSource, /onProfileHeaderPress: \(\) => \{[\s\S]*if \(isAthleteLimitedState\) return;[\s\S]*setIsProfileViewOpen\(true\);[\s\S]*\}/)
  assert.match(appSource, /<ProfileView isVisible=\{isProfileViewOpen\} onClose=\{\(\) => setIsProfileViewOpen\(false\)\} onSignOut=\{handleProfileSignOut\} athleteProfile=\{profileViewProfile\}[\s\S]*role=\{isCoachBootstrapState \? 'coach' : 'athlete'\}[\s\S]*athletes=\{coachAthletesList\}[\s\S]*selectedAthleteId=\{selectedCoachAthleteId\}[\s\S]*isAthletesLoading=\{isCoachAthletesLoading\}[\s\S]*onAthleteActionTarget=\{handleTrainNavigation\}[\s\S]*onOpenExerciseDetail=\{\(exercise\) => handleOpenExerciseDetail\(exercise, 'profile-view'\)\}[\s\S]*themePreference=\{appThemePreference\}[\s\S]*onChangeThemePreference=\{handleThemePreferenceChange\}[\s\S]*\/>/)
})

test('mobile profile view exposes a real sign-out action at the bottom of the menu', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')

  assert.match(appSource, /const \{ authSession, bootstrapState, sessionStore, signInWithPassword, signUpWithPassword, resetPasswordForEmail, signOut, refreshAuthSession, updateAuthSession, updateAthleteProfile, updateCoachProfile, createCoachBodyMetricLog, getLatestCoachBodyMetricLog \} = useMobileAuthSession\(\);/)
  assert.match(appSource, /import \{[\s\S]*orchestrateProfileSignOut,[\s\S]*\} from '\.\/src\/auth\/auth-profile-actions\.js';/)
  assert.match(appSource, /async function handleProfileSignOut\(\) \{[\s\S]*await orchestrateProfileSignOut\(\{[\s\S]*signOut,[\s\S]*setAuthErrorMessage,[\s\S]*setAuthNoticeMessage,[\s\S]*setProfileSaveNotice,[\s\S]*setAuthMode,[\s\S]*setIsProfileViewOpen,[\s\S]*\}\);[\s\S]*\}/)
  assert.match(appSource, /const profileViewProfile = useMemo\(\(\) => \{[\s\S]*effectiveBootstrapState\.coachProfile\?\.displayName[\s\S]*effectiveBootstrapState\.coachProfile\?\.firstName[\s\S]*effectiveBootstrapState\.coachProfile\?\.lastName[\s\S]*return effectiveBootstrapState\.athleteProfile[\s\S]*\}, \[effectiveBootstrapState\.athleteProfile, effectiveBootstrapState\.coachProfile, isCoachBootstrapState\]\);/)
  assert.match(appSource, /<ProfileView isVisible=\{isProfileViewOpen\} onClose=\{\(\) => setIsProfileViewOpen\(false\)\} onSignOut=\{handleProfileSignOut\} athleteProfile=\{profileViewProfile\}[\s\S]*\/>/)

  assert.match(profileSource, /LogOut/)
  assert.match(profileSource, /function ProfileSignOutButton\({ onSignOut, theme }\)/)
  assert.match(profileSource, /AppButton/)
  assert.match(profileSource, /Sign Out/)
  assert.match(profileSource, /tone=\"danger\"/)
  assert.match(profileSource, /onPress=\{onSignOut\}/)
  assert.match(profileSource, /<ProfileSignOutButton onSignOut=\{onSignOut\} theme=\{resolvedTheme\} \/>/)
  assert.match(profileSource, /export function ProfileView\({ isVisible, onClose, onSignOut, athleteProfile, onSaveProfile, isSavingProfile = false, saveNotice = '', role = 'athlete', athletes = \[\], selectedAthleteId = null, isAthletesLoading = false, onAthleteActionTarget, onOpenExerciseDetail, onOpenProgramDetail, themePreference = 'dark', onChangeThemePreference, weightUnitPreference = 'lb', distanceUnitPreference = 'km', onChangeWeightUnitPreference, onChangeDistanceUnitPreference, languagePreference = 'en', onChangeLanguagePreference, theme }\)/)
  assert.match(profileSource, /<ProfileViewContent onClose=\{onClose\} onSignOut=\{onSignOut\} athleteProfile=\{athleteProfile\}[\s\S]*onSaveProfile=\{onSaveProfile\}[\s\S]*isSavingProfile=\{isSavingProfile\}[\s\S]*saveNotice=\{saveNotice\}[\s\S]*role=\{role\}[\s\S]*athletes=\{athletes\}[\s\S]*selectedAthleteId=\{selectedAthleteId\}[\s\S]*isAthletesLoading=\{isAthletesLoading\}[\s\S]*onAthleteActionTarget=\{onAthleteActionTarget\}[\s\S]*onOpenExerciseDetail=\{onOpenExerciseDetail\}[\s\S]*onOpenProgramDetail=\{onOpenProgramDetail\}[\s\S]*themePreference=\{themePreference\}[\s\S]*onChangeThemePreference=\{onChangeThemePreference\}[\s\S]*languagePreference=\{languagePreference\}[\s\S]*onChangeLanguagePreference=\{onChangeLanguagePreference\}[\s\S]*theme=\{theme\} \/>/)
})


test('mobile profile view uses role-aware identity data instead of hardcoded profile identity copy', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /function formatProfileIdentityBirthLabel\(value\)/)
  assert.match(profileSource, /function formatProfileIdentityHeight\(athleteProfile, unitsPreference\)/)
  assert.match(profileSource, /function formatProfileIdentityWeight\(athleteProfile, unitsPreference\)/)
  assert.match(profileSource, /function getProfileIdentityModel\(profile, role = 'athlete'\)/)
  assert.match(profileSource, /if \(role === 'coach'\) \{[\s\S]*const coachFullName = \[profile\?\.firstName, profile\?\.lastName\]\.filter\(Boolean\)\.join\(' '\)[\s\S]*const coachDisplayName = String\(profile\?\.displayName \|\| ''\)\.trim\(\)[\s\S]*displayName: coachFullName \|\| coachDisplayName \|\| profile\?\.firstName \|\| 'Coach'[\s\S]*metaLabel: ''/)
  assert.match(profileSource, /const fullName = \[profile\?\.firstName, profile\?\.lastName\]\.filter\(Boolean\)\.join\(' '\)/)
  assert.match(profileSource, /displayName: fullName \|\| profile\?\.firstName \|\| 'Athlete'[\s\S]*metaLabel: ''[\s\S]*avatarUrl: getSafeProfileImageUri\(profile\?\.avatarUrl\)/)
  assert.doesNotMatch(profileSource, /profile\?\.position \|\| 'Coach profile connected'/)
  assert.doesNotMatch(profileSource, /'Athletes linked in roster'/)
  assert.doesNotMatch(profileSource, /const unitsPreference = profile\?\.unitsPreference \|\| 'imperial'/)
  assert.doesNotMatch(profileSource, /const metaSegments = \[/)
  assert.doesNotMatch(profileSource, /formatProfileIdentityBirthLabel\(profile\?\.dateOfBirth\)/)
  assert.doesNotMatch(profileSource, /profile\?\.position \|\| 'Position pending'/)
  assert.doesNotMatch(profileSource, /formatProfileIdentityHeight\(profile, unitsPreference\)/)
  assert.doesNotMatch(profileSource, /formatProfileIdentityWeight\(profile, unitsPreference\)/)
  assert.doesNotMatch(profileSource, /metaLabel: metaSegments\.join\(' \| '\)/)
  assert.doesNotMatch(profileSource, /metaLabel: athleteProfile\?\.status \? `Status: \$\{athleteProfile\.status\}` : 'Athlete profile connected'/)
  assert.match(profileSource, /displayName: fullName \|\| profile\?\.firstName \|\| 'Athlete'/)
  assert.match(profileSource, /<Text className="text-\[32px\] font-bold" style=\{\{ color: resolvedTheme\.text \}\}>\{profileIdentity\.displayName\}<\/Text>/)
  assert.match(profileSource, /const profileIdentity = getProfileIdentityModel\(athleteProfile, role\)/)
  assert.match(profileSource, /const safeProfileAvatarUri = getSafeProfileImageUri\(profileIdentity\.avatarUrl\)/)
  assert.match(profileSource, /const hasProfileAvatar = Boolean\(safeProfileAvatarUri\)/)
  assert.match(profileSource, /function getCoachNameDraftValues\(profile\) \{[\s\S]*const normalizedDisplayName = String\(profile\?\.displayName \|\| ''\)\.trim\(\)[\s\S]*displayNameParts\.slice\(1\)\.join\(' '\)/)
  assert.match(profileSource, /function getProfileDetailModel\(athleteProfile, role = 'athlete'\)/)
  assert.match(profileSource, /if \(role === 'coach'\) \{[\s\S]*const coachNameDraft = getCoachNameDraftValues\(athleteProfile\)[\s\S]*\{ id: 'first-name', label: 'First name', value: coachNameDraft\.firstName, type: 'text' \}[\s\S]*\{ id: 'last-name', label: 'Last name', value: coachNameDraft\.lastName, type: 'text' \}[\s\S]*\{ id: 'phone-number', label: 'Phone number', value: athleteProfile\?\.phoneNumber \|\| '', type: 'text' \}[\s\S]*\{ id: 'avatar-url', label: 'Avatar URL', value: athleteProfile\?\.avatarUrl \|\| '', type: 'hidden' \}[\s\S]*\}/)
  assert.doesNotMatch(profileSource, /<Text className="text-\[32px\] font-bold text-white">Thomas<\/Text>/)
  assert.doesNotMatch(profileSource, /Joined Apr 2026 \| 7 Workouts/)
})

test('mobile profile view exposes a saveable profile details flow wired back into the app auth layer', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const providerSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/auth/session-provider.js'), 'utf8')

  assert.match(providerSource, /async updateCoachProfile\(updates = \{\}\) \{[\s\S]*identityClient\.updateCoachProfile\(/)
  assert.match(providerSource, /async updateCoachProfile\(updates = \{\}\) \{[\s\S]*if \(updates\.avatarAsset && identityClient\?\.uploadCoachAvatar\)[\s\S]*readAvatarAssetBuffer\({ uri: updates\.avatarAsset\.uri, fetchImpl }\)[\s\S]*identityClient\.uploadCoachAvatar\([\s\S]*nextUpdates\.avatarUrl = uploadedAvatar\.publicUrl[\s\S]*delete nextUpdates\.avatarAsset[\s\S]*identityClient\.updateCoachProfile\({ coachId, updates: nextUpdates }\)/)
  assert.match(providerSource, /setBootstrapState\(\(current\) => \(\{[\s\S]*coachProfile: updatedCoachProfile/)
  assert.match(providerSource, /async updateAthleteProfile\(updates = \{\}\) \{[\s\S]*identityClient\.updateAthleteProfile\(/)
  assert.match(providerSource, /setBootstrapState\(\(current\) => \(\{[\s\S]*athleteProfile: updatedAthleteProfile/)

  assert.match(appSource, /const \{ authSession, bootstrapState, sessionStore, signInWithPassword, signUpWithPassword, resetPasswordForEmail, signOut, refreshAuthSession, updateAuthSession, updateAthleteProfile, updateCoachProfile, createCoachBodyMetricLog, getLatestCoachBodyMetricLog \} = useMobileAuthSession\(\);/)
  assert.match(appSource, /import \{[\s\S]*orchestrateSaveProfile,[\s\S]*\} from '\.\/src\/auth\/auth-profile-actions\.js';/)
  assert.match(appSource, /async function handleSaveProfile\(profileDraft\) \{[\s\S]*await orchestrateSaveProfile\(\{[\s\S]*profileDraft,[\s\S]*isCoachBootstrapState,[\s\S]*updateCoachProfile,[\s\S]*updateAthleteProfile,[\s\S]*setAuthErrorMessage,[\s\S]*setAuthNoticeMessage,[\s\S]*setProfileSaveNotice,[\s\S]*setIsProfileSaving,[\s\S]*\}\);[\s\S]*\}/)
  assert.doesNotMatch(appSource, /handleSaveProfile\([\s\S]*setIsProfileViewOpen\(false\);/)
  assert.match(appSource, /const profileViewProfile = useMemo\(\(\) => \{[\s\S]*effectiveBootstrapState\.coachProfile\?\.displayName[\s\S]*effectiveBootstrapState\.coachProfile\?\.firstName[\s\S]*effectiveBootstrapState\.coachProfile\?\.lastName[\s\S]*return effectiveBootstrapState\.athleteProfile[\s\S]*\}, \[effectiveBootstrapState\.athleteProfile, effectiveBootstrapState\.coachProfile, isCoachBootstrapState\]\);/)
  assert.doesNotMatch(appSource, /const coachNameParts = \(bootstrapState\.coachProfile\?\.displayName \|\| 'Coach'\)\.trim\(\)\.split/)
  assert.match(appSource, /<ProfileView isVisible=\{isProfileViewOpen\} onClose=\{\(\) => setIsProfileViewOpen\(false\)\} onSignOut=\{handleProfileSignOut\} athleteProfile=\{profileViewProfile\}[\s\S]*onSaveProfile=\{handleSaveProfile\}[\s\S]*isSavingProfile=\{isProfileSaving\}[\s\S]*saveNotice=\{profileSaveNotice\}[\s\S]*role=\{isCoachBootstrapState \? 'coach' : 'athlete'\}[\s\S]*athletes=\{coachAthletesList\}[\s\S]*selectedAthleteId=\{selectedCoachAthleteId\}[\s\S]*onAthleteActionTarget=\{handleTrainNavigation\}[\s\S]*onOpenExerciseDetail=\{\(exercise\) => handleOpenExerciseDetail\(exercise, 'profile-view'\)\}[\s\S]*themePreference=\{appThemePreference\}[\s\S]*onChangeThemePreference=\{handleThemePreferenceChange\}[\s\S]*theme=\{appTheme\} \/>/)

  assert.match(profileSource, /function ProfileField\({ field, onChange, onOpenDatePicker, onOpenDropdown, unitsPreference, theme }\)/)
  assert.match(profileSource, /onChangeText=\{\(nextValue\) => onChange\?\.\(field\.id, nextValue\)\}/)
  assert.match(profileSource, /function validateProfileDraft\(draftProfile, role = 'athlete'\)/)
  assert.doesNotMatch(profileSource, /First name is required\./)
  assert.doesNotMatch(profileSource, /Last name is required\./)
  assert.match(profileSource, /if \(draftProfile\.height && convertHeightDraftToMetricCm\(draftProfile\.height, draftProfile\['units-preference'\]\) == null\)/)
  assert.match(profileSource, /if \(draftProfile\.weight && convertWeightDraftToMetricKg\(draftProfile\.weight, draftProfile\['units-preference'\]\) == null\)/)
  assert.match(profileSource, /const \[saveErrorMessage, setSaveErrorMessage\] = useState\(''\)/)
  assert.match(profileSource, /const \[saveSuccessMessage, setSaveSuccessMessage\] = useState\(''\)/)
  assert.match(profileSource, /const \[isSaveNoticeVisible, setIsSaveNoticeVisible\] = useState\(false\)/)
  assert.match(profileSource, /const visibleSaveSuccessMessage = saveNotice \|\| saveSuccessMessage/)
  assert.match(profileSource, /useEffect\(\(\) => \{[\s\S]*if \(!isSaveNoticeVisible \|\| !visibleSaveSuccessMessage\) return undefined[\s\S]*const hideProfileSaveNoticeTimer = setTimeout\(\(\) => \{[\s\S]*setIsSaveNoticeVisible\(false\)[\s\S]*setSaveSuccessMessage\(''\)[\s\S]*\}, 3000\)[\s\S]*return \(\) => clearTimeout\(hideProfileSaveNoticeTimer\)[\s\S]*\}, \[isSaveNoticeVisible, visibleSaveSuccessMessage\]\)/)
  assert.match(profileSource, /useEffect\(\(\) => \{[\s\S]*if \(saveNotice\) \{[\s\S]*setIsSaveNoticeVisible\(true\)[\s\S]*\}[\s\S]*\}, \[saveNotice\]\)/)
  assert.match(profileSource, /const validationError = validateProfileDraft\(draftProfile, role\)/)
  assert.match(profileSource, /try \{[\s\S]*await onSaveProfile\?\.\(activeProfileUpdate\)[\s\S]*setSaveSuccessMessage\('Profile updated\.'\)[\s\S]*\} catch \(error\) \{[\s\S]*setSaveErrorMessage\(error\?\.message \|\| 'Something went sideways while saving the profile\.'\)[\s\S]*setSaveSuccessMessage\(''\)[\s\S]*\}/)
  assert.match(profileSource, /setSaveErrorMessage\(validationError\)/)
  assert.match(profileSource, /saveNotice \|\| saveSuccessMessage/)
  assert.match(profileSource, /isSavingProfile \? 'Saving\.\.\.' : 'Save Profile'/)
  assert.match(profileSource, /disabled=\{isSaveDisabled\}/)
})

test('mobile profile details no longer mark first and last name as required fields', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.doesNotMatch(profileSource, /required: true/)
  assert.doesNotMatch(profileSource, /First name \*/)
  assert.doesNotMatch(profileSource, /Last name \*/)
  assert.doesNotMatch(profileSource, /field\.required \? <Text className="text-\[#ef4444\]"> \*<\/Text> : null/)
})

test('mobile profile details normalize ISO birth dates and stored metric strings before formatting for the menu and editor', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /const isoDateMatch = String\(value\)\.match\(/)
  assert.match(profileSource, /new Date\(Number\(isoDateMatch\[1\]\), Number\(isoDateMatch\[2\]\) - 1, Number\(isoDateMatch\[3\]\)\)/)
  assert.match(profileSource, /const normalizedHeight = formatProfileNumberDraft\(field\.value, 'cm'\)/)
  assert.match(profileSource, /return unitsPreference === 'imperial'\s*\? convertCentimetersToImperialHeight\(normalizedHeight\)/)
  assert.match(profileSource, /const normalizedWeight = formatProfileNumberDraft\(field\.value, 'kg'\)/)
  assert.match(profileSource, /return unitsPreference === 'imperial'\s*\? convertKilogramsToImperialWeight\(normalizedWeight\)/)
  assert.doesNotMatch(profileSource, /return unitsPreference === 'imperial'\s*\? convertCentimetersToImperialHeight\(field\.value\)/)
  assert.doesNotMatch(profileSource, /return unitsPreference === 'imperial'\s*\? convertKilogramsToImperialWeight\(field\.value\)/)
})

test('mobile profile details use a bottom-sheet date picker with readable light text', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /const \[isDatePickerVisible, setIsDatePickerVisible\] = useState\(false\)/)
  assert.match(profileSource, /<Modal transparent visible=\{isDatePickerVisible\} animationType="fade" onRequestClose=\{\(\) => setIsDatePickerVisible\(false\)\}/)
  assert.match(profileSource, /<DateTimePicker value=\{datePickerValue\} mode="date" display="spinner" textColor=\{resolvedTheme\.text\} themeVariant=\{resolvedTheme\.id\} onChange=\{handleDateChange\} \/>/)
  assert.match(profileSource, /style=\{\{ backgroundColor: resolvedTheme\.overlay \}\}/)
  assert.match(profileSource, /<Pressable className="flex-1" onPress=\{\(\) => setIsDatePickerVisible\(false\)\} \/>/)
  assert.match(profileSource, /<Text className="text-\[15px\] font-semibold text-\[#34D399\]">Done<\/Text>|style=\{\{ color: resolvedTheme\.accentText \}\}>Done<\/Text>/)
  assert.doesNotMatch(profileSource, /\{isDatePickerVisible \? \([\s\S]*<View className="rounded-\[18px\] border border-\[#243041\] bg-\[#111827\] px-3 py-3"/)
})

test('mobile profile details use date picker plus dropdown sheets for gender and position', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /const PROFILE_GENDER_OPTIONS = \[/)
  assert.match(profileSource, /label: 'Male'/)
  assert.match(profileSource, /label: 'Female'/)
  assert.match(profileSource, /label: 'Other'/)
  assert.match(profileSource, /label: 'Prefer not to say'/)
  assert.match(profileSource, /const PROFILE_POSITION_OPTIONS = \[/)
  assert.match(profileSource, /label: 'Forward'/)
  assert.match(profileSource, /label: 'Defence'/)
  assert.match(profileSource, /label: 'Goalie'/)
  assert.match(profileSource, /function formatProfileDateDisplay\(value\)/)
  assert.match(profileSource, /const \[isDatePickerVisible, setIsDatePickerVisible\] = useState\(false\)/)
  assert.match(profileSource, /const \[activeDropdownFieldId, setActiveDropdownFieldId\] = useState\(null\)/)
  assert.match(profileSource, /function ProfileDropdownField\({ field, selectedValue, onOpen, theme }\)/)
  assert.match(profileSource, /function ProfileDropdownSheet\({ visible, title, options, selectedValue, onSelect, onClose, theme }\)/)
  assert.match(profileSource, /function ProfileDropdownSheet\({ visible, title, options, selectedValue, onSelect, onClose, theme }\) \{[\s\S]*const resolvedTheme = theme \|\| getAppTheme\('dark'\)/)
  assert.match(profileSource, /<View className="flex-1 justify-end" style=\{\{ backgroundColor: resolvedTheme\.overlay \}\}>/)
  assert.match(profileSource, /style=\{\{ borderWidth: 1, borderColor: isSelected \? resolvedTheme\.accentBorder : resolvedTheme\.border, backgroundColor: isSelected \? resolvedTheme\.accentSurface : resolvedTheme\.surface \}\}/)
  assert.match(profileSource, /<ProfileDropdownSheet[\s\S]*visible=\{Boolean\(activeDropdownFieldId\)\}[\s\S]*theme=\{resolvedTheme\}/)
  assert.match(profileSource, /onOpen=\{onOpenDropdown\}/)
  assert.match(profileSource, /setActiveDropdownFieldId\(fieldId\)/)
  assert.match(profileSource, /DateTimePicker/)
  assert.match(profileSource, /display="spinner"/)
  assert.match(profileSource, /setIsDatePickerVisible\(true\)/)
  assert.match(profileSource, /setDatePickerValue\(selectedDate\)/)
  assert.match(profileSource, /setDraftProfile\(\(current\) => \(\{[\s\S]*'date-of-birth': nextDateValue/)
  assert.match(profileSource, /const hasProfileChanges = profileDetailModel\.fields\.some\(/)
  assert.match(profileSource, /const isSaveDisabled = isSavingProfile \|\| !hasProfileChanges/)
  assert.match(profileSource, /disabled=\{isSaveDisabled\}/)
  assert.match(profileSource, /\{field\.type === 'date' \? \(/)
  assert.match(profileSource, /field\.type === 'dropdown' \? \(/)
  assert.doesNotMatch(profileSource, /function ProfileSegmentedField\(/)
})

test('mobile profile details render units as a single clean segmented control without duplicate labels', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /function ProfileChoicePillField\({ field, options, selectedValue, onChange, theme }\)/)
  assert.doesNotMatch(profileSource, /<Text className="text-\[15px\] font-semibold text-white">\{field\.label\}<\/Text>[\s\S]*function ProfileChoicePillField/)
  assert.match(profileSource, /<AppSegmentedControl/)
  assert.match(profileSource, /activeId = options\.find\(/)
  assert.match(profileSource, /field\.id === 'units-preference' \? String\(nextOption\.label\)\.toLowerCase\(\) : nextOption\.label/)
  assert.doesNotMatch(profileSource, /className=\{`flex-1 items-center justify-center rounded-\[14px\] px-4 py-3/)
})

test('mobile profile view supports avatar upload wiring through expo image picker and the auth save seam', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const mobilePackageSource = readFileSync(resolve(process.cwd(), 'apps/mobile/package.json'), 'utf8')

  assert.match(mobilePackageSource, /"expo-image-picker"/)
  assert.match(profileSource, /import \* as ImagePicker from 'expo-image-picker'/)
  assert.match(profileSource, /import \{ Image, Modal, Platform, Pressable, ScrollView, Text, TextInput, View \} from 'react-native'/)
  assert.match(profileSource, /\{ id: 'avatar-url', label: 'Avatar URL', value: athleteProfile\?\.avatarUrl \|\| '', type: 'hidden' \}/)
  assert.match(profileSource, /const safeDraftAvatarUri = getSafeProfileImageUri\(draftProfile\['avatar-url'\]\)/)
  assert.match(profileSource, /const hasAvatar = Boolean\(safeDraftAvatarUri\)/)
  assert.match(profileSource, /async function handleAvatarUpload\(\)/)
  assert.match(profileSource, /const activeProfileUpdate = buildAthleteProfileUpdatePayload\(draftProfile, athleteProfile, role\)/)
  assert.match(profileSource, /buildAthleteProfileUpdatePayload\(draftProfile, athleteProfile, role = 'athlete'\)/)
  assert.match(profileSource, /await ImagePicker\.requestMediaLibraryPermissionsAsync\(\)/)
  assert.match(profileSource, /await ImagePicker\.launchImageLibraryAsync\(/)
  assert.match(profileSource, /mediaTypes: \['images'\]/)
  assert.match(profileSource, /const nextAvatarUrl = asset\.uri/)
  assert.match(profileSource, /'avatar-url': nextAvatarUrl/)
  assert.match(profileSource, /'avatar-asset': \{[\s\S]*uri: asset\.uri[\s\S]*mimeType: asset\.mimeType \|\| 'image\/jpeg'[\s\S]*fileName: asset\.fileName \|\| `\$\{role\}-avatar-\$\{Date\.now\(\)\}\.jpg`/)
  assert.match(profileSource, /avatarAsset: draftProfile\['avatar-asset'\] \?\? null/)
  assert.doesNotMatch(profileSource, /base64: true/)
  assert.doesNotMatch(profileSource, /data:image\/jpeg;base64/)
  assert.match(profileSource, /onPress=\{handleAvatarUpload\}/)
  assert.match(profileSource, /\{hasAvatar \?/)
  assert.match(profileSource, /<Image[\s\S]*source=\{\{ uri: safeDraftAvatarUri \}\}/)
  assert.match(appSource, /import \{[\s\S]*orchestrateSaveProfile,[\s\S]*\} from '\.\/src\/auth\/auth-profile-actions\.js';/)
  assert.match(appSource, /async function handleSaveProfile\(profileDraft\) \{[\s\S]*await orchestrateSaveProfile\(\{[\s\S]*profileDraft,[\s\S]*isCoachBootstrapState,[\s\S]*updateCoachProfile,[\s\S]*updateAthleteProfile,[\s\S]*setAuthErrorMessage,[\s\S]*setAuthNoticeMessage,[\s\S]*setProfileSaveNotice,[\s\S]*setIsProfileSaving,[\s\S]*\}\);[\s\S]*\}/)
})

test('mobile coach profile phone field uses a phone keyboard and formatted phone draft values', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /function formatPhoneNumberDraft\(value\) \{[\s\S]*digitsOnly/)
  assert.match(profileSource, /if \(field\.id === 'phone-number'\) return formatPhoneNumberDraft\(field\.value\)/)
  assert.match(profileSource, /keyboardType=\{field\.id === 'height' \|\| field\.id === 'weight' \? 'decimal-pad' : field\.id === 'phone-number' \? 'phone-pad' : 'default'\}/)
  assert.match(profileSource, /textContentType=\{field\.id === 'phone-number' \? 'telephoneNumber' : 'none'\}/)
  assert.match(profileSource, /autoComplete=\{field\.id === 'phone-number' \? 'tel' : 'off'\}/)
  assert.match(profileSource, /placeholder=\{field\.id === 'phone-number' \? '\(555\) 555-5555' : getNumericFieldPlaceholder\(field\.id, unitsPreference\)\}/)
  assert.match(profileSource, /\[fieldId\]: fieldId === 'phone-number' \? formatPhoneNumberDraft\(nextValue\) : nextValue/)
})

test('mobile profile menu shows the saved athlete avatar instead of the generic placeholder when avatarUrl is a valid image URI', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /function getSafeProfileImageUri\(value\) \{[\s\S]*allowedImageUriPattern/)
  assert.match(profileSource, /const safeProfileAvatarUri = getSafeProfileImageUri\(profileIdentity\.avatarUrl\)/)
  assert.match(profileSource, /const hasProfileAvatar = Boolean\(safeProfileAvatarUri\)/)
  assert.match(profileSource, /\{hasProfileAvatar \?/)
  assert.match(profileSource, /<Image source=\{\{ uri: safeProfileAvatarUri \}\} className="h-full w-full" resizeMode="cover" \/>/)
  assert.match(profileSource, /function getProfileIdentityModel\(profile, role = 'athlete'\) \{[\s\S]*avatarUrl: getSafeProfileImageUri\(profile\?\.avatarUrl\)/)
  assert.match(profileSource, /\) : \(\s*<UserCircle2 color=\{resolvedTheme\.iconMuted\} size=\{68\} strokeWidth=\{1\.8\} \/>/)
})

test('mobile profile avatar preview does not pass invalid stored strings into React Native Image', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.match(profileSource, /const safeDraftAvatarUri = getSafeProfileImageUri\(draftProfile\['avatar-url'\]\)/)
  assert.match(profileSource, /const hasAvatar = Boolean\(safeDraftAvatarUri\)/)
  assert.match(profileSource, /<Image[\s\S]*source=\{\{ uri: safeDraftAvatarUri \}\}[\s\S]*className="h-full w-full"[\s\S]*resizeMode="cover"[\s\S]*onLoadStart=\{\(\) => setIsAvatarImageLoading\(true\)\}[\s\S]*onLoadEnd=\{\(\) => setIsAvatarImageLoading\(false\)\}/)
  assert.doesNotMatch(profileSource, /Boolean\(draftProfile\['avatar-url'\]\)/)
  assert.doesNotMatch(profileSource, /Boolean\(profileIdentity\.avatarUrl\)/)
  assert.doesNotMatch(profileSource, /source=\{\{ uri: draftProfile\['avatar-url'\] \}\}/)
  assert.doesNotMatch(profileSource, /source=\{\{ uri: profileIdentity\.avatarUrl \}\}/)
})

test('mobile profile primary action buttons do not render the decorative top highlight line', () => {
  const profileSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/profile-view.js'), 'utf8')

  assert.doesNotMatch(profileSource, /className="absolute inset-x-0 top-0 h-\[1px\]"/)
  assert.doesNotMatch(profileSource, /style=\{\{ backgroundColor: resolvedTheme\.buttonHighlight \}\}/)
})
