import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

test('mobile workout sheet can open a dedicated workout edit view from the Edit action', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const workoutSheetSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-sheet.js'), 'utf8')

  assert.match(appSource, /const \[isWorkoutEditViewOpen, setIsWorkoutEditViewOpen\] = useState\(false\);/)
  assert.match(appSource, /const \[workoutEditReturnSurface, setWorkoutEditReturnSurface\] = useState\(null\);/)
  assert.match(appSource, /const \[workoutEditDraftModel, setWorkoutEditDraftModel\] = useState\(null\);/)
  assert.match(appSource, /const workoutEditViewModel = useMemo\(\(\) => getWorkoutEditViewModel\(\{ workoutSheetModel, workoutDraftModel: workoutEditDraftModel \}\), \[workoutEditDraftModel, workoutSheetModel\]\);/)
  assert.match(appSource, /<WorkoutEditView[\s\S]*isVisible=\{isWorkoutEditViewOpen\}/)
  assert.match(workoutSheetSource, /onEditWorkout/)
  assert.match(workoutSheetSource, /<Pressable onPress=\{onEditWorkout\}>/)
})

test('mobile workout edit cancel returns to the workout sheet instead of the main train view', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')

  assert.match(appSource, /workout-edit-selection\.js/)
  assert.match(appSource, /onClose=\{handleCloseWorkoutEditView\}/)
})

test('mobile workout edit view matches the edit reference structure and uses NativeWind plus Lucide', () => {
  const editViewSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-edit-view.js'), 'utf8')
  const modelSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/train/workout-edit-view-models.js'), 'utf8')
  const workoutSheetSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-sheet.js'), 'utf8')
  const sharedPickerSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/exercise-multi-select-view.js'), 'utf8')

  assert.match(editViewSource, /function createDraftFromModel\(model\) \{[\s\S]*workoutName: model\.title \|\| '',[\s\S]*workoutNotes: model\.workoutNotes \|\| model\.notes \|\| '',/)
  assert.match(editViewSource, /<TextInput[\s\S]*placeholder=\{model\.workoutNamePlaceholder \|\| 'Workout name'\}/)
  assert.match(editViewSource, /value=\{draft\.workoutName\}/)
  assert.match(editViewSource, /placeholder=\{model\.workoutNotesPlaceholder \|\| 'Add notes'\}/)
  assert.match(editViewSource, /value=\{draft\.workoutNotes\}/)
  assert.match(editViewSource, /draft\.exercises\.map\(\(exercise, exerciseIndex\) => \(/)
  assert.match(editViewSource, /AppOutlinedActionButton/)
  assert.match(editViewSource, /label=\{model\.addExerciseLabel \|\| 'Add Exercise'\}/)
  assert.match(editViewSource, /leftIcon=\{<Dumbbell color=\{resolvedTheme\.accentText\} size=\{18\} strokeWidth=\{2\.2\} \/>\}/)
  assert.match(editViewSource, /model\.addExerciseLabel \|\| 'Add Exercise'/)
  assert.match(editViewSource, /model\.deleteLabel \|\| 'Delete Workout'/)
  assert.match(editViewSource, /Trash2 color=\{resolvedTheme\.dangerText\} size=\{16\} strokeWidth=\{2\.2\} \/>/)

  assert.match(editViewSource, /draft\.exercises\.map\(\(exercise, exerciseIndex\) => \([\s\S]*handleOpenAddExercise\}/)
  assert.match(editViewSource, /AppDangerPillButton/)
  assert.match(editViewSource, /label=\{model\.deleteLabel \|\| 'Delete Workout'\}/)
  assert.match(editViewSource, /leftIcon=\{<Trash2 color=\{resolvedTheme\.dangerText\} size=\{16\} strokeWidth=\{2\.2\} \/>\}/)
  assert.match(editViewSource, /style=\{\{ marginTop: 20 \}\}/)
  assert.match(editViewSource, /const \[isAddExerciseViewOpen, setIsAddExerciseViewOpen\] = useState\(false\)/)
  assert.match(editViewSource, /const \[selectedAddExerciseIds, setSelectedAddExerciseIds\] = useState\(\[\]\)/)
  assert.match(editViewSource, /const \[addExerciseSearchQuery, setAddExerciseSearchQuery\] = useState\(''\)/)
  assert.match(editViewSource, /function handleOpenAddExercise\(\) \{[\s\S]*setIsAddExerciseViewOpen\(true\)/)
  assert.match(editViewSource, /function handleCloseAddExercise\(\) \{[\s\S]*setIsAddExerciseViewOpen\(false\)[\s\S]*setSelectedAddExerciseIds\(\[\]\)[\s\S]*setAddExerciseSearchQuery\(''\)/)
  assert.match(editViewSource, /async function handleConfirmAddExercises\(\) \{[\s\S]*await onAddExercises\?\.\(selectedAddExerciseIds\)[\s\S]*handleCloseAddExercise\(\)/)
  assert.match(editViewSource, /onPress=\{handleOpenAddExercise\}/)
  assert.match(editViewSource, /<ExerciseMultiSelectView[\s\S]*isVisible=\{isAddExerciseViewOpen\}[\s\S]*presentation=\"inline\"[\s\S]*selectedExerciseIds=\{selectedAddExerciseIds\}[\s\S]*searchQuery=\{addExerciseSearchQuery\}[\s\S]*onSearchChange=\{setAddExerciseSearchQuery\}[\s\S]*onAddExercises=\{handleConfirmAddExercises\}/)
  assert.match(editViewSource, /TextInput/)
  assert.match(editViewSource, /useState/)
  assert.match(editViewSource, /keyboardType="numeric"/)
  assert.match(editViewSource, /multiline/)
  assert.match(editViewSource, /onChangeText=/)
  assert.match(editViewSource, /Cancel/)
  assert.match(editViewSource, /Save/)
  assert.match(editViewSource, /Add notes/)
  assert.match(editViewSource, /Add Notes/)
  assert.match(editViewSource, /Add Set/)
  assert.match(editViewSource, /Link2/)
  assert.match(editViewSource, /ArrowUpDown/)
  assert.match(editViewSource, /if \(icon === 'zap'\) return <Dumbbell color=\{theme\.iconMuted\} size=\{22\} strokeWidth=\{2\.2\} \/>/)
  assert.match(editViewSource, /<View className="flex-row gap-2">/)
  assert.match(editViewSource, /ArrowUp color=\{canMoveExerciseUp \? theme\.accentText : theme\.iconMuted\}/)
  assert.match(editViewSource, /ArrowDown color=\{canMoveExerciseDown \? theme\.accentText : theme\.iconMuted\}/)
  assert.match(editViewSource, /Clock3/)
  assert.match(editViewSource, /Mic/)
  assert.match(editViewSource, /Sparkles/)
  assert.match(editViewSource, /className=/)
  assert.match(editViewSource, /SafeAreaProvider/)
  assert.match(editViewSource, /useSafeAreaInsets/)
  assert.match(editViewSource, /AppDangerPillButton/)
  assert.match(editViewSource, /AppOutlinedActionButton/)
  assert.doesNotMatch(editViewSource, /<Text style=\{/)

  assert.match(workoutSheetSource, /from '\.\.\/theme\/app-theme\.js'/)
  assert.match(workoutSheetSource, /from '\.\.\/ui\/primitives\.js'/)
  assert.match(workoutSheetSource, /getAppTheme\('dark'\)/)
  assert.match(workoutSheetSource, /AppButton/)
  assert.match(workoutSheetSource, /AppSurfaceCard/)
  assert.match(workoutSheetSource, /shadowColor: theme\.cardShadow|shadowColor: resolvedTheme\.cardShadow/)
  assert.doesNotMatch(workoutSheetSource, /inset-x-3 top-\[1px\] h-10 rounded-full/)
  assert.doesNotMatch(workoutSheetSource, /#34D399|#243041|#111827|text-white|text-slate-400|text-slate-300/)

  assert.match(modelSource, /export function createEmptyWorkoutEditDraftModel\(\)/)
  assert.match(modelSource, /title: ''/)
  assert.match(modelSource, /workoutNamePlaceholder: 'Workout name'/)
  assert.match(modelSource, /workoutNotesPlaceholder: 'Add notes'/)
  assert.match(modelSource, /addExerciseLabel: 'Add Exercise'/)
  assert.match(modelSource, /deleteLabel: 'Delete Workout'/)
  assert.match(modelSource, /exercises: \[\]/)
  assert.match(modelSource, /getWorkoutEditViewModel\(\{ workoutSheetModel, workoutDraftModel = null \}\)/)
  assert.match(modelSource, /if \(workoutDraftModel\) \{/)
  assert.match(modelSource, /workoutNamePlaceholder: 'Workout name'/)
  assert.match(modelSource, /editLabel: 'Save'/)
  assert.match(modelSource, /cancelLabel: 'Cancel'/)
  assert.match(modelSource, /exerciseNotesPlaceholder: 'Add Notes'/)
  assert.match(modelSource, /return \{[\s\S]*deleteLabel: 'Delete Workout'/)
  assert.match(modelSource, /workoutNotes: workoutSheetModel\.workoutNotes \|\| workoutSheetModel\.notes \|\| ''/)
  assert.match(modelSource, /addExerciseSheet: \{[\s\S]*title: 'Exercises'[\s\S]*searchPlaceholder: 'Search or Create Exercises'[\s\S]*addButtonLabel: 'Add'[\s\S]*\}/)

  assert.match(sharedPickerSource, /export function ExerciseMultiSelectView\(/)
  assert.match(sharedPickerSource, /selectedExerciseIds\.includes\(exercise\.id\)/)
  assert.match(sharedPickerSource, /label=\{`\$\{sheet\.addButtonLabel\} \$\{selectedExerciseIds\.length\}`\}/)
  assert.match(sharedPickerSource, /placeholder=\{sheet\.searchPlaceholder\}/)
  assert.match(sharedPickerSource, /sheet\.title/)
})

test('mobile workout edit add set button routes through the app seam and persists a cloned planned set row', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const editViewSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-edit-view.js'), 'utf8')
  const modelSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/train/workout-edit-view-models.js'), 'utf8')

  assert.match(editViewSource, /async function handleAddSet\(exerciseId\)/)
  assert.match(editViewSource, /const nextSortOrder = Math\.max\(0, \.\.\.exercise\.sets\.map\(\(set\) => Number\(set\.sortOrder\) \|\| 0\)\) \+ 1/)
  assert.match(editViewSource, /const tempSetId = `\$\{exerciseId\}-draft-set-\$\{nextSortOrder\}`/)
  assert.match(editViewSource, /const persistedSet = await onAddSet\?\.\(exerciseId\)/)
  assert.match(editViewSource, /set\.id === tempSetId[\s\S]*\.\.\.persistedSet,[\s\S]*setNumber: persistedSet\.setNumber \?\? set\.setNumber/)
  assert.match(appSource, /onAddSet=\{handleAddWorkoutEditSet\}/)

  assert.match(modelSource, /programWorkoutExerciseId: exercise\.programWorkoutExerciseId \|\| null/)
  assert.match(modelSource, /programWorkoutSetId: set\.programWorkoutSetId \|\| set\.id \|\| null/)
  assert.match(modelSource, /sortOrder: set\.sortOrder \?\? \(Number\.parseInt\(set\.setNumber, 10\) \|\| 0\)/)
  assert.match(modelSource, /setType: set\.setType \|\| 'straight'/)
  assert.match(modelSource, /prescribedRestSeconds: set\.prescribedRestSeconds \?\? parseRestLabelToSeconds\(exercise\.restLabel\)/)

  assert.match(appSource, /workout-edit-mutations\.js/)
  assert.match(appSource, /async function handleAddWorkoutEditSet\(exerciseId\) \{[\s\S]*orchestrateAddWorkoutEditSet\(\{/)
})

test('mobile workout edit view supports changing exercise sort order through the planned workout seam', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const editViewSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-edit-view.js'), 'utf8')
  const modelSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/train/workout-edit-view-models.js'), 'utf8')

  assert.match(editViewSource, /async function handleMoveExerciseUp\(exerciseId\) \{/)
  assert.match(editViewSource, /async function handleMoveExerciseDown\(exerciseId\) \{/)
  assert.match(editViewSource, /onMoveExerciseUp=\{handleMoveExerciseUp\}/)
  assert.match(editViewSource, /onMoveExerciseDown=\{handleMoveExerciseDown\}/)
  assert.match(editViewSource, /canMoveExerciseUp=\{exerciseIndex > 0\}/)
  assert.match(editViewSource, /canMoveExerciseDown=\{exerciseIndex < draft\.exercises\.length - 1\}/)
  assert.match(editViewSource, /disabled=\{!canMoveExerciseUp\}/)
  assert.match(editViewSource, /disabled=\{!canMoveExerciseDown\}/)
  assert.match(editViewSource, /onPress=\{\(\) => onMoveExerciseUp\?\.\(exercise\.id\)\}/)
  assert.match(editViewSource, /onPress=\{\(\) => onMoveExerciseDown\?\.\(exercise\.id\)\}/)
  assert.doesNotMatch(editViewSource, /function WorkoutEditExerciseOrderSheet\(/)
  assert.doesNotMatch(editViewSource, /Change Exercise Order/)

  assert.match(appSource, /onMoveExercise=\{handleMoveWorkoutEditExercise\}/)
  assert.match(appSource, /workout-edit-mutations\.js/)
  assert.match(appSource, /async function handleMoveWorkoutEditExercise\(exerciseId, direction\) \{[\s\S]*orchestrateMoveWorkoutEditExercise\(\{[\s\S]*\}/)
  assert.doesNotMatch(appSource, /async function handleMoveWorkoutEditExercise\(exerciseId, direction\) \{[\s\S]*updateProgramWorkoutExercise\(/)

  assert.match(modelSource, /sortOrder: exercise\.sortOrder \?\? exerciseIndex \+ 1/)
  assert.match(modelSource, /sortOrderLabel: String\(exercise\.sortOrder \?\? exerciseIndex \+ 1\)/)
})

test('mobile workout edit view supports swipe-to-delete set rows through the planned workout seam', () => {
  const appSource = readFileSync(resolve(process.cwd(), 'apps/mobile/App.js'), 'utf8')
  const editViewSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-edit-view.js'), 'utf8')
  const indexSource = readFileSync(resolve(process.cwd(), 'apps/mobile/index.js'), 'utf8')

  assert.match(indexSource, /import 'react-native-gesture-handler';/)
  assert.match(indexSource, /import \{ GestureHandlerRootView \} from 'react-native-gesture-handler';/)
  assert.match(indexSource, /<GestureHandlerRootView style=\{\{ flex: 1 \}\}>[\s\S]*<App \/>[\s\S]*<\/GestureHandlerRootView>/)

  assert.match(editViewSource, /import \{ Modal, Pressable, ScrollView, Text, TextInput, View \} from 'react-native';/)
  assert.match(editViewSource, /import \{ Swipeable \} from 'react-native-gesture-handler';/)
  assert.match(editViewSource, /function SwipeableSetRow\(/)
  assert.match(editViewSource, /<Swipeable[\s\S]*overshootRight=\{false\}[\s\S]*renderRightActions=\{renderRightActions\}[\s\S]*rightThreshold=\{48\}/)
  assert.match(editViewSource, /function renderRightActions\(\) \{[\s\S]*<Pressable[\s\S]*onPress=\{onDelete\}[\s\S]*theme\.dangerSurface[\s\S]*theme\.dangerBorder[\s\S]*Trash2/)
  assert.doesNotMatch(editViewSource, /<Text className="text-\[13px\] font-semibold" style=\{\{ color: theme\.dangerText \}\}>Delete<\/Text>/)
  assert.match(editViewSource, /<View className="w-full overflow-hidden rounded-\[18px\]">/)
  assert.doesNotMatch(editViewSource, /PanResponder\.create\(/)
  assert.doesNotMatch(editViewSource, /Animated\.Value\(0\)/)
  assert.doesNotMatch(editViewSource, /pointerEvents="box-none"/)
  assert.match(editViewSource, /<View className="min-h-\[50px\] flex-row items-center" style=\{\{ backgroundColor: theme\.background \}\}>/)
  assert.match(editViewSource, /onDeleteSet=\{handleDeleteSet\}/)
  assert.match(editViewSource, /Delete/)
  assert.match(editViewSource, /async function handleDeleteSet\(exerciseId, setId\)/)
  assert.match(editViewSource, /const deleteResult = await onDeleteSet\?\.\(exerciseId, setId\)/)
  assert.match(editViewSource, /sets: currentExercise\.sets\.filter\(\(set\) => set\.id !== setId\)\.map\(\(set, index\) => \(\{[\s\S]*setNumber: index \+ 1,[\s\S]*\}\)\)/)

  assert.match(appSource, /onDeleteSet=\{handleDeleteWorkoutEditSet\}/)
  assert.match(appSource, /workout-edit-mutations\.js/)
  assert.match(appSource, /async function handleDeleteWorkoutEditSet\(exerciseId, setId\) \{[\s\S]*orchestrateDeleteWorkoutEditSet\(\{/)
})

test('mobile workout edit view rehydrates a blank workout name for a newly created workout instead of keeping the last opened title', () => {
  const editViewSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-edit-view.js'), 'utf8')

  assert.match(editViewSource, /const \[draft, setDraft\] = useState\(\(\) => \(model \? createDraftFromModel\(model\) : null\)\)/)
  assert.match(editViewSource, /useEffect\(\(\) => \{[\s\S]*if \(!model\) \{[\s\S]*setDraft\(null\)[\s\S]*return[\s\S]*\}[\s\S]*setDraft\(createDraftFromModel\(model\)\)[\s\S]*\}, \[model\]\)/)
  assert.match(editViewSource, /workoutName: model\.title \|\| ''/)
  assert.match(editViewSource, /value=\{draft\.workoutName\}/)
  assert.doesNotMatch(editViewSource, /defaultValue=\{model\.title\}/)
})

test('mobile workout edit view opens a dedicated rest timer edit sheet from the timer control', () => {
  const editViewSource = readFileSync(resolve(process.cwd(), 'apps/mobile/src/screens/workout-edit-view.js'), 'utf8')

  assert.match(editViewSource, /const \[restTimerSheetExerciseId, setRestTimerSheetExerciseId\] = useState\(null\)/)
  assert.match(editViewSource, /function WorkoutEditRestTimerSheet\(/)
  assert.match(editViewSource, /Edit Rest Timer/)
  assert.match(editViewSource, /-15s/)
  assert.match(editViewSource, /\+15s/)
  assert.match(editViewSource, /Remove/)
  assert.match(editViewSource, /onPress=\{\(\) => onOpenRestTimerSheet\?\.\(exercise\)\}/)
  assert.match(editViewSource, /<WorkoutEditRestTimerSheet/)
})
