import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const workoutsDataTablePath = resolve(repoRoot, 'apps/web/components/admin/workouts-data-table.jsx')

test('workouts table upload button opens cancel-style PDF import dialog with table upload content', () => {
  const source = readFileSync(workoutsDataTablePath, 'utf8')

  assert.doesNotMatch(source, /ImageIcon/)
  assert.doesNotMatch(source, /Choose workout image/)
  assert.doesNotMatch(source, /workoutImportImageName/)
  assert.doesNotMatch(source, /No image attached/)
  assert.doesNotMatch(source, /Upload image/)
  assert.doesNotMatch(source, /accept="image\/\*"/)
  assert.match(source, /import \{[^}]*Bot[^}]*ChevronDown[^}]*FileText[^}]*LoaderCircle[^}]*MoreHorizontal[^}]*Plus[^}]*Trash2[^}]*Upload[^}]*\} from 'lucide-react'/)
  assert.match(source, /import \{ Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle \} from '@\/components\/ui\/empty'/)

  assert.match(source, /const \[isAiWorkoutImportDialogOpen, setIsAiWorkoutImportDialogOpen\] = useState\(false\)/)
  assert.match(source, /const \[isWorkoutAiProcessing, setIsWorkoutAiProcessing\] = useState\(false\)/)
  assert.match(source, /const \[workoutImportFiles, setWorkoutImportFiles\] = useState\(\[\]\)/)
  assert.match(source, /function handleWorkoutImportPdfUpload\(event\)/)
  assert.doesNotMatch(source, /setWorkoutImportFiles\(pdfFiles\)/)
  assert.match(source, /setWorkoutImportFiles\(\(currentFiles\) => \{/)
  assert.match(source, /return \[\.\.\.currentFiles, \.\.\.newPdfFiles\]/)
  assert.match(source, /setIsAiWorkoutImportDialogOpen\(true\)/)
  assert.match(source, /const workoutImportPreviewFiles = useMemo\(\(\) => workoutImportFiles\.map\(\(file\) => \(\{/)
  assert.match(source, /previewUrl: URL\.createObjectURL\(file\)/)
  assert.match(source, /URL\.revokeObjectURL\(previewFile\.previewUrl\)/)
  assert.match(source, /function handleWorkoutImportPdfButtonClick\(\)/)
  assert.match(source, /if \(workoutImportFiles\.length > 0\) \{/)
  assert.match(source, /setIsAiWorkoutImportDialogOpen\(true\)[\s\S]*return/)
  assert.match(source, /document\.getElementById\('workout-import-pdf-upload'\)\?\.click\(\)/)
  assert.match(source, /async function handleGenerateWorkoutImportDraft\(\)/)
  assert.match(source, /setIsWorkoutAiProcessing\(true\)/)
  assert.match(source, /const formData = new FormData\(\)/)
  assert.match(source, /workoutImportFiles\.forEach\(\(file\) => formData\.append\('files', file\)\)/)
  assert.match(source, /fetch\('\/api\/admin\/ai-workout-drafts'/)
  assert.match(source, /setAiWorkoutDrafts\(body\.drafts \?\? \[\]\)/)
  assert.match(source, /setIsWorkoutAiProcessing\(false\)/)
  assert.doesNotMatch(source, /window\.setTimeout\(completeWorkoutAiDraftGeneration, 3000\)/)
  assert.doesNotMatch(source, /setAiWorkoutDrafts\(createSampleAiWorkoutDrafts\(workoutImportFiles\)\)/)
  assert.doesNotMatch(source, /function completeWorkoutAiDraftGeneration\(\)/)
  assert.match(source, /function handleCancelWorkoutAiProcessing\(\)/)

  assert.match(source, /aria-label="Workout import PDF upload"/)
  assert.match(source, /onClick=\{handleWorkoutImportPdfButtonClick\}/)
  assert.match(source, /id="workout-import-pdf-upload"/)
  assert.match(source, /accept="application\/pdf"/)
  assert.match(source, /onChange=\{handleWorkoutImportPdfUpload\}/)
  assert.match(source, /<Button[\s\S]*variant="outline"[\s\S]*onClick=\{handleWorkoutImportPdfButtonClick\}[\s\S]*rounded-\[12px\][\s\S]*min-h-\[40px\][\s\S]*border-\[color:var\(--admin-dashboard-card-border\)\][\s\S]*bg-\[var\(--admin-dashboard-control-bg\)\][\s\S]*hover:bg-\[var\(--admin-dashboard-control-hover-bg\)\][\s\S]*<Upload className="size-4" aria-hidden="true" \/>[\s\S]*Upload PDF[\s\S]*<\/Button>/)

  assert.match(source, /<Dialog open=\{isAiWorkoutImportDialogOpen\} onOpenChange=\{setIsAiWorkoutImportDialogOpen\}>/)
  assert.match(source, /<DialogTitle>Generate workout with AI<\/DialogTitle>/)
  assert.match(source, /\{isWorkoutAiProcessing \? \(/)
  assert.match(source, /<Empty[\s\S]*className="min-h-\[420px\] border-0 bg-transparent p-0"[\s\S]*>/)
  assert.match(source, /<EmptyMedia[\s\S]*variant="icon"[\s\S]*bg-\[#3BE0AF\]\/10[\s\S]*text-\[#3BE0AF\][\s\S]*>/)
  assert.match(source, /<LoaderCircle className="size-6 animate-spin text-\[#3BE0AF\]" aria-hidden="true" \/>/)
  assert.doesNotMatch(source, /<LoaderCircle className="size-6 animate-spin text-white" aria-hidden="true" \/>/)
  assert.match(source, /<EmptyTitle[\s\S]*>Processing your request<\/EmptyTitle>/)
  assert.match(source, /<EmptyDescription[\s\S]*Please wait while we process your[\s\S]*request\. Do not refresh the page\.[\s\S]*<\/EmptyDescription>/)
  assert.match(source, /onClick=\{handleCancelWorkoutAiProcessing\}[\s\S]*Cancel/)
  assert.match(source, /\) : \(/)
  assert.doesNotMatch(source, /Upload a workout PDF, review the file, then generate the first AI draft\./)
  assert.match(source, /<DialogDescription>Upload some workouts PDF, review the files and then generate the first AI draft\.<\/DialogDescription>/)
  assert.doesNotMatch(source, /Drop files here or[\s\S]*browse files/)
  assert.doesNotMatch(source, /Maximum file size: 50MB • Maximum files: 10/)
  assert.match(source, /Files \(\{workoutImportFiles\.length\}\)/)
  assert.match(source, /Add files/)
  assert.match(source, /Remove all/)
  assert.match(source, /<Bot className="size-4" aria-hidden="true" \/>[\s\S]*Generate with AI/)
  assert.match(source, /className="rounded-\[12px\] min-h-\[40px\] bg-\[var\(--admin-shell-primary-button-bg\)\] text-\[#0B1120\] hover:bg-\[var\(--admin-shell-primary-button-bg\)\]"/)
  assert.match(source, /Name/)
  assert.match(source, /Type/)
  assert.match(source, /Size/)
  assert.match(source, /Actions/)
  assert.match(source, /<TableHeader className="\[&_tr\]:border-\[color:var\(--admin-dashboard-card-border\)\]">/)
  assert.match(source, /<TableBody className="\[&_tr\]:border-\[color:var\(--admin-dashboard-card-border\)\]">/)
  assert.match(source, /workoutImportPreviewFiles\.map\(\(previewFile\) => \(/)
  assert.match(source, /<a[\s\S]*href=\{previewFile\.previewUrl\}[\s\S]*target="_blank"[\s\S]*rel="noreferrer"[\s\S]*hover:text-\[#3BE0AF\][\s\S]*\{previewFile\.file\.name\}[\s\S]*<\/a>/)
  assert.match(source, /PDF/)
  assert.match(source, /Cancel/)
  assert.match(source, /Generate with AI/)
  assert.match(source, /Create workout/)
})
