import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const cssPath = resolve(repoRoot, 'apps/web/app/globals.css')
const cardPath = resolve(repoRoot, 'apps/web/components/ui/card.jsx')
const chartPath = resolve(repoRoot, 'apps/web/components/ui/chart.jsx')
const selectPath = resolve(repoRoot, 'apps/web/components/ui/select.jsx')
const dashboardPath = resolve(repoRoot, 'apps/web/components/admin/dashboard-overview.jsx')

test('admin dashboard overview body uses light-mode theme tokens for cards charts and controls', () => {
  const cssSource = readFileSync(cssPath, 'utf8')
  const cardSource = readFileSync(cardPath, 'utf8')
  const chartSource = readFileSync(chartPath, 'utf8')
  const selectSource = readFileSync(selectPath, 'utf8')
  const dashboardSource = readFileSync(dashboardPath, 'utf8')

  assert.match(cssSource, /html\[data-theme='light'\]\s*\{[^}]*--admin-shell-bg:\s*#F8FAFC;[^}]*--admin-dashboard-card-bg:\s*#ffffff;[^}]*--admin-dashboard-card-text:\s*#0f172a;[^}]*--admin-dashboard-card-muted:\s*#64748b;[^}]*--admin-dashboard-chart-grid:\s*#e2e8f0;[^}]*--admin-dashboard-chart-header-divider:\s*#F8FAFC;/)
  assert.match(cssSource, /html\[data-theme='dark'\]\s*\{[^}]*--admin-dashboard-card-bg:\s*#0e1828;[^}]*--admin-dashboard-card-text:\s*#eef4ff;[^}]*--admin-dashboard-card-muted:\s*#8ea0bc;[^}]*--admin-dashboard-chart-grid:\s*#24334a;[^}]*--admin-dashboard-chart-header-divider:\s*#24334a;/)

  assert.match(cssSource, /\.admin-shell-workspace\s*\{[^}]*background:\s*var\(--admin-shell-bg\);/)
  assert.match(cssSource, /\.admin-shell-workspace-title\s*\{[^}]*color:\s*var\(--admin-dashboard-card-text\);/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-range-button\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-range-menu\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-range-option-active\s*\{/)

  assert.match(selectSource, /border-\[color:var\(--admin-dashboard-card-border\)\]/)
  assert.match(selectSource, /borderColor:\s*'var\(--admin-dashboard-card-border\)'/)
  assert.match(selectSource, /bg-\[var\(--admin-dashboard-control-bg\)\]/)
  assert.match(selectSource, /text-\[var\(--admin-dashboard-card-text\)\]/)
  assert.match(selectSource, /bg-\[var\(--admin-dashboard-card-bg\)\]/)
  assert.match(selectSource, /data-\[highlighted\]:bg-\[var\(--admin-shell-nav-active-bg\)\]/)
  assert.match(selectSource, /data-\[highlighted\]:text-\[var\(--admin-shell-nav-active-text\)\]/)
  assert.match(selectSource, /bg-\[#F8FAFC\]/)
  assert.doesNotMatch(selectSource, /border-\[#24334A\]|bg-\[#111D30\]|text-\[#DCE6F8\]|focus:bg-\[#15233A\]/)

  assert.match(cardSource, /border-\[var\(--admin-dashboard-card-border\)\]/)
  assert.match(cardSource, /text-\[var\(--admin-dashboard-card-text\)\]/)
  assert.match(cardSource, /backgroundColor:\s*'var\(--admin-dashboard-card-bg\)'/)
  assert.match(cardSource, /backgroundImage:\s*'var\(--admin-dashboard-card-gradient\)'/)
  assert.match(cardSource, /text-\[var\(--admin-dashboard-card-muted\)\]/)
  assert.doesNotMatch(cardSource, /border-\[#24334A\]|text-\[#EEF4FF\]|text-\[#8EA0BC\]/)

  assert.match(chartSource, /bg-\[var\(--admin-dashboard-tooltip-bg\)\]/)
  assert.match(chartSource, /border-\[var\(--admin-dashboard-tooltip-border\)\]/)
  assert.match(chartSource, /text-\[var\(--admin-dashboard-card-text\)\]/)
  assert.match(chartSource, /text-\[var\(--admin-dashboard-card-muted\)\]/)
  assert.doesNotMatch(chartSource, /bg-\[#0a101d\]|border-\[#30405e\]|text-\[#eef4ff\]|text-\[#7f91af\]/)

  assert.match(dashboardSource, /admin-shell-overview-performance-chart/)
  assert.match(dashboardSource, /AreaChart/)
  assert.match(dashboardSource, /BarChart/)
  assert.match(dashboardSource, /ChartContainer/)
  assert.match(dashboardSource, /ChartTooltipContent/)
  assert.match(dashboardSource, /ChartLegendContent/)
  assert.match(dashboardSource, /dataKey="completed"/)
  assert.match(dashboardSource, /dataKey="assigned"/)
  assert.match(dashboardSource, /SelectTrigger[\s\S]*aria-label="Select a value"/)
  assert.match(dashboardSource, /admin-shell-overview-card-value/)
  assert.match(dashboardSource, /needsAttention:\s*AlertTriangle/)
  assert.match(dashboardSource, /dataKey="missed"/)
  assert.match(dashboardSource, /Training consistency/)
  assert.match(dashboardSource, /text-\[var\(--admin-dashboard-card-text\)\]/)
  assert.match(dashboardSource, /text-\[var\(--admin-dashboard-card-muted\)\]/)
  assert.doesNotMatch(dashboardSource, /text-\[#EEF4FF\]|text-\[#8EA0BC\]/)
  assert.match(cssSource, /\.admin-shell-overview-card-header\s*\{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-chart\s*\{[^}]*display:\s*flex;/)
  assert.match(dashboardSource, /completed:\s*\{[\s\S]*color:\s*'#3be0af'/)
  assert.match(dashboardSource, /assigned:\s*\{[\s\S]*color:\s*'#58c6ff'/)
  assert.match(cssSource, /\.admin-shell-overview-session-chart\s*\{[^}]*display:\s*flex;/)
  assert.match(dashboardSource, /planAdherenceChartConfig/)
  assert.match(dashboardSource, /Training consistency/)
  assert.doesNotMatch(dashboardSource, /RadarChart/)
  assert.doesNotMatch(dashboardSource, /PolarAngleAxis dataKey="time"/)
  assert.doesNotMatch(dashboardSource, /fillSessionTime/)
  assert.match(cssSource, /\.admin-shell-overview-card-value\s*\{[^}]*color:\s*var\(--admin-dashboard-card-text\);/)
  assert.match(cssSource, /\.admin-shell-overview-performance-value\s*\{[^}]*color:\s*var\(--admin-dashboard-card-text\);/)
  assert.match(cssSource, /\.admin-shell-overview-insight-value\s*\{[^}]*color:\s*var\(--admin-dashboard-card-text\);/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bar-completed\s*\{[^}]*background:\s*linear-gradient\(180deg, rgba\(59, 224, 175, 0\.96\)/)
  assert.doesNotMatch(dashboardSource, /stroke="#24334A"|stroke="#24334a"/)
})
