import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const athletesDataTablePath = resolve(repoRoot, 'apps/web/components/admin/athletes-data-table.jsx')
const tabsPath = resolve(repoRoot, 'apps/web/components/ui/tabs.jsx')

test('create athlete dialog uses the athlete profile form layout instead of invite copy', () => {
  assert.ok(existsSync(athletesDataTablePath), `expected athletes data table file to exist: ${athletesDataTablePath}`)
  assert.ok(existsSync(tabsPath), `expected shared tabs primitive to exist: ${tabsPath}`)

  const athletesDataTableSource = readFileSync(athletesDataTablePath, 'utf8')
  const tabsSource = readFileSync(tabsPath, 'utf8')

  assert.match(athletesDataTableSource, /from '@\/components\/ui\/input'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/select'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/tabs'/)
  assert.match(athletesDataTableSource, /Create athlete profile/)
  assert.match(athletesDataTableSource, /Add the athlete's personal details, profile photo, and preferred measurements\./)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-form/)
  assert.match(athletesDataTableSource, /<Dialog open=\{isCreateEditAthleteDialogOpen\} onOpenChange=\{setIsCreateEditAthleteDialogOpen\} modal=\{false\}>/)
  assert.match(athletesDataTableSource, /pageScrollable/)
  assert.doesNotMatch(athletesDataTableSource, /max-h-\[calc\(100vh-4rem\)\]/)
  assert.doesNotMatch(athletesDataTableSource, /min-h-0/)
  assert.doesNotMatch(athletesDataTableSource, /overflow-y-auto/)
  assert.match(athletesDataTableSource, /Upload avatar/)
  assert.match(athletesDataTableSource, /Avatar uploaded/)
  assert.match(athletesDataTableSource, /PNG, JPG up to 2MB/)
  assert.match(athletesDataTableSource, /type="file"/)
  assert.match(athletesDataTableSource, /First name/)
  assert.match(athletesDataTableSource, /Last name/)
  assert.match(athletesDataTableSource, /Date of birth/)
  assert.match(athletesDataTableSource, /Gender/)
  assert.match(athletesDataTableSource, /Position/)
  assert.match(athletesDataTableSource, /Height/)
  assert.match(athletesDataTableSource, /Weight/)
  assert.match(athletesDataTableSource, /defaultValue="imperial"/)
  assert.match(athletesDataTableSource, /<TabsTrigger value="imperial">Imperial<\/TabsTrigger>/)
  assert.match(athletesDataTableSource, /<TabsTrigger value="metric">Metric<\/TabsTrigger>/)
  assert.match(athletesDataTableSource, /<SelectItem value="forward">Forward<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="defense">Defense<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="goalie">Goalie<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="male">Male<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="female">Female<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="other">Other<\/SelectItem>/)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-row admin-shell-athletes-create-row-two-up/)
  assert.match(athletesDataTableSource, /h-36 w-36/)
  assert.match(athletesDataTableSource, /relative flex cursor-pointer flex-col items-center justify-center gap-4 px-6 py-2 text-center/)
  assert.match(athletesDataTableSource, /rounded-full border border-dashed border-\[#2B3D57\] bg-\[#0D1625\]/)
  assert.match(athletesDataTableSource, /absolute -right-2 -top-1 flex h-5 w-5 items-center justify-center rounded-full border border-\[#24334A\] bg-\[#111D30\] text-\[10px\]/)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-tabs/)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-submit/)
  assert.match(athletesDataTableSource, />\s*Create\s*<\/Button>/)

  assert.match(tabsSource, /export \{ Tabs, TabsList, TabsTrigger, TabsContent \}/)
  assert.match(tabsSource, /TabsPrimitive\.Root/)
  assert.match(tabsSource, /TabsPrimitive\.Trigger/)
  assert.match(tabsSource, /TabsPrimitive\.List/)
  assert.doesNotMatch(tabsSource, /bg-\[#111D30\] p-1 text-\[#8EA0BC\]/)
  assert.doesNotMatch(tabsSource, /inline-flex h-11 w-full items-center/)
  assert.match(tabsSource, /inline-flex h-11 w-full rounded-\[14px\]/)
})
