import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const calendarViewPath = resolve(repoRoot, 'apps/web/components/admin/workouts-calendar-view.jsx')
const calendarRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/workout-calendar/route.js')

test('workout calendar uses responsive event cards and the existing schedule dialog for editing workouts', () => {
  for (const path of [calendarViewPath, calendarRoutePath]) {
    assert.ok(existsSync(path), `expected workout calendar file to exist: ${path}`)
  }

  const calendarSource = readFileSync(calendarViewPath, 'utf8')
  const routeSource = readFileSync(calendarRoutePath, 'utf8')

  assert.match(calendarSource, /export default function WorkoutsCalendarView/)
  assert.match(calendarSource, /const \[selectedEventId, setSelectedEventId\] = useState\(null\)/)
  assert.match(calendarSource, /const \[isAssignmentDialogOpen, setIsAssignmentDialogOpen\] = useState\(false\)/)
  assert.match(calendarSource, /const \[assignmentDraft, setAssignmentDraft\] = useState\(\(\) => createAssignmentDraft\(\)\)/)
  assert.match(calendarSource, /const selectedEvent = useMemo/)
  assert.match(calendarSource, /Workout Calendar/)
  assert.match(calendarSource, /renderWeekGrid/)
  assert.match(calendarSource, /renderMonthGrid/)

  assert.match(calendarSource, /className="admin-shell-workouts-calendar-view grid gap-5"/)
  assert.match(calendarSource, /admin-shell-workouts-calendar-header grid gap-4 xl:grid-cols-\[minmax\(0,1fr\)_auto\] xl:items-start/)
  assert.match(calendarSource, /grid w-full gap-3 lg:grid-cols-\[auto_minmax\(0,1fr\)_auto\] lg:items-center/)
  assert.match(calendarSource, /justify-self-start xl:justify-self-end/)
  assert.match(calendarSource, /order-last w-full text-left[\s\S]*lg:order-none[\s\S]*lg:min-w-\[220px\][\s\S]*lg:text-center/)
  assert.match(calendarSource, /function DraggableWeekEventCard/)
  assert.match(calendarSource, /Open event editor/)
  assert.match(calendarSource, /function StaticEventCard[\s\S]*rounded-\[16px\] border px-3 py-3/)
  assert.match(calendarSource, /function StaticEventCard[\s\S]*line-clamp-2/)
  assert.match(calendarSource, /function StaticEventCard[\s\S]*text-\[10px\] font-semibold uppercase tracking-\[0\.16em\]/)
  assert.match(calendarSource, /getEventToneClasses/)
  assert.match(calendarSource, /Ends \{event\.endHour\}/)
  assert.match(calendarSource, /rounded-\[18px\] border px-4 py-4 text-left shadow-\[0_10px_24px_rgba\(0,0,0,0\.18\)\]/)
  assert.doesNotMatch(calendarSource, /Move earlier/)
  assert.doesNotMatch(calendarSource, /Move later/)
  assert.doesNotMatch(calendarSource, /Drag workout/)

  assert.match(calendarSource, /const \[isMonthOverflowDialogOpen, setIsMonthOverflowDialogOpen\] = useState\(false\)/)
  assert.match(calendarSource, /const \[monthOverflowDate, setMonthOverflowDate\] = useState\(null\)/)
  assert.match(calendarSource, /const \[dayPlaylistEventIds, setDayPlaylistEventIds\] = useState\(\[\]\)/)
  assert.match(calendarSource, /const \[dayPlaylistIndex, setDayPlaylistIndex\] = useState\(0\)/)
  assert.match(calendarSource, /useSearchParams/)
  assert.match(calendarSource, /debugDenseDay/)
  assert.match(calendarSource, /const DEBUG_DENSE_DAY_EVENTS = \[/)
  assert.match(calendarSource, /Preview mode/)
  assert.match(calendarSource, /Debug dense day/)
  assert.match(calendarSource, /forceDenseDayPreview \? \(/)
  assert.match(calendarSource, /function renderMonthGrid[\s\S]*events\.slice\(0, 2\)/)
  assert.match(calendarSource, /function renderMonthGrid[\s\S]*events\.length > 2/)
  assert.match(calendarSource, /function renderMonthGrid[\s\S]*Open workout overflow for day/)
  assert.match(calendarSource, /function renderMonthGrid[\s\S]*\+\{events\.length - 2\} more/)
  assert.match(calendarSource, /function openMonthOverflow\(date\)/)
  assert.match(calendarSource, /setMonthOverflowDate\(date\)/)
  assert.match(calendarSource, /setIsMonthOverflowDialogOpen\(true\)/)
  assert.match(calendarSource, /Dialog open=\{isMonthOverflowDialogOpen\}/)
  assert.match(calendarSource, /DialogTitle>\{monthOverflowEvents\.length\} workout\{monthOverflowEvents\.length === 1 \? '' : 's'\}/)
  assert.match(calendarSource, /Sorted by time/)
  assert.match(calendarSource, /\[\.\.\.getEventsForDate\(monthOverflowDate, calendarEvents\)\]\.sort/)
  assert.match(calendarSource, /left\.startHour \?\? '06:00'/)
  assert.match(calendarSource, /max-w-\[calc\(100%-1rem\)\][\s\S]*rounded-t-\[28px\][\s\S]*rounded-b-\[18px\][\s\S]*p-5/)
  assert.match(calendarSource, /data-\[state=open\]:slide-in-from-bottom-\[18%\]/)
  assert.match(calendarSource, /data-\[state=closed\]:slide-out-to-bottom-\[18%\]/)
  assert.match(calendarSource, /sm:max-w-\[420px\]/)
  assert.match(calendarSource, /sm:rounded-\[28px\]/)
  assert.match(calendarSource, /sm:bottom-auto[\s\S]*sm:top-\[50%\][\s\S]*sm:-translate-y-1\/2/)
  assert.match(calendarSource, /Day/)
  assert.match(calendarSource, /monthOverflowDate \? \(/)
  assert.match(calendarSource, /weekday: 'long'/)
  assert.match(calendarSource, /Workout count/)
  assert.match(calendarSource, /Open all in day/)
  assert.match(calendarSource, /function buildDayPlaylistEventIds\(events\)/)
  assert.match(calendarSource, /const playlistKeys = new Set\(\)/)
  assert.match(calendarSource, /playlistKey = `\$\{event\.startHour \?\? '06:00'\}-\$\{event\.title\.trim\(\)\.toLowerCase\(\)\}`/)
  assert.match(calendarSource, /const eventIds = buildDayPlaylistEventIds\(events\)/)
  assert.match(calendarSource, /setDayPlaylistEventIds\(eventIds\)/)
  assert.match(calendarSource, /setDayPlaylistIndex\(0\)/)
  assert.match(calendarSource, /openEventDialog\(firstEvent\.id, \{ dayPlaylistEventIds: eventIds, dayPlaylistIndex: 0, dayPlaylistRawCount: events\.length \}\)/)
  assert.match(calendarSource, /const activeDayPlaylistEvents = useMemo/)
  assert.match(calendarSource, /const unresolvedDayPlaylistEventIds = useMemo/)
  assert.match(calendarSource, /const activeDayPlaylistDedupedCount = activeDayPlaylistEvents\.length/)
  assert.match(calendarSource, /const activeDayPlaylistRawCount = dayPlaylistRawCount/)
  assert.match(calendarSource, /const isDayPlaylistActive = activeDayPlaylistEvents\.length > 1/)
  assert.match(calendarSource, /function goToDayPlaylistEvent\(nextIndex\)/)
  assert.match(calendarSource, /function reopenMonthOverflowFromPlaylist\(\)/)
  assert.match(calendarSource, /setIsAssignmentDialogOpen\(false\)/)
  assert.match(calendarSource, /setIsMonthOverflowDialogOpen\(true\)/)
  assert.match(calendarSource, /Previous workout/)
  assert.match(calendarSource, /Next workout/)
  assert.match(calendarSource, /Back to overflow list/)
  assert.match(calendarSource, /Save & next/)
  assert.match(calendarSource, /async function saveAndAdvanceDayPlaylist\(\)/)
  assert.match(calendarSource, /const nextUnresolvedEventId = unresolvedDayPlaylistEventIds\.find/)
  assert.match(calendarSource, /setCompletedDayPlaylistEventIds\(\(currentIds\) => currentIds\.includes\(selectedEvent\.id\) \? currentIds : \[\.\.\.currentIds, selectedEvent\.id\]\)/)
  assert.match(calendarSource, /await updateScheduledEvent\(\{ advanceToNext: true \}\)/)
  assert.match(calendarSource, /Workout \{dayPlaylistIndex \+ 1\} of \{activeDayPlaylistDedupedCount\}/)
  assert.match(calendarSource, /Deduped from \{activeDayPlaylistRawCount\} to \{activeDayPlaylistDedupedCount\}/)
  assert.match(calendarSource, /border-t border-\[#24334A\] pt-3/)
  assert.match(calendarSource, /monthOverflowEvents\.map/)
  assert.match(calendarSource, /rounded-full h-2\.5 w-2\.5/)
  assert.match(calendarSource, /typeLabel/)
  assert.match(calendarSource, /Open event editor"/)
  assert.match(calendarSource, /function renderWeekGrid[\s\S]*Weekly schedule/)

  assert.match(calendarSource, /overflow-x-auto/)
  assert.match(calendarSource, /min-w-\[720px\]/)
  assert.match(calendarSource, /Assign workout/)
  assert.match(calendarSource, /Drop workout here/)
  assert.match(calendarSource, /Slot/)
  assert.match(calendarSource, /Schedule workout/)
  assert.match(calendarSource, /function openEventDialog\([\s\S]*dayPlaylistEventIds: nextPlaylistEventIds = \[\],[\s\S]*dayPlaylistIndex: nextDayPlaylistIndex = 0,[\s\S]*dayPlaylistRawCount: nextDayPlaylistRawCount = 0[\s\S]*\)/)
  assert.match(calendarSource, /setSelectedEventId\(eventId\)/)
  assert.match(calendarSource, /setAssignmentDraft\(createAssignmentDraft\(event\.startDate, event\.startHour, event\.workoutTemplateId\)\)/)
  assert.match(calendarSource, /setIsAssignmentDialogOpen\(true\)/)

  assert.match(calendarSource, /Dialog open=\{isAssignmentDialogOpen\} onOpenChange=\{\(open\) => \{/)
  assert.match(calendarSource, /DialogTitle>Schedule workout<\/DialogTitle>/)
  assert.match(calendarSource, /Select a workout template and save it into this calendar slot\./)
  assert.match(calendarSource, /selectedEvent \? selectedEvent\.title : selectedTemplate\.title/)
  assert.match(calendarSource, /selectedEvent \? 'Save changes' : 'Save assignment'/)
  assert.match(calendarSource, /selectedEvent \? updateScheduledEvent : createAssignment/)
  assert.match(calendarSource, /selectedEvent \? \(/)
  assert.match(calendarSource, /Delete workout/)
  assert.doesNotMatch(calendarSource, /Selected workout details/)
  assert.doesNotMatch(calendarSource, /Click a scheduled workout to inspect the slot, template, and calendar actions\./)
  assert.doesNotMatch(calendarSource, /Time window/)
  assert.doesNotMatch(calendarSource, /Calendar actions/)

  assert.match(routeSource, /export async function GET\(request\)/)
  assert.match(routeSource, /export async function POST\(request\)/)
  assert.match(routeSource, /export async function PATCH\(request\)/)
  assert.match(routeSource, /export async function DELETE\(request\)/)
})
