import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const cssPath = resolve(repoRoot, 'apps/web/app/globals.css')
const adminIndexPath = resolve(repoRoot, 'apps/web/app/admin/page.jsx')
const adminUiPath = resolve(repoRoot, 'apps/web/app/admin/ui/page.jsx')
const adminSectionPath = resolve(repoRoot, 'apps/web/app/admin/[section]/page.jsx')
const adminSubsectionPath = resolve(repoRoot, 'apps/web/app/admin/[section]/[subsection]/page.jsx')
const adminShellPath = resolve(repoRoot, 'apps/web/components/admin/admin-shell.jsx')
const dashboardOverviewPath = resolve(repoRoot, 'apps/web/components/admin/dashboard-overview.jsx')
const athletesListViewPath = resolve(repoRoot, 'apps/web/components/admin/athletes-list-view.jsx')
const athletesDataTablePath = resolve(repoRoot, 'apps/web/components/admin/athletes-data-table.jsx')
const adminAthletesRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/athletes/route.js')
const adminAthleteRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-athlete-repository.js')
const invitesListViewPath = resolve(repoRoot, 'apps/web/components/admin/invites-list-view.jsx')
const invitesDataTablePath = resolve(repoRoot, 'apps/web/components/admin/invites-data-table.jsx')
const adminInvitesRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/invites/route.js')
const adminInviteRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-invite-repository.js')
const groupsListViewPath = resolve(repoRoot, 'apps/web/components/admin/groups-list-view.jsx')
const groupsDataTablePath = resolve(repoRoot, 'apps/web/components/admin/groups-data-table.jsx')
const adminGroupsRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/groups/route.js')
const adminGroupRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-group-repository.js')
const rankingsListViewPath = resolve(repoRoot, 'apps/web/components/admin/rankings-list-view.jsx')
const rankingsDataTablePath = resolve(repoRoot, 'apps/web/components/admin/rankings-data-table.jsx')
const programsLibraryViewPath = resolve(repoRoot, 'apps/web/components/admin/programs-library-view.jsx')
const programsDataTablePath = resolve(repoRoot, 'apps/web/components/admin/programs-data-table.jsx')
const adminProgramsRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/programs/route.js')
const adminProgramRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-program-repository.js')
const exercisesLibraryViewPath = resolve(repoRoot, 'apps/web/components/admin/exercises-library-view.jsx')
const exercisesDataTablePath = resolve(repoRoot, 'apps/web/components/admin/exercises-data-table.jsx')
const adminExercisesRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/exercises/route.js')
const adminExerciseRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-exercise-repository.js')
const programPlannerPagePath = resolve(repoRoot, 'apps/web/app/admin/programs/[programId]/page.jsx')
const programPlannerViewPath = resolve(repoRoot, 'apps/web/components/admin/program-planner-view.jsx')
const programPlannerDataPath = resolve(repoRoot, 'apps/web/components/admin/program-planner-data.js')
const programPlannerUtilsPath = resolve(repoRoot, 'apps/web/components/admin/program-planner-utils.js')
const kanbanUiPath = resolve(repoRoot, 'apps/web/components/ui/kanban.jsx')
const adminButtonPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-button.jsx')
const adminNavigationPath = resolve(repoRoot, 'apps/web/components/admin/admin-navigation.js')
const sidebarPath = resolve(repoRoot, 'apps/web/components/ui/sidebar.jsx')
const dropdownMenuPath = resolve(repoRoot, 'apps/web/components/ui/dropdown-menu.jsx')
const cardPath = resolve(repoRoot, 'apps/web/components/ui/card.jsx')
const inviteAthleteIllustrationPath = resolve(repoRoot, 'apps/web/public/admin/invite_athlete_img.svg')
const rulesetPath = resolve(repoRoot, 'docs/admin-ui-ruleset.md')

test('admin navigation uses real nested routes driven by shared config', () => {
  for (const path of [
    adminIndexPath,
    adminUiPath,
    adminSectionPath,
    adminSubsectionPath,
    adminShellPath,
    dashboardOverviewPath,
    athletesListViewPath,
    athletesDataTablePath,
    adminAthletesRoutePath,
    adminAthleteRepositoryPath,
    invitesListViewPath,
    invitesDataTablePath,
    adminInvitesRoutePath,
    adminInviteRepositoryPath,
    groupsListViewPath,
    groupsDataTablePath,
    adminGroupsRoutePath,
    adminGroupRepositoryPath,
    rankingsListViewPath,
    rankingsDataTablePath,
    programsLibraryViewPath,
    programsDataTablePath,
    adminProgramsRoutePath,
    adminProgramRepositoryPath,
    exercisesLibraryViewPath,
    exercisesDataTablePath,
    adminExercisesRoutePath,
    adminExerciseRepositoryPath,
    programPlannerPagePath,
    programPlannerViewPath,
    programPlannerDataPath,
    programPlannerUtilsPath,
    kanbanUiPath,
    adminButtonPath,
    adminNavigationPath,
    sidebarPath,
    dropdownMenuPath,
    cardPath,
    inviteAthleteIllustrationPath,
  ]) {
    assert.ok(existsSync(path), `expected admin navigation file to exist: ${path}`)
  }

  const cssSource = readFileSync(cssPath, 'utf8')
  const adminIndexSource = readFileSync(adminIndexPath, 'utf8')
  const adminUiSource = readFileSync(adminUiPath, 'utf8')
  const adminSectionSource = readFileSync(adminSectionPath, 'utf8')
  const adminSubsectionSource = readFileSync(adminSubsectionPath, 'utf8')
  const adminShellSource = readFileSync(adminShellPath, 'utf8')
  const dashboardOverviewSource = readFileSync(dashboardOverviewPath, 'utf8')
  const athletesListViewSource = readFileSync(athletesListViewPath, 'utf8')
  const athletesDataTableSource = readFileSync(athletesDataTablePath, 'utf8')
  const adminAthletesRouteSource = readFileSync(adminAthletesRoutePath, 'utf8')
  const adminAthleteRepositorySource = readFileSync(adminAthleteRepositoryPath, 'utf8')
  const invitesListViewSource = readFileSync(invitesListViewPath, 'utf8')
  const invitesDataTableSource = readFileSync(invitesDataTablePath, 'utf8')
  const adminInvitesRouteSource = readFileSync(adminInvitesRoutePath, 'utf8')
  const adminInviteRepositorySource = readFileSync(adminInviteRepositoryPath, 'utf8')
  const groupsListViewSource = readFileSync(groupsListViewPath, 'utf8')
  const groupsDataTableSource = readFileSync(groupsDataTablePath, 'utf8')
  const adminGroupsRouteSource = readFileSync(adminGroupsRoutePath, 'utf8')
  const adminGroupRepositorySource = readFileSync(adminGroupRepositoryPath, 'utf8')
  const rankingsListViewSource = readFileSync(rankingsListViewPath, 'utf8')
  const rankingsDataTableSource = readFileSync(rankingsDataTablePath, 'utf8')
  const programsLibraryViewSource = readFileSync(programsLibraryViewPath, 'utf8')
  const programsDataTableSource = readFileSync(programsDataTablePath, 'utf8')
  const adminProgramsRouteSource = readFileSync(adminProgramsRoutePath, 'utf8')
  const adminProgramRepositorySource = readFileSync(adminProgramRepositoryPath, 'utf8')
  const exercisesLibraryViewSource = readFileSync(exercisesLibraryViewPath, 'utf8')
  const exercisesDataTableSource = readFileSync(exercisesDataTablePath, 'utf8')
  const adminExercisesRouteSource = readFileSync(adminExercisesRoutePath, 'utf8')
  const adminExerciseRepositorySource = readFileSync(adminExerciseRepositoryPath, 'utf8')
  const programPlannerPageSource = readFileSync(programPlannerPagePath, 'utf8')
  const programPlannerViewSource = readFileSync(programPlannerViewPath, 'utf8')
  const programPlannerDataSource = readFileSync(programPlannerDataPath, 'utf8')
  const programPlannerUtilsSource = readFileSync(programPlannerUtilsPath, 'utf8')
  const kanbanUiSource = readFileSync(kanbanUiPath, 'utf8')
  const adminButtonSource = readFileSync(adminButtonPath, 'utf8')
  const adminNavigationSource = readFileSync(adminNavigationPath, 'utf8')
  const sidebarSource = readFileSync(sidebarPath, 'utf8')
  const dropdownMenuSource = readFileSync(dropdownMenuPath, 'utf8')
  const cardSource = readFileSync(cardPath, 'utf8')
  const rulesetSource = readFileSync(rulesetPath, 'utf8')

  assert.match(cssSource, /--card:\s*lab\(10\.573547% 1\.442514 -14\.355978\);/)
  assert.match(cssSource, /\.ui-badge \{[^}]*column-gap:\s*6px;/)
  assert.doesNotMatch(cssSource, /\.ui-badge \{[^}]*text-transform:\s*uppercase;/)
  assert.match(adminIndexSource, /redirect\('\/admin\/dashboard'\)/)
  assert.match(adminUiSource, /redirect\('\/admin\/dashboard'\)/)

  assert.match(adminSectionSource, /AdminShell/)
  assert.match(adminSectionSource, /params/)
  assert.match(adminSectionSource, /section/)
  assert.match(adminSubsectionSource, /AdminShell/)
  assert.match(adminSubsectionSource, /subsection/)
  assert.match(adminSubsectionSource, /redirect\('\/admin\/dashboard'\)/)

  assert.match(adminShellSource, /from '@\/components\/ui\/sidebar'/)
  assert.match(adminShellSource, /from '@\/components\/ui\/dropdown-menu'/)
  assert.match(adminShellSource, /from '\.\/admin-navigation'/)
  assert.match(adminShellSource, /from '\.\/dashboard-overview'/)
  assert.match(adminShellSource, /from '\.\/athletes-list-view'/)
  assert.match(adminShellSource, /from '\.\/invites-list-view'/)
  assert.match(adminShellSource, /from '\.\/groups-list-view'/)
  assert.match(adminShellSource, /from '\.\/rankings-list-view'/)
  assert.match(adminShellSource, /from '\.\/programs-library-view'/)
  assert.match(adminShellSource, /SidebarProvider/)
  assert.match(adminShellSource, /SidebarInset/)
  assert.match(adminShellSource, /SidebarTrigger/)
  assert.match(adminShellSource, /SidebarRail/)
  assert.match(adminShellSource, /SidebarGroupLabel/)
  assert.match(adminShellSource, /SidebarContent className="px-3 pb-20 group-data-\[collapsible=icon\]:px-2"/)
  assert.match(adminShellSource, /AdminDashboardSidebar/)
  assert.match(adminShellSource, /currentPath/)
  assert.match(adminShellSource, /pageTitle/)
  assert.match(adminShellSource, /DashboardOverview/)
  assert.match(adminShellSource, /DashboardShellHeader/)
  assert.match(adminShellSource, /useState\(/)
  assert.match(adminShellSource, /const \[topbarSearchQuery, setTopbarSearchQuery\] = useState\(''\)/)
  assert.match(adminShellSource, /<DashboardShellHeader searchQuery=\{topbarSearchQuery\} onSearchQueryChange=\{setTopbarSearchQuery\} \/>/)
  assert.match(adminShellSource, /from '@\/components\/ui\/input'/)
  assert.match(adminShellSource, /from '@\/components\/ui\/button'/)
  assert.match(adminShellSource, /Search athletes, programs, or groups/)
  assert.match(adminShellSource, /aria-label="Toggle sidebar"/)
  assert.match(adminShellSource, /<SidebarTrigger/)
  assert.match(adminShellSource, /rounded-md border border-\[#24334A\]/)
  assert.match(adminShellSource, /hover:bg-\[#15233A\] hover:text-\[#EEF4FF\]/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*<Input/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*value=\{searchQuery\}/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*onChange=\{\(event\) => onSearchQueryChange\(event\.target\.value\)\}/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*<Button/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*admin-dashboard-topbar-search/)
  assert.match(adminShellSource, /placeholder="Search athletes, programs, or groups"/)
  assert.match(adminShellSource, /rounded-\[12px\]/)
  assert.doesNotMatch(adminShellSource, /rounded-l-lg/)
  assert.doesNotMatch(adminShellSource, /rounded-r-lg/)
  assert.doesNotMatch(adminShellSource, /rounded-l-none/)
  assert.doesNotMatch(adminShellSource, /rounded-r-none/)
  assert.match(adminShellSource, /h-\[35px\] max-h-\[35px\]/)
  assert.match(adminShellSource, /aria-label="Search athletes, programs, or groups"/)
  assert.match(adminShellSource, /aria-label="Submit search"/)
  assert.match(adminShellSource, /bg-\[#3BE0AF\][\s\S]*text-\[#0B1120\][\s\S]*hover:bg-\[#35c89d\]/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*<DropdownMenu/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*aria-label="Open top account menu"/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*side="bottom"/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*align="end"/)
  assert.match(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*DropdownMenuLabel>My Account<\/DropdownMenuLabel/)
  assert.doesNotMatch(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*<span[\s\S]*aria-label="Anthony Fortugno"/)
  assert.doesNotMatch(adminShellSource, /function DashboardShellHeader\(\{ searchQuery = '', onSearchQueryChange = \(\) => \{\} \}\) \{[\s\S]*<label className="admin-dashboard-topbar-search flex h-11 min-w-0 flex-1 items-center gap-3 rounded-lg border border-\[#24334A\] bg-\[#111D30\] px-4 text-sm text-\[#8EA0BC\]">[\s\S]*<input/)
  assert.match(adminShellSource, /const topSections = \[\.\.\.adminNavigation, \.\.\.adminBottomNavigation\]/)
  assert.doesNotMatch(adminShellSource, /const bottomSections = adminBottomNavigation/)
  assert.match(adminShellSource, /const workspaceSwitcher =/)
  assert.match(adminShellSource, /const accountSwitcher =/)
  assert.match(adminShellSource, /DropdownMenuLabel>Athletes<\/DropdownMenuLabel/)
  assert.doesNotMatch(adminShellSource, /DropdownMenuLabel>Shortcuts<\/DropdownMenuLabel/)
  assert.match(adminShellSource, /function getAthleteInitials\(/)
  assert.match(adminShellSource, /function formatAthleteBirthSummary\(/)
  assert.match(adminShellSource, /function formatAthleteDateOfBirth\(/)
  assert.match(adminShellSource, /function getAthleteAge\(/)
  assert.match(adminShellSource, /<DropdownMenuShortcut className="ml-0 text-\[11px\] font-semibold tracking-\[0\.12em\] text-\[#8EA0BC\]">\{athlete\.shortcutCode\}<\/DropdownMenuShortcut>/)
  assert.match(adminShellSource, /const accountMenuItems = \[/)
  assert.match(adminShellSource, /\{ id: 'profile', label: 'Profile' \}/)
  assert.match(adminShellSource, /\{ id: 'billing', label: 'Billing' \}/)
  assert.match(adminShellSource, /\{ id: 'settings', label: 'Settings' \}/)
  assert.match(adminShellSource, /\{ id: 'keyboard-shortcuts', label: 'Keyboard shortcuts' \}/)
  assert.match(adminShellSource, /DropdownMenuSeparator \/>/)
  assert.match(adminShellSource, /side="right"/)
  assert.match(adminShellSource, /align="start"/)
  assert.match(adminShellSource, /sideOffset=\{12\}/)
  assert.match(adminShellSource, /className="h-14 w-full rounded-2xl border border-\[#24334A\] bg-\[#111D30\] px-3 hover:bg-\[#15233a\] hover:text-\[#eef4ff\] group-data-\[collapsible=icon\]:hidden"/)
  assert.match(adminShellSource, /function SidebarAccountSwitcher\(\) \{[\s\S]*<DropdownMenu[\s\S]*<DropdownMenuTrigger asChild[\s\S]*<SidebarMenuButton size="lg"/)
  assert.match(adminShellSource, /function SidebarAccountSwitcher\(\) \{[\s\S]*<DropdownMenuContent[\s\S]*My Account/)
  assert.match(adminShellSource, /function SidebarBrandLogo\(\) \{[\s\S]*?className="flex items-center justify-start px-3 py-\[14px\] group-data-\[collapsible=icon\]:justify-center group-data-\[collapsible=icon\]:px-2"/)
  assert.doesNotMatch(adminShellSource, /function SidebarBrandLogo\(\) \{[\s\S]*?<div className="[^"]*rounded-2xl border border-\[#24334A\] bg-\[#111D30\]/)
  assert.match(adminShellSource, /PPLUS Training/)
  assert.match(adminShellSource, /const workspaceSwitcher =/)
  assert.match(adminShellSource, /DropdownMenu/)
  assert.match(adminShellSource, /DropdownMenuTrigger/)
  assert.match(adminShellSource, /DropdownMenuContent/)
  assert.match(adminShellSource, /DropdownMenuLabel/)
  assert.match(adminShellSource, /DropdownMenuItem/)
  assert.match(adminShellSource, /side="right"/)
  assert.match(adminShellSource, /align="start"/)
  assert.match(adminShellSource, /sideOffset=\{12\}/)
  assert.match(adminShellSource, /className="w-\[280px\] rounded-2xl border border-\[#24334A\] bg-\[#111D30\] p-2 text-\[#DCE6F8\] shadow-\[0_16px_40px_rgba\(0,0,0,0\.45\)\]"/)
  assert.match(adminShellSource, /<DropdownMenu[\s\S]*<DropdownMenuTrigger asChild[\s\S]*<SidebarMenuButton size="lg"/)
  assert.match(adminShellSource, /Search athlete or shortcut/)
  assert.match(adminShellSource, /function SidebarWorkspaceSwitcher\([\s\S]*Search athlete or shortcut[\s\S]*className="h-\[35px\] max-h-\[35px\] flex-1 rounded-\[12px\] border-\[#24334A\] bg-\[#111D30\] px-4 text-sm text-\[#DCE6F8\] placeholder:text-\[#70809E\] focus-visible:border-\[#3BE0AF\] focus-visible:ring-\[#3BE0AF\]\/20"/)

  assert.match(adminShellSource, /tonyfortugno22@gmail\.com/)
  assert.match(adminShellSource, /ChevronsUpDown/)
  assert.match(adminShellSource, /BadgeCheck/)
  assert.match(adminShellSource, /SidebarMenuButton[\s\S]*workspaceSwitcher/)
  assert.match(adminShellSource, /SidebarMenuButton[\s\S]*accountSwitcher/)
  assert.match(adminShellSource, /AthletesListView/)
  assert.match(adminShellSource, /InvitesListView/)
  assert.match(adminShellSource, /GroupsListView/)
  assert.match(adminShellSource, /RankingsListView/)
  assert.match(adminShellSource, /<InvitesListView searchQuery=\{topbarSearchQuery\} \/>/)
  assert.match(adminShellSource, /<GroupsListView searchQuery=\{topbarSearchQuery\} \/>/)
  assert.match(adminShellSource, /<RankingsListView searchQuery=\{topbarSearchQuery\} \/>/)
  assert.match(adminShellSource, /ProgramsLibraryView/)
  assert.match(adminNavigationSource, /id: 'programs'/)
  assert.match(adminNavigationSource, /label: 'Library'/)
  assert.match(adminNavigationSource, /label: 'Calendar'/)
  assert.match(adminNavigationSource, /id: 'settings'/)
  assert.match(adminNavigationSource, /label: 'Profile'/)
  assert.match(adminNavigationSource, /label: 'Preferences'/)
  assert.match(adminNavigationSource, /label: 'Integrations'/)
  assert.match(adminNavigationSource, /label: 'Admin Tools'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Assigned'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Templates'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Sessions'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Categories'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Medias?'/)
  assert.doesNotMatch(adminNavigationSource, /id: 'analytics'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/analytics/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Workspace'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Team'/)
  assert.doesNotMatch(adminShellSource, /currentPath === '\/admin\/analytics'/)
  assert.doesNotMatch(adminShellSource, /currentPath === '\/admin\/analytics\//)
  assert.match(adminShellSource, /group\.items\?\.length/)
  assert.match(adminShellSource, /<details className="group\/admin-sidebar-item" open=\{showSubtabs\}>/)
  assert.match(adminShellSource, /className="min-h-10 rounded-2xl px-3 text-\[13px\] font-medium text-\[#dbe4ef\] data-\[active=true\]:bg-\[#2d4c4c\] data-\[active=true\]:text-\[#3BE0AF\] hover:bg-\[#111d30\] hover:text-\[#eef4ff\] group-data-\[collapsible=icon\]:!size-10 group-data-\[collapsible=icon\]:justify-center group-data-\[collapsible=icon\]:rounded-xl group-data-\[collapsible=icon\]:px-0"/)
  assert.match(adminShellSource, /className="h-8 rounded-xl px-3 text-\[12px\] text-\[#8ea0bc\] data-\[active=true\]:bg-\[#2d4c4c\] data-\[active=true\]:font-medium data-\[active=true\]:text-\[#3BE0AF\] hover:bg-\[#111d30\] hover:text-\[#eef4ff\]"/)
  assert.match(adminShellSource, /<SidebarMenuButton\s+asChild[\s\S]*<summary className="list-none/)
  assert.doesNotMatch(adminShellSource, /\{isActive && group\.items\?\.length \? \(/)
  assert.match(adminShellSource, /collapsible="icon"/)
  assert.match(adminShellSource, /<SidebarRail/)
  assert.match(sidebarSource, /function SidebarRail/)
  assert.match(sidebarSource, /function SidebarTrigger/)
  assert.match(sidebarSource, /PanelLeftIcon/)
  assert.match(sidebarSource, /w-10 transition-all ease-linear group-data-\[side=left\]:-right-5/)
  assert.doesNotMatch(sidebarSource, /pointer-events-auto absolute left-1\/2 top-6 z-10 flex size-8/)
  assert.match(dropdownMenuSource, /"use client"/)
  assert.match(dropdownMenuSource, /from "radix-ui"/)
  assert.match(dropdownMenuSource, /DropdownMenu as DropdownMenuPrimitive/)
  assert.match(dropdownMenuSource, /data-\[side=right\]:slide-in-from-left-2/)
  assert.match(dropdownMenuSource, /function DropdownMenuShortcut/)
  assert.match(cardSource, /function Card\(/)
  assert.match(cardSource, /bg-\[color:var\(--card\)\]/)
  assert.match(cardSource, /backgroundColor:\s*'var\(--card\)'/)
  assert.match(cardSource, /backgroundImage:\s*'linear-gradient\(to top, rgb\(59 224 175 \/ 0\.05\), var\(--card\)\)'/)
  assert.match(cardSource, /function CardHeader\(/)
  assert.match(cardSource, /function CardTitle\(/)
  assert.match(cardSource, /function CardDescription\(/)
  assert.match(cardSource, /function CardAction\(/)
  assert.match(cardSource, /function CardFooter\(/)
  assert.match(cardSource, /data-slot="card"/)
  assert.doesNotMatch(adminShellSource, /collapsible="none"/)
  assert.doesNotMatch(adminShellSource, /<SidebarTrigger className="md:hidden/)
  assert.match(adminShellSource, /!isDashboardOverview && !isAllAthletesView && !isAthleteInvitesView && !isAthleteGroupsView && !isAthleteRankingsView && !isProgramsLibraryView &&/)
  assert.match(adminShellSource, /currentPath === '\/admin\/athletes'/)
  assert.match(adminShellSource, /currentPath === '\/admin\/athletes\/invites'/)
  assert.match(adminShellSource, /currentPath === '\/admin\/athletes\/groups'/)
  assert.match(adminShellSource, /currentPath === '\/admin\/athletes\/rankings'/)
  assert.match(adminShellSource, /currentPath === '\/admin\/programs'/)
  assert.match(dashboardOverviewSource, /'use client'/)
  assert.match(dashboardOverviewSource, /useState/)
  assert.match(dashboardOverviewSource, /Users/)
  assert.match(dashboardOverviewSource, /CalendarRange/)
  assert.match(dashboardOverviewSource, /Activity/)
  assert.match(dashboardOverviewSource, /BadgeCheck/)
  assert.match(dashboardOverviewSource, /TrendingUp/)
  assert.match(dashboardOverviewSource, /TrendingDown/)
  assert.match(dashboardOverviewSource, /Send\b/)
  assert.match(dashboardOverviewSource, /icon:\s*Users/)
  assert.match(dashboardOverviewSource, /icon:\s*CalendarRange/)
  assert.match(dashboardOverviewSource, /icon:\s*Activity/)
  assert.match(dashboardOverviewSource, /icon:\s*BadgeCheck/)
  assert.match(dashboardOverviewSource, /icon:\s*Send/)
  assert.doesNotMatch(dashboardOverviewSource, /icon:\s*ClipboardList/)
  assert.doesNotMatch(dashboardOverviewSource, /icon:\s*SendHorizontal/)
  assert.match(dashboardOverviewSource, /overviewChartTabs/)
  assert.match(dashboardOverviewSource, /Last month/)
  assert.match(dashboardOverviewSource, /Last 7 days/)
  assert.match(dashboardOverviewSource, /Last 3 months/)
  assert.match(dashboardOverviewSource, /Last year/)
  assert.match(dashboardOverviewSource, /24 hours/)
  assert.match(dashboardOverviewSource, /30 days/)
  assert.match(dashboardOverviewSource, /12 month/)
  assert.match(dashboardOverviewSource, /overviewRangeOptions/)
  assert.match(dashboardOverviewSource, /from '@\/components\/ui\/badge'/)
  assert.match(dashboardOverviewSource, /from '@\/components\/ui\/card'/)
  assert.match(dashboardOverviewSource, /overviewRangeCardData/)
  assert.match(dashboardOverviewSource, /summaryCardRows = \[cards\.slice\(0, 3\), cards\.slice\(3\)\]/)
  assert.match(dashboardOverviewSource, /activeRange/)
  assert.match(dashboardOverviewSource, /setActiveRange/)
  assert.match(dashboardOverviewSource, /Dashboard overview/)
  assert.match(dashboardOverviewSource, /Dashboard summary cards/)
  assert.match(dashboardOverviewSource, /Dashboard analytics panels/)
  assert.match(dashboardOverviewSource, /Dashboard range options/)
  assert.match(dashboardOverviewSource, /Dashboard/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-toolbar/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-range-button/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-range-menu/)
  assert.match(dashboardOverviewSource, /Athletes/)
  assert.match(dashboardOverviewSource, /Programs/)
  assert.match(dashboardOverviewSource, /Sessions/)
  assert.match(dashboardOverviewSource, /Compliance/)
  assert.match(dashboardOverviewSource, /Pending invites/)
  assert.match(dashboardOverviewSource, /value: '8'/)
  assert.match(dashboardOverviewSource, /value: '4'/)
  assert.match(dashboardOverviewSource, /value: '148'/)
  assert.match(dashboardOverviewSource, /value: '3'/)
  assert.match(dashboardOverviewSource, /Roster growth stayed ahead of plan/)
  assert.match(dashboardOverviewSource, /Assignment volume needs attention/)
  assert.match(dashboardOverviewSource, /Completed sessions kept climbing/)
  assert.match(dashboardOverviewSource, /Daily adherence meets projections/)
  assert.match(dashboardOverviewSource, /Three invites are still pending/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-card-label-row/)
  assert.match(dashboardOverviewSource, /<span className="admin-shell-overview-card-label">\{card\.label\}<\/span>/)
  assert.doesNotMatch(dashboardOverviewSource, /admin-shell-overview-card-icon/)
  assert.match(dashboardOverviewSource, /<OverviewSummaryCard key=\{card\.id\} card=\{card\} \/>/)
  assert.match(dashboardOverviewSource, /<section className="flex flex-col gap-4 px-4 lg:px-0" aria-label="Dashboard summary cards">/)
  assert.match(dashboardOverviewSource, /className="grid grid-cols-1 gap-4 lg:grid-cols-3"/)
  assert.match(dashboardOverviewSource, /className="grid grid-cols-1 gap-4 lg:grid-cols-2"/)
  assert.match(dashboardOverviewSource, /function OverviewSummaryCard\(\{ card \}\)/)
  assert.match(dashboardOverviewSource, /className="@container\/card h-full"/)
  assert.match(dashboardOverviewSource, /CardDescription/)
  assert.match(dashboardOverviewSource, /CardTitle/)
  assert.match(dashboardOverviewSource, /CardAction/)
  assert.match(dashboardOverviewSource, /CardFooter/)
  assert.match(dashboardOverviewSource, /className="@container\/card h-full"/)
  assert.match(dashboardOverviewSource, /tone=\{card\.changeDirection === 'negative' \? 'danger' : 'success'\}/)
  assert.match(dashboardOverviewSource, /<Badge tone=\{card\.changeDirection === 'negative' \? 'danger' : 'success'\}>[\s\S]*\{card\.change\}[\s\S]*<TrendArrowIcon direction=\{card\.changeDirection\} \/>/)
  assert.match(dashboardOverviewSource, /<TrendArrowIcon direction=\{card\.changeDirection\} \/>/)
  assert.match(dashboardOverviewSource, /Trending up this month/)
  assert.match(dashboardOverviewSource, /Down 20% this period/)
  assert.match(dashboardOverviewSource, /Strong athlete retention/)
  assert.match(dashboardOverviewSource, /Steady compliance increase/)
  assert.match(dashboardOverviewSource, /More coaches inviting athletes/)
  assert.match(dashboardOverviewSource, /footerHeadline/)
  assert.match(dashboardOverviewSource, /footerSubtext/)
  assert.match(dashboardOverviewSource, /overviewPerformanceData/)
  assert.match(dashboardOverviewSource, /overviewComplianceData/)
  assert.match(dashboardOverviewSource, /overviewSessionTimeData/)
  assert.match(dashboardOverviewSource, /interactiveAreaChartData/)
  assert.match(dashboardOverviewSource, /interactiveAreaChartConfig/)
  assert.match(dashboardOverviewSource, /areaChartLegendData/)
  assert.match(dashboardOverviewSource, /areaChartLegendConfig/)
  assert.match(dashboardOverviewSource, /function AreaChartInteractiveCard\(\)/)
  assert.match(dashboardOverviewSource, /Area Chart - Interactive/)
  assert.match(dashboardOverviewSource, /Showing total visitors for the last 3 months/)
  assert.match(dashboardOverviewSource, /<section className="admin-shell-overview-analytics-layout" aria-label="Dashboard analytics panels">[\s\S]*<AreaChartInteractiveCard \/>[\s\S]*<div className="admin-shell-overview-bottom-row">[\s\S]*<BarChartMultipleCard \/>[\s\S]*<AreaChartLegendCard \/>[\s\S]*<\/div>[\s\S]*<\/section>/)
  assert.match(dashboardOverviewSource, /function BarChartMultipleCard\(\)/)
  assert.match(dashboardOverviewSource, /Bar Chart - Multiple/)
  assert.match(dashboardOverviewSource, /January - June 2024/)
  assert.match(dashboardOverviewSource, /Showing total visitors for the last 6 months/)
  assert.match(dashboardOverviewSource, /<BarChartMultipleCard \/>/)
  assert.match(dashboardOverviewSource, /function AreaChartLegendCard\(\)/)
  assert.match(dashboardOverviewSource, /<AreaChartLegendCard \/>/)
  assert.match(dashboardOverviewSource, /Area Chart - Legend/)
  assert.match(dashboardOverviewSource, /Trending up by 5\.2% this month/)
  assert.match(dashboardOverviewSource, /from 'recharts'/)
  assert.match(dashboardOverviewSource, /from '@\/components\/ui\/chart'/)
  assert.match(dashboardOverviewSource, /from '@\/components\/ui\/select'/)
  assert.match(dashboardOverviewSource, /<ChartContainer config=\{interactiveAreaChartConfig\} className="aspect-auto h-\[250px\] w-full">/)
  assert.match(dashboardOverviewSource, /<AreaChart accessibilityLayer data=\{filteredData\}>/)
  assert.match(dashboardOverviewSource, /<SelectTrigger className="w-\[160px\] rounded-lg sm:ml-auto" aria-label="Select a value">/)
  assert.match(dashboardOverviewSource, /Last 3 months/)
  assert.match(dashboardOverviewSource, /<ChartContainer config=\{areaChartLegendConfig\} className="h-\[250px\] w-full">/)
  assert.match(dashboardOverviewSource, /<BarChart accessibilityLayer data=\{areaChartLegendData\}/)
  assert.match(dashboardOverviewSource, /<ChartTooltip cursor=\{false\} content=\{<ChartTooltipContent indicator="dashed" \/>\} \/>/)
  assert.match(dashboardOverviewSource, /<Bar dataKey="desktop" fill="var\(--color-desktop\)" radius=\{4\} \/>/)
  assert.match(dashboardOverviewSource, /<Bar dataKey="mobile" fill="var\(--color-mobile\)" radius=\{4\} \/>/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-card-change-arrow-icon/)
  assert.match(dashboardOverviewSource, /function TrendArrowIcon/)
  assert.match(dashboardOverviewSource, /<TrendingDown className="admin-shell-overview-card-change-arrow-icon"/)
  assert.match(dashboardOverviewSource, /<TrendingUp className="admin-shell-overview-card-change-arrow-icon"/)
  assert.doesNotMatch(dashboardOverviewSource, /<ArrowDown className="admin-shell-overview-card-change-arrow-icon"/)
  assert.doesNotMatch(dashboardOverviewSource, /<ArrowUp className="admin-shell-overview-card-change-arrow-icon"/)
  assert.doesNotMatch(dashboardOverviewSource, /<TrendArrowIcon direction=\{card\.direction\} \/>/)
  assert.doesNotMatch(dashboardOverviewSource, /\{card\.direction === 'negative' \? '↓' : '↑'\}/)
  assert.doesNotMatch(dashboardOverviewSource, /\{data\.changeDirection === 'negative' \? '↓' : '↑'\}/)

  assert.match(athletesListViewSource, /'use client'/)
  assert.match(athletesListViewSource, /searchQuery/)
  assert.match(athletesListViewSource, /<AthletesDataTable searchQuery=\{searchQuery\} \/>/)
  assert.doesNotMatch(athletesListViewSource, /Search for an athlete by name\.\.\./)
  assert.doesNotMatch(athletesListViewSource, /Dialog/)
  assert.doesNotMatch(athletesListViewSource, /from '\.\.\/ui\/dialog'/)
  assert.match(athletesListViewSource, /<AthletesDataTable searchQuery=\{searchQuery\} \/>/)
  assert.doesNotMatch(athletesListViewSource, /Thomas Thibault/)
  assert.doesNotMatch(athletesListViewSource, /Training Program/)
  assert.doesNotMatch(athletesListViewSource, /12 \/ 40/)

  assert.match(athletesDataTableSource, /'use client'/)
  assert.match(athletesDataTableSource, /from '@tanstack\/react-table'/)
  assert.match(athletesDataTableSource, /useReactTable/)
  assert.match(athletesDataTableSource, /getCoreRowModel/)
  assert.match(athletesDataTableSource, /getFilteredRowModel/)
  assert.match(athletesDataTableSource, /getPaginationRowModel/)
  assert.match(athletesDataTableSource, /flexRender/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/table'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/checkbox'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/dropdown-menu'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/avatar'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/progress'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/badge'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/button'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/dialog'/)
  assert.match(athletesDataTableSource, /MoreHorizontal/)
  assert.match(athletesDataTableSource, /function NameCell\(/)
  assert.match(athletesDataTableSource, /function WorkoutsCell\(/)
  assert.match(athletesDataTableSource, /function StatusCell\(/)
  assert.match(athletesDataTableSource, /className="admin-shell-athletes-name-cell"/)
  assert.match(athletesDataTableSource, /className="admin-shell-athletes-avatar"/)
  assert.match(athletesDataTableSource, /className="admin-shell-athletes-name-copy"/)
  assert.match(athletesDataTableSource, /className="admin-shell-athletes-name-text"/)
  assert.match(athletesDataTableSource, /className="admin-shell-athletes-name-meta"/)
  assert.match(athletesDataTableSource, /formatAthleteDateOfBirthSummary/)
  assert.match(athletesDataTableSource, /initials=\{getInitials\(name\)\}/)
  assert.match(athletesDataTableSource, /Name/)
  assert.match(athletesDataTableSource, /Program/)
  assert.match(athletesDataTableSource, /Workouts/)
  assert.match(athletesDataTableSource, /Last active/)
  assert.match(athletesDataTableSource, /Status/)
  assert.match(athletesDataTableSource, /fetch\('\/api\/admin\/athletes'/)
  assert.match(athletesDataTableSource, /setAthletes\(/)
  assert.match(athletesDataTableSource, /setLoading\(/)
  assert.match(athletesDataTableSource, /setError\(/)
  assert.doesNotMatch(athletesDataTableSource, /const athletes = \[/)
  assert.doesNotMatch(athletesDataTableSource, /Mason Lee/)
  assert.doesNotMatch(athletesDataTableSource, /Noah Smith/)
  assert.doesNotMatch(athletesDataTableSource, /Speed Development/)
  assert.doesNotMatch(athletesDataTableSource, /Today, 8:30 AM/)
  assert.match(athletesDataTableSource, /Active/)
  assert.match(athletesDataTableSource, /Inactive/)
  assert.match(athletesDataTableSource, /const tone = status === 'Inactive' \? 'danger' : status === 'Active' \? 'success' : 'warning'/)
  assert.match(athletesDataTableSource, /const className =[\s\S]*normal-case tracking-normal/)
  assert.match(athletesDataTableSource, /<Badge tone=\{tone\} className=\{className\}>/)
  assert.match(athletesDataTableSource, /bg-emerald-500\/15 text-emerald-300 hover:bg-emerald-500\/20/)
  assert.match(athletesDataTableSource, /bg-red-500\/15 text-red-300 hover:bg-red-500\/20/)
  assert.doesNotMatch(athletesDataTableSource, /admin-shell-athletes-payment-status/)
  assert.match(athletesDataTableSource, /Columns/)
  assert.match(athletesDataTableSource, /DropdownMenuCheckboxItem/)
  assert.match(athletesDataTableSource, /columnVisibility/)
  assert.match(athletesDataTableSource, /setColumnVisibility/)
  assert.match(athletesDataTableSource, /getAllColumns\(\)/)
  assert.match(athletesDataTableSource, /toggleVisibility/)
  assert.match(athletesDataTableSource, /getColumn\('name'\)\?\.setFilterValue/)
  assert.match(athletesDataTableSource, /column\.columnDef\.meta\?\.label \?\? column\.id/)
  assert.match(athletesDataTableSource, /label: 'Name'/)
  assert.match(athletesDataTableSource, /label: 'Program'/)
  assert.match(athletesDataTableSource, /label: 'Workouts'/)
  assert.match(athletesDataTableSource, /label: 'Last active'/)
  assert.match(athletesDataTableSource, /label: 'Status'/)

  assert.match(adminAthletesRouteSource, /createAdminAthleteRepository/)
  assert.match(adminAthletesRouteSource, /repository\.listAthletes\(\)/)
  assert.match(adminAthletesRouteSource, /return json\(\{ athletes \}\)/)

  assert.match(adminAthleteRepositorySource, /athlete_profiles/)
  assert.match(adminAthleteRepositorySource, /programs/)
  assert.match(adminAthleteRepositorySource, /workout_sessions/)
  assert.match(adminAthleteRepositorySource, /listAthletes\(\)/)
  assert.match(adminAthleteRepositorySource, /fullName/)
  assert.match(adminAthleteRepositorySource, /lastActive/)
  assert.match(athletesDataTableSource, /export default function AthletesDataTable\(\{ searchQuery = '' \}\)/)
  assert.match(athletesDataTableSource, /const \[isInviteDialogOpen, setIsInviteDialogOpen\] = useState\(false\)/)
  assert.match(athletesDataTableSource, /const \[isCreateEditAthleteDialogOpen, setIsCreateEditAthleteDialogOpen\] = useState\(false\)/)
  assert.match(athletesDataTableSource, /const \[isDeleteDialogOpen, setIsDeleteDialogOpen\] = useState\(false\)/)
  assert.match(athletesDataTableSource, /useEffect\(/)
  assert.match(athletesDataTableSource, /table\.getColumn\('name'\)\?\.setFilterValue\(searchQuery\)/)
  assert.match(athletesDataTableSource, /Create athlete/)
  assert.match(athletesDataTableSource, /<Button[\s\S]*Create athlete[\s\S]*<\/Button>/)
  assert.match(athletesDataTableSource, /onClick=\{\(\) => setIsCreateEditAthleteDialogOpen\(true\)\}/)
  assert.match(athletesDataTableSource, /className="admin-shell-athletes-example-controls flex items-center justify-between gap-3"/)
  assert.match(athletesDataTableSource, /<div className="admin-shell-athletes-example-controls flex items-center justify-between gap-3">[\s\S]*<DropdownMenu>[\s\S]*admin-shell-athletes-example-columns-button[\s\S]*<Button[\s\S]*admin-shell-athletes-invite-button bg-\[#3BE0AF\] text-\[#0B1120\] hover:bg-\[#35c89d\] rounded-\[12px\] min-h-\[40px\]/)
  assert.match(athletesDataTableSource, /<Dialog open=\{isCreateEditAthleteDialogOpen\} onOpenChange=\{setIsCreateEditAthleteDialogOpen\} modal=\{false\}>/)
  assert.match(athletesDataTableSource, /<DialogContent[\s\S]*pageScrollable[\s\S]*className="admin-shell-athletes-invite-dialog[^\"]*sm:max-w-\[720px\][^\"]*"/)
  assert.match(athletesDataTableSource, /<DialogTitle>Create athlete profile<\/DialogTitle>/)
  assert.match(athletesDataTableSource, /Add the athlete's personal details, profile photo, and preferred measurements\./)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-form/)
  assert.match(athletesDataTableSource, /Upload avatar/)
  assert.match(athletesDataTableSource, /Avatar uploaded/)
  assert.match(athletesDataTableSource, /PNG, JPG up to 2MB/)
  assert.match(athletesDataTableSource, /First name/)
  assert.match(athletesDataTableSource, /Last name/)
  assert.match(athletesDataTableSource, /Date of birth/)
  assert.match(athletesDataTableSource, /Gender/)
  assert.match(athletesDataTableSource, /Position/)
  assert.match(athletesDataTableSource, /Height/)
  assert.match(athletesDataTableSource, /Weight/)
  assert.match(athletesDataTableSource, /defaultValue="imperial"/)
  assert.match(athletesDataTableSource, /<TabsTrigger value="imperial">Imperial<\/TabsTrigger>/)
  assert.match(athletesDataTableSource, /<TabsTrigger value="metric">Metric<\/TabsTrigger>/)
  assert.match(athletesDataTableSource, /<SelectItem value="male">Male<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="female">Female<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="other">Other<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="forward">Forward<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="defense">Defense<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<SelectItem value="goalie">Goalie<\/SelectItem>/)
  assert.match(athletesDataTableSource, /<DialogFooter className="border-t border-\[#24334A\] px-6 py-5 sm:justify-end gap-3"/)
  assert.match(athletesDataTableSource, /variant="outline"[\s\S]*className="rounded-\[12px\] min-h-\[40px\] border-\[#24334A\] bg-\[#111D30\] text-\[#DCE6F8\] hover:bg-\[#15233A\] hover:text-\[#EEF4FF\]"[\s\S]*Cancel/)
  assert.match(athletesDataTableSource, /className="admin-shell-athletes-create-submit rounded-\[12px\] min-h-\[40px\] bg-\[#3BE0AF\] text-\[#0B1120\] hover:bg-\[#35c89d\]"[\s\S]*Create/)
  assert.match(athletesDataTableSource, /function RowActionsCell\(\{[\s\S]*isOpen = false,[\s\S]*onOpenChange = \(\) => \{\},[\s\S]*onEditAction = \(\) => \{\},[\s\S]*onDeleteAction = \(\) => \{\},[\s\S]*\}\)/)
  assert.match(athletesDataTableSource, /<DropdownMenu open=\{isOpen\} onOpenChange=\{onOpenChange\}>/)
  assert.match(athletesDataTableSource, /function RowActionsCell[\s\S]*onEditAction\(\)[\s\S]*onOpenChange\(false\)/)
  assert.match(athletesDataTableSource, /function RowActionsCell[\s\S]*onDeleteAction\(\)[\s\S]*onOpenChange\(false\)/)
  assert.match(athletesDataTableSource, /const \[openRowActionMenuId, setOpenRowActionMenuId\] = useState\(null\)/)
  assert.match(athletesDataTableSource, /const \[pendingRowAction, setPendingRowAction\] = useState\(null\)/)
  assert.match(athletesDataTableSource, /cell: \(\{ row \}\) => \([\s\S]*isOpen=\{openRowActionMenuId === row\.original\.id\}/)
  assert.match(athletesDataTableSource, /onOpenChange=\{\(isOpen\) => \{[\s\S]*setOpenRowActionMenuId\(isOpen \? row\.original\.id : null\)/)
  assert.match(athletesDataTableSource, /onEditAction=\{\(\) => setPendingRowAction\(\{ type: 'edit', athleteId: row\.original\.id \}\)\}/)
  assert.match(athletesDataTableSource, /onDeleteAction=\{\(\) => setPendingRowAction\(\{ type: 'delete', athleteId: row\.original\.id \}\)\}/)
  assert.match(athletesDataTableSource, /useEffect\(\(\) => \{[\s\S]*if \(openRowActionMenuId \|\| !pendingRowAction\) return[\s\S]*pendingRowAction\.type === 'edit'[\s\S]*setIsCreateEditAthleteDialogOpen\(true\)[\s\S]*pendingRowAction\.type === 'delete'[\s\S]*setIsDeleteDialogOpen\(true\)[\s\S]*setPendingRowAction\(null\)/)
  assert.doesNotMatch(athletesDataTableSource, /function RowActionsCell[\s\S]*event\.preventDefault\(\)[\s\S]*on(Edit|Delete)Action\(\)/)
  assert.doesNotMatch(athletesDataTableSource, /function RowActionsCell[\s\S]*window\.setTimeout\(\(\) => on(Edit|Delete)Action\(\), 0\)/)

  assert.match(athletesDataTableSource, /<Dialog open=\{isDeleteDialogOpen\} onOpenChange=\{setIsDeleteDialogOpen\}>/)
  assert.match(athletesDataTableSource, /<DialogTitle>Delete athlete<\/DialogTitle>/)
  assert.match(athletesDataTableSource, /<DialogDescription>This athlete will be removed from the workspace\.<\/DialogDescription>/)
  assert.doesNotMatch(athletesDataTableSource, /<Dialog open=\{isDeleteDialogOpen\} onOpenChange=\{setIsDeleteDialogOpen\}>[\s\S]*border-b border-\[#24334A\][\s\S]*<DialogTitle>Delete athlete<\/DialogTitle>/)
  assert.match(athletesDataTableSource, /className="rounded-\[12px\] min-h-\[40px\] bg-red-500\/90 text-white hover:bg-red-500"[\s\S]*Delete/)

  assert.doesNotMatch(athletesDataTableSource, /function RowActionsCell\(\) \{[\s\S]*Open program/)
  assert.doesNotMatch(athletesDataTableSource, /function RowActionsCell\(\) \{[\s\S]*Review workouts/)
  assert.match(athletesDataTableSource, /First name/)
  assert.match(athletesDataTableSource, /Last name/)
  assert.doesNotMatch(athletesDataTableSource, /invite-athlete-name/)
  assert.doesNotMatch(athletesDataTableSource, /className="admin-shell-athletes-example-actions flex items-center gap-3"/)
  assert.doesNotMatch(athletesDataTableSource, /Filter names\.\.\./)
  assert.doesNotMatch(athletesDataTableSource, /admin-shell-athletes-example-filter/)
  assert.match(athletesDataTableSource, /Previous/)
  assert.match(athletesDataTableSource, /Next/)
  assert.doesNotMatch(athletesDataTableSource, /Amount/)
  assert.doesNotMatch(athletesDataTableSource, /Filter emails\.\.\./)
  assert.doesNotMatch(athletesDataTableSource, /getColumn\('email'\)\?\.setFilterValue/)
  assert.doesNotMatch(athletesDataTableSource, /ken99@example\.com/)
  assert.doesNotMatch(athletesDataTableSource, /Rows per page:/)

  assert.match(invitesListViewSource, /'use client'/)
  assert.match(invitesListViewSource, /searchQuery/)
  assert.match(invitesListViewSource, /<InvitesDataTable searchQuery=\{searchQuery\} \/>/)
  assert.doesNotMatch(invitesListViewSource, /Search for an athlete by name\.\.\./)
  assert.doesNotMatch(invitesListViewSource, /AdminButton/)
  assert.match(invitesListViewSource, /admin-shell-invites-view/)

  assert.match(invitesDataTableSource, /'use client'/)
  assert.match(invitesDataTableSource, /from '@tanstack\/react-table'/)
  assert.match(invitesDataTableSource, /from '@\/components\/ui\/table'/)
  assert.match(invitesDataTableSource, /from '@\/components\/ui\/checkbox'/)
  assert.match(invitesDataTableSource, /from '@\/components\/ui\/dropdown-menu'/)
  assert.match(invitesDataTableSource, /from '@\/components\/ui\/avatar'/)
  assert.match(invitesDataTableSource, /from '@\/components\/ui\/badge'/)
  assert.match(invitesDataTableSource, /from '@\/components\/ui\/button'/)
  assert.match(invitesDataTableSource, /from '@\/components\/ui\/dialog'/)
  assert.match(invitesDataTableSource, /export default function InvitesDataTable\(\{ searchQuery = '' \}\)/)
  assert.match(invitesDataTableSource, /const \[isInviteDialogOpen, setIsInviteDialogOpen\] = useState\(false\)/)
  assert.match(invitesDataTableSource, /const \[isCancelInviteDialogOpen, setIsCancelInviteDialogOpen\] = useState\(false\)/)
  assert.match(invitesDataTableSource, /Invite an athlete/)
  assert.match(invitesDataTableSource, /onClick=\{\(\) => setIsInviteDialogOpen\(true\)\}/)
  assert.match(invitesDataTableSource, /function RowActionsCell\(\{ onResendInvite = \(\) => \{\}, onCancelInvite = \(\) => \{\} \}\)/)
  assert.match(invitesDataTableSource, /<DropdownMenuItem onSelect=\{onResendInvite\}>Resend invite<\/DropdownMenuItem>/)
  assert.doesNotMatch(invitesDataTableSource, /Copy invite link/)
  assert.match(invitesDataTableSource, /<DropdownMenuItem onSelect=\{onCancelInvite\}>Cancel invite<\/DropdownMenuItem>/)
  assert.match(invitesDataTableSource, /cell: \(\) => \([\s\S]*<RowActionsCell[\s\S]*onResendInvite=\{\(\) => setIsInviteDialogOpen\(true\)\}[\s\S]*onCancelInvite=\{\(\) => setIsCancelInviteDialogOpen\(true\)\}[\s\S]*\/>/)
  assert.match(invitesDataTableSource, /Name/)
  assert.match(invitesDataTableSource, /Role/)
  assert.match(invitesDataTableSource, /Sent/)
  assert.match(invitesDataTableSource, /Status/)
  assert.match(invitesDataTableSource, /fetch\('\/api\/admin\/invites'/)
  assert.match(invitesDataTableSource, /setInvites\(/)
  assert.match(invitesDataTableSource, /setLoading\(/)
  assert.match(invitesDataTableSource, /setError\(/)
  assert.doesNotMatch(invitesDataTableSource, /const invites = \[/)
  assert.doesNotMatch(invitesDataTableSource, /thomas@gmail\.com/)
  assert.doesNotMatch(invitesDataTableSource, /mia\.chen@gmail\.com/)
  assert.doesNotMatch(invitesDataTableSource, /Jordan Alvarez/)
  assert.match(invitesDataTableSource, /Pending/)
  assert.match(invitesDataTableSource, /Accepted/)
  assert.match(invitesDataTableSource, /admin-shell-athletes-example-controls flex items-center justify-between gap-3/)
  assert.match(invitesDataTableSource, /admin-shell-athletes-invite-button bg-\[#3BE0AF\] text-\[#0B1120\] hover:bg-\[#35c89d\] rounded-\[12px\] min-h-\[40px\]/)
  assert.match(invitesDataTableSource, /table\.getColumn\('name'\)\?\.setFilterValue\(searchQuery\)/)
  assert.match(invitesDataTableSource, /<Dialog open=\{isInviteDialogOpen\} onOpenChange=\{setIsInviteDialogOpen\}>/)
  assert.match(invitesDataTableSource, /<DialogTitle>Invite an athlete<\/DialogTitle>/)
  assert.match(invitesDataTableSource, /Email address/)
  assert.match(invitesDataTableSource, /Send invite/)
  assert.match(invitesDataTableSource, /<Dialog open=\{isCancelInviteDialogOpen\} onOpenChange=\{setIsCancelInviteDialogOpen\}>/)
  assert.match(invitesDataTableSource, /<DialogTitle>Cancel invite<\/DialogTitle>/)
  assert.match(invitesDataTableSource, /This invite will be canceled and removed from the invites list\./)
  assert.match(invitesDataTableSource, /className="rounded-\[12px\] min-h-\[40px\] bg-red-500\/90 text-white hover:bg-red-500"[\s\S]*Cancel invite/)
  assert.doesNotMatch(invitesDataTableSource, /<Dialog open=\{isCancelInviteDialogOpen\} onOpenChange=\{setIsCancelInviteDialogOpen\}>[\s\S]*border-b border-\[#24334A\][\s\S]*<DialogTitle>Cancel invite<\/DialogTitle>/)
  assert.doesNotMatch(invitesDataTableSource, /Search for an athlete by name\.\.\./)
  assert.doesNotMatch(invitesDataTableSource, /Rows per page:/)

  assert.match(adminInvitesRouteSource, /createAdminInviteRepository/)
  assert.match(adminInvitesRouteSource, /repository\.listInvites\(\)/)
  assert.match(adminInvitesRouteSource, /return json\(\{ invites \}\)/)

  assert.match(adminInviteRepositorySource, /athlete_invitations/)
  assert.match(adminInviteRepositorySource, /athlete_profiles/)
  assert.match(adminInviteRepositorySource, /listInvites\(\)/)
  assert.match(adminInviteRepositorySource, /invitee_email/)
  assert.match(adminInviteRepositorySource, /expires_at/)
  assert.match(adminInviteRepositorySource, /used_at/)
  assert.match(adminInviteRepositorySource, /revoked_at/)
  assert.match(adminInviteRepositorySource, /Expired/)
  assert.match(adminInviteRepositorySource, /Canceled/)

  assert.match(groupsListViewSource, /'use client'/)
  assert.match(groupsListViewSource, /searchQuery/)
  assert.match(groupsListViewSource, /<GroupsDataTable searchQuery=\{searchQuery\} \/>/)
  assert.doesNotMatch(groupsListViewSource, /Search for a group by name\.\.\./)
  assert.doesNotMatch(groupsListViewSource, /AdminButton/)
  assert.match(groupsListViewSource, /admin-shell-groups-view/)

  assert.match(groupsDataTableSource, /'use client'/)
  assert.match(groupsDataTableSource, /from '@tanstack\/react-table'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/table'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/checkbox'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/dropdown-menu'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/badge'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/button'/)
  assert.match(groupsDataTableSource, /export default function GroupsDataTable\(\{ searchQuery = '' \}\)/)
  assert.match(groupsDataTableSource, /const \[groups, setGroups\] = useState\(\[\]\)/)
  assert.match(groupsDataTableSource, /const \[loading, setLoading\] = useState\(true\)/)
  assert.match(groupsDataTableSource, /const \[error, setError\] = useState\(''\)/)
  assert.match(groupsDataTableSource, /fetch\('\/api\/admin\/groups'/)
  assert.match(groupsDataTableSource, /setGroups\(/)
  assert.match(groupsDataTableSource, /setLoading\(/)
  assert.match(groupsDataTableSource, /setError\(/)
  assert.match(groupsDataTableSource, /Create group/)
  assert.match(groupsDataTableSource, /Group/)
  assert.match(groupsDataTableSource, /Athletes/)
  assert.match(groupsDataTableSource, /Access/)
  assert.match(groupsDataTableSource, /Updated/)
  assert.match(groupsDataTableSource, /Status/)
  assert.match(groupsDataTableSource, /admin-shell-athletes-example-controls flex items-center justify-between gap-3/)
  assert.match(groupsDataTableSource, /admin-shell-athletes-invite-button bg-\[#3BE0AF\] text-\[#0B1120\] hover:bg-\[#35c89d\] rounded-\[12px\] min-h-\[40px\]/)
  assert.match(groupsDataTableSource, /table\.getColumn\('name'\)\?\.setFilterValue\(searchQuery\)/)
  assert.match(groupsDataTableSource, /Previous/)
  assert.match(groupsDataTableSource, /Next/)
  assert.doesNotMatch(groupsDataTableSource, /GROUPS_BACKEND_NOT_CONFIGURED/)
  assert.doesNotMatch(groupsDataTableSource, /Groups backend not configured yet\./)
  assert.doesNotMatch(groupsDataTableSource, /Apply the athlete_groups and athlete_group_memberships schema before enabling this surface\./)
  assert.doesNotMatch(groupsDataTableSource, /disabled=\{isBackendUnconfigured\}/)
  assert.doesNotMatch(groupsDataTableSource, /const groups = \[/)
  assert.doesNotMatch(groupsDataTableSource, /Group 1/)
  assert.doesNotMatch(groupsDataTableSource, /Groupe 2/)
  assert.doesNotMatch(groupsDataTableSource, /Mason Lee/)
  assert.doesNotMatch(groupsDataTableSource, /Noah Smith/)
  assert.doesNotMatch(groupsDataTableSource, /Search for a group by name\.\.\./)
  assert.doesNotMatch(groupsDataTableSource, /Rows per page:/)

  assert.match(adminGroupsRouteSource, /createAdminGroupRepository/)
  assert.match(adminGroupsRouteSource, /repository\.listGroups\(\)/)
  assert.match(adminGroupsRouteSource, /repository\.listAthleteOptions\(\)/)
  assert.match(adminGroupsRouteSource, /repository\.listProgramOptions\(\)/)
  assert.match(adminGroupsRouteSource, /return json\(\{ groups, athleteOptions, programOptions \}\)/)
  assert.match(adminGroupsRouteSource, /export async function POST\(request\)/)
  assert.match(adminGroupsRouteSource, /export async function PATCH\(request\)/)
  assert.match(adminGroupsRouteSource, /assign-program/)
  assert.match(adminGroupsRouteSource, /unarchive/)
  assert.match(adminGroupsRouteSource, /delete/)

  assert.match(adminGroupRepositorySource, /athlete_groups/)

  assert.match(adminGroupRepositorySource, /requestTable\('athlete_groups'/)
  assert.match(adminGroupRepositorySource, /requestTable\('athlete_group_memberships'/)
  assert.match(adminGroupRepositorySource, /requestTable\('athlete_profiles'/)

  assert.match(rankingsListViewSource, /'use client'/)
  assert.match(rankingsListViewSource, /searchQuery/)
  assert.match(rankingsListViewSource, /<RankingsDataTable searchQuery=\{searchQuery\} \/>/)
  assert.doesNotMatch(rankingsListViewSource, /Search for an athlete by name\.\.\./)
  assert.match(rankingsListViewSource, /admin-shell-rankings-view/)

  assert.match(rankingsDataTableSource, /'use client'/)
  assert.match(rankingsDataTableSource, /from '@tanstack\/react-table'/)
  assert.match(rankingsDataTableSource, /from '@\/components\/ui\/table'/)
  assert.match(rankingsDataTableSource, /from '@\/components\/ui\/checkbox'/)
  assert.match(rankingsDataTableSource, /from '@\/components\/ui\/dropdown-menu'/)
  assert.match(rankingsDataTableSource, /from '@\/components\/ui\/avatar'/)
  assert.match(rankingsDataTableSource, /from '@\/components\/ui\/progress'/)
  assert.match(rankingsDataTableSource, /from '@\/components\/ui\/badge'/)
  assert.match(rankingsDataTableSource, /export default function RankingsDataTable\(\{ searchQuery = '' \}\)/)
  assert.match(rankingsDataTableSource, /Leaderboard window/)
  assert.match(rankingsDataTableSource, /Rank/)
  assert.match(rankingsDataTableSource, /Name/)
  assert.match(rankingsDataTableSource, /Program/)
  assert.match(rankingsDataTableSource, /Workouts/)
  assert.match(rankingsDataTableSource, /Last active/)
  assert.match(rankingsDataTableSource, /Status/)
  assert.match(rankingsDataTableSource, /gold_badge\.svg/)
  assert.match(rankingsDataTableSource, /silver_badge\.svg/)
  assert.match(rankingsDataTableSource, /bronze_badget\.svg/)
  assert.match(rankingsDataTableSource, /table\.getColumn\('name'\)\?\.setFilterValue\(searchQuery\)/)
  assert.match(rankingsDataTableSource, /admin-shell-athletes-example-controls flex items-center justify-between gap-3/)
  assert.doesNotMatch(rankingsDataTableSource, /Search for an athlete by name\.\.\./)
  assert.doesNotMatch(rankingsDataTableSource, /Rows per page:/)

  assert.match(adminShellSource, /<ProgramsLibraryView searchQuery=\{topbarSearchQuery\} \/>/)

  assert.match(programsLibraryViewSource, /'use client'/)
  assert.match(programsLibraryViewSource, /Programs Library/)
  assert.match(programsLibraryViewSource, /searchQuery/)
  assert.match(programsLibraryViewSource, /<ProgramsDataTable searchQuery=\{searchQuery\} \/>/)
  assert.doesNotMatch(programsLibraryViewSource, /Search for a program by name\.\.\./)
  assert.doesNotMatch(programsLibraryViewSource, /Rows per page:/)
  assert.doesNotMatch(programsLibraryViewSource, /Program 1/)
  assert.doesNotMatch(programsLibraryViewSource, /from 'lucide-react'/)

  assert.match(programsDataTableSource, /'use client'/)
  assert.match(programsDataTableSource, /from '@tanstack\/react-table'/)
  assert.match(programsDataTableSource, /useReactTable/)
  assert.match(programsDataTableSource, /getCoreRowModel/)
  assert.match(programsDataTableSource, /getFilteredRowModel/)
  assert.match(programsDataTableSource, /getPaginationRowModel/)
  assert.match(programsDataTableSource, /from '@\/components\/ui\/table'/)
  assert.match(programsDataTableSource, /from '@\/components\/ui\/checkbox'/)
  assert.match(programsDataTableSource, /from '@\/components\/ui\/dropdown-menu'/)
  assert.match(programsDataTableSource, /from '@\/components\/ui\/button'/)
  assert.match(programsDataTableSource, /from '@\/components\/ui\/dialog'/)
  assert.match(programsDataTableSource, /from '@\/components\/ui\/tabs'/)
  assert.match(programsDataTableSource, /from '@\/components\/ui\/textarea'/)
  assert.match(programsDataTableSource, /from '@\/components\/ui\/item'/)
  assert.match(programsDataTableSource, /export default function ProgramsDataTable\(\{ searchQuery = '' \}\)/)
  assert.match(programsDataTableSource, /const \[isCreateProgramDialogOpen, setIsCreateProgramDialogOpen\] = useState\(false\)/)
  assert.match(programsDataTableSource, /const \[programDialogMode, setProgramDialogMode\] = useState\('create'\)/)
  assert.match(programsDataTableSource, /const \[selectedProgramId, setSelectedProgramId\] = useState\(null\)/)
  assert.match(programsDataTableSource, /const \[programFormValues, setProgramFormValues\] = useState\(\(\) => createProgramFormValues\(\)\)/)
  assert.match(programsDataTableSource, /const \[openRowActionMenuId, setOpenRowActionMenuId\] = useState\(null\)/)
  assert.match(programsDataTableSource, /const \[pendingRowAction, setPendingRowAction\] = useState\(null\)/)
  assert.match(programsDataTableSource, /function openCreateProgramDialog\(\) \{[\s\S]*setProgramDialogMode\('create'\)[\s\S]*setSelectedProgramId\(null\)[\s\S]*setProgramFormValues\(createProgramFormValues\(\)\)[\s\S]*setIsCreateProgramDialogOpen\(true\)/)
  assert.match(programsDataTableSource, /function openEditProgramDialog\(programId\) \{[\s\S]*setProgramDialogMode\('edit'\)[\s\S]*setSelectedProgramId\(programId\)[\s\S]*setProgramFormValues\(createProgramFormValues\(selectedProgram\)\)[\s\S]*setIsCreateProgramDialogOpen\(true\)/)
  assert.match(programsDataTableSource, /onClick=\{openCreateProgramDialog\}/)
  assert.match(programsDataTableSource, /<Dialog[\s\S]*open=\{isCreateProgramDialogOpen\}[\s\S]*onOpenChange=\{\(isOpen\) => \{[\s\S]*setIsCreateProgramDialogOpen\(isOpen\)/)
  assert.match(programsDataTableSource, /programDialogMode === 'edit' \? 'Edit program' : 'Create a program'/)
  assert.match(programsDataTableSource, /Update \$\{programFormValues\.name \|\| selectedProgramId \|\| 'this program'\} with the schedule details below\./)
  assert.match(programsDataTableSource, /Set up a coach-managed program with the core schedule details below\./)
  assert.match(programsDataTableSource, /function RowActionsCell\(\{[\s\S]*isOpen = false,[\s\S]*onOpenChange = \(\) => \{\},[\s\S]*onEditAction = \(\) => \{\},[\s\S]*\}\)/)
  assert.match(programsDataTableSource, /<DropdownMenu open=\{isOpen\} onOpenChange=\{onOpenChange\}>/)
  assert.match(programsDataTableSource, /<DropdownMenuItem[\s\S]*onEditAction\(\)[\s\S]*onOpenChange\(false\)[\s\S]*>\s*Edit\s*<\/DropdownMenuItem>/)
  assert.match(programsDataTableSource, /Name/)
  assert.match(programsDataTableSource, /Weeks/)
  assert.match(programsDataTableSource, /Start date/)
  assert.match(programsDataTableSource, /End date/)
  assert.match(programsDataTableSource, /Description/)
  assert.match(programsDataTableSource, /Tabs/)
  assert.match(programsDataTableSource, /TabsList/)
  assert.match(programsDataTableSource, /TabsTrigger value="details">Details<\/TabsTrigger>/)
  assert.match(programsDataTableSource, /TabsTrigger value="athletes">Athletes<\/TabsTrigger>/)
  assert.match(programsDataTableSource, /TabsContent value="details"/)
  assert.match(programsDataTableSource, /TabsContent value="athletes"/)
  assert.match(programsDataTableSource, /<Textarea/)
  assert.match(programsDataTableSource, /type="date"/)
  assert.match(programsDataTableSource, /TabsContent value="details"[\s\S]*className="grid gap-4 md:grid-cols-2"[\s\S]*Name[\s\S]*Weeks/)
  assert.match(programsDataTableSource, /TabsContent value="details"[\s\S]*className="grid gap-4 md:grid-cols-2"[\s\S]*Start date[\s\S]*End date/)
  assert.match(programsDataTableSource, /TabsContent value="details"[\s\S]*Description/)
  assert.match(programsDataTableSource, /TabsContent value="athletes"[\s\S]*ItemGroup/)
  assert.match(programsDataTableSource, /TabsContent value="athletes"[\s\S]*ItemTitle/)
  assert.match(programsDataTableSource, /TabsContent value="athletes"[\s\S]*ItemDescription/)
  assert.match(programsDataTableSource, /TabsContent value="athletes"[\s\S]*ItemSeparator/)
  assert.match(programsDataTableSource, /TabsContent value="athletes"[\s\S]*Add athlete to program/)
  assert.match(programsDataTableSource, /Cancel/)
  assert.match(programsDataTableSource, /Create/)
  assert.match(programsDataTableSource, /Program/)
  assert.match(programsDataTableSource, /Duration/)
  assert.match(programsDataTableSource, /Workouts/)
  assert.match(programsDataTableSource, /Exercises/)
  assert.match(programsDataTableSource, /Created date/)
  assert.match(programsDataTableSource, /Status/)
  assert.match(programsDataTableSource, /from 'next\/link'/)
  assert.match(programsDataTableSource, /href=\{`\/admin\/programs\/\$\{programId\}`\}/)
  assert.match(programsDataTableSource, /table\.getColumn\('name'\)\?\.setFilterValue\(searchQuery\)/)
  assert.match(programsDataTableSource, /useEffect\(/)
  assert.match(programsDataTableSource, /fetch\('\/api\/admin\/programs'/)
  assert.match(programsDataTableSource, /setPrograms\(/)
  assert.match(programsDataTableSource, /setLoading\(/)
  assert.match(programsDataTableSource, /setError\(/)
  assert.doesNotMatch(programsDataTableSource, /const programs = \[/)
  assert.doesNotMatch(programsDataTableSource, /Program 1/)
  assert.doesNotMatch(programsDataTableSource, /7 athletes/)
  assert.doesNotMatch(programsDataTableSource, /12 weeks/)
  assert.doesNotMatch(programsDataTableSource, /118/)
  assert.doesNotMatch(programsDataTableSource, /5\/17\/2026/)
  assert.match(programsDataTableSource, /cell: \(\{ row \}\) => \([\s\S]*isOpen=\{openRowActionMenuId === row\.original\.id\}[\s\S]*onOpenChange=\{\(isOpen\) => \{[\s\S]*setOpenRowActionMenuId\(isOpen \? row\.original\.id : null\)[\s\S]*\}\}[\s\S]*onEditAction=\{\(\) => setPendingRowAction\(\{ type: 'edit', programId: row\.original\.id \}\)\}[\s\S]*\)/)

  assert.match(adminProgramsRouteSource, /createAdminProgramRepository/)
  assert.match(adminProgramsRouteSource, /repository\.listPrograms\(\)/)
  assert.match(adminProgramsRouteSource, /return json\(\{ programs \}\)/)

  assert.match(adminProgramRepositorySource, /requestTable\(\s*'programs'/)
  assert.match(adminProgramRepositorySource, /program_weeks/)
  assert.match(adminProgramRepositorySource, /program_workouts/)
  assert.match(adminProgramRepositorySource, /program_workout_exercises/)
  assert.match(adminProgramRepositorySource, /athlete_profiles\(first_name,last_name\)/)
  assert.match(adminProgramRepositorySource, /listPrograms\(\)/)
  assert.match(programsDataTableSource, /useEffect\(\(\) => \{[\s\S]*if \(openRowActionMenuId \|\| !pendingRowAction\) return[\s\S]*if \(pendingRowAction\.type === 'edit'\) \{[\s\S]*openEditProgramDialog\(pendingRowAction\.programId\)[\s\S]*\}[\s\S]*setPendingRowAction\(null\)[\s\S]*\}, \[openRowActionMenuId, pendingRowAction\]\)/)
  assert.match(programsDataTableSource, /admin-shell-athletes-example-controls flex items-center justify-between gap-3/)
  assert.match(programsDataTableSource, /admin-shell-athletes-invite-button bg-\[#3BE0AF\] text-\[#0B1120\] hover:bg-\[#35c89d\] rounded-\[12px\] min-h-\[40px\]/)
  assert.match(programsDataTableSource, /<DialogFooter className="border-t border-\[#24334A\] px-6 py-5 sm:justify-end gap-3">/)
  assert.doesNotMatch(programsDataTableSource, /Search for a program by name\.\.\./)
  assert.doesNotMatch(programsDataTableSource, /Rows per page:/)

  assert.match(adminShellSource, /<ExercisesLibraryView searchQuery=\{topbarSearchQuery\} \/>/)

  assert.match(exercisesLibraryViewSource, /'use client'/)
  assert.match(exercisesLibraryViewSource, /Exercise library/)
  assert.match(exercisesLibraryViewSource, /searchQuery/)
  assert.match(exercisesLibraryViewSource, /<ExercisesDataTable searchQuery=\{searchQuery\} \/>/)

  assert.match(exercisesDataTableSource, /'use client'/)
  assert.match(exercisesDataTableSource, /from '@tanstack\/react-table'/)
  assert.match(exercisesDataTableSource, /from '@\/components\/ui\/table'/)
  assert.match(exercisesDataTableSource, /from '@\/components\/ui\/dropdown-menu'/)
  assert.match(exercisesDataTableSource, /import Checkbox from '@\/components\/ui\/checkbox'/)
  assert.match(exercisesDataTableSource, /export default function ExercisesDataTable\(\{ searchQuery = '' \}\)/)
  assert.match(exercisesDataTableSource, /rowSelection/)
  assert.match(exercisesDataTableSource, /columnFilters/)
  assert.match(exercisesDataTableSource, /columnVisibility/)
  assert.match(exercisesDataTableSource, /pagination/)
  assert.match(exercisesDataTableSource, /getFilteredRowModel\(/)
  assert.match(exercisesDataTableSource, /getPaginationRowModel\(/)
  assert.match(exercisesDataTableSource, /table\.getColumn\('name'\)\?\.setFilterValue\(searchQuery\)/)
  assert.match(exercisesDataTableSource, /Exercise/)
  assert.match(exercisesDataTableSource, /Muscle/)
  assert.match(exercisesDataTableSource, /Equipment/)
  assert.match(exercisesDataTableSource, /Sets/)
  assert.match(exercisesDataTableSource, /Reps/)
  assert.match(exercisesDataTableSource, /Duration/)
  assert.match(exercisesDataTableSource, /Distance/)
  assert.match(exercisesDataTableSource, /Rest/)
  assert.match(exercisesDataTableSource, /Select all/)
  assert.match(exercisesDataTableSource, /Select row/)
  assert.match(exercisesDataTableSource, /Columns/)
  assert.match(exercisesDataTableSource, /Create exercise/)
  assert.match(exercisesDataTableSource, /Previous/)
  assert.match(exercisesDataTableSource, /Next/)
  assert.match(exercisesDataTableSource, /table\.previousPage\(\)/)
  assert.match(exercisesDataTableSource, /table\.nextPage\(\)/)
  assert.match(exercisesDataTableSource, /admin-shell-athletes-table-shell/)
  assert.match(exercisesDataTableSource, /admin-shell-athletes-actions-cell/)
  assert.match(exercisesDataTableSource, /MoreHorizontal/)
  assert.match(exercisesDataTableSource, /useEffect\(/)
  assert.match(exercisesDataTableSource, /fetch\('\/api\/admin\/exercises'/)
  assert.match(exercisesDataTableSource, /setExercises\(/)
  assert.match(exercisesDataTableSource, /setLoading\(/)
  assert.match(exercisesDataTableSource, /setError\(/)
  assert.doesNotMatch(exercisesDataTableSource, /const exercises = \[/)
  assert.doesNotMatch(exercisesDataTableSource, /Skater hops/)
  assert.doesNotMatch(exercisesDataTableSource, /Sled sprint/)
  assert.doesNotMatch(exercisesDataTableSource, /Copenhagen plank/)
  assert.doesNotMatch(exercisesDataTableSource, /import Avatar from '@\/components\/ui\/avatar'/)
  assert.doesNotMatch(exercisesDataTableSource, /admin-shell-athletes-avatar/)

  assert.match(adminExercisesRouteSource, /createAdminExerciseRepository/)
  assert.match(adminExercisesRouteSource, /repository\.listExercises\(\)/)
  assert.match(adminExercisesRouteSource, /return json\(\{ exercises \}\)/)

  assert.match(adminExerciseRepositorySource, /rest\/v1\/exercises/)
  assert.match(adminExerciseRepositorySource, /exercise_muscle_maps\(role,sort_order,muscles\(name\)\)/)
  assert.match(adminExerciseRepositorySource, /default_equipment/)
  assert.match(adminExerciseRepositorySource, /listExercises\(\)/)

  assert.match(programPlannerPageSource, /import AdminShell from '\.\.\/\.\.\/\.\.\/\.\.\/components\/admin\/admin-shell'/)
  assert.match(programPlannerPageSource, /import ProgramPlannerView from '\.\.\/\.\.\/\.\.\/\.\.\/components\/admin\/program-planner-view'/)
  assert.match(programPlannerPageSource, /import \{ getProgramPlannerById \} from '\.\.\/\.\.\/\.\.\/\.\.\/components\/admin\/program-planner-utils'/)
  assert.match(programPlannerPageSource, /notFound/)
  assert.match(programPlannerPageSource, /const program = getProgramPlannerById\(programId\)/)
  assert.match(programPlannerPageSource, /if \(!program\) \{[\s\S]*notFound\(\)[\s\S]*\}/)
  assert.match(programPlannerPageSource, /return <AdminShell currentPath="\/admin\/programs" contentOverride=\{<ProgramPlannerView program=\{program\} \/>\} \/>/)

  assert.match(adminShellSource, /export default function AdminShell\(\{ currentPath = '', contentOverride = null \}\)/)
  assert.match(adminShellSource, /const shouldRenderContentOverride = Boolean\(contentOverride\)/)
  assert.match(adminShellSource, /shouldRenderContentOverride \? \(/)
  assert.match(adminShellSource, /\{contentOverride\}/)

  assert.match(programPlannerViewSource, /from 'next\/link'/)
  assert.match(programPlannerViewSource, /from '@\/components\/ui\/kanban'/)
  assert.match(programPlannerViewSource, /from '@\/components\/ui\/sheet'/)
  assert.match(programPlannerViewSource, /from '@\/components\/ui\/tooltip'/)
  assert.match(programPlannerViewSource, /useRef/)
  assert.match(programPlannerViewSource, /from '\.\/program-planner-utils'/)
  assert.match(programPlannerViewSource, /function getNextWeekId\(weeks = \[\]\)/)
  assert.match(programPlannerViewSource, /const nextWeekId = getNextWeekId\(currentPlanner\.weeks\)/)
  assert.match(programPlannerViewSource, /id: nextWeekId/)
  assert.match(programPlannerViewSource, /function ProgramWeekRow/)
  assert.match(programPlannerViewSource, /function ProgramWeekRow[\s\S]*>{week\.label}</)
  assert.match(programPlannerViewSource, /function ProgramWeekRow[\s\S]*Scroll week left/)
  assert.match(programPlannerViewSource, /function ProgramWeekRow[\s\S]*Delete week/)
  assert.match(programPlannerViewSource, /function ProgramWeekRow[\s\S]*Scroll week right/)
  assert.doesNotMatch(programPlannerViewSource, /function ProgramWeekRow[\s\S]*Move whole day content/)
  assert.doesNotMatch(programPlannerViewSource, /function ProgramWeekRow[\s\S]*Swap day content/)
  assert.doesNotMatch(programPlannerViewSource, /function ProgramWeekRow[\s\S]*Day 1 to Day 7 stay locked while the contents can shift\./)
  assert.match(programPlannerViewSource, /scrollBy\(\{ left: direction \* sliderStep, behavior: 'smooth' \}\)/)
  assert.match(programPlannerViewSource, /overflow-x-auto scroll-smooth/)
  assert.match(programPlannerViewSource, /program-planner-scroll-shell/)
  assert.match(programPlannerViewSource, /overflow-hidden/)
  assert.match(programPlannerViewSource, /min-w-0/)
  assert.match(programPlannerViewSource, /program-planner-scroll-track/)
  assert.doesNotMatch(programPlannerViewSource, /program-planner-scroll-edge-left/)
  assert.doesNotMatch(programPlannerViewSource, /program-planner-scroll-edge-right/)
  assert.match(programPlannerViewSource, /program-planner-scroll-button/)
  assert.match(programPlannerViewSource, /data-scroll-direction="left"/)
  assert.match(programPlannerViewSource, /data-scroll-direction="right"/)
  assert.match(programPlannerViewSource, /Scroll week left/)
  assert.match(programPlannerViewSource, /Scroll week right/)
  assert.match(programPlannerViewSource, /min-w-\[1960px\]/)
  assert.match(programPlannerViewSource, /Workout details/)
  assert.match(programPlannerViewSource, /Program planner/)
  assert.match(programPlannerViewSource, /Coach-managed progression plan/)
  assert.match(programPlannerViewSource, /Schedule summary/)
  assert.match(programPlannerViewSource, /program-planner-header-kicker/)
  assert.match(programPlannerViewSource, /program-planner-header-summary-card/)
  assert.doesNotMatch(programPlannerViewSource, /Planner detail/)
  assert.doesNotMatch(programPlannerViewSource, /Move whole day content horizontally when the training week needs a reshuffle without changing the Day 1 to Day 7 structure\./)
  assert.doesNotMatch(programPlannerViewSource, /Move whole day content horizontally while workout cards stay sortable inside each day lane\./)
  assert.match(programPlannerViewSource, /week-hover-trash-button/)
  assert.match(programPlannerViewSource, /border-dashed/)

  assert.match(programPlannerDataSource, /export const programPlannerSeed = \[/)
  assert.match(programPlannerDataSource, /id: 'program-1'/)
  assert.match(programPlannerDataSource, /weekCount:/)
  assert.match(programPlannerDataSource, /day-1/)
  assert.match(programPlannerDataSource, /sections:/)

  assert.match(programPlannerUtilsSource, /export function getProgramPlannerById/)
  assert.match(programPlannerUtilsSource, /return matchedProgram \? cloneProgram\(matchedProgram\) : null/)
  assert.doesNotMatch(programPlannerUtilsSource, /buildFallbackPlanner/)
  assert.match(programPlannerUtilsSource, /export function createFixedDaySlots/)
  assert.match(programPlannerUtilsSource, /export function swapDayLaneContent/)
  assert.match(programPlannerUtilsSource, /export function reorderWorkoutCards/)

  assert.match(kanbanUiSource, /@dnd-kit\/core/)
  assert.match(kanbanUiSource, /@dnd-kit\/sortable/)
  assert.match(kanbanUiSource, /export function KanbanBoard/)
  assert.match(kanbanUiSource, /export function KanbanColumn/)
  assert.match(kanbanUiSource, /export function KanbanItem/)

  assert.match(cssSource, /\.program-planner-scroll-shell \{/)
  assert.doesNotMatch(cssSource, /\.program-planner-scroll-shell::before/)
  assert.match(cssSource, /\.program-planner-scroll-shell::after/)
  assert.match(cssSource, /rgba\(11, 17, 32, 0\.985\)/)
  assert.match(cssSource, /\.program-planner-scroll-track \{/)
  assert.match(cssSource, /scrollbar-width:\s*none/)
  assert.match(cssSource, /\.program-planner-scroll-track::-webkit-scrollbar \{/)
  assert.match(cssSource, /display:\s*none/)
  assert.match(cssSource, /\.program-planner-scroll-button\[data-scroll-direction='left'\]/)
  assert.match(cssSource, /\.program-planner-scroll-button\[data-scroll-direction='right'\]/)
  assert.doesNotMatch(cssSource, /\.program-planner-scroll-edge-left/)
  assert.doesNotMatch(cssSource, /\.program-planner-scroll-edge-right/)

  assert.match(adminButtonSource, /export default function AdminButton/)
  assert.match(adminButtonSource, /children/)
  assert.match(adminButtonSource, /variant = 'primary'/)
  assert.match(adminButtonSource, /primary: ''/)
  assert.match(adminButtonSource, /secondary: 'admin-button-secondary'/)
  assert.match(adminButtonSource, /ghost: 'admin-button-ghost'/)
  assert.match(adminButtonSource, /danger: 'admin-button-danger'/)
  assert.match(adminButtonSource, /compact: 'admin-button-compact'/)
  assert.match(adminButtonSource, /default: 'admin-button-default'/)
  assert.match(adminButtonSource, /prominent: 'admin-button-prominent'/)
  assert.match(adminButtonSource, /className = ''/)
  assert.match(adminButtonSource, /\['admin-button', variantClass, sizeClass, className\]/)

  assert.match(adminNavigationSource, /href: '\/admin\/dashboard'/)
  assert.match(adminNavigationSource, /title: 'Overview'/)
  assert.match(adminNavigationSource, /description: 'Here is an overview of your platform\.'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/dashboard\/today'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/dashboard\/alerts'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/dashboard\/recent-activity'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Recent activity'/)
  assert.match(adminNavigationSource, /href: '\/admin\/athletes'/)
  assert.match(adminNavigationSource, /href: '\/admin\/programs'/)
  assert.match(adminNavigationSource, /href: '\/admin\/workouts'/)
  assert.match(adminNavigationSource, /href: '\/admin\/exercises'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/analytics'/)
  assert.match(adminNavigationSource, /href: '\/admin\/settings'/)
  assert.match(adminNavigationSource, /href: '\/admin\/athletes\/groups'/)
  assert.match(adminNavigationSource, /href: '\/admin\/athletes\/rankings'/)
  assert.match(adminNavigationSource, /label: 'Rankings'/)
  assert.match(adminNavigationSource, /title: 'Athlete rankings'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/athletes\/progress'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Progress'/)
  assert.doesNotMatch(adminNavigationSource, /title: 'Athlete progress'/)
  assert.match(adminNavigationSource, /title: 'Program library'/)
  assert.match(adminNavigationSource, /label: 'Library'/)
  assert.match(adminNavigationSource, /description: 'Browse the programs library table reference view\.'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/programs\/templates'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/workouts\/sessions'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/analytics\/compliance'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/settings\/team'/)
  assert.match(adminNavigationSource, /defaultHref/)

  assert.match(sidebarSource, /w-\[var\(--sidebar-width\)\]/)
  assert.match(sidebarSource, /group-data-\[collapsible=icon\]:w-\[var\(--sidebar-width-icon\)\]/)
  assert.match(sidebarSource, /group-data-\[collapsible=icon\]:w-\[calc\(var\(--sidebar-width-icon\)\+1rem\)\]/)
  assert.doesNotMatch(sidebarSource, /w-\(--sidebar-width\)/)
  assert.doesNotMatch(sidebarSource, /w-\(--sidebar-width-icon\)/)
  assert.match(sidebarSource, /w-10 transition-all ease-linear group-data-\[side=left\]:-right-5/)
  assert.match(cssSource, /--sidebar-foreground:\s*#dbe4ef;/)
  assert.match(cssSource, /--sidebar-border:\s*#24334a;/)
  assert.match(cssSource, /--sidebar-accent:\s*#111d30;/)
  assert.match(cssSource, /--sidebar-ring:\s*rgba\(59, 224, 175, 0\.38\);/)
  assert.match(cssSource, /\.admin-shell-workspace\s*\{[\s\S]*min-height:\s*calc\(100vh - 16px\);/)
  assert.match(cssSource, /\.admin-shell-workspace-dashboard\s*\{[\s\S]*padding:\s*24px;/)
  assert.match(cssSource, /\.admin-shell-workspace-title\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-overview-range-button\s*\{[\s\S]*border-radius:\s*8px;/)
  assert.match(cssSource, /\.admin-shell-overview-range-button\s*\{[\s\S]*min-height:\s*44px;/)
  assert.match(cssSource, /\.admin-shell-overview-range-menu\s*\{[\s\S]*position:\s*absolute;/)
  assert.match(cssSource, /\.admin-shell-overview-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(5, minmax\(0, 1fr\)\);/)
  assert.match(cssSource, /\.admin-shell-overview-card-label-row\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-overview-card-body\s*\{[\s\S]*padding:\s*0 24px 24px;/)
  assert.match(cssSource, /\.admin-shell-overview-card-description\s*\{[\s\S]*color:\s*#8ea0bc;/)
  assert.match(cssSource, /\.admin-shell-overview-card-header\s*\{[\s\S]*display:\s*flex;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-card-value-row\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-card-icon-shell\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-card\s*\{[^}]*min-height:/)
  assert.match(cssSource, /\.admin-shell-overview-card\s*\{[\s\S]*align-content:\s*start;/)
  assert.match(cssSource, /\.admin-shell-overview-card\s*\{[\s\S]*gap:\s*0;/)
  assert.match(cssSource, /\.admin-shell-overview-card\s*\{[\s\S]*border-radius:\s*8px;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value\s*\{[\s\S]*font-size:\s*2\.1rem;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-card-change-negative\s*\{[\s\S]*color:\s*#ff8d8d;/)
  assert.match(cssSource, /\.admin-shell-overview-card-change-arrow-icon\s*\{[\s\S]*width:\s*0\.82rem;/)
  assert.match(cssSource, /\.admin-shell-overview-analytics-layout\s*\{[\s\S]*display:\s*grid;[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\);/)
  assert.match(cssSource, /\.admin-shell-overview-bottom-row\s*\{[\s\S]*display:\s*grid;/)
  assert.match(cssSource, /\.admin-shell-overview-bottom-row\s*\{[\s\S]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\);/)
  assert.match(cssSource, /\.admin-shell-overview-performance-panel\s*\{[\s\S]*padding:\s*24px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-panel\s*\{[\s\S]*border-radius:\s*8px;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox\s*\{[\s\S]*appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox\s*\{[\s\S]*-webkit-appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox\s*\{[\s\S]*width:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox\s*\{[\s\S]*height:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox\s*\{[\s\S]*border-radius:\s*3px;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox\s*\{[\s\S]*border:\s*1px solid rgba\(72, 88, 116, 0\.95\);/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox\s*\{[\s\S]*background:\s*#111a2c;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox:checked\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox:checked\s*\{[\s\S]*background-image:\s*url\(/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox\s*\{[\s\S]*background-size:\s*8px 8px;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-invite-dialog\s*\{[^}]*position:\s*relative;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-label\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-button\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-button\s*\{[\s\S]*cursor:\s*pointer;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-button\s*\{[\s\S]*background:\s*transparent;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-icon\s*\{[\s\S]*width:\s*12px;/)
  assert.match(cssSource, /\.admin-shell-athletes-name-copy\s*\{[\s\S]*display:\s*grid;/)
  assert.match(cssSource, /\.admin-shell-athletes-name-copy\s*\{[\s\S]*gap:\s*2px;/)
  assert.match(cssSource, /\.admin-shell-athletes-name-meta\s*\{[\s\S]*color:\s*#8ea0bc;/)
  assert.match(cssSource, /\.admin-shell-athletes-name-meta\s*\{[\s\S]*font-size:\s*0\.72rem;/)

  assert.match(cssSource, /\.admin-shell-overview-performance-value\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-chart\s*\{[\s\S]*min-height:\s*320px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-meta\s*\{[\s\S]*display:\s*flex;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-meta\s*\{[\s\S]*justify-items:\s*flex-start;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-meta\s*\{[\s\S]*gap:\s*8px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-legend\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-legend-dot-completed\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-legend-dot-assigned\s*\{[\s\S]*background:\s*#58c6ff;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-tooltip\s*\{[\s\S]*position:\s*absolute;/)
  assert.match(cssSource, /\.admin-shell-overview-side-column\s*\{[\s\S]*grid-template-rows:\s*repeat\(2, minmax\(0, 1fr\)\);/)
  assert.match(cssSource, /\.admin-shell-overview-insight-card\s*\{[\s\S]*min-height:\s*198px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-card\s*\{[\s\S]*border-radius:\s*8px;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell\s+\.ui-checkbox\s*\{[\s\S]*width:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-row\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-row\s*\{[\s\S]*align-items:\s*center;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-icon\s*\{[\s\S]*width:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-icon\s*\{[\s\S]*height:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-value\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bars\s*\{[\s\S]*align-items:\s*end;/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bar-completed\s*\{[\s\S]*rgba\(59, 224, 175, 0\.96\)[\s\S]*rgba\(31, 176, 135, 0\.72\)/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bar-assigned\s*\{[\s\S]*rgba\(88, 198, 255, 0\.96\)[\s\S]*rgba\(58, 154, 232, 0\.72\)/)
  assert.match(cssSource, /\.admin-shell-overview-session-chart\s*\{[\s\S]*min-height:\s*132px;/)
  assert.match(cssSource, /\.admin-shell-overview-chart-point\s*\{[\s\S]*fill:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-overview-chart-point-active\s*\{[\s\S]*fill:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-overview-chart-point-active\s*\{[\s\S]*stroke:\s*#f5f8ff;/)
  assert.match(cssSource, /\.admin-shell-workspace-panel\s*\{[\s\S]*width:\s*min\(100%, 520px\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*gap:\s*8px;/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*border:\s*1px solid var\(--admin-accent-outline\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*background:\s*rgba\(8, 27, 24, 0\.9\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*color:\s*var\(--admin-accent\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*font-weight:\s*600;/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*box-shadow:\s*none;/)
  assert.match(cssSource, /\.admin-button-default\s*\{[\s\S]*min-height:\s*40px;/)
  assert.match(cssSource, /\.admin-button-default\s*\{[\s\S]*padding:\s*0 14px;/)
  assert.match(cssSource, /\.admin-button-default\s*\{[\s\S]*border-radius:\s*8px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-button\s*\{[\s\S]*justify-self:\s*end;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-button-icon\s*\{[\s\S]*width:\s*14px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-button-icon\s*\{[\s\S]*height:\s*14px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog\s*\{[\s\S]*width:\s*min\(100%, 800px\);/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog\s*\{[\s\S]*padding:\s*32px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-close\s*\{[\s\S]*position:\s*absolute;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-illustration\s*\{[\s\S]*margin:\s*0 auto;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-field input\s*\{[\s\S]*min-height:\s*46px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-submit\s*\{[\s\S]*justify-self:\s*end;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-submit\s*\{[\s\S]*min-height:\s*40px;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-invite-dialog-submit\s*\{[^}]*background:\s*#3be0af;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-invite-button\s*\{[^}]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-athletes-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-athletes-top-search\s*\{[\s\S]*min-height:\s*40px;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-table-card-header\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-table-card-title\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-table-card-count\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-table-card\s*\{[\s\S]*border-radius:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-athletes-table\s*\{[\s\S]*border-collapse:\s*separate;/)
  assert.match(cssSource, /\.admin-shell-athletes-status-badge\s*\{[\s\S]*color:\s*#66efbf;/)
  assert.match(cssSource, /\.admin-shell-athletes-progress-fill\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-athletes-pagination\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-invites-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-invites-table-card\s*\{[\s\S]*border-radius:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-invites-table-card\s*\{[\s\S]*padding:\s*20px 28px 22px;/)
  assert.match(cssSource, /\.admin-shell-invites-table\s*\{[\s\S]*border-collapse:\s*separate;/)
  assert.match(cssSource, /\.admin-shell-invites-table-shell\s*\{[\s\S]*overflow:\s*hidden;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-invites-table-shell\s*\{[\s\S]*padding-top:/)
  assert.match(cssSource, /\.admin-shell-invites-checkbox-cell input\s*\{[\s\S]*appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-invites-checkbox-cell input\s*\{[\s\S]*width:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-invites-checkbox-cell input:checked\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-invites-role-chip\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-invites-role-chip\s*\{[\s\S]*border:\s*1px solid rgba\(58, 73, 101, 0\.95\);/)
  assert.match(cssSource, /\.admin-shell-invites-avatar\s*\{[\s\S]*width:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-invites-status-badge\s*\{[\s\S]*color:\s*#66efbf;/)
  assert.match(cssSource, /\.admin-shell-invites-status-badge-pending\s*\{[\s\S]*color:\s*#f1c76a;/)
  assert.match(cssSource, /\.admin-shell-invites-status-dot-pending\s*\{[\s\S]*background:\s*#f1c76a;/)
  assert.match(cssSource, /\.admin-shell-invites-pagination\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-groups-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-groups-top-search\s*\{[\s\S]*min-height:\s*40px;/)
  assert.match(cssSource, /\.admin-shell-groups-create-button\s*\{[\s\S]*justify-self:\s*end;/)
  assert.match(cssSource, /\.admin-shell-groups-table-card\s*\{[\s\S]*border-radius:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-groups-table\s*\{[\s\S]*border-collapse:\s*separate;/)
  assert.match(cssSource, /\.admin-shell-groups-checkbox-cell input\s*\{[\s\S]*appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-groups-checkbox-cell input\s*\{[\s\S]*width:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-groups-checkbox-cell input:checked\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-groups-name-meta\s*\{[\s\S]*font-size:\s*0\.72rem;/)
  assert.match(cssSource, /\.admin-shell-groups-access-chip\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-groups-access-chip\s*\{[\s\S]*border:\s*1px solid rgba\(58, 73, 101, 0\.95\);/)
  assert.match(cssSource, /\.admin-shell-groups-status-badge\s*\{[\s\S]*color:\s*#66efbf;/)
  assert.match(cssSource, /\.admin-shell-groups-pagination\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-rankings-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-rankings-top-search\s*\{[\s\S]*min-height:\s*40px;/)
  assert.match(cssSource, /\.admin-shell-rankings-table-card\s*\{[\s\S]*border-radius:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-rankings-table\s*\{[\s\S]*border-collapse:\s*separate;/)
  assert.match(cssSource, /\.admin-shell-rankings-checkbox-cell input\s*\{[\s\S]*appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-rankings-checkbox-cell input\s*\{[\s\S]*width:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-rankings-checkbox-cell input:checked\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-rankings-rank-badge-image\s*\{[\s\S]*width:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-rankings-rank-number\s*\{[\s\S]*font-weight:\s*700;/)
  assert.match(cssSource, /\.admin-shell-rankings-name-meta\s*\{[\s\S]*font-size:\s*0\.72rem;/)
  assert.match(cssSource, /\.admin-shell-rankings-progress-fill\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-rankings-status-badge\s*\{[\s\S]*color:\s*#66efbf;/)
  assert.match(cssSource, /\.admin-shell-rankings-pagination\s*\{[\s\S]*justify-content:\s*space-between;/)

  assert.match(rulesetSource, /reference standard UI kit/i)
  assert.match(rulesetSource, /components\/ui/i)
})
