import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const repoRoot = resolve(import.meta.dirname, '..')
const adminDashboardWorkflowSpecPath = resolve(repoRoot, 'apps/web/e2e/admin-dashboard-workflows.spec.js')

test('admin dashboard seeded-data browser workflow is registered and uses mocked safe fixture data', () => {
  assert.equal(existsSync(adminDashboardWorkflowSpecPath), true)
  const source = readFileSync(adminDashboardWorkflowSpecPath, 'utf8')

  assert.match(source, /ADMIN_DASHBOARD_SEEDED_DATA_WORKFLOW_CHECK/)
  assert.match(source, /admin-dashboard-seeded-data-loads/)
  assert.match(source, /dashboard-loads-with-seeded-data/)
  assert.match(source, /WEB_TEST_LAYERS\.SAFE_WORKFLOW/)
  assert.match(source, /test\('Dashboard loads with seeded data'/)
  assert.match(source, /seedAdminBrowserSession\(page\)/)
  assert.match(source, /pplus_admin_access_token/)
  assert.match(source, /pplus_admin_refresh_token/)
  assert.match(source, /page\.route\(['"]\*\*\/api\/admin\/dashboard\/overview\?\*\*['"]/)
  assert.match(source, /seededDashboardOverview/)
  assert.match(source, /range=last-month/)
  assert.match(source, /Dashboard summary cards/)
  assert.match(source, /Athletes/)
  assert.match(source, /50% active/)
  assert.match(source, /Programs/)
  assert.match(source, /100% assigned/)
  assert.match(source, /Workouts/)
  assert.match(source, /67% assigned/)
  assert.match(source, /Exercises/)
  assert.match(source, /50% used/)
  assert.match(source, /Invites/)
  assert.match(source, /67% accepted/)
  assert.match(source, /Training execution/)
  assert.match(source, /67% completed/)
  assert.match(source, /Workout results/)
  assert.match(source, /Showing all Speed workout results/)
  assert.match(source, /Training consistency/)
  assert.match(source, /No dashboard data yet/)
  assert.match(source, /Dashboard overview error/)
})

test('admin dashboard KPI cards reflect changed fixture values instead of hardcoded demo values', () => {
  assert.equal(existsSync(adminDashboardWorkflowSpecPath), true)
  const source = readFileSync(adminDashboardWorkflowSpecPath, 'utf8')

  assert.match(source, /ADMIN_DASHBOARD_KPI_FIXTURE_CHANGES_WORKFLOW_CHECK/)
  assert.match(source, /admin-dashboard-kpi-cards-reflect-fixture-changes/)
  assert.match(source, /kpi-cards-reflect-fixture-changes-honestly/)
  assert.match(source, /test\('KPI cards reflect fixture changes honestly'/)
  assert.match(source, /changedKpiDashboardOverview/)
  assert.match(source, /footerHeadline/)
  assert.match(source, /9 active athletes/)
  assert.match(source, /22% active/)
  assert.match(source, /5 of 5 assigned programs/)
  assert.match(source, /40% assigned/)
  assert.match(source, /7 total workout templates/)
  assert.match(source, /14% assigned/)
  assert.match(source, /11 exercise library records/)
  assert.match(source, /73% used/)
  assert.match(source, /8 athlete invites/)
  assert.match(source, /25% accepted/)
  assert.match(source, /expect\(summaryCards\.getByText\('50% active'\)\)\.toHaveCount\(0\)/)
  assert.match(source, /expect\(summaryCards\.getByText\('100% assigned'\)\)\.toHaveCount\(0\)/)
  assert.match(source, /expect\(summaryCards\.getByText\('67% accepted'\)\)\.toHaveCount\(0\)/)
})
