import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const groupsListViewPath = resolve(repoRoot, 'apps/web/components/admin/groups-list-view.jsx')
const groupsDataTablePath = resolve(repoRoot, 'apps/web/components/admin/groups-data-table.jsx')
const adminGroupsRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/groups/route.js')
const adminGroupRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-group-repository.js')
const schemaDocPath = resolve(repoRoot, 'docs/schema-v1.md')
const schemaSqlPath = resolve(repoRoot, 'infra/supabase/schema-v1.sql')
const initialMigrationPath = resolve(repoRoot, 'infra/supabase/migrations/0001_initial_schema.sql')

test('groups admin supports real create, membership sync, and archive seams', () => {
  for (const path of [
    groupsListViewPath,
    groupsDataTablePath,
    adminGroupsRoutePath,
    adminGroupRepositoryPath,
    schemaDocPath,
    schemaSqlPath,
    initialMigrationPath,
  ]) {
    assert.ok(existsSync(path), `expected groups admin file to exist: ${path}`)
  }

  const groupsListViewSource = readFileSync(groupsListViewPath, 'utf8')
  const groupsDataTableSource = readFileSync(groupsDataTablePath, 'utf8')
  const adminGroupsRouteSource = readFileSync(adminGroupsRoutePath, 'utf8')
  const adminGroupRepositorySource = readFileSync(adminGroupRepositoryPath, 'utf8')
  const schemaDocSource = readFileSync(schemaDocPath, 'utf8')
  const schemaSqlSource = readFileSync(schemaSqlPath, 'utf8')
  const initialMigrationSource = readFileSync(initialMigrationPath, 'utf8')

  assert.match(groupsListViewSource, /<GroupsDataTable searchQuery=\{searchQuery\} \/>/)

  assert.match(groupsDataTableSource, /from '@tanstack\/react-table'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/dialog'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/input'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/textarea'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/select'/)
  assert.match(groupsDataTableSource, /import \{ Avatar, AvatarFallback, AvatarImage \} from '@\/components\/ui\/avatar'/)
  assert.match(groupsDataTableSource, /function GroupAvatarStack\(\{ athletes = \[\] \}\)/)
  assert.match(groupsDataTableSource, /className="flex -space-x-2"/)
  assert.match(groupsDataTableSource, /<AvatarImage src=\{athlete\.avatarUrl\} alt=\{athlete\.name\}/)
  assert.match(groupsDataTableSource, /\+\{overflowCount\}/)
  assert.match(groupsDataTableSource, /<GroupCell name=\{row\.original\.name\} athletes=\{row\.original\.athletes\}/)
  assert.doesNotMatch(groupsDataTableSource, /formatAthletePreview\(athleteNames\)/)
  assert.match(groupsDataTableSource, /const \[athleteOptions, setAthleteOptions\] = useState\(\[\]\)/)
  assert.match(groupsDataTableSource, /const \[programOptions, setProgramOptions\] = useState\(\[\]\)/)
  assert.match(groupsDataTableSource, /const \[isCreateEditGroupDialogOpen, setIsCreateEditGroupDialogOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isArchiveGroupDialogOpen, setIsArchiveGroupDialogOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isDeleteGroupDialogOpen, setIsDeleteGroupDialogOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isAssignProgramDialogOpen, setIsAssignProgramDialogOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[groupDialogMode, setGroupDialogMode\] = useState\('create'\)/)
  assert.match(groupsDataTableSource, /const \[selectedGroupId, setSelectedGroupId\] = useState\(null\)/)
  assert.match(groupsDataTableSource, /const \[openRowActionMenuId, setOpenRowActionMenuId\] = useState\(null\)/)
  assert.match(groupsDataTableSource, /const \[pendingRowAction, setPendingRowAction\] = useState\(null\)/)
  assert.match(groupsDataTableSource, /fetch\('\/api\/admin\/groups'/)
  assert.match(groupsDataTableSource, /setGroups\(Array\.isArray\(payload\?\.groups\) \? payload\.groups : \[\]\)/)
  assert.match(groupsDataTableSource, /setAthleteOptions\(Array\.isArray\(payload\?\.athleteOptions\) \? payload\.athleteOptions : \[\]\)/)
  assert.match(groupsDataTableSource, /setProgramOptions\(Array\.isArray\(payload\?\.programOptions\) \? payload\.programOptions : \[\]\)/)
  assert.match(groupsDataTableSource, /function openCreateGroupDialog\(\)/)
  assert.match(groupsDataTableSource, /function openEditGroupDialog\(groupId\)/)
  assert.match(groupsDataTableSource, /onClick=\{openCreateGroupDialog\}/)
  assert.match(groupsDataTableSource, /<Dialog open=\{isCreateEditGroupDialogOpen\} onOpenChange=\{setIsCreateEditGroupDialogOpen\}>/)
  assert.match(groupsDataTableSource, /groupDialogMode === 'edit' \? 'Edit group' : 'Create a group'/)
  assert.match(groupsDataTableSource, /Manage memberships/)
  assert.match(groupsDataTableSource, /<GroupAvatarStack athletes=\{selectedGroup\?\.athletes \?\? \[\]\}/)
  assert.match(groupsDataTableSource, /selectedGroup\?\.athleteCountLabel \?\? '0 athletes'/)
  assert.match(groupsDataTableSource, /Assign program/)
  assert.match(groupsDataTableSource, /<Dialog open=\{isAssignProgramDialogOpen\} onOpenChange=\{setIsAssignProgramDialogOpen\}>/)
  assert.match(groupsDataTableSource, /<DialogTitle>Assign program<\/DialogTitle>/)
  assert.match(groupsDataTableSource, /onAssignProgramAction=\{\(\) => setPendingRowAction\(\{ type: 'assign-program', groupId: row\.original\.id \}\)\}/)
  assert.match(groupsDataTableSource, /method: groupDialogMode === 'edit' \? 'PATCH' : 'POST'/)
  assert.match(groupsDataTableSource, /method: 'PATCH'/)
  assert.match(groupsDataTableSource, /action: 'update'/)
  assert.match(groupsDataTableSource, /action: 'archive'/)
  assert.match(groupsDataTableSource, /<Dialog open=\{isArchiveGroupDialogOpen\} onOpenChange=\{setIsArchiveGroupDialogOpen\}>/)
  assert.match(groupsDataTableSource, /<DialogTitle>Archive group<\/DialogTitle>/)
  assert.match(groupsDataTableSource, /Archive this group and remove it from active access\./)
  assert.match(groupsDataTableSource, /<Dialog open=\{isDeleteGroupDialogOpen\} onOpenChange=\{setIsDeleteGroupDialogOpen\}>/)
  assert.match(groupsDataTableSource, /<DialogTitle>Delete group<\/DialogTitle>/)
  assert.match(groupsDataTableSource, /Unarchive/)
  assert.match(groupsDataTableSource, /Delete/)
  assert.match(groupsDataTableSource, /action: 'unarchive'/)
  assert.match(groupsDataTableSource, /action: 'delete'/)
  assert.match(groupsDataTableSource, /onArchiveAction=\{\(\) => setPendingRowAction\(\{ type: 'archive', groupId: row\.original\.id \}\)\}/)
  assert.match(groupsDataTableSource, /athleteOptions\.map\(/)
  assert.match(groupsDataTableSource, /No groups found\./)
  assert.doesNotMatch(groupsDataTableSource, /GROUPS_BACKEND_NOT_CONFIGURED/)
  assert.doesNotMatch(groupsDataTableSource, /Group 1/)
  assert.doesNotMatch(groupsDataTableSource, /Mason Lee/)

  assert.match(adminGroupsRouteSource, /createAdminGroupRepository/)
  assert.match(adminGroupsRouteSource, /export async function GET\(\)/)
  assert.match(adminGroupsRouteSource, /export async function POST\(request\)/)
  assert.match(adminGroupsRouteSource, /export async function PATCH\(request\)/)
  assert.match(adminGroupsRouteSource, /repository\.listGroups\(\)/)
  assert.match(adminGroupsRouteSource, /repository\.listAthleteOptions\(\)/)
  assert.match(adminGroupsRouteSource, /repository\.listProgramOptions\(\)/)
  assert.match(adminGroupsRouteSource, /repository\.createGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.updateGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.archiveGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.unarchiveGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.deleteGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.assignProgramToGroup\(/)
  assert.match(adminGroupsRouteSource, /return json\(\{ groups, athleteOptions, programOptions \}\)/)

  assert.match(adminGroupRepositorySource, /athlete_groups/)
  assert.match(adminGroupRepositorySource, /athlete_group_memberships/)
  assert.match(adminGroupRepositorySource, /athlete_profiles/)
  assert.match(adminGroupRepositorySource, /async function insertTable\(/)
  assert.match(adminGroupRepositorySource, /async function patchTable\(/)
  assert.match(adminGroupRepositorySource, /async function deleteTable\(/)
  assert.match(adminGroupRepositorySource, /listGroups\(\)/)
  assert.match(adminGroupRepositorySource, /listAthleteOptions\(\)/)
  assert.match(adminGroupRepositorySource, /listProgramOptions\(\)/)
  assert.match(adminGroupRepositorySource, /createGroup\(\{/)
  assert.match(adminGroupRepositorySource, /updateGroup\(\{/)
  assert.match(adminGroupRepositorySource, /archiveGroup\(\{/)
  assert.match(adminGroupRepositorySource, /unarchiveGroup\(\{/)
  assert.match(adminGroupRepositorySource, /deleteGroup\(\{/)
  assert.match(adminGroupRepositorySource, /assignProgramToGroup\(\{/)
  assert.match(adminGroupRepositorySource, /programs/)
  assert.match(adminGroupRepositorySource, /program_weeks/)
  assert.match(adminGroupRepositorySource, /program_days/)
  assert.match(adminGroupRepositorySource, /program_workouts/)
  assert.match(adminGroupRepositorySource, /program_workout_exercises/)
  assert.match(adminGroupRepositorySource, /program_workout_sets/)
  assert.match(adminGroupRepositorySource, /coach_profiles/)
  assert.match(adminGroupRepositorySource, /created_by_user_id/)
  assert.match(adminGroupRepositorySource, /archived_at/)

  assert.match(schemaDocSource, /## athlete_groups/)
  assert.match(schemaDocSource, /## athlete_group_memberships/)
  assert.match(schemaDocSource, /[Cc]oach-owned athlete collections used for admin organization, filtering, and bulk assignment targeting\./)
  assert.match(schemaSqlSource, /create table if not exists athlete_groups \(/)
  assert.match(schemaSqlSource, /create table if not exists athlete_group_memberships \(/)
  assert.match(initialMigrationSource, /create table if not exists athlete_groups \(/)
  assert.match(initialMigrationSource, /create table if not exists athlete_group_memberships \(/)
})
