import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const exercisesDataTablePath = resolve(repoRoot, 'apps/web/components/admin/exercises-data-table.jsx')
const exercisesLibraryViewPath = resolve(repoRoot, 'apps/web/components/admin/exercises-library-view.jsx')
const exerciseEditorDialogPath = resolve(repoRoot, 'apps/web/components/admin/exercise-editor-dialog.jsx')
const exerciseArchiveDialogPath = resolve(repoRoot, 'apps/web/components/admin/exercise-archive-dialog.jsx')
const exerciseDeleteDialogPath = resolve(repoRoot, 'apps/web/components/admin/exercise-delete-dialog.jsx')
const adminExerciseRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-exercise-repository.js')
const globalsCssPath = resolve(repoRoot, 'apps/web/app/globals.css')

test('exercise library uses admin light-mode controls and direct Supabase mp4 video URLs', () => {
  const tableSource = readFileSync(exercisesDataTablePath, 'utf8')
  const viewSource = readFileSync(exercisesLibraryViewPath, 'utf8')
  const repositorySource = readFileSync(adminExerciseRepositoryPath, 'utf8')
  const archiveDialogSource = readFileSync(exerciseArchiveDialogPath, 'utf8')
  const deleteDialogSource = readFileSync(exerciseDeleteDialogPath, 'utf8')
  const globalsCss = readFileSync(globalsCssPath, 'utf8')

  assert.match(viewSource, /admin-shell-exercises-library-view/)
  assert.match(viewSource, /admin-shell-athletes-page-title/)
  assert.match(tableSource, /admin-shell-athletes-filter-trigger/)
  assert.match(tableSource, /admin-shell-athletes-pagination-bar/)
  assert.match(tableSource, /admin-shell-athletes-page-size-select/)
  assert.match(tableSource, /admin-shell-athletes-empty-state/)
  assert.match(tableSource, /Create exercise/)
  assert.match(tableSource, /DropdownMenuSeparator/)
  assert.match(tableSource, /const \[isBulkExerciseMenuOpen, setIsBulkExerciseMenuOpen\] = useState\(false\)/)
  assert.match(tableSource, /const selectedExerciseRows = table\.getSelectedRowModel\(\)\.rows\.map\(\(row\) => row\.original\)/)
  assert.match(tableSource, /const selectedExerciseCount = selectedExerciseRows\.length/)
  assert.match(tableSource, /open=\{isBulkExerciseMenuOpen && selectedExerciseCount > 0\}/)
  assert.match(tableSource, /handleBulkExerciseMenuOpenChange/)
  assert.match(tableSource, /disabled=\{selectedExerciseCount === 0\}/)
  assert.match(tableSource, /aria-disabled=\{selectedExerciseCount === 0\}/)
  assert.match(tableSource, /aria-label="Exercise bulk actions"/)
  assert.match(tableSource, /\{selectedExerciseCount > 0 \? `Bulk actions \(\$\{selectedExerciseCount\}\)` : 'Bulk actions'\}/)
  assert.match(tableSource, /Duplicate[\s\S]*Assign muscle group[\s\S]*Assign equipment[\s\S]*Export[\s\S]*<DropdownMenuSeparator \/>[\s\S]*Archive[\s\S]*Delete/)
  assert.match(tableSource, /import \{ Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle \} from '@\/components\/ui\/sheet'/)
  assert.match(tableSource, /const \[isAssignMuscleGroupSheetOpen, setIsAssignMuscleGroupSheetOpen\] = useState\(false\)/)
  assert.match(tableSource, /const \[assignMuscleGroupId, setAssignMuscleGroupId\] = useState\(''\)/)
  assert.match(tableSource, /function handleAssignSelectedExercisesToMuscleGroup\(\)[\s\S]*setIsAssignMuscleGroupSheetOpen\(true\)/)
  assert.match(tableSource, /async function handleConfirmAssignMuscleGroup\(\)/)
  assert.match(tableSource, /selectedExerciseRows\.map\(\(exercise\) =>[\s\S]*requestExercisesApi\(`\/api\/admin\/exercises\/\$\{exercise\.id\}`[\s\S]*method: 'PATCH'[\s\S]*primaryMuscleId: assignMuscleGroupId/)
  assert.match(tableSource, /<Sheet open=\{isAssignMuscleGroupSheetOpen\} onOpenChange=\{handleAssignMuscleGroupSheetOpenChange\}>/)
  assert.match(tableSource, /<SheetTitle>Assign muscle group<\/SheetTitle>/)
  assert.match(tableSource, /<SheetDescription>Choose the primary muscle group for the selected exercises\.<\/SheetDescription>/)
  assert.match(tableSource, /Primary muscle group[\s\S]*Select a muscle group/)
  assert.match(tableSource, /selectedAssignMuscleGroup = editorMuscleOptions\.find\(\(muscleOption\) => muscleOption\.value === assignMuscleGroupId\)/)
  assert.match(tableSource, /<SelectItem key=\{muscleOption\.value\} value=\{muscleOption\.value\} className="admin-shell-exercises-assign-muscle-select-item">[\s\S]*\{muscleOption\.label\}/)
  assert.doesNotMatch(tableSource, /<SelectItem key=\{muscleOption\.id\} value=\{muscleOption\.id\}/)
  assert.match(globalsCss, /\.admin-shell-exercises-assign-muscle-select-trigger \{[\s\S]*min-height: 44px;[\s\S]*border: 1px solid var\(--admin-dashboard-card-border\);[\s\S]*border-radius: 12px;[\s\S]*background: var\(--admin-dashboard-control-bg\);[\s\S]*color: var\(--admin-dashboard-card-text\);/)
  assert.match(globalsCss, /\.admin-shell-exercises-assign-muscle-select-trigger:hover \{[\s\S]*background: var\(--admin-dashboard-control-hover-bg\);[\s\S]*\}/)
  assert.match(globalsCss, /\.admin-shell-exercises-assign-muscle-select-trigger\[data-state='open'\] \{[\s\S]*box-shadow: 0 0 0 2px var\(--admin-input-focus\);[\s\S]*\}/)
  assert.match(globalsCss, /\.admin-shell-exercises-assign-muscle-select-content \{[\s\S]*background: var\(--admin-shell-control-bg\) !important;[\s\S]*color: var\(--admin-shell-text\) !important;[\s\S]*\}/)
  assert.match(globalsCss, /\.admin-shell-exercises-assign-muscle-select-item\[data-highlighted\],[\s\S]*\.admin-shell-exercises-assign-muscle-select-item:hover,[\s\S]*\.admin-shell-exercises-assign-muscle-select-item:focus \{[\s\S]*background: var\(--admin-shell-nav-active-bg\) !important;[\s\S]*color: var\(--admin-shell-nav-active-text\) !important;[\s\S]*\}/)
  assert.match(tableSource, /Selected exercises[\s\S]*selectedExerciseCount[\s\S]*Assignment preview/)
  assert.match(tableSource, /await loadExercises\(\)[\s\S]*setRowSelection\(\{\}\)[\s\S]*setIsAssignMuscleGroupSheetOpen\(false\)[\s\S]*setAssignMuscleGroupId\(''\)/)
  assert.match(tableSource, /catch \(assignmentError\)[\s\S]*setAssignMuscleGroupError\(assignmentError\?\.message \|\| 'Failed to assign muscle group\.'\)/)
  assert.match(tableSource, /disabled=\{!assignMuscleGroupId \|\| selectedExerciseCount === 0 \|\| isAssigningMuscleGroup\}/)
  assert.match(tableSource, /isAssigningMuscleGroup \? 'Assigning\.\.\.' : 'Assign muscle group'/)
  assert.doesNotMatch(tableSource, /Confirm assignment/)
  assert.match(tableSource, /import MultiCombobox from '@\/components\/ui\/multi-combobox'/)
  assert.match(tableSource, /const \[isAssignEquipmentSheetOpen, setIsAssignEquipmentSheetOpen\] = useState\(false\)/)
  assert.match(tableSource, /const \[assignEquipmentIds, setAssignEquipmentIds\] = useState\(\[\]\)/)
  assert.match(tableSource, /const \[assignEquipmentError, setAssignEquipmentError\] = useState\(''\)/)
  assert.match(tableSource, /const \[isAssigningEquipment, setIsAssigningEquipment\] = useState\(false\)/)
  assert.match(tableSource, /function handleAssignSelectedExercisesToEquipment\(\)[\s\S]*setAssignEquipmentError\(''\)[\s\S]*setAssignEquipmentIds\(\[\]\)[\s\S]*setIsAssignEquipmentSheetOpen\(true\)/)
  assert.match(tableSource, /<Sheet open=\{isAssignEquipmentSheetOpen\} onOpenChange=\{handleAssignEquipmentSheetOpenChange\}>/)
  assert.match(tableSource, /<SheetTitle>Assign equipment<\/SheetTitle>/)
  assert.match(tableSource, /<SheetDescription>Choose the equipment needed for the selected exercises\.<\/SheetDescription>/)
  assert.match(tableSource, /Equipment needed[\s\S]*Choose equipment\.\.\./)
  assert.match(tableSource, /<MultiCombobox[\s\S]*id="assign-exercise-equipment"[\s\S]*className="admin-shell-exercise-combobox admin-shell-exercises-assign-equipment-combobox"[\s\S]*options=\{editorEquipmentOptions\}[\s\S]*selectedValues=\{assignEquipmentIds\}[\s\S]*onSelectedValuesChange=\{setAssignEquipmentIds\}/)
  assert.doesNotMatch(tableSource, /Equipment selected/)
  assert.doesNotMatch(tableSource, /selectedAssignEquipmentOptions/)
  assert.match(tableSource, /Assignment preview[\s\S]*Selected exercises will use this equipment list\./)
  assert.match(tableSource, /Current: \{Array\.isArray\(exercise\.equipmentNeeded\)[\s\S]*exercise\.equipmentNeeded\.join\(', '\)[\s\S]*exercise\.equipment \|\| 'Unassigned'/)
  assert.match(tableSource, /await Promise\.all\([\s\S]*selectedExerciseRows\.map\(\(exercise\) => requestExercisesApi\(`\/api\/admin\/exercises\/\$\{exercise\.id\}`,[\s\S]*method: 'PATCH',[\s\S]*equipmentNeeded: assignEquipmentIds,[\s\S]*\}\)/)
  assert.match(tableSource, /await loadExercises\(\)[\s\S]*setRowSelection\(\{\}\)[\s\S]*setIsAssignEquipmentSheetOpen\(false\)[\s\S]*setAssignEquipmentIds\(\[\]\)/)
  assert.match(tableSource, /catch \(assignmentError\)[\s\S]*setAssignEquipmentError\(assignmentError\?\.message \|\| 'Failed to assign equipment\.'\)/)
  assert.match(tableSource, /\{assignEquipmentError \? \([\s\S]*\{assignEquipmentError\}/)
  assert.match(tableSource, /disabled=\{assignEquipmentIds\.length === 0 \|\| selectedExerciseCount === 0 \|\| isAssigningEquipment\}/)
  assert.match(tableSource, /onClick=\{handleConfirmAssignEquipment\}/)
  assert.match(tableSource, /isAssigningEquipment \? 'Assigning\.\.\.' : 'Assign equipment'/)
  assert.match(repositorySource, /payload\.default_equipment = equipmentValues\.length > 0 \? equipmentValues\.join\(', '\) : null/)
  assert.match(tableSource, /from '@\/lib\/admin-exercises-export'/)
  assert.doesNotMatch(tableSource, /const exerciseExportColumns = \[/)
  assert.doesNotMatch(tableSource, /function getExercisesExportFileName\(/)
  assert.match(tableSource, /const \[isExportExerciseSheetOpen, setIsExportExerciseSheetOpen\] = useState\(false\)/)
  assert.match(tableSource, /const \[selectedExportExerciseIds, setSelectedExportExerciseIds\] = useState\(\[\]\)/)
  assert.match(tableSource, /const \[isExportingExercises, setIsExportingExercises\] = useState\(false\)/)
  assert.match(tableSource, /function handleExportSelectedExercises\(\)[\s\S]*setSelectedExportExerciseIds\(selectedExerciseRows\.map\(\(exercise\) => exercise\.id\)\.filter\(Boolean\)\)[\s\S]*setIsExportExerciseSheetOpen\(true\)/)
  assert.match(tableSource, /const exportExercisesToReview = useMemo\([\s\S]*exercises\.filter\(\(exercise\) => selectedExportExerciseIds\.includes\(exercise\.id\)\)/)
  assert.match(tableSource, /const exportExercisesDisabled = isExportingExercises \|\| exportExercisesToReview\.length === 0/)
  assert.match(tableSource, /async function handleConfirmExportExercises\(\) \{[\s\S]*buildExercisesExportCsv\(exportExercisesToReview\)[\s\S]*downloadExercisesExportFile\(\{[\s\S]*fileName: exportExercisesFileName,[\s\S]*setIsExportExerciseSheetOpen\(false\)[\s\S]*setSelectedExportExerciseIds\(\[\]\)[\s\S]*table\.resetRowSelection\(\)/)
  assert.match(tableSource, /<Sheet open=\{isExportExerciseSheetOpen\} onOpenChange=\{setIsExportExerciseSheetOpen\}>/)
  assert.match(tableSource, /<SheetTitle>Export exercises<\/SheetTitle>/)
  assert.match(tableSource, /Review the selected exercises before downloading a CSV export\./)
  assert.match(tableSource, /Selected exercises[\s\S]*\{exportExercisesToReview\.length\}[\s\S]*Format[\s\S]*CSV[\s\S]*Filename[\s\S]*\{exportExercisesFileName\}/)
  assert.match(tableSource, /Included columns[\s\S]*exerciseExportColumns\.map\(\(column\) =>/)
  assert.match(tableSource, /Selected exercise preview[\s\S]*exportExercisesToReview\.map\(\(exercise\) =>/)
  assert.match(tableSource, /No exercises selected\./)
  assert.match(tableSource, /disabled=\{exportExercisesDisabled\}/)
  assert.match(tableSource, /onClick=\{handleConfirmExportExercises\}/)
  assert.match(tableSource, /isExportingExercises \? 'Preparing CSV\.\.\.' : 'Download CSV'/)
  assert.match(tableSource, /setSelectedExportExerciseIds\(\[\]\)/)
  assert.match(tableSource, /import ExerciseArchiveDialog from '@\/components\/admin\/exercise-archive-dialog'/)
  assert.match(tableSource, /const \[selectedDeleteExerciseIds, setSelectedDeleteExerciseIds\] = useState\(\[\]\)/)
  assert.match(tableSource, /const deleteExercisesToReview = useMemo\([\s\S]*exercises\.filter\(\(exercise\) => selectedDeleteExerciseIds\.includes\(exercise\.id\)\)/)
  assert.match(tableSource, /const exerciseDeleteDialogItems = deleteExercisesToReview\.length > 0 \? deleteExercisesToReview : \(exercisePendingDelete \? \[exercisePendingDelete\] : \[\]\)/)
  assert.match(tableSource, /function handleDeleteExerciseDialogOpenChange\(isOpen\) \{[\s\S]*setIsExerciseDeleteDialogOpen\(isOpen\)[\s\S]*if \(!isOpen\) \{[\s\S]*setExercisePendingDelete\(null\)[\s\S]*setSelectedDeleteExerciseIds\(\[\]\)[\s\S]*setExerciseDeleteError\(''\)/)
  assert.match(tableSource, /function handleDeleteSelectedExercises\(\)[\s\S]*setIsBulkExerciseMenuOpen\(false\)[\s\S]*setExerciseDeleteError\(''\)[\s\S]*setExercisePendingDelete\(null\)[\s\S]*setSelectedDeleteExerciseIds\(selectedExerciseRows\.map\(\(exercise\) => exercise\.id\)\.filter\(Boolean\)\)[\s\S]*setIsExerciseDeleteDialogOpen\(true\)/)
  assert.match(tableSource, /<ExerciseDeleteDialog[\s\S]*open=\{isExerciseDeleteDialogOpen\}[\s\S]*onOpenChange=\{handleDeleteExerciseDialogOpenChange\}[\s\S]*exercises=\{exerciseDeleteDialogItems\}/)
  assert.match(deleteDialogSource, /const resolvedExercises = exercises\.length > 0 \? exercises : fallbackExercise/)
  assert.match(deleteDialogSource, /const exerciseCount = resolvedExercises\.length/)
  assert.match(deleteDialogSource, /Delete exercises/)
  assert.match(deleteDialogSource, /Delete selected exercises permanently from the library\./)
  assert.match(deleteDialogSource, /This cannot be undone\./)
  assert.match(deleteDialogSource, /\{exerciseCount\} exercise\{exerciseCount === 1 \? '' : 's'\} selected/)
  assert.match(deleteDialogSource, /previewExercises\.map\(\(exercise\) =>/)
  assert.match(deleteDialogSource, /hiddenExerciseCount > 0/)
  assert.match(deleteDialogSource, /isDeleting \? 'Deleting\.\.\.' : deleteButtonLabel/)
  assert.match(tableSource, /async function handleDeleteExercise\(\) \{[\s\S]*const exerciseIds = selectedDeleteExerciseIds\.length > 0[\s\S]*\? selectedDeleteExerciseIds[\s\S]*: \(exercisePendingDelete\?\.id \? \[exercisePendingDelete\.id\] : \[\]\)/)
  assert.match(tableSource, /if \(exerciseIds\.length === 0\) return/)
  assert.match(tableSource, /setIsDeletingExercise\(true\)[\s\S]*setExerciseDeleteError\(''\)/)
  assert.match(tableSource, /await Promise\.all\([\s\S]*exerciseIds\.map\(\(exerciseId\) => requestExercisesApi\(`\/api\/admin\/exercises\/\$\{exerciseId\}`,[\s\S]*method: 'DELETE'/)
  assert.match(tableSource, /await loadExercises\(\)[\s\S]*setRowSelection\(\{\}\)[\s\S]*setIsExerciseDeleteDialogOpen\(false\)[\s\S]*setExercisePendingDelete\(null\)[\s\S]*setSelectedDeleteExerciseIds\(\[\]\)/)
  assert.match(tableSource, /if \(exerciseFormValues\.id && exerciseIds\.includes\(exerciseFormValues\.id\)\)[\s\S]*setIsExerciseEditorOpen\(false\)/)
  assert.match(tableSource, /catch \(deleteError\)[\s\S]*setExerciseDeleteError\(deleteError\?\.message \|\| 'Failed to delete exercises\.'\)/)
  assert.match(tableSource, /finally \{[\s\S]*setIsDeletingExercise\(false\)/)
  assert.match(tableSource, /<ExerciseDeleteDialog[\s\S]*isDeleting=\{isDeletingExercise\}[\s\S]*errorMessage=\{exerciseDeleteError\}[\s\S]*onConfirmDelete=\{handleDeleteExercise\}/)
  assert.match(tableSource, /openDeleteExerciseDialog\(exerciseId\)[\s\S]*setSelectedDeleteExerciseIds\(\[\]\)[\s\S]*setExercisePendingDelete\(selectedExercise\)/)
  assert.match(tableSource, /handleDeleteSelectedExercises\(\)[\s\S]*setExercisePendingDelete\(null\)[\s\S]*setSelectedDeleteExerciseIds\(selectedExerciseRows\.map\(\(exercise\) => exercise\.id\)\.filter\(Boolean\)\)/)
  assert.match(tableSource, /handleDeleteExerciseDialogOpenChange\(isOpen\)[\s\S]*setSelectedDeleteExerciseIds\(\[\]\)/)
  assert.match(tableSource, /const \[isArchiveExerciseDialogOpen, setIsArchiveExerciseDialogOpen\] = useState\(false\)/)
  assert.match(tableSource, /const \[selectedArchiveExerciseIds, setSelectedArchiveExerciseIds\] = useState\(\[\]\)/)
  assert.match(tableSource, /const \[isArchivingExercises, setIsArchivingExercises\] = useState\(false\)/)
  assert.match(tableSource, /const \[archiveExerciseMessage, setArchiveExerciseMessage\] = useState\(''\)/)
  assert.match(tableSource, /const archiveExercisesToReview = useMemo\([\s\S]*exercises\.filter\(\(exercise\) => selectedArchiveExerciseIds\.includes\(exercise\.id\)\)/)
  assert.match(tableSource, /const archiveEligibleExercises = useMemo\([\s\S]*archiveExercisesToReview\.filter\(\(exercise\) => normalizeExerciseStatus\(exercise\.status\) !== 'archived'\)/)
  assert.match(tableSource, /const archiveSkippedExercises = useMemo\([\s\S]*archiveExercisesToReview\.filter\(\(exercise\) => normalizeExerciseStatus\(exercise\.status\) === 'archived'\)/)
  assert.match(tableSource, /function handleArchiveExerciseDialogOpenChange\(isOpen\) \{[\s\S]*setIsArchiveExerciseDialogOpen\(isOpen\)[\s\S]*if \(!isOpen\) \{[\s\S]*setSelectedArchiveExerciseIds\(\[\]\)[\s\S]*setArchiveExerciseMessage\(''\)/)
  assert.match(tableSource, /function handleArchiveSelectedExercises\(\)[\s\S]*setArchiveExerciseMessage\(''\)[\s\S]*setSelectedArchiveExerciseIds\(selectedExerciseRows\.map\(\(exercise\) => exercise\.id\)\.filter\(Boolean\)\)[\s\S]*setIsArchiveExerciseDialogOpen\(true\)/)
  assert.match(tableSource, /async function handleConfirmArchiveExercises\(\) \{[\s\S]*if \(archiveEligibleExercises\.length === 0\) return[\s\S]*setIsArchivingExercises\(true\)[\s\S]*await Promise\.all\([\s\S]*archiveEligibleExercises\.map\(\(exercise\) => requestExercisesApi\(`\/api\/admin\/exercises\/\$\{exercise\.id\}`,[\s\S]*method: 'PATCH',[\s\S]*status: 'archived',[\s\S]*\}\)/)
  assert.match(tableSource, /await loadExercises\(\)[\s\S]*setRowSelection\(\{\}\)[\s\S]*setIsArchiveExerciseDialogOpen\(false\)[\s\S]*setSelectedArchiveExerciseIds\(\[\]\)[\s\S]*setArchiveExerciseMessage\(''\)/)
  assert.match(tableSource, /catch \(archiveError\)[\s\S]*setArchiveExerciseMessage\(archiveError\?\.message \|\| 'Failed to archive exercises\.'\)/)
  assert.match(tableSource, /finally \{[\s\S]*setIsArchivingExercises\(false\)/)
  assert.match(tableSource, /<ExerciseArchiveDialog[\s\S]*open=\{isArchiveExerciseDialogOpen\}[\s\S]*onOpenChange=\{handleArchiveExerciseDialogOpenChange\}[\s\S]*exercises=\{archiveExercisesToReview\}[\s\S]*eligibleCount=\{archiveEligibleExercises\.length\}[\s\S]*skippedCount=\{archiveSkippedExercises\.length\}[\s\S]*isArchiving=\{isArchivingExercises\}[\s\S]*message=\{archiveExerciseMessage\}[\s\S]*onConfirm=\{handleConfirmArchiveExercises\}/)
  assert.match(archiveDialogSource, /export default function ExerciseArchiveDialog/)
  assert.match(archiveDialogSource, /<DialogTitle>Archive exercises<\/DialogTitle>/)
  assert.match(archiveDialogSource, /Archive selected exercises so they stay out of the active library without being permanently deleted\./)
  assert.match(archiveDialogSource, /Archived exercises can be restored later from archived status\./)
  assert.match(archiveDialogSource, /const exerciseCount = exercises\.length/)
  assert.match(archiveDialogSource, /const resolvedEligibleCount = typeof eligibleCount === 'number' \? eligibleCount : exerciseCount/)
  assert.match(archiveDialogSource, /skippedCount = 0/)
  assert.match(archiveDialogSource, /\{resolvedEligibleCount\} will be archived/)
  assert.match(archiveDialogSource, /\{skippedCount\} already archived/)
  assert.match(archiveDialogSource, /disabled=\{isArchiving \|\| resolvedEligibleCount === 0\}/)
  assert.match(archiveDialogSource, /isArchiving \? 'Archiving\.\.\.' : 'Archive exercises'/)
  assert.match(globalsCss, /\.admin-shell-exercises-assign-equipment-combobox \.multi-combobox-trigger \{[\s\S]*border: 1px solid var\(--admin-dashboard-card-border\);[\s\S]*background: var\(--admin-dashboard-control-bg\);[\s\S]*color: var\(--admin-dashboard-card-text\);[\s\S]*\}/)
  assert.match(tableSource, /className="flex w-full flex-wrap items-start justify-between gap-3"/)
  assert.match(tableSource, /className="flex min-w-0 flex-1 flex-wrap items-center justify-start gap-2"/)
  assert.match(tableSource, /className="flex shrink-0 flex-col items-end gap-1\.5 sm:flex-row sm:items-center sm:gap-3"/)

  assert.match(repositorySource, /'thumbnail_url'/)
  assert.match(repositorySource, /'video_url'/)
  assert.match(repositorySource, /normalizeDirectExerciseVideoUrl/)
  assert.match(repositorySource, /input\?\.video_url/)
  assert.match(repositorySource, /bucket:\s*'exercise-videos'/)
  assert.match(repositorySource, /contentType:\s*normalizedUpload\.contentType \|\| contentType \|\| 'video\/mp4'/)
  assert.match(tableSource, /youtubeLink/)
  assert.match(tableSource, /onGenerateYoutubeMedia/)
  assert.doesNotMatch(repositorySource, /default.*youtube/i)
  assert.doesNotMatch(repositorySource, /video_url:\s*normalizeOptionalString\(input\?\.youtube/i)

  assert.doesNotMatch(tableSource, /className="rounded-\[12px\] min-h-\[40px\] !border !border-\[#24334A\] bg-transparent text-\[#DCE6F8\]/)
  assert.doesNotMatch(tableSource, /className="h-9 w-\[76px\] rounded-\[10px\] !border-\[#24334A\] bg-\[#111D30\]/)
  assert.doesNotMatch(tableSource, /className="h-24 text-center text-\[#8EA0BC\]"/)
})

test('exercise editor dialog seam uses admin theme tokens instead of hard-coded dark colors', () => {
  const dialogSource = readFileSync(exerciseEditorDialogPath, 'utf8')

  assert.match(dialogSource, /SheetContent[\s\S]*?var\(--admin-dashboard-card-bg\)/)
  assert.match(dialogSource, /SheetContent[\s\S]*?var\(--admin-dashboard-card-border\)/)
  assert.match(dialogSource, /SheetContent[\s\S]*?var\(--admin-dashboard-card-text\)/)
  assert.match(dialogSource, /FieldInput[\s\S]*?var\(--admin-dashboard-control-bg\)/)
  assert.match(dialogSource, /FieldInput[\s\S]*?var\(--admin-dashboard-card-muted\)/)
  assert.match(dialogSource, /Textarea[\s\S]*?var\(--admin-dashboard-control-bg\)/)

  assert.doesNotMatch(dialogSource, /border-\[#24334A\]|bg-\[#0F1728\]|bg-\[#111D30\]|text-\[#DCE6F8\]|text-\[#EEF4FF\]|placeholder:text-\[#70809E\]/)
})
