import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const groupsListViewPath = resolve(repoRoot, 'apps/web/components/admin/groups-list-view.jsx')
const groupsDataTablePath = resolve(repoRoot, 'apps/web/components/admin/groups-data-table.jsx')
const adminGroupsRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/groups/route.js')
const adminGroupRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-group-repository.js')
const schemaDocPath = resolve(repoRoot, 'docs/schema-v1.md')
const schemaSqlPath = resolve(repoRoot, 'infra/supabase/schema-v1.sql')
const initialMigrationPath = resolve(repoRoot, 'infra/supabase/migrations/0001_initial_schema.sql')

test('groups admin supports real create, membership sync, and archive seams', () => {
  for (const path of [
    groupsListViewPath,
    groupsDataTablePath,
    adminGroupsRoutePath,
    adminGroupRepositoryPath,
    schemaDocPath,
    schemaSqlPath,
    initialMigrationPath,
  ]) {
    assert.ok(existsSync(path), `expected groups admin file to exist: ${path}`)
  }

  const groupsListViewSource = readFileSync(groupsListViewPath, 'utf8')
  const groupsDataTableSource = readFileSync(groupsDataTablePath, 'utf8')
  const adminGroupsRouteSource = readFileSync(adminGroupsRoutePath, 'utf8')
  const adminGroupRepositorySource = readFileSync(adminGroupRepositoryPath, 'utf8')
  const schemaDocSource = readFileSync(schemaDocPath, 'utf8')
  const schemaSqlSource = readFileSync(schemaSqlPath, 'utf8')
  const initialMigrationSource = readFileSync(initialMigrationPath, 'utf8')

  assert.match(groupsListViewSource, /<GroupsDataTable searchQuery=\{searchQuery\} \/>/)

  assert.match(groupsDataTableSource, /from '@tanstack\/react-table'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/dialog'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/sheet'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/item'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/input'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/textarea'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/select'/)
  assert.match(groupsDataTableSource, /import \{ Avatar, AvatarFallback, AvatarImage \} from '@\/components\/ui\/avatar'/)
  assert.match(groupsDataTableSource, /function GroupAvatarStack\(\{ athletes = \[\] \}\)/)
  assert.match(groupsDataTableSource, /className="flex -space-x-2"/)
  assert.match(groupsDataTableSource, /<AvatarImage src=\{athlete\.avatarUrl\} alt=\{athlete\.name\}/)
  assert.match(groupsDataTableSource, /\+\{overflowCount\}/)
  assert.match(groupsDataTableSource, /<GroupCell name=\{row\.original\.name\} athletes=\{row\.original\.athletes\}/)
  assert.doesNotMatch(groupsDataTableSource, /formatAthletePreview\(athleteNames\)/)
  assert.match(groupsDataTableSource, /const \[athleteOptions, setAthleteOptions\] = useState\(\[\]\)/)
  assert.match(groupsDataTableSource, /const \[isCreateEditGroupDialogOpen, setIsCreateEditGroupDialogOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isDeleteGroupDialogOpen, setIsDeleteGroupDialogOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[groupDialogMode, setGroupDialogMode\] = useState\('create'\)/)
  assert.match(groupsDataTableSource, /const \[selectedGroupId, setSelectedGroupId\] = useState\(null\)/)
  assert.match(groupsDataTableSource, /const \[openRowActionMenuId, setOpenRowActionMenuId\] = useState\(null\)/)
  assert.match(groupsDataTableSource, /const \[pendingRowAction, setPendingRowAction\] = useState\(null\)/)
  assert.match(groupsDataTableSource, /fetch\('\/api\/admin\/groups'/)
  assert.match(groupsDataTableSource, /setGroups\(Array\.isArray\(payload\?\.groups\) \? payload\.groups : \[\]\)/)
  assert.match(groupsDataTableSource, /setAthleteOptions\(Array\.isArray\(payload\?\.athleteOptions\) \? payload\.athleteOptions : \[\]\)/)
  assert.match(groupsDataTableSource, /function openCreateGroupDialog\(\)/)
  assert.match(groupsDataTableSource, /function openEditGroupDialog\(groupId\)/)
  assert.match(groupsDataTableSource, /onClick=\{openCreateGroupDialog\}/)
  assert.match(groupsDataTableSource, /<Sheet open=\{isCreateEditGroupDialogOpen\} onOpenChange=\{setIsCreateEditGroupDialogOpen\}>/)
  assert.match(groupsDataTableSource, /<SheetContent side="right" className="admin-shell-groups-create-sheet[^\"]*!max-w-\[var\(--container-lg\)\][^\"]*"/)
  assert.match(groupsDataTableSource, /groupDialogMode === 'edit' \? 'Edit group' : 'Create a group'/)
  assert.match(groupsDataTableSource, /Update the information below\./)
  assert.match(groupsDataTableSource, /Fill out the information below\./)
  assert.match(groupsDataTableSource, /admin-shell-athletes-example-columns-button admin-shell-athletes-create-select-trigger w-full/)
  assert.match(groupsDataTableSource, /Athletes list/)
  assert.match(groupsDataTableSource, /Add or remove athletes from this group\./)
  assert.match(groupsDataTableSource, /<ItemGroup className="gap-0">/)
  assert.match(groupsDataTableSource, /Added to group/)
  assert.match(groupsDataTableSource, /Available to add/)
  assert.match(groupsDataTableSource, /Remove athlete from group/)
  assert.match(groupsDataTableSource, /Add athlete to group/)
  assert.match(groupsDataTableSource, /<SheetFooter className="shrink-0 border-t border-\[color:var\(--admin-dashboard-card-border\)\] px-6 py-5 sm:flex-row sm:justify-end gap-3">/)
  assert.match(groupsDataTableSource, /className="admin-shell-groups-create-submit rounded-\[12px\] min-h-\[40px\] bg-\[var\(--admin-shell-primary-button-bg\)\] text-\[#0B1120\] hover:bg-\[var\(--admin-shell-primary-button-bg\)\]"/)
  assert.match(groupsDataTableSource, /groupDialogMode === 'edit' \? 'Save changes' : 'Create group'/)
  assert.doesNotMatch(groupsDataTableSource, /<SheetFooter className="shrink-0 border-t border-\[color:var\(--admin-dashboard-card-border\)\] px-6 py-5 sm:justify-end gap-3">/)
  assert.doesNotMatch(groupsDataTableSource, /Manage memberships/)
  assert.doesNotMatch(groupsDataTableSource, /Add or remove athlete memberships for this group\./)
  assert.doesNotMatch(groupsDataTableSource, /Save group/)
  assert.doesNotMatch(groupsDataTableSource, /<Dialog open=\{isCreateEditGroupDialogOpen\}/)
  assert.doesNotMatch(groupsDataTableSource, /admin-shell-groups-create-sheet[^\"]*sm:max-w-\[720px\]/)
  assert.doesNotMatch(groupsDataTableSource, /onAssignProgramAction/)
  assert.doesNotMatch(groupsDataTableSource, /onArchiveAction/)
  assert.doesNotMatch(groupsDataTableSource, /type: 'assign-program'/)
  assert.doesNotMatch(groupsDataTableSource, /type: 'archive'/)
  assert.match(groupsDataTableSource, /method: groupDialogMode === 'edit' \? 'PATCH' : 'POST'/)
  assert.match(groupsDataTableSource, /method: 'PATCH'/)
  assert.match(groupsDataTableSource, /action: 'update'/)
  assert.match(groupsDataTableSource, /<Dialog open=\{isDeleteGroupDialogOpen\} onOpenChange=\{setIsDeleteGroupDialogOpen\}>/)
  assert.match(groupsDataTableSource, /<DialogContent className="admin-shell-athletes-invite-dialog border border-\[var\(--admin-dashboard-card-border\)\] bg-\[var\(--admin-dashboard-card-bg\)\] text-\[var\(--admin-dashboard-card-text\)\] sm:max-w-\[440px\]">/)
  assert.match(groupsDataTableSource, /<DialogTitle>Delete group<\/DialogTitle>/)
  assert.match(groupsDataTableSource, /<DialogDescription>This group will be permanently deleted\.<\/DialogDescription>/)
  assert.match(groupsDataTableSource, /<DialogFooter className="sm:flex-row sm:justify-end gap-3">/)
  assert.match(groupsDataTableSource, /className="rounded-\[12px\] min-h-\[40px\]"[\s\S]*Cancel/)
  assert.match(groupsDataTableSource, /className="rounded-\[12px\] min-h-\[40px\] bg-red-500\/90 text-white hover:bg-red-500"[\s\S]*Delete group/)
  assert.doesNotMatch(groupsDataTableSource, /<Dialog open=\{isDeleteGroupDialogOpen\} onOpenChange=\{setIsDeleteGroupDialogOpen\}>[\s\S]*sm:max-w-\[560px\]/)
  assert.doesNotMatch(groupsDataTableSource, /<Dialog open=\{isDeleteGroupDialogOpen\} onOpenChange=\{setIsDeleteGroupDialogOpen\}>[\s\S]*border-t/)
  assert.match(groupsDataTableSource, /action: 'delete'/)
  assert.match(groupsDataTableSource, /athleteOptions\.map\(/)
  assert.match(groupsDataTableSource, /No groups found\./)
  assert.doesNotMatch(groupsDataTableSource, /GROUPS_BACKEND_NOT_CONFIGURED/)
  assert.doesNotMatch(groupsDataTableSource, /Group 1/)
  assert.doesNotMatch(groupsDataTableSource, /Mason Lee/)

  assert.match(adminGroupsRouteSource, /createAdminGroupRepository/)
  assert.match(adminGroupsRouteSource, /export async function GET\(\)/)
  assert.match(adminGroupsRouteSource, /export async function POST\(request\)/)
  assert.match(adminGroupsRouteSource, /export async function PATCH\(request\)/)
  assert.match(adminGroupsRouteSource, /repository\.listGroups\(\)/)
  assert.match(adminGroupsRouteSource, /repository\.listAthleteOptions\(\)/)
  assert.match(adminGroupsRouteSource, /repository\.listProgramOptions\(\)/)
  assert.match(adminGroupsRouteSource, /repository\.createGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.updateGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.archiveGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.unarchiveGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.deleteGroup\(/)
  assert.match(adminGroupsRouteSource, /repository\.assignProgramToGroup\(/)
  assert.match(adminGroupsRouteSource, /return json\(\{ groups, athleteOptions, programOptions \}\)/)

  assert.match(adminGroupRepositorySource, /athlete_groups/)
  assert.match(adminGroupRepositorySource, /athlete_group_memberships/)
  assert.match(adminGroupRepositorySource, /athlete_profiles/)
  assert.match(adminGroupRepositorySource, /async function insertTable\(/)
  assert.match(adminGroupRepositorySource, /async function patchTable\(/)
  assert.match(adminGroupRepositorySource, /async function deleteTable\(/)
  assert.match(adminGroupRepositorySource, /listGroups\(\)/)
  assert.match(adminGroupRepositorySource, /listAthleteOptions\(\)/)
  assert.match(adminGroupRepositorySource, /listProgramOptions\(\)/)
  assert.match(adminGroupRepositorySource, /createGroup\(\{/)
  assert.match(adminGroupRepositorySource, /updateGroup\(\{/)
  assert.match(adminGroupRepositorySource, /archiveGroup\(\{/)
  assert.match(adminGroupRepositorySource, /unarchiveGroup\(\{/)
  assert.match(adminGroupRepositorySource, /deleteGroup\(\{/)
  assert.match(adminGroupRepositorySource, /assignProgramToGroup\(\{/)
  assert.match(adminGroupRepositorySource, /programs/)
  assert.match(adminGroupRepositorySource, /program_weeks/)
  assert.match(adminGroupRepositorySource, /program_days/)
  assert.match(adminGroupRepositorySource, /program_workouts/)
  assert.match(adminGroupRepositorySource, /program_workout_exercises/)
  assert.match(adminGroupRepositorySource, /program_workout_sets/)
  assert.match(adminGroupRepositorySource, /coach_profiles/)
  assert.match(adminGroupRepositorySource, /created_by_user_id/)
  assert.match(adminGroupRepositorySource, /archived_at/)

  assert.match(schemaDocSource, /## athlete_groups/)
  assert.match(schemaDocSource, /## athlete_group_memberships/)
  assert.match(schemaDocSource, /[Cc]oach-owned athlete collections used for admin organization, filtering, and bulk assignment targeting\./)
  assert.match(schemaSqlSource, /create table if not exists athlete_groups \(/)
  assert.match(schemaSqlSource, /create table if not exists athlete_group_memberships \(/)
  assert.match(initialMigrationSource, /create table if not exists athlete_groups \(/)
  assert.match(initialMigrationSource, /create table if not exists athlete_group_memberships \(/)
})
