import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const cssPath = resolve(repoRoot, 'apps/web/app/globals.css')
const adminIndexPath = resolve(repoRoot, 'apps/web/app/admin/page.jsx')
const adminUiPath = resolve(repoRoot, 'apps/web/app/admin/ui/page.jsx')
const adminSectionPath = resolve(repoRoot, 'apps/web/app/admin/[section]/page.jsx')
const adminSubsectionPath = resolve(repoRoot, 'apps/web/app/admin/[section]/[subsection]/page.jsx')
const adminShellPath = resolve(repoRoot, 'apps/web/components/admin/admin-shell.jsx')
const dashboardOverviewPath = resolve(repoRoot, 'apps/web/components/admin/dashboard-overview.jsx')
const adminNavigationPath = resolve(repoRoot, 'apps/web/components/admin/admin-navigation.js')
const sidebarPath = resolve(repoRoot, 'apps/web/components/ui/sidebar.jsx')
const rulesetPath = resolve(repoRoot, 'docs/admin-ui-ruleset.md')

test('admin navigation uses real nested routes driven by shared config', () => {
  for (const path of [
    adminIndexPath,
    adminUiPath,
    adminSectionPath,
    adminSubsectionPath,
    adminShellPath,
    dashboardOverviewPath,
    adminNavigationPath,
    sidebarPath,
  ]) {
    assert.ok(existsSync(path), `expected admin navigation file to exist: ${path}`)
  }

  const cssSource = readFileSync(cssPath, 'utf8')
  const adminIndexSource = readFileSync(adminIndexPath, 'utf8')
  const adminUiSource = readFileSync(adminUiPath, 'utf8')
  const adminSectionSource = readFileSync(adminSectionPath, 'utf8')
  const adminSubsectionSource = readFileSync(adminSubsectionPath, 'utf8')
  const adminShellSource = readFileSync(adminShellPath, 'utf8')
  const dashboardOverviewSource = readFileSync(dashboardOverviewPath, 'utf8')
  const adminNavigationSource = readFileSync(adminNavigationPath, 'utf8')
  const sidebarSource = readFileSync(sidebarPath, 'utf8')
  const rulesetSource = readFileSync(rulesetPath, 'utf8')

  assert.match(adminIndexSource, /redirect\('\/admin\/dashboard'\)/)
  assert.match(adminUiSource, /redirect\('\/admin\/dashboard'\)/)

  assert.match(adminSectionSource, /AdminShell/)
  assert.match(adminSectionSource, /params/)
  assert.match(adminSectionSource, /section/)
  assert.match(adminSubsectionSource, /AdminShell/)
  assert.match(adminSubsectionSource, /subsection/)
  assert.match(adminSubsectionSource, /redirect\('\/admin\/dashboard'\)/)

  assert.match(adminShellSource, /from '\.\.\/ui\/sidebar-layout'/)
  assert.match(adminShellSource, /from '\.\.\/ui\/sidebar'/)
  assert.match(adminShellSource, /from '\.\/admin-navigation'/)
  assert.match(adminShellSource, /from '\.\/dashboard-overview'/)
  assert.match(adminShellSource, /brandLogoSrc="\/admin\/logo_pplus_training\.svg"/)
  assert.match(adminShellSource, /currentPath/)
  assert.match(adminShellSource, /pageTitle/)
  assert.match(adminShellSource, /DashboardOverview/)
  assert.match(adminShellSource, /group\.items\?\.map\(\(item\) => \(\{ \.\.\.item \}\)\) \?\? \[\]/)
  assert.match(adminShellSource, /!isDashboardOverview &&/)
  assert.match(dashboardOverviewSource, /'use client'/)
  assert.match(dashboardOverviewSource, /useState/)
  assert.match(dashboardOverviewSource, /Users/)
  assert.match(dashboardOverviewSource, /CalendarRange/)
  assert.match(dashboardOverviewSource, /Activity/)
  assert.match(dashboardOverviewSource, /BadgeCheck/)
  assert.match(dashboardOverviewSource, /ArrowUp/)
  assert.match(dashboardOverviewSource, /ArrowDown/)
  assert.match(dashboardOverviewSource, /Send\b/)
  assert.match(dashboardOverviewSource, /icon:\s*Users/)
  assert.match(dashboardOverviewSource, /icon:\s*CalendarRange/)
  assert.match(dashboardOverviewSource, /icon:\s*Activity/)
  assert.match(dashboardOverviewSource, /icon:\s*BadgeCheck/)
  assert.match(dashboardOverviewSource, /icon:\s*Send/)
  assert.doesNotMatch(dashboardOverviewSource, /icon:\s*ClipboardList/)
  assert.doesNotMatch(dashboardOverviewSource, /icon:\s*SendHorizontal/)
  assert.match(dashboardOverviewSource, /Last month/)
  assert.match(dashboardOverviewSource, /Last 7 days/)
  assert.match(dashboardOverviewSource, /Last 3 months/)
  assert.match(dashboardOverviewSource, /Last year/)
  assert.match(dashboardOverviewSource, /overviewRangeOptions/)
  assert.match(dashboardOverviewSource, /overviewRangeCardData/)
  assert.match(dashboardOverviewSource, /activeRange/)
  assert.match(dashboardOverviewSource, /setActiveRange/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-toolbar/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-range-button/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-range-menu/)
  assert.match(dashboardOverviewSource, /Active athletes/)
  assert.match(dashboardOverviewSource, /Programs assigned/)
  assert.match(dashboardOverviewSource, /Sessions this week/)
  assert.match(dashboardOverviewSource, /Compliance/)
  assert.match(dashboardOverviewSource, /Pending invites/)
  assert.match(dashboardOverviewSource, /value: '8'/)
  assert.match(dashboardOverviewSource, /value: '4'/)
  assert.match(dashboardOverviewSource, /value: '12'/)
  assert.match(dashboardOverviewSource, /value: '3'/)
  assert.match(dashboardOverviewSource, /change: '28\.4%'/)
  assert.match(dashboardOverviewSource, /change: '12\.6%'/)
  assert.match(dashboardOverviewSource, /change: '31%'/)
  assert.match(dashboardOverviewSource, /change: '11\.3%'/)
  assert.match(dashboardOverviewSource, /overviewPerformanceData/)
  assert.match(dashboardOverviewSource, /overviewComplianceData/)
  assert.match(dashboardOverviewSource, /overviewSessionTimeData/)
  assert.match(dashboardOverviewSource, /Sessions/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-performance-kicker-row/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-performance-kicker-icon/)
  assert.match(dashboardOverviewSource, /<Activity className="admin-shell-overview-performance-kicker-icon"/)
  assert.match(dashboardOverviewSource, /Completed/)
  assert.match(dashboardOverviewSource, /Assigned/)
  assert.match(dashboardOverviewSource, /overviewCompletedGradient/)
  assert.match(dashboardOverviewSource, /stopColor="rgba\(59, 224, 175, 0\.28\)"/)
  assert.match(dashboardOverviewSource, /stopColor="rgba\(59, 224, 175, 0\.02\)"/)
  assert.match(dashboardOverviewSource, /stroke="#3be0af"/)
  assert.match(dashboardOverviewSource, /stroke="#58c6ff"/)
  assert.match(dashboardOverviewSource, /fill="#3be0af"/)
  assert.match(dashboardOverviewSource, /className=\{isActive \? 'admin-shell-overview-chart-point-active' : 'admin-shell-overview-chart-point'\}/)
  assert.match(dashboardOverviewSource, /Overall compliance/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-insight-label-row/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-insight-label-icon/)
  assert.match(dashboardOverviewSource, /<BadgeCheck className="admin-shell-overview-insight-label-icon"/)
  assert.match(dashboardOverviewSource, /Sessions by time of the day/)
  assert.match(dashboardOverviewSource, /<Activity className="admin-shell-overview-insight-label-icon"/)
  assert.match(dashboardOverviewSource, /View report/)
  assert.match(dashboardOverviewSource, /Apr 22 - May 21, 2026/)
  assert.match(dashboardOverviewSource, /May 21, 2026/)
  assert.match(dashboardOverviewSource, /footer: 'Last month'/)
  assert.match(dashboardOverviewSource, /footer: 'Last year'/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-card-change-arrow-icon/)
  assert.match(dashboardOverviewSource, /function TrendArrowIcon/)
  assert.match(dashboardOverviewSource, /<ArrowDown className="admin-shell-overview-card-change-arrow-icon"/)
  assert.match(dashboardOverviewSource, /<ArrowUp className="admin-shell-overview-card-change-arrow-icon"/)
  assert.match(dashboardOverviewSource, /<TrendArrowIcon direction=\{card\.direction\} \/>/)
  assert.doesNotMatch(dashboardOverviewSource, /\{card\.direction === 'negative' \? '↓' : '↑'\}/)
  assert.doesNotMatch(dashboardOverviewSource, /\{data\.changeDirection === 'negative' \? '↓' : '↑'\}/)

  assert.match(adminNavigationSource, /href: '\/admin\/dashboard'/)
  assert.match(adminNavigationSource, /title: 'Overview'/)
  assert.match(adminNavigationSource, /description: 'Here is an overview of your platform\.'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/dashboard\/today'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/dashboard\/alerts'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/dashboard\/recent-activity'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Recent activity'/)
  assert.match(adminNavigationSource, /href: '\/admin\/athletes'/)
  assert.match(adminNavigationSource, /href: '\/admin\/programs'/)
  assert.match(adminNavigationSource, /href: '\/admin\/workouts'/)
  assert.match(adminNavigationSource, /href: '\/admin\/exercises'/)
  assert.match(adminNavigationSource, /href: '\/admin\/analytics'/)
  assert.match(adminNavigationSource, /href: '\/admin\/settings'/)
  assert.match(adminNavigationSource, /href: '\/admin\/athletes\/groups'/)
  assert.match(adminNavigationSource, /href: '\/admin\/programs\/templates'/)
  assert.match(adminNavigationSource, /href: '\/admin\/workouts\/sessions'/)
  assert.match(adminNavigationSource, /href: '\/admin\/analytics\/compliance'/)
  assert.match(adminNavigationSource, /href: '\/admin\/settings\/team'/)
  assert.match(adminNavigationSource, /defaultHref/)

  assert.match(sidebarSource, /from 'next\/link'/)
  assert.match(sidebarSource, /currentPath\s*=\s*''/)
  assert.match(sidebarSource, /href\s*=\s*''/)
  assert.match(sidebarSource, /<Link/)
  assert.match(sidebarSource, /ui-sidebar-group-button-current/)
  assert.match(sidebarSource, /ui-sidebar-subitem-current/)
  assert.match(sidebarSource, /const isExpanded = isActive && Boolean\(group\.items\?\.length\)/)
  assert.match(sidebarSource, /const showChevron = Boolean\(group\.items\?\.length\)/)
  assert.match(sidebarSource, /showChevron \?/)
  assert.doesNotMatch(sidebarSource, /const isExpanded = isActive\n/)
  assert.match(sidebarSource, /startsWith\(/)

  assert.match(cssSource, /\.ui-sidebar\s*\{[\s\S]*max-width:\s*236px;/)
  assert.match(cssSource, /\.ui-sidebar\s*\{[\s\S]*border-radius:\s*0;/)
  assert.match(cssSource, /\.ui-sidebar\s*\{[\s\S]*box-shadow:\s*none;/)
  assert.match(cssSource, /\.ui-sidebar\s*\{[\s\S]*border-right:\s*1px solid/)
  assert.match(cssSource, /\.ui-sidebar-layout\s*\{[\s\S]*gap:\s*0;/)
  assert.match(cssSource, /\.ui-sidebar-layout\s*\{[\s\S]*padding:\s*0;/)
  assert.match(cssSource, /\.ui-sidebar-search\s*\{[\s\S]*min-height:\s*36px;/)
  assert.match(cssSource, /\.ui-sidebar-group-button\s*\{[\s\S]*grid-template-columns:\s*auto 1fr auto;/)
  assert.match(cssSource, /\.ui-sidebar-subitem-current::before\s*\{[\s\S]*width:\s*2px;/)
  assert.match(cssSource, /\.admin-shell-workspace\s*\{[\s\S]*min-height:\s*calc\(100vh - 16px\);/)
  assert.match(cssSource, /\.admin-shell-workspace-title\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-overview-range-button\s*\{[\s\S]*border-radius:\s*999px;/)
  assert.match(cssSource, /\.admin-shell-overview-range-menu\s*\{[\s\S]*position:\s*absolute;/)
  assert.match(cssSource, /\.admin-shell-overview-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(5, minmax\(0, 1fr\)\);/)
  assert.match(cssSource, /\.admin-shell-overview-card-header\s*\{[\s\S]*display:\s*flex;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value-row\s*\{[\s\S]*align-items:\s*center;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value-row\s*\{[\s\S]*justify-content:\s*flex-start;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-card-icon-shell\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-card\s*\{[^}]*min-height:/)
  assert.match(cssSource, /\.admin-shell-overview-card\s*\{[\s\S]*align-content:\s*start;/)
  assert.match(cssSource, /\.admin-shell-overview-card\s*\{[\s\S]*gap:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-card\s*\{[\s\S]*border-radius:\s*24px;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value\s*\{[\s\S]*font-size:\s*2\.1rem;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-card-change-negative\s*\{[\s\S]*color:\s*#ff8d8d;/)
  assert.match(cssSource, /\.admin-shell-overview-card-change-arrow-icon\s*\{[\s\S]*width:\s*0\.82rem;/)
  assert.match(cssSource, /\.admin-shell-overview-analytics-layout\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 1\.75fr\) minmax\(280px, 0\.92fr\);/)
  assert.match(cssSource, /\.admin-shell-overview-performance-panel\s*\{[\s\S]*padding:\s*26px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-kicker-row\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-kicker-icon\s*\{[\s\S]*width:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-kicker-icon\s*\{[\s\S]*height:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-value\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-chart\s*\{[\s\S]*min-height:\s*320px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-meta\s*\{[\s\S]*display:\s*flex;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-meta\s*\{[\s\S]*justify-items:\s*flex-start;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-meta\s*\{[\s\S]*gap:\s*8px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-legend\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-legend-dot-completed\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-legend-dot-assigned\s*\{[\s\S]*background:\s*#58c6ff;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-tooltip\s*\{[\s\S]*position:\s*absolute;/)
  assert.match(cssSource, /\.admin-shell-overview-side-column\s*\{[\s\S]*grid-template-rows:\s*repeat\(2, minmax\(0, 1fr\)\);/)
  assert.match(cssSource, /\.admin-shell-overview-insight-card\s*\{[\s\S]*min-height:\s*198px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-row\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-row\s*\{[\s\S]*align-items:\s*center;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-icon\s*\{[\s\S]*width:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-icon\s*\{[\s\S]*height:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-value\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bars\s*\{[\s\S]*align-items:\s*end;/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bar-completed\s*\{[\s\S]*rgba\(59, 224, 175, 0\.96\)[\s\S]*rgba\(31, 176, 135, 0\.72\)/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bar-assigned\s*\{[\s\S]*rgba\(88, 198, 255, 0\.96\)[\s\S]*rgba\(58, 154, 232, 0\.72\)/)
  assert.match(cssSource, /\.admin-shell-overview-session-chart\s*\{[\s\S]*min-height:\s*132px;/)
  assert.match(cssSource, /\.admin-shell-overview-chart-point\s*\{[\s\S]*fill:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-overview-chart-point-active\s*\{[\s\S]*fill:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-overview-chart-point-active\s*\{[\s\S]*stroke:\s*#f5f8ff;/)
  assert.match(cssSource, /\.admin-shell-workspace-panel\s*\{[\s\S]*width:\s*min\(100%, 520px\);/)

  assert.match(rulesetSource, /reference standard UI kit/i)
  assert.match(rulesetSource, /components\/ui/i)
})
