import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const repoRoot = resolve(import.meta.dirname, '..')
const dashboardOverviewPath = resolve(repoRoot, 'apps/web/components/admin/dashboard-overview.jsx')
const calendarHeatmapPath = resolve(repoRoot, 'apps/web/components/ui/calendar-heatmap.jsx')

test('dashboard overview fetches real v2 coach overview API data instead of hardcoded KPI mocks', () => {
  const source = readFileSync(dashboardOverviewPath, 'utf8')
  const calendarHeatmapSource = readFileSync(calendarHeatmapPath, 'utf8')

  assert.match(source, /fetch\(`\/api\/admin\/dashboard\/overview\?range=\$\{activeRange\}`/)
  assert.match(source, /setOverview\(payload\.overview/)
  assert.match(source, /setLoading\(true\)/)
  assert.match(source, /setError\(/)
  assert.match(source, /Dashboard overview loading/)
  assert.match(source, /Dashboard overview error/)
  assert.match(source, /No dashboard data yet/)
  assert.match(source, /const cards = buildSummaryCards\(overview\?\.summary\)/)
  assert.match(source, /athletes/)
  assert.match(source, /programs/)
  assert.match(source, /workouts/)
  assert.match(source, /exercises/)
  assert.match(source, /invites/)
  assert.doesNotMatch(source, /dueWorkouts/)
  assert.doesNotMatch(source, /planAdherence/)
  assert.doesNotMatch(source, /needsAttention/)
  assert.match(source, /trainingExecution=\{overview\?\.trainingExecution\}/)
  assert.match(source, /workoutResults=\{overview\?\.workoutResults\}/)
  assert.match(source, /trainingConsistency=\{overview\?\.trainingConsistency\}/)
  assert.match(source, /CalendarHeatmap/)
  assert.match(source, /const heatmapDates = buildTrainingConsistencyWeightedDates\(trainingConsistency\?\.dailyActivity\)/)
  assert.match(source, /weightedDates=\{heatmapDates\}/)
  assert.match(source, /variantClassnames=\{trainingConsistencyHeatmapVariants\}/)
  assert.match(source, /numberOfMonths=\{1\}/)
  assert.match(source, /Monthly activity heatmap/)
  assert.match(source, /Use the arrows to review previous months\./)
  assert.match(source, /WorkoutResultsPanel/)
  assert.match(source, /BarChart/)
  assert.match(source, /<BarChart\s+accessibilityLayer\s+data=\{chartData\}/)
  assert.doesNotMatch(source, /layout="vertical"/)
  assert.match(source, /XAxis[\s\S]*dataKey="workoutName"[\s\S]*tickLine=\{false\}[\s\S]*tickMargin=\{10\}[\s\S]*axisLine=\{false\}/)
  assert.match(source, /YAxis[\s\S]*tickLine=\{false\}[\s\S]*axisLine=\{false\}[\s\S]*tickMargin=\{8\}/)
  assert.match(source, /const workoutResultsChartHeight = 320/)
  assert.match(source, /Card className="admin-shell-overview-insight-card admin-shell-overview-workout-results-card"/)
  assert.match(source, /CardContent className="admin-shell-overview-workout-results-content"/)
  assert.match(source, /style=\{\{ height: workoutResultsChartHeight, minHeight: workoutResultsChartHeight \}\}/)
  assert.match(source, /ChartTooltipContent indicator="dashed"/)
  assert.match(source, /<Bar dataKey="assigned" fill="var\(--color-assigned\)" radius=\{4\} \/>/)
  assert.match(source, /<Bar dataKey="completed" fill="var\(--color-completed\)" radius=\{4\} \/>/)
  assert.match(source, /<Bar dataKey="missed" fill="var\(--color-missed\)" radius=\{4\} \/>/)
  assert.doesNotMatch(source, /Bar dataKey="value"/)
  assert.doesNotMatch(source, /workoutResultStatusOptions/)
  assert.match(source, /workoutResultCategoryOptions/)
  assert.match(source, /Category/)
  assert.doesNotMatch(source, /aria-label="Status"/)
  assert.match(source, /Assigned/)
  assert.match(source, /Completed/)
  assert.match(source, /Missed/)
  assert.match(source, /Warmup/)
  assert.match(source, /Speed Accelerator/)
  assert.match(source, /Edge Work/)
  assert.match(source, /Conditioning/)
  assert.match(source, /disabled=\{false\}/)
  assert.match(calendarHeatmapSource, /disabled:\s*'opacity-100'/)
  assert.match(calendarHeatmapSource, /day_button:[\s\S]*text-\[var\(--admin-dashboard-card-text\)\]/)
  assert.doesNotMatch(source, /disabled\s*$/m)
  assert.match(source, /Training execution/)
  assert.match(source, /Training consistency/)
  assert.match(calendarHeatmapSource, /navLayout="around"/)
  assert.match(calendarHeatmapSource, /month:\s*'relative space-y-3/)
  assert.match(calendarHeatmapSource, /button_previous:[\s\S]*absolute left-3 top-3/)
  assert.match(calendarHeatmapSource, /button_next:[\s\S]*absolute right-3 top-3/)
  assert.doesNotMatch(calendarHeatmapSource, /nav:\s*'absolute inset-x-0 top-0 flex items-center justify-between'/)
  assert.doesNotMatch(source, /const overviewRangeCardData = \{/)
  assert.doesNotMatch(source, /value: '148'/)
  assert.doesNotMatch(source, /Daily adherence meets projections/)
  assert.doesNotMatch(source, /Sessions by time of the day/)
  assert.doesNotMatch(source, /RadarChart/)
})
