import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const programsDataTablePath = resolve(repoRoot, 'apps/web/components/admin/programs-data-table.jsx')
const adminProgramRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-program-repository.js')

test('programs library surface uses admin light-mode tokens instead of dark-coded colors', () => {
  const programsSource = readFileSync(programsDataTablePath, 'utf8')
  const repositorySource = readFileSync(adminProgramRepositoryPath, 'utf8')

  assert.match(programsSource, /const programFilterRangeInputClassName =/)
  assert.match(programsSource, /const programFilterRangeSeparatorClassName =/)
  assert.match(programsSource, /className=\{programFilterRangeInputClassName\}/)
  assert.match(programsSource, /className=\{programFilterRangeSeparatorClassName\}/)
  assert.match(programsSource, /admin-shell-athletes-filter-trigger/)
  assert.match(programsSource, /admin-shell-athletes-pagination-bar/)
  assert.match(programsSource, /admin-shell-athletes-empty-state/)
  assert.match(programsSource, /className="grid gap-5 admin-shell-athletes-create-tabs"/)
  assert.match(programsSource, /<TabsList className="admin-shell-program-dialog-tabs-list">/)
  assert.match(programsSource, /<TabsTrigger value="details" className="admin-shell-program-dialog-tabs-trigger">Details<\/TabsTrigger>/)
  assert.match(programsSource, /<TabsTrigger value="athletes" className="admin-shell-program-dialog-tabs-trigger">Athletes<\/TabsTrigger>/)
  assert.match(programsSource, /admin-shell-athletes-status-badge admin-shell-athletes-status-badge-active/)
  assert.match(programsSource, /admin-shell-athletes-status-badge admin-shell-athletes-status-badge-inactive/)
  assert.match(programsSource, /admin-shell-athletes-status-badge admin-shell-athletes-status-badge-pending/)
  assert.match(programsSource, /admin-shell-athletes-example-pagination-button-active/)
  assert.match(programsSource, /Assign athletes to this program\./)
  assert.match(programsSource, /handleToggleProgramAthlete/)
  assert.match(programsSource, /\{ value: 'unassigned', label: 'Unassigned' \}/)
  assert.match(repositorySource, /function formatProgramTypeLabel\(row\)/)
  assert.match(repositorySource, /row\?\.athlete_id \? 'Assigned' : 'Unassigned'/)

  assert.doesNotMatch(programsSource, /bg-\[#111D30\]|bg-\[#0F1728\]|bg-\[#15233A\]/)
  assert.doesNotMatch(programsSource, /border-\[#24334A\]|!border-\[#24334A\]/)
  assert.doesNotMatch(programsSource, /text-\[#DCE6F8\]|text-\[#EEF4FF\]|text-\[#8EA0BC\]|text-\[#70809E\]/)
  assert.doesNotMatch(programsSource, /hover:bg-\[#15233A\]|hover:text-\[#EEF4FF\]/)
  assert.doesNotMatch(programsSource, /className="h-9 w-\[76px\] rounded-\[10px\] !border-\[#24334A\] bg-\[#111D30\]/)
  assert.doesNotMatch(programsSource, /className="h-24 text-center text-\[#8EA0BC\]"/)
  assert.doesNotMatch(programsSource, /<DropdownMenuItem>Assign<\/DropdownMenuItem>/)
  assert.doesNotMatch(programsSource, /<DropdownMenuItem>Archive<\/DropdownMenuItem>/)
  assert.match(programsSource, /\[\.\.\.currentAthleteIds, nextAthleteId\]/)
})

test('programs library row action dropdown matches requested action order and handoffs', () => {
  const programsSource = readFileSync(programsDataTablePath, 'utf8')

  assert.match(programsSource, /function RowActionsCell\([\s\S]*onDuplicateAction = \(\) => \{\},[\s\S]*onAssignAction = \(\) => \{\},[\s\S]*onExportAction = \(\) => \{\},[\s\S]*onArchiveAction = \(\) => \{\},[\s\S]*onDeleteAction = \(\) => \{\},/)
  assert.match(programsSource, /<DropdownMenuContent align="end" className="min-w-\[190px\]">[\s\S]*Duplicate[\s\S]*Assign to athletes[\s\S]*Export[\s\S]*<DropdownMenuSeparator \/>[\s\S]*Archive[\s\S]*Delete/)
  assert.match(programsSource, /<DropdownMenu open=\{isBulkActionsMenuOpen\} onOpenChange=\{handleBulkActionsMenuOpenChange\}>[\s\S]*Bulk actions[\s\S]*Duplicate[\s\S]*Assign to athletes[\s\S]*Export[\s\S]*<DropdownMenuSeparator \/>[\s\S]*Archive[\s\S]*Delete/)
  assert.match(programsSource, /disabled=\{selectedProgramCount === 0\}/)
  assert.match(programsSource, /selectedProgramCount > 0 \? `Bulk actions \(\$\{selectedProgramCount\}\)` : 'Bulk actions'/)
  assert.match(programsSource, /disabled=\{selectedProgramCount !== 1\}[\s\S]*handleDuplicateSelectedProgram/)
  assert.match(programsSource, /disabled=\{selectedProgramCount !== 1\}[\s\S]*handleAssignSelectedProgram/)
  assert.match(programsSource, /handleExportSelectedPrograms/)
  assert.match(programsSource, /handleOpenArchiveSelectedProgramsDialog/)
  assert.match(programsSource, /handleOpenDeleteSelectedProgramsDialog/)
  assert.match(programsSource, /onDuplicateAction=\{\(\) => setPendingRowAction\(\{ type: 'duplicate', programId: row\.original\.id \}\)\}/)
  assert.match(programsSource, /onAssignAction=\{\(\) => setPendingRowAction\(\{ type: 'assign', programId: row\.original\.id \}\)\}/)
  assert.match(programsSource, /onExportAction=\{\(\) => setPendingRowAction\(\{ type: 'export', programId: row\.original\.id \}\)\}/)
  assert.match(programsSource, /onArchiveAction=\{\(\) => setPendingRowAction\(\{ type: 'archive', programId: row\.original\.id \}\)\}/)
  assert.match(programsSource, /if \(pendingRowAction\.type === 'assign'\) \{[\s\S]*openAssignProgramDialog\(pendingRowAction\.programId\)/)
  assert.match(programsSource, /if \(pendingRowAction\.type === 'duplicate'\) \{[\s\S]*openDuplicateProgramDialog\(pendingRowAction\.programId\)/)
  assert.match(programsSource, /if \(pendingRowAction\.type === 'export'\) \{[\s\S]*openExportProgramSheet\(\[pendingRowAction\.programId\]\)/)
  assert.match(programsSource, /if \(pendingRowAction\.type === 'archive'\) \{[\s\S]*setSelectedArchiveProgramIds\(\[pendingRowAction\.programId\]\)[\s\S]*setIsArchiveProgramDialogOpen\(true\)/)
})

test('programs library archive action is confirmed and persisted through the admin route', () => {
  const programsSource = readFileSync(programsDataTablePath, 'utf8')
  const routeSource = readFileSync(resolve(repoRoot, 'apps/web/app/api/admin/programs/route.js'), 'utf8')
  const repositorySource = readFileSync(adminProgramRepositoryPath, 'utf8')

  assert.match(programsSource, /const \[isArchiveProgramDialogOpen, setIsArchiveProgramDialogOpen\] = useState\(false\)/)
  assert.match(programsSource, /const archiveProgramsToReview = useMemo\(\(\) => programs\.filter\(\(program\) => selectedArchiveProgramIds\.includes\(program\.id\)\)/)
  assert.match(programsSource, /const archiveEligiblePrograms = archiveProgramsToReview\.filter\(\(program\) => normalizeProgramFilterValue\(program\.statusValue \|\| program\.status\) !== 'archived'\)/)
  assert.match(programsSource, /const archiveSkippedPrograms = archiveProgramsToReview\.filter\(\(program\) => normalizeProgramFilterValue\(program\.statusValue \|\| program\.status\) === 'archived'\)/)
  assert.match(programsSource, /async function handleArchiveProgram\(\) \{[\s\S]*const programIdsToArchive = archiveEligiblePrograms\.map\(\(program\) => program\.id\)\.filter\(Boolean\)[\s\S]*method: 'PATCH'[\s\S]*body: JSON\.stringify\(\{ action: 'archive-programs', programIds: programIdsToArchive \}\)/)
  assert.doesNotMatch(programsSource, /for \(const programId of programIdsToArchive\)[\s\S]*body: JSON\.stringify\(\{ id: programId, action: 'archive' \}\)/)
  assert.match(programsSource, /result\?\.archivedPrograms[\s\S]*result\?\.skippedPrograms[\s\S]*setPrograms\(\(current\) => current\.map\(\(program\) => archivedProgramMap\.get\(program\.id\) \?\? program\)\)/)
  assert.match(programsSource, /<DialogContent className="admin-shell-programs-archive-dialog border border-\[var\(--admin-dashboard-card-border\)\] bg-\[var\(--admin-dashboard-card-bg\)\] text-\[var\(--admin-dashboard-card-text\)\] sm:max-w-\[560px\]">[\s\S]*<DialogTitle>Archive programs<\/DialogTitle>[\s\S]*Review the selected programs before moving them out of active workflows\./)
  assert.match(programsSource, /admin-shell-programs-archive-summary[\s\S]*\{archiveEligiblePrograms\.length\} program\{archiveEligiblePrograms\.length === 1 \? '' : 's'\} will be archived[\s\S]*Archived programs are hidden from active program workflows but stay available for records\./)
  assert.match(programsSource, /Ready to archive[\s\S]*archiveEligiblePrograms\.map\(\(program\) =>[\s\S]*\{program\.name\}[\s\S]*\{program\.athletesLabel\}[\s\S]*<StatusCell status=\{program\.status\} \/>/)
  assert.match(programsSource, /Already archived[\s\S]*archiveSkippedPrograms\.map\(\(program\) =>[\s\S]*Already archived[\s\S]*<StatusCell status=\{program\.status\} \/>/)
  assert.match(programsSource, /disabled=\{archiveEligiblePrograms\.length === 0 \|\| isArchivingProgram\}[\s\S]*\{isArchivingProgram \? 'Archiving\.\.\.' : `Archive \$\{archiveEligiblePrograms\.length\} program\$\{archiveEligiblePrograms\.length === 1 \? '' : 's'\}`\}/)
  assert.match(routeSource, /if \(payload\?\.action === 'archive-programs'\) \{[\s\S]*repository\.archivePrograms\(\{ programIds: payload\?\.programIds \}\)[\s\S]*return json\(\{ archivedPrograms, skippedPrograms \}\)/)
  assert.match(repositorySource, /async archivePrograms\(\{ programIds = \[\] \}\) \{[\s\S]*normalizeProgramIds\(programIds\)[\s\S]*requestTable\('programs', `\?select=id,status&id=in\.\(\$\{inFilter\(normalizedProgramIds\)\}\)`\)[\s\S]*const eligibleProgramIds = programRows\.filter[\s\S]*status: 'archived'[\s\S]*return \{ archivedPrograms, skippedPrograms \}/)
  assert.match(repositorySource, /async archiveProgram\(programId\) \{[\s\S]*const result = await this\.archivePrograms\(\{ programIds: \[programId\] \}\)/)
})

test('programs library duplicate workflow has a dedicated sheet and persisted duplicate route', () => {
  const programsSource = readFileSync(programsDataTablePath, 'utf8')
  const routeSource = readFileSync(resolve(repoRoot, 'apps/web/app/api/admin/programs/route.js'), 'utf8')
  const repositorySource = readFileSync(adminProgramRepositoryPath, 'utf8')

  assert.match(programsSource, /const \[duplicateCopyOptions, setDuplicateCopyOptions\] = useState\(createDuplicateCopyOptions\(\)\)/)
  assert.match(programsSource, /const duplicateSourceProgram = useMemo\(\(\) => programs\.find\(\(program\) => program\.id === selectedDuplicateSourceProgramId\)/)
  assert.match(programsSource, /function openDuplicateProgramDialog\(programId\) \{[\s\S]*setSelectedDuplicateSourceProgramId\(programId\)[\s\S]*setProgramFormValues\(\{[\s\S]*athleteIds: \[\],[\s\S]*name: `\$\{selectedProgram\.name\} copy`/)
  assert.match(programsSource, /<SheetTitle>\{programDialogMode === 'edit' \? 'Edit program' : programDialogMode === 'duplicate' \? 'Duplicate program' : programDialogMode === 'assign' \? 'Assign to athletes' : 'Create a program'\}<\/SheetTitle>/)
  assert.match(programsSource, /Create a copy of this program and choose which program content should carry over\./)
  assert.match(programsSource, /admin-shell-programs-duplicate-source-card[\s\S]*Source program[\s\S]*\{duplicateSourceProgram\.name\}[\s\S]*\{duplicateSourceProgram\.duration\}[\s\S]*\{duplicateSourceProgram\.workouts\} workouts[\s\S]*\{duplicateSourceProgram\.exercises\} exercises/)
  assert.match(programsSource, /Copy from original[\s\S]*Program details[\s\S]*Assigned athletes[\s\S]*Workout schedule[\s\S]*Workout exercises and sets[\s\S]*Notes \/ descriptions/)
  assert.match(programsSource, /Exercise history and completed sessions are never copied\./)
  assert.match(programsSource, /body: JSON\.stringify\(isDuplicatingProgram[\s\S]*\{ action: 'duplicate', sourceProgramId: selectedDuplicateSourceProgramId, copyOptions: duplicateCopyOptions, \.\.\.payload \}/)
  assert.match(programsSource, /title: isEditingProgram \? 'Program updated' : isAssigningProgram \? 'Program assignments updated' : isDuplicatingProgram \? 'Program duplicated' : 'Program created'/)
  assert.match(routeSource, /if \(payload\?\.action === 'duplicate'\) \{[\s\S]*repository\.duplicateProgram\(\{[\s\S]*sourceProgramId: payload\?\.sourceProgramId,[\s\S]*copyOptions: payload\?\.copyOptions/)
  assert.match(repositorySource, /async duplicateProgram\(\{ sourceProgramId, athleteIds = \[\], name, startDate = '', endDate = '', description = '', copyOptions = \{\} \}\) \{[\s\S]*cloneProgramPlanningTree\(\{ sourceProgramId, targetProgramId: createdProgramId, copyOptions: resolvedCopyOptions \}\)/)
  assert.match(repositorySource, /async function cloneProgramPlanningTree\(\{ sourceProgramId, targetProgramId, copyOptions = \{\} \}\)/)
})

test('programs library assign-to-athletes action has a dedicated assignment sheet design and persisted workflow', () => {
  const programsSource = readFileSync(programsDataTablePath, 'utf8')
  const routeSource = readFileSync(resolve(repoRoot, 'apps/web/app/api/admin/programs/route.js'), 'utf8')
  const repositorySource = readFileSync(adminProgramRepositoryPath, 'utf8')

  assert.match(programsSource, /function openAssignProgramDialog\(programId\) \{[\s\S]*setProgramDialogMode\('assign'\)[\s\S]*setActiveProgramDialogTab\('athletes'\)[\s\S]*setSelectedProgramId\(programId\)/)
  assert.match(programsSource, /const assignSourceProgram = programDialogMode === 'assign' \? selectedProgram : null/)
  assert.match(programsSource, /<SheetTitle>\{programDialogMode === 'edit' \? 'Edit program' : programDialogMode === 'duplicate' \? 'Duplicate program' : programDialogMode === 'assign' \? 'Assign to athletes' : 'Create a program'\}<\/SheetTitle>/)
  assert.match(programsSource, /Choose which athletes should receive this program\./)
  assert.match(programsSource, /admin-shell-programs-assign-source-card[\s\S]*Program to assign[\s\S]*\{assignSourceProgram\.name\}[\s\S]*\{assignSourceProgram\.duration\}[\s\S]*\{assignSourceProgram\.workouts\} workouts[\s\S]*\{assignSourceProgram\.exercises\} exercises/)
  assert.match(programsSource, /admin-shell-programs-assignment-summary[\s\S]*Selected athletes[\s\S]*\{programFormValues\.athleteIds\.length\}[\s\S]*Available athletes[\s\S]*\{athleteOptions\.length\}/)
  assert.doesNotMatch(programsSource, /Assignment changes save to this program when you click Save assignments\./)
  assert.doesNotMatch(programsSource, /Current: \{assignSourceProgram\.athletesLabel\}/)
  assert.match(programsSource, /const isAssigningProgram = programDialogMode === 'assign'/)
  assert.match(programsSource, /method: isEditingProgram \|\| isAssigningProgram \? 'PATCH' : 'POST'/)
  assert.match(programsSource, /body: JSON\.stringify\(isDuplicatingProgram[\s\S]*: isAssigningProgram[\s\S]*\{ action: 'assign-athletes', id: selectedProgramId, athleteIds: programFormValues\.athleteIds \}/)
  assert.match(programsSource, /programDialogMode === 'assign' \? 'Assign athletes'/)
  assert.match(programsSource, /program\.assignedAthleteIds[\s\S]*program\.athleteIds/)
  assert.match(routeSource, /if \(payload\?\.action === 'assign-athletes'\) \{[\s\S]*repository\.assignProgramToAthletes\(\{[\s\S]*programId: payload\?\.id,[\s\S]*athleteIds: payload\?\.athleteIds/)
  assert.match(repositorySource, /function createProgramAssignmentGroupKey\(row = \{\}\)/)
  assert.match(repositorySource, /assignedAthleteIds/)
  assert.match(repositorySource, /async assignProgramToAthletes\(\{ programId, athleteIds = \[\] \}\)/)
  assert.match(repositorySource, /cloneProgramPlanningTree\(\{[\s\S]*sourceProgramId: programId,[\s\S]*targetProgramId: createdProgram\.id,[\s\S]*copyOptions: \{ schedule: true, exercises: true, notes: true \}/)
  assert.match(repositorySource, /patchTable\('program_workouts', `\?program_id=eq\.\$\{encodeURIComponent\(programId\)\}`,[\s\S]*athlete_id: primaryAthleteId/)
})

test('programs library export action opens a dedicated non-mutating export sheet', () => {
  const programsSource = readFileSync(programsDataTablePath, 'utf8')

  assert.match(programsSource, /from '@\/lib\/admin-programs-export'/)
  assert.match(programsSource, /const \[isExportProgramSheetOpen, setIsExportProgramSheetOpen\] = useState\(false\)/)
  assert.match(programsSource, /const \[selectedExportProgramIds, setSelectedExportProgramIds\] = useState\(\[\]\)/)
  assert.match(programsSource, /const exportProgramsToReview = useMemo\(\(\) => programs\.filter\(\(program\) => selectedExportProgramIds\.includes\(program\.id\)\)/)
  assert.match(programsSource, /function openExportProgramSheet\(programIds\) \{[\s\S]*setSelectedExportProgramIds\(nextProgramIds\)[\s\S]*setIsExportProgramSheetOpen\(true\)/)
  assert.match(programsSource, /if \(pendingRowAction\.type === 'export'\) \{[\s\S]*openExportProgramSheet\(\[pendingRowAction\.programId\]\)/)
  assert.match(programsSource, /function handleExportSelectedPrograms\(\) \{[\s\S]*openExportProgramSheet\(selectedProgramIds\)/)
  assert.match(programsSource, /<Sheet open=\{isExportProgramSheetOpen\} onOpenChange=\{setIsExportProgramSheetOpen\}>[\s\S]*className="admin-shell-programs-export-sheet border-l border-\[color:var\(--admin-dashboard-card-border\)\] bg-\[var\(--admin-dashboard-card-bg\)\] p-0 text-\[var\(--admin-dashboard-card-text\)\] !max-w-\[var\(--container-lg\)\]"/)
  assert.match(programsSource, /<SheetTitle>Export programs<\/SheetTitle>[\s\S]*Review the selected programs before downloading a CSV export\./)
  assert.match(programsSource, /admin-shell-programs-export-summary[\s\S]*Selected programs[\s\S]*\{exportProgramsToReview\.length\}[\s\S]*Format[\s\S]*CSV[\s\S]*Filename[\s\S]*\{exportProgramsFileName\}/)
  assert.match(programsSource, /Included columns[\s\S]*<div className="grid grid-cols-1 gap-2 sm:grid-cols-2">[\s\S]*programExportColumns\.map\(\(column\) =>/)
  assert.match(programsSource, /Selected program preview[\s\S]*<div className="grid max-h-\[360px\] gap-2 overflow-y-auto pr-1 \[scrollbar-width:none\] \[-ms-overflow-style:none\] \[&::-webkit-scrollbar\]:hidden">[\s\S]*exportProgramsToReview\.map\(\(program\) =>/)
  assert.match(programsSource, /onClick=\{handleConfirmExportPrograms\}[\s\S]*Download CSV/)
  assert.doesNotMatch(programsSource, /function exportProgram\(programId\) \{[\s\S]*exportPrograms\(selectedProgram \? \[selectedProgram\] : \[\]\)/)
})

test('programs library delete bulk action is confirmed and persisted through one admin route workflow', () => {
  const programsSource = readFileSync(programsDataTablePath, 'utf8')
  const routeSource = readFileSync(resolve(repoRoot, 'apps/web/app/api/admin/programs/route.js'), 'utf8')
  const repositorySource = readFileSync(adminProgramRepositoryPath, 'utf8')

  assert.match(programsSource, /const \[isDeleteProgramDialogOpen, setIsDeleteProgramDialogOpen\] = useState\(false\)/)
  assert.match(programsSource, /const deleteProgramsToReview = useMemo\(\(\) => programs\.filter\(\(program\) => selectedDeleteProgramIds\.includes\(program\.id\)\)/)
  assert.match(programsSource, /const deleteProgramCount = deleteProgramsToReview\.length/)
  assert.match(programsSource, /function handleOpenDeleteSelectedProgramsDialog\(\) \{[\s\S]*setSelectedDeleteProgramIds\(selectedProgramIds\)[\s\S]*setIsDeleteProgramDialogOpen\(true\)/)
  assert.match(programsSource, /if \(pendingRowAction\.type === 'delete'\) \{[\s\S]*setSelectedDeleteProgramIds\(\[pendingRowAction\.programId\]\)[\s\S]*setIsDeleteProgramDialogOpen\(true\)/)
  assert.match(programsSource, /async function handleDeleteProgram\(\) \{[\s\S]*const programIdsToDelete = deleteProgramsToReview\.map\(\(program\) => program\.id\)\.filter\(Boolean\)[\s\S]*method: 'DELETE'[\s\S]*body: JSON\.stringify\(\{ action: 'delete-programs', programIds: programIdsToDelete \}\)/)
  assert.doesNotMatch(programsSource, /for \(const programId of programIdsToDelete\)[\s\S]*body: JSON\.stringify\(\{ id: programId \}\)/)
  assert.match(programsSource, /result\?\.deletedPrograms[\s\S]*const deletedProgramIds = deletedPrograms\.map\(\(program\) => program\.id\)\.filter\(Boolean\)[\s\S]*setPrograms\(\(current\) => current\.filter\(\(program\) => !deletedProgramIds\.includes\(program\.id\)\)\)/)
  assert.match(programsSource, /<Dialog open=\{isDeleteProgramDialogOpen\} onOpenChange=\{setIsDeleteProgramDialogOpen\}>[\s\S]*<DialogContent className="admin-shell-programs-delete-dialog border border-\[var\(--admin-dashboard-card-border\)\] bg-\[var\(--admin-dashboard-card-bg\)\] text-\[var\(--admin-dashboard-card-text\)\] sm:max-w-\[440px\]">/)
  assert.match(programsSource, /<DialogTitle>\{deleteProgramCount === 1 \? 'Delete program' : 'Delete programs'\}<\/DialogTitle>[\s\S]*This action cannot be undone\./)
  assert.match(programsSource, /admin-shell-programs-delete-summary[\s\S]*<Trash2 className="size-5" aria-hidden="true" \/>[\s\S]*\{deleteProgramCount\} program\{deleteProgramCount === 1 \? '' : 's'\} will be permanently deleted[\s\S]*Deleting programs removes them from the program library and cannot be reversed\./)
  assert.match(programsSource, /Programs selected[\s\S]*deleteProgramsToReview\.slice\(0, 3\)\.map\(\(program\) =>[\s\S]*\{program\.name\}[\s\S]*\{program\.athletesLabel\}[\s\S]*<StatusCell status=\{program\.status\} \/>/)
  assert.match(programsSource, /deleteProgramCount > 3 \? \([\s\S]*\+ \{deleteProgramCount - 3\} more/)
  assert.match(programsSource, /<DialogFooter className="sm:flex-row sm:justify-end gap-3">[\s\S]*rounded-\[12px\] min-h-\[40px\][\s\S]*\{isDeletingProgram \? 'Deleting\.\.\.' : deleteProgramCount === 1 \? 'Delete program' : `Delete \$\{deleteProgramCount\} programs`\}/)
  assert.doesNotMatch(programsSource, /<DialogContent[^>]*admin-shell-programs-delete-dialog[^>]*sm:max-w-\[560px\]/)
  assert.doesNotMatch(programsSource, /admin-shell-programs-delete-dialog[\s\S]*<DialogFooter className="[^"]*border-t/)
  assert.doesNotMatch(programsSource, /<Sheet open=\{isDeleteProgramDialogOpen\}/)
  assert.match(routeSource, /if \(payload\?\.action === 'delete-programs'\) \{[\s\S]*repository\.deletePrograms\(\{ programIds: payload\?\.programIds \}\)[\s\S]*return json\(\{ deletedPrograms \}\)/)
  assert.match(routeSource, /repository\.deleteProgram\(payload\?\.id\)/)
  assert.match(repositorySource, /async deletePrograms\(\{ programIds = \[\] \}\) \{[\s\S]*normalizeProgramIds\(programIds\)[\s\S]*At least one program id is required\.[\s\S]*requestTable\('programs', `\?select=id&id=in\.\(\$\{inFilter\(normalizedProgramIds\)\}\)`\)[\s\S]*deleteTable\('programs', `\?id=in\.\(\$\{inFilter\(normalizedProgramIds\)\}\)`\)[\s\S]*return \{ deletedPrograms \}/)
  assert.match(repositorySource, /async deleteProgram\(programId\) \{[\s\S]*const result = await this\.deletePrograms\(\{ programIds: \[programId\] \}\)[\s\S]*return result\.deletedPrograms\[0\]/)
})

test('programs library controls keep the same dropdown row positioning as the other admin tables', () => {
  const programsSource = readFileSync(programsDataTablePath, 'utf8')

  const controlsMatch = programsSource.match(/<div className="flex flex-col gap-3">[\s\S]*?\n      \{programToast \? \(/)?.[0] ?? ''
  assert.ok(controlsMatch.includes('<div className="flex flex-col gap-3">'))
  assert.match(controlsMatch, /<div className="flex w-full flex-wrap items-start justify-between gap-3">[\s\S]*<div className="flex min-w-0 flex-1 flex-wrap items-center justify-start gap-2">[\s\S]*<Filters[\s\S]*Add filter[\s\S]*<div className="flex shrink-0 items-center justify-end gap-3">[\s\S]*<DropdownMenu>[\s\S]*Columns[\s\S]*Create a program/)
  assert.doesNotMatch(controlsMatch, /<div className="grid gap-3">/)
  assert.doesNotMatch(controlsMatch, /<div className="flex w-full items-center justify-between gap-3">[\s\S]*Columns[\s\S]*Create a program[\s\S]*<Filters/)
})
