import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const groupsListViewPath = resolve(repoRoot, 'apps/web/components/admin/groups-list-view.jsx')
const groupsDataTablePath = resolve(repoRoot, 'apps/web/components/admin/groups-data-table.jsx')
const adminGroupsRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/groups/route.js')
const adminGroupRouteHandlersPath = resolve(repoRoot, 'apps/web/lib/admin-group-route-handlers.js')
const adminGroupRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-group-repository.js')
const schemaDocPath = resolve(repoRoot, 'docs/schema-v1.md')
const schemaSqlPath = resolve(repoRoot, 'infra/supabase/schema-v1.sql')
const initialMigrationPath = resolve(repoRoot, 'infra/supabase/migrations/0001_initial_schema.sql')

test('groups admin supports real create, membership sync, and archive seams', () => {
  for (const path of [
    groupsListViewPath,
    groupsDataTablePath,
    adminGroupsRoutePath,
    adminGroupRouteHandlersPath,
    adminGroupRepositoryPath,
    schemaDocPath,
    schemaSqlPath,
    initialMigrationPath,
  ]) {
    assert.ok(existsSync(path), `expected groups admin file to exist: ${path}`)
  }

  const groupsListViewSource = readFileSync(groupsListViewPath, 'utf8')
  const groupsDataTableSource = readFileSync(groupsDataTablePath, 'utf8')
  const adminGroupsRouteSource = readFileSync(adminGroupsRoutePath, 'utf8')
  const adminGroupRouteHandlersSource = readFileSync(adminGroupRouteHandlersPath, 'utf8')
  const adminGroupRepositorySource = readFileSync(adminGroupRepositoryPath, 'utf8')
  const schemaDocSource = readFileSync(schemaDocPath, 'utf8')
  const schemaSqlSource = readFileSync(schemaSqlPath, 'utf8')
  const initialMigrationSource = readFileSync(initialMigrationPath, 'utf8')

  assert.match(groupsListViewSource, /<GroupsDataTable searchQuery=\{searchQuery\} \/>/)

  assert.match(groupsDataTableSource, /from '@tanstack\/react-table'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/dialog'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/sheet'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/item'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/input'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/textarea'/)
  assert.match(groupsDataTableSource, /from '@\/components\/ui\/select'/)
  assert.match(groupsDataTableSource, /import \{ useToast \} from '@\/hooks\/use-toast'/)
  assert.match(groupsDataTableSource, /const \{ toastManager \} = useToast\(\)/)
  assert.match(groupsDataTableSource, /import \{ Avatar, AvatarFallback, AvatarImage \} from '@\/components\/ui\/avatar'/)
  assert.match(groupsDataTableSource, /function GroupAvatarStack\(\{ athletes = \[\] \}\)/)
  assert.match(groupsDataTableSource, /className="flex -space-x-2"/)
  assert.match(groupsDataTableSource, /<AvatarImage src=\{athlete\.avatarUrl\} alt=\{athlete\.name\}/)
  assert.match(groupsDataTableSource, /\+\{overflowCount\}/)
  assert.match(groupsDataTableSource, /<GroupCell name=\{row\.original\.name\} athletes=\{row\.original\.athletes\}/)
  assert.doesNotMatch(groupsDataTableSource, /formatAthletePreview\(athleteNames\)/)
  assert.match(groupsDataTableSource, /const \[athleteOptions, setAthleteOptions\] = useState\(\[\]\)/)
  assert.match(groupsDataTableSource, /const \[isCreateEditGroupDialogOpen, setIsCreateEditGroupDialogOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isDeleteGroupDialogOpen, setIsDeleteGroupDialogOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isAddAthletesSheetOpen, setIsAddAthletesSheetOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isRestoreGroupsSheetOpen, setIsRestoreGroupsSheetOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isRestoringGroups, setIsRestoringGroups\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isArchiveGroupsDialogOpen, setIsArchiveGroupsDialogOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isArchivingGroups, setIsArchivingGroups\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isExportGroupsSheetOpen, setIsExportGroupsSheetOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[isExportingGroups, setIsExportingGroups\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[selectedBulkAthleteIds, setSelectedBulkAthleteIds\] = useState\(\[\]\)/)
  assert.match(groupsDataTableSource, /const \[athleteSearchQuery, setAthleteSearchQuery\] = useState\(''\)/)
  assert.match(groupsDataTableSource, /const \[isAddingAthletesToGroups, setIsAddingAthletesToGroups\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[groupDialogMode, setGroupDialogMode\] = useState\('create'\)/)
  assert.match(groupsDataTableSource, /const \[selectedGroupId, setSelectedGroupId\] = useState\(null\)/)
  assert.match(groupsDataTableSource, /const \[openRowActionMenuId, setOpenRowActionMenuId\] = useState\(null\)/)
  assert.match(groupsDataTableSource, /const \[pendingRowAction, setPendingRowAction\] = useState\(null\)/)
  assert.match(groupsDataTableSource, /fetch\('\/api\/admin\/groups'/)
  assert.match(groupsDataTableSource, /setGroups\(Array\.isArray\(payload\?\.groups\) \? payload\.groups : \[\]\)/)
  assert.match(groupsDataTableSource, /setAthleteOptions\(Array\.isArray\(payload\?\.athleteOptions\) \? payload\.athleteOptions : \[\]\)/)
  assert.match(groupsDataTableSource, /function openCreateGroupDialog\(\)/)
  assert.match(groupsDataTableSource, /function openEditGroupDialog\(groupId\)/)
  assert.match(groupsDataTableSource, /onClick=\{openCreateGroupDialog\}/)
  assert.match(groupsDataTableSource, /function handleAddAthletesSheetOpenChange\(open\) \{[\s\S]*setIsAddAthletesSheetOpen\(open\)[\s\S]*if \(!open\) \{[\s\S]*setIsBulkActionsMenuOpen\(false\)[\s\S]*setSelectedBulkAthleteIds\(\[\]\)[\s\S]*setAthleteSearchQuery\(''\)[\s\S]*\}/)
  assert.match(groupsDataTableSource, /function toggleSelectedBulkAthleteId\(athleteId\)/)
  assert.match(groupsDataTableSource, /async function handleAddAthletesToGroupsSubmit\(\)/)
  assert.match(groupsDataTableSource, /if \(selectedBulkAthleteIds\.length === 0 \|\| selectedBulkGroupIds\.length === 0 \|\| isAddingAthletesToGroups\) return/)
  assert.match(groupsDataTableSource, /fetch\('\/api\/admin\/groups', \{[\s\S]*method: 'PATCH'[\s\S]*action: 'add-athletes'[\s\S]*groupIds: selectedBulkGroupIds,[\s\S]*athleteIds: selectedBulkAthleteIds/)
  assert.match(groupsDataTableSource, /return payload\?\.result \?\? \{\}/)
  assert.match(groupsDataTableSource, /await toastManager\.promise\(submitPromise, \{[\s\S]*loading: \{ title: 'Adding athletes to groups\.\.\.'[\s\S]*success: \(result\) => \(\{[\s\S]*title: 'Athletes added to groups',[\s\S]*description: `\$\{result\?\.athletesAdded \?\? selectedBulkAthleteIds\.length\} athlete\$\{selectedBulkAthleteIds\.length === 1 \? '' : 's'\} added to \$\{result\?\.groupsUpdated \?\? selectedBulkGroupIds\.length\} group\$\{selectedBulkGroupIds\.length === 1 \? '' : 's'\}\.`[\s\S]*error: \(submitError\) => \(\{[\s\S]*title: 'Failed to add athletes to groups'/)
  assert.match(groupsDataTableSource, /setIsAddAthletesSheetOpen\(false\)[\s\S]*setSelectedBulkAthleteIds\(\[\]\)[\s\S]*setRowSelection\(\{\}\)[\s\S]*setRefreshKey\(\(currentValue\) => currentValue \+ 1\)/)
  assert.match(groupsDataTableSource, /finally \{[\s\S]*setIsAddingAthletesToGroups\(false\)[\s\S]*\}/)
  assert.match(groupsDataTableSource, /onSelect=\{\(event\) => \{\s*event\.preventDefault\(\)\s*setIsBulkActionsMenuOpen\(false\)\s*setSelectedBulkAthleteIds\(\[\]\)\s*setAthleteSearchQuery\(''\)\s*setIsAddAthletesSheetOpen\(true\)\s*\}\}[\s\S]*Add athletes/)
  assert.match(groupsDataTableSource, /function handleOpenRestoreGroupsSheet\(\) \{[\s\S]*if \(selectedGroupCount === 0 \|\| isRestoringGroups\) return[\s\S]*setIsBulkActionsMenuOpen\(false\)[\s\S]*setIsRestoreGroupsSheetOpen\(true\)[\s\S]*\}/)
  assert.match(groupsDataTableSource, /async function handleConfirmRestoreGroups\(\)/)
  assert.match(groupsDataTableSource, /if \(restoreEligibleGroups\.length === 0 \|\| isRestoringGroups\) return/)
  assert.match(groupsDataTableSource, /fetch\('\/api\/admin\/groups', \{[\s\S]*method: 'PATCH'[\s\S]*action: 'restore'[\s\S]*groupIds: restoreEligibleGroups\.map\(\(group\) => group\.id\)/)
  assert.match(groupsDataTableSource, /loading: \{ title: 'Restoring groups\.\.\.'/)
  assert.match(groupsDataTableSource, /title: 'Groups restored'/)
  assert.match(groupsDataTableSource, /description: `[\s\S]*result\?\.restoredCount \?\? restoreEligibleGroups\.length[\s\S]*restored\.[\s\S]*result\?\.skippedCount[\s\S]*result\.skippedCount[\s\S]*skipped\./)
  assert.match(groupsDataTableSource, /title: 'Failed to restore groups'/)
  assert.match(groupsDataTableSource, /setIsRestoreGroupsSheetOpen\(false\)[\s\S]*setRowSelection\(\{\}\)[\s\S]*setRefreshKey\(\(currentValue\) => currentValue \+ 1\)/)
  assert.match(groupsDataTableSource, /const archiveEligibleGroups = selectedBulkGroups\.filter\(\(group\) => normalizeGroupFilterValue\(group\.statusValue \|\| group\.status\) !== 'archived'\)/)
  assert.match(groupsDataTableSource, /const archiveSkippedGroups = selectedBulkGroups\.filter\(\(group\) => normalizeGroupFilterValue\(group\.statusValue \|\| group\.status\) === 'archived'\)/)
  assert.match(groupsDataTableSource, /function handleOpenArchiveGroupsDialog\(\) \{[\s\S]*if \(selectedGroupCount === 0 \|\| isArchivingGroups\) return[\s\S]*setIsBulkActionsMenuOpen\(false\)[\s\S]*setIsArchiveGroupsDialogOpen\(true\)/)
  assert.match(groupsDataTableSource, /fetch\('\/api\/admin\/groups', \{[\s\S]*method: 'PATCH'[\s\S]*action: 'archive',[\s\S]*groupIds: archiveEligibleGroups\.map\(\(group\) => group\.id\)/)
  assert.match(groupsDataTableSource, /loading: \{ title: 'Archiving groups\.\.\.'/)
  assert.match(groupsDataTableSource, /title: 'Groups archived'/)
  assert.match(groupsDataTableSource, /title: 'Failed to archive groups'/)
  assert.match(groupsDataTableSource, /setIsArchiveGroupsDialogOpen\(false\)[\s\S]*setRowSelection\(\{\}\)[\s\S]*setRefreshKey\(\(currentValue\) => currentValue \+ 1\)/)
  assert.match(groupsDataTableSource, /<Dialog open=\{isArchiveGroupsDialogOpen\} onOpenChange=\{setIsArchiveGroupsDialogOpen\}>/)
  assert.match(groupsDataTableSource, /<DialogContent className="admin-shell-groups-archive-dialog[^\"]*sm:max-w-\[560px\][^\"]*"/)
  assert.match(groupsDataTableSource, /<DialogTitle>Archive groups<\/DialogTitle>/)
  assert.match(groupsDataTableSource, /Review the selected groups before moving them out of active workflows\./)
  assert.match(groupsDataTableSource, /Ready to archive/)
  assert.match(groupsDataTableSource, /Already archived/)
  assert.match(groupsDataTableSource, /No selected groups can be archived\. Only active groups can be archived\./)
  assert.match(groupsDataTableSource, /disabled=\{archiveEligibleGroups\.length === 0 \|\| isArchivingGroups\}/)
  assert.match(groupsDataTableSource, /\{isArchivingGroups \? 'Archiving\.\.\.' : `Archive \$\{archiveEligibleGroups\.length\} group\$\{archiveEligibleGroups\.length === 1 \? '' : 's'\}`\}/)
  assert.match(groupsDataTableSource, /from '@\/lib\/admin-groups-export'/)
  assert.match(groupsDataTableSource, /buildGroupsExportCsv,[\s\S]*downloadGroupsExportFile,[\s\S]*getGroupsExportFileName,[\s\S]*groupExportColumns,/)
  assert.match(groupsDataTableSource, /const exportGroupsFileName = getGroupsExportFileName\(\)/)
  assert.match(groupsDataTableSource, /const exportGroupsDisabled = selectedGroupCount === 0 \|\| isExportingGroups/)
  assert.match(groupsDataTableSource, /function handleOpenExportGroupsSheet\(\) \{[\s\S]*if \(exportGroupsDisabled\) return[\s\S]*setIsBulkActionsMenuOpen\(false\)[\s\S]*setIsExportGroupsSheetOpen\(true\)/)
  assert.match(groupsDataTableSource, /function handleConfirmExportGroups\(\) \{[\s\S]*if \(exportGroupsDisabled\) return[\s\S]*buildGroupsExportCsv\(selectedBulkGroups\)[\s\S]*fileName: exportGroupsFileName[\s\S]*text\/csv;charset=utf-8[\s\S]*Groups export ready[\s\S]*setIsExportGroupsSheetOpen\(false\)[\s\S]*setRowSelection\(\{\}\)/)
  assert.match(groupsDataTableSource, /aria-label="Open groups export workflow"[\s\S]*onSelect=\{\(event\) => \{\s*event\.preventDefault\(\)\s*handleOpenExportGroupsSheet\(\)\s*\}\}[\s\S]*Export/)
  assert.match(groupsDataTableSource, /<Sheet open=\{isExportGroupsSheetOpen\} onOpenChange=\{setIsExportGroupsSheetOpen\}>/)
  assert.match(groupsDataTableSource, /<SheetContent side="right" className="admin-shell-groups-export-sheet[^\"]*!max-w-\[var\(--container-lg\)\][^\"]*"/)
  assert.match(groupsDataTableSource, /<SheetTitle>Export groups<\/SheetTitle>/)
  assert.match(groupsDataTableSource, /Review the selected groups before downloading a CSV export\./)
  assert.match(groupsDataTableSource, /Selected groups[\s\S]*\{selectedGroupCount\}[\s\S]*Format[\s\S]*CSV[\s\S]*Filename[\s\S]*\{exportGroupsFileName\}/)
  assert.match(groupsDataTableSource, /Included columns[\s\S]*groupExportColumns\.map\(\(column\) =>/)
  assert.match(groupsDataTableSource, /Selected group preview[\s\S]*selectedBulkGroups\.map\(\(group\) =>/)
  assert.doesNotMatch(groupsDataTableSource, /This export includes group IDs and athlete membership names\. Share it carefully\./)
  assert.match(groupsDataTableSource, /disabled=\{exportGroupsDisabled\}[\s\S]*onClick=\{handleConfirmExportGroups\}[\s\S]*\{isExportingGroups \? 'Preparing CSV\.\.\.' : 'Download CSV'\}/)
  assert.match(groupsDataTableSource, /<Sheet open=\{isAddAthletesSheetOpen\} onOpenChange=\{handleAddAthletesSheetOpenChange\}>/)
  assert.match(groupsDataTableSource, /<SheetContent side="right" className="admin-shell-groups-add-athletes-sheet[^\"]*!max-w-\[var\(--container-lg\)\][^\"]*"/)
  assert.match(groupsDataTableSource, /<SheetTitle className="text-\[var\(--admin-dashboard-card-text\)\]">Add athletes<\/SheetTitle>/)
  assert.match(groupsDataTableSource, /Choose athletes to add to \{selectedGroupCount\} selected groups\./)
  assert.match(groupsDataTableSource, /Selected groups/)
  assert.match(groupsDataTableSource, /Athletes list/)
  assert.match(groupsDataTableSource, /Search athletes\.\.\./)
  assert.match(groupsDataTableSource, /selectedBulkAthleteIds\.includes\(athlete\.id\)/)
  assert.match(groupsDataTableSource, /border-\[var\(--admin-shell-primary-button-bg\)\] bg-\[#3BE0AF\]\/10 hover:bg-\[#3BE0AF\]\/10/)
  assert.match(groupsDataTableSource, /disabled=\{isAddingAthletesToGroups \|\| selectedBulkAthleteIds\.length === 0 \|\| selectedGroupCount === 0\}/)
  assert.match(groupsDataTableSource, /\{isAddingAthletesToGroups \? 'Adding\.\.\.' : 'Add athletes'\}/)
  assert.match(groupsDataTableSource, /<Sheet open=\{isCreateEditGroupDialogOpen\} onOpenChange=\{setIsCreateEditGroupDialogOpen\}>/)
  assert.match(groupsDataTableSource, /<SheetContent side="right" className="admin-shell-groups-create-sheet[^\"]*!max-w-\[var\(--container-lg\)\][^\"]*"/)
  assert.match(groupsDataTableSource, /groupDialogMode === 'edit' \? 'Edit group' : 'Create a group'/)
  assert.match(groupsDataTableSource, /Update the information below\./)
  assert.match(groupsDataTableSource, /Fill out the information below\./)
  assert.match(groupsDataTableSource, /admin-shell-athletes-example-columns-button admin-shell-athletes-create-select-trigger w-full/)
  assert.match(groupsDataTableSource, /Athletes list/)
  assert.match(groupsDataTableSource, /Add or remove athletes from this group\./)
  assert.match(groupsDataTableSource, /<ItemGroup className="gap-0">/)
  assert.match(groupsDataTableSource, /Added to group/)
  assert.match(groupsDataTableSource, /Available to add/)
  assert.match(groupsDataTableSource, /Remove athlete from group/)
  assert.match(groupsDataTableSource, /Add athlete to group/)
  assert.match(groupsDataTableSource, /<SheetFooter className="shrink-0 border-t border-\[color:var\(--admin-dashboard-card-border\)\] px-6 py-5 sm:flex-row sm:justify-end gap-3">/)
  assert.match(groupsDataTableSource, /className="admin-shell-groups-create-submit rounded-\[12px\] min-h-\[40px\] bg-\[var\(--admin-shell-primary-button-bg\)\] text-\[#0B1120\] hover:bg-\[var\(--admin-shell-primary-button-bg\)\]"/)
  assert.match(groupsDataTableSource, /groupDialogMode === 'edit' \? 'Save changes' : 'Create group'/)
  assert.doesNotMatch(groupsDataTableSource, /<SheetFooter className="shrink-0 border-t border-\[color:var\(--admin-dashboard-card-border\)\] px-6 py-5 sm:justify-end gap-3">/)
  assert.doesNotMatch(groupsDataTableSource, /Manage memberships/)
  assert.doesNotMatch(groupsDataTableSource, /Add or remove athlete memberships for this group\./)
  assert.doesNotMatch(groupsDataTableSource, /Save group/)
  assert.doesNotMatch(groupsDataTableSource, /<Dialog open=\{isCreateEditGroupDialogOpen\}/)
  assert.doesNotMatch(groupsDataTableSource, /admin-shell-groups-create-sheet[^\"]*sm:max-w-\[720px\]/)
  assert.doesNotMatch(groupsDataTableSource, /onAssignProgramAction/)
  assert.doesNotMatch(groupsDataTableSource, /onArchiveAction/)
  assert.doesNotMatch(groupsDataTableSource, /type: 'assign-program'/)
  assert.doesNotMatch(groupsDataTableSource, /type: 'archive'/)
  assert.match(groupsDataTableSource, /const \[isAssignProgramSheetOpen, setIsAssignProgramSheetOpen\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /const \[selectedAssignProgramId, setSelectedAssignProgramId\] = useState\(''\)/)
  assert.match(groupsDataTableSource, /const \[programOptions, setProgramOptions\] = useState\(\[\]\)/)
  assert.match(groupsDataTableSource, /const \[isAssigningProgram, setIsAssigningProgram\] = useState\(false\)/)
  assert.match(groupsDataTableSource, /setProgramOptions\(Array\.isArray\(payload\?\.programOptions\) \? payload\.programOptions : \[\]\)/)
  assert.match(groupsDataTableSource, /handleOpenAssignProgramSheet\(\)/)
  assert.match(groupsDataTableSource, /<Sheet open=\{isAssignProgramSheetOpen\} onOpenChange=\{handleAssignProgramSheetOpenChange\}>/)
  assert.match(groupsDataTableSource, /admin-shell-groups-assign-program-sheet[^\"]*!max-w-\[var\(--container-lg\)\]/)
  assert.match(groupsDataTableSource, /Choose a program to assign to \{selectedGroupCount\} selected groups\./)
  assert.match(groupsDataTableSource, /This clones the selected program into every athlete in the selected groups\./)
  assert.match(groupsDataTableSource, /body: JSON\.stringify\(\{[\s\S]*action: 'assign-program',[\s\S]*groupIds: selectedBulkGroupIds,[\s\S]*sourceProgramId: selectedAssignProgramId/)
  assert.match(groupsDataTableSource, /setIsAssignProgramSheetOpen\(false\)[\s\S]*setSelectedAssignProgramId\(''\)[\s\S]*setRowSelection\(\{\}\)[\s\S]*setRefreshKey\(\(currentValue\) => currentValue \+ 1\)/)
  assert.match(groupsDataTableSource, /\{isAssigningProgram \? 'Assigning\.\.\.' : 'Assign program'\}/)
  assert.match(groupsDataTableSource, /method: groupDialogMode === 'edit' \? 'PATCH' : 'POST'/)
  assert.match(groupsDataTableSource, /method: 'PATCH'/)
  assert.match(groupsDataTableSource, /action: 'update'/)
  assert.match(groupsDataTableSource, /<Dialog open=\{isDeleteGroupDialogOpen\} onOpenChange=\{setIsDeleteGroupDialogOpen\}>/)
  assert.match(groupsDataTableSource, /<DialogContent className="admin-shell-groups-delete-dialog border border-\[var\(--admin-dashboard-card-border\)\] bg-\[var\(--admin-dashboard-card-bg\)\] text-\[var\(--admin-dashboard-card-text\)\] sm:max-w-\[440px\]">/)
  assert.match(groupsDataTableSource, /<DialogTitle>Delete group<\/DialogTitle>/)
  assert.match(groupsDataTableSource, /<DialogDescription>This group will be permanently deleted\.<\/DialogDescription>/)
  assert.match(groupsDataTableSource, /<DialogFooter className="sm:flex-row sm:justify-end gap-3">/)
  assert.match(groupsDataTableSource, /className="rounded-\[12px\] min-h-\[40px\]"[\s\S]*Cancel/)
  assert.match(groupsDataTableSource, /className="rounded-\[12px\] min-h-\[40px\] bg-red-500\/90 text-white hover:bg-red-500"[\s\S]*Delete group/)
  assert.doesNotMatch(groupsDataTableSource, /<Dialog open=\{isDeleteGroupDialogOpen\} onOpenChange=\{setIsDeleteGroupDialogOpen\}>[\s\S]*sm:max-w-\[560px\]/)
  assert.doesNotMatch(groupsDataTableSource, /<Dialog open=\{isDeleteGroupDialogOpen\} onOpenChange=\{setIsDeleteGroupDialogOpen\}>[\s\S]*border-t/)
  assert.match(groupsDataTableSource, /action: 'delete'/)
  assert.match(groupsDataTableSource, /athleteOptions\.map\(/)
  assert.match(groupsDataTableSource, /No groups found\./)
  assert.doesNotMatch(groupsDataTableSource, /GROUPS_BACKEND_NOT_CONFIGURED/)
  assert.doesNotMatch(groupsDataTableSource, /Group 1/)
  assert.doesNotMatch(groupsDataTableSource, /Mason Lee/)

  assert.match(adminGroupsRouteSource, /createAdminGroupRouteHandlers/)
  assert.match(adminGroupsRouteSource, /export const GET = handlers\.GET/)
  assert.match(adminGroupsRouteSource, /export const POST = handlers\.POST/)
  assert.match(adminGroupsRouteSource, /export const PATCH = handlers\.PATCH/)
  assert.match(adminGroupRouteHandlersSource, /createAdminGroupRepository/)
  assert.match(adminGroupRouteHandlersSource, /repository\.listGroups\(\)/)
  assert.match(adminGroupRouteHandlersSource, /repository\.listAthleteOptions\(\)/)
  assert.match(adminGroupRouteHandlersSource, /repository\.listProgramOptions\(\)/)
  assert.match(adminGroupRouteHandlersSource, /repository\.createGroup\(/)
  assert.match(adminGroupRouteHandlersSource, /repository\.updateGroup\(/)
  assert.match(adminGroupRouteHandlersSource, /repository\.archiveGroup\(/)
  assert.match(adminGroupRouteHandlersSource, /repository\.archiveGroups\(/)
  assert.match(adminGroupRouteHandlersSource, /repository\.unarchiveGroup\(/)
  assert.match(adminGroupRouteHandlersSource, /repository\.restoreGroups\(/)
  assert.match(adminGroupRouteHandlersSource, /repository\.deleteGroup\(/)
  assert.match(adminGroupRouteHandlersSource, /repository\.assignProgramToGroups\(/)
  assert.match(adminGroupRouteHandlersSource, /repository\.addAthletesToGroups\(/)
  assert.match(adminGroupRouteHandlersSource, /body\?\.action === 'restore'/)
  assert.match(adminGroupRouteHandlersSource, /Array\.isArray\(body\?\.groupIds\)/)
  assert.match(adminGroupRouteHandlersSource, /body\?\.action === 'add-athletes'/)
  assert.match(adminGroupRouteHandlersSource, /return json\(\{ result \}\)/)
  assert.match(adminGroupRouteHandlersSource, /return json\(\{ groups, athleteOptions, programOptions \}\)/)

  assert.match(adminGroupRepositorySource, /athlete_groups/)
  assert.match(adminGroupRepositorySource, /athlete_group_memberships/)
  assert.match(adminGroupRepositorySource, /athlete_profiles/)
  assert.match(adminGroupRepositorySource, /async function insertTable\(/)
  assert.match(adminGroupRepositorySource, /async function patchTable\(/)
  assert.match(adminGroupRepositorySource, /async function deleteTable\(/)
  assert.match(adminGroupRepositorySource, /listGroups\(\)/)
  assert.match(adminGroupRepositorySource, /listAthleteOptions\(\)/)
  assert.match(adminGroupRepositorySource, /listProgramOptions\(\)/)
  assert.match(adminGroupRepositorySource, /requestTable\('program_workouts', '\?select=id,program_id'\)/)
  assert.match(adminGroupRepositorySource, /const workoutCountByProgramId = createCounter\(workoutRows, 'program_id'\)/)
  assert.match(adminGroupRepositorySource, /workoutCount,\s*\n\s*workouts: String\(workoutCount\)/)
  assert.match(adminGroupRepositorySource, /createGroup\(\{/)
  assert.match(adminGroupRepositorySource, /updateGroup\(\{/)
  assert.match(adminGroupRepositorySource, /archiveGroup\(\{/)
  assert.match(adminGroupRepositorySource, /archiveGroups\(\{ groupIds = \[\] \}\)/)
  assert.match(adminGroupRepositorySource, /const archivableGroupIds = groupRows\.filter\(\(group\) => group\?\.status !== 'archived'\)\.map\(\(group\) => group\.id\)/)
  assert.match(adminGroupRepositorySource, /if \(!archivableGroupIds\.length\) throw createRepositoryError\('No active groups selected to archive\.', 400\)/)
  assert.match(adminGroupRepositorySource, /skippedCount: normalizedGroupIds\.length - archivableGroupIds\.length/)
  assert.match(adminGroupRepositorySource, /unarchiveGroup\(\{/)
  assert.match(adminGroupRepositorySource, /restoreGroups\(\{ groupIds = \[\] \}\)/)
  assert.match(adminGroupRepositorySource, /const groupRows = await requestTable\('athlete_groups', `\?select=id,status&id=in\.\$\{groupFilter\}`\)/)
  assert.match(adminGroupRepositorySource, /const restorableGroupIds = groupRows\.filter\(\(group\) => group\?\.status === 'archived'\)\.map\(\(group\) => group\.id\)/)
  assert.match(adminGroupRepositorySource, /if \(!restorableGroupIds\.length\) throw createRepositoryError\('No archived groups selected to restore\.', 400\)/)
  assert.match(adminGroupRepositorySource, /skippedCount: normalizedGroupIds\.length - restorableGroupIds\.length/)
  assert.match(adminGroupRepositorySource, /deleteGroup\(\{/)
  assert.match(adminGroupRepositorySource, /assignProgramToGroup\(\{/)
  assert.match(adminGroupRepositorySource, /assignProgramToGroups\(\{ groupIds = \[\], groupId = '', sourceProgramId \}\)/)
  assert.match(adminGroupRepositorySource, /const normalizedGroupIds = normalizeAthleteIds\(groupIds\.length \? groupIds : \[groupId\]\)/)
  assert.match(adminGroupRepositorySource, /const athleteIdSet = new Set\(\)/)
  assert.match(adminGroupRepositorySource, /groupAthleteIds\.forEach\(\(athleteId\) => athleteIdSet\.add\(athleteId\)\)/)
  assert.match(adminGroupRepositorySource, /Selected groups have no athlete memberships to assign\./)
  assert.match(adminGroupRepositorySource, /groupsUpdated: normalizedGroupIds\.length/)
  assert.match(adminGroupRepositorySource, /athletesUpdated: athleteIds\.length/)
  assert.match(adminGroupRepositorySource, /addAthletesToGroups\(\{/)
  assert.match(adminGroupRepositorySource, /groupIds = \[\], athleteIds = \[\]/)
  assert.match(adminGroupRepositorySource, /const existingAthleteIds = await getGroupAthleteIds\(groupId\)/)
  assert.match(adminGroupRepositorySource, /await syncMemberships\(groupId, \[\.\.\.existingAthleteIds, \.\.\.normalizedAthleteIds\]\)/)
  assert.match(adminGroupRepositorySource, /groupsUpdated: normalizedGroupIds\.length/)
  assert.match(adminGroupRepositorySource, /athletesAdded: normalizedAthleteIds\.length/)
  assert.match(adminGroupRepositorySource, /programs/)
  assert.match(adminGroupRepositorySource, /program_weeks/)
  assert.match(adminGroupRepositorySource, /program_days/)
  assert.match(adminGroupRepositorySource, /program_workouts/)
  assert.match(adminGroupRepositorySource, /program_workout_exercises/)
  assert.match(adminGroupRepositorySource, /program_workout_sets/)
  assert.match(adminGroupRepositorySource, /coach_profiles/)
  assert.match(adminGroupRepositorySource, /created_by_user_id/)
  assert.match(adminGroupRepositorySource, /archived_at/)

  assert.match(schemaDocSource, /## athlete_groups/)
  assert.match(schemaDocSource, /## athlete_group_memberships/)
  assert.match(schemaDocSource, /[Cc]oach-owned athlete collections used for admin organization, filtering, and bulk assignment targeting\./)
  assert.match(schemaSqlSource, /create table if not exists athlete_groups \(/)
  assert.match(schemaSqlSource, /create table if not exists athlete_group_memberships \(/)
  assert.match(initialMigrationSource, /create table if not exists athlete_groups \(/)
  assert.match(initialMigrationSource, /create table if not exists athlete_group_memberships \(/)
})
