import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pagePath = resolve(repoRoot, 'apps/web/app/admin/login/page.jsx')
const cssPath = resolve(repoRoot, 'apps/web/app/globals.css')
const layoutPath = resolve(repoRoot, 'apps/web/app/layout.jsx')
const buttonPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-button.jsx')
const cardPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-card.jsx')
const inputPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-input.jsx')
const labelPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-label.jsx')
const pageShellPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-page-shell.jsx')
const sectionHeaderPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-section-header.jsx')
const selectPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-select.jsx')
const textareaPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-textarea.jsx')

test('admin login screen source matches the figma auth_dark frame seams', () => {
  const pageSource = readFileSync(pagePath, 'utf8')
  const cssSource = readFileSync(cssPath, 'utf8')
  const layoutSource = readFileSync(layoutPath, 'utf8')
  const buttonSource = readFileSync(buttonPath, 'utf8')
  const cardSource = readFileSync(cardPath, 'utf8')
  const inputSource = readFileSync(inputPath, 'utf8')
  const labelSource = readFileSync(labelPath, 'utf8')
  const pageShellSource = readFileSync(pageShellPath, 'utf8')
  const sectionHeaderSource = readFileSync(sectionHeaderPath, 'utf8')
  const selectSource = readFileSync(selectPath, 'utf8')
  const textareaSource = readFileSync(textareaPath, 'utf8')

  assert.match(layoutSource, /title:\s*'PPLUS Training'/)
  assert.match(layoutSource, /description:\s*'Coach dashboard and athlete management for PPLUS Training\.'/)

  assert.match(pageSource, /from '\.\.\/\.\.\/\.\.\/components\/admin\/ui\/admin-button'/)
  assert.match(pageSource, /from '\.\.\/\.\.\/\.\.\/components\/admin\/ui\/admin-card'/)
  assert.match(pageSource, /from '\.\.\/\.\.\/\.\.\/components\/admin\/ui\/admin-input'/)
  assert.match(pageSource, /from '\.\.\/\.\.\/\.\.\/components\/admin\/ui\/admin-label'/)
  assert.match(pageSource, /from '\.\.\/\.\.\/\.\.\/components\/admin\/ui\/admin-page-shell'/)
  assert.match(pageSource, /id="auth-theme-dark"/)
  assert.match(pageSource, /id="auth-theme-light"/)
  assert.match(pageSource, /name="auth-theme"/)
  assert.match(pageSource, /defaultChecked/)
  assert.match(pageSource, /<AdminPageShell/)
  assert.match(pageSource, /<AdminCard/)
  assert.match(pageSource, /<AdminLabel[^>]*htmlFor="email"/)
  assert.match(pageSource, /<AdminInput[^>]*id="email"/)
  assert.match(pageSource, /<AdminLabel[^>]*htmlFor="password"/)
  assert.match(pageSource, /<AdminInput[^>]*id="password"/)
  assert.match(pageSource, /<AdminButton[^>]*type="submit"[^>]*size="default"/)

  assert.match(buttonSource, /export default function AdminButton/)
  assert.match(buttonSource, /variant\s*=\s*'primary'/)
  assert.match(buttonSource, /size\s*=\s*'default'/)
  assert.match(buttonSource, /admin-button-secondary/)
  assert.match(buttonSource, /admin-button-ghost/)
  assert.match(buttonSource, /admin-button-danger/)
  assert.match(buttonSource, /admin-button-compact/)
  assert.match(buttonSource, /admin-button-default/)
  assert.match(buttonSource, /admin-button-prominent/)
  assert.match(buttonSource, /admin-button-auth/)
  assert.match(cardSource, /export default function AdminCard/)
  assert.match(cardSource, /layout\s*=\s*'default'/)
  assert.match(cardSource, /padding\s*=\s*'default'/)
  assert.match(cardSource, /variant\s*=\s*'default'/)
  assert.match(cardSource, /admin-card-auth/)
  assert.match(cardSource, /admin-card-padding-default/)
  assert.match(cardSource, /admin-card-padding-spacious/)
  assert.match(cardSource, /admin-card-padding-auth/)
  assert.match(cardSource, /admin-card-interactive/)
  assert.match(cardSource, /admin-card-metric/)
  assert.match(inputSource, /export default function AdminInput/)
  assert.match(inputSource, /admin-input/)
  assert.match(labelSource, /export default function AdminLabel/)
  assert.match(labelSource, /admin-label/)
  assert.match(pageShellSource, /export default function AdminPageShell/)
  assert.match(pageShellSource, /admin-page-shell/)
  assert.match(sectionHeaderSource, /export default function AdminSectionHeader/)
  assert.match(sectionHeaderSource, /admin-section-header/)
  assert.match(selectSource, /export default function AdminSelect/)
  assert.match(selectSource, /admin-select/)
  assert.match(textareaSource, /export default function AdminTextarea/)
  assert.match(textareaSource, /admin-textarea/)

  assert.match(pageSource, /className="admin-login-pattern"/)
  assert.match(pageSource, /className="admin-auth-frame"/)
  assert.match(pageSource, /className="admin-auth-marketing"/)
  assert.match(pageSource, /className="admin-auth-signin-shell"/)
  assert.match(pageSource, /className="admin-auth-theme-toggle-row"/)
  assert.match(pageSource, /className="admin-auth-signin-body"/)
  assert.match(pageSource, /src="\/admin\/auth_theme_toggle\.svg"/)
  assert.match(pageSource, /className="admin-auth-theme-toggle admin-auth-theme-toggle-light"/)
  assert.match(pageSource, /src="\/admin\/auth_theme_toggle_light\.svg"/)
  assert.match(pageSource, /className="admin-auth-theme-hit admin-auth-theme-hit-light"/)
  assert.match(pageSource, /className="admin-auth-theme-hit admin-auth-theme-hit-dark"/)
  assert.match(pageSource, /htmlFor="auth-theme-light"/)
  assert.match(pageSource, /htmlFor="auth-theme-dark"/)
  assert.match(pageSource, /aria-label="Switch to light mode"/)
  assert.match(pageSource, /aria-label="Switch to dark mode"/)
  assert.match(pageSource, /src="\/admin\/auth_trophy\.svg"/)
  assert.match(pageSource, /The Best Hockey Training App/)
  assert.match(pageSource, /ELITE HOCKEY TRAINING/)
  assert.match(pageSource, /Off-Ice Work/)
  assert.match(pageSource, /On-Ice Results/)
  assert.match(pageSource, /guided trainings, simple tracking, and a clear plan built for long-term development\./)
  assert.match(pageSource, /src="\/admin\/auth_app_store_badge\.svg"/)
  assert.match(pageSource, /src="\/admin\/logo_pplus_training\.svg"/)
  assert.match(pageSource, /className="admin-auth-signin-logo admin-auth-signin-logo-dark"/)
  assert.match(pageSource, /className="admin-auth-signin-logo admin-auth-signin-logo-light"/)
  assert.match(pageSource, /src="\/admin\/logo_ppht_light_mode\.svg"/)
  assert.match(pageSource, /alt="PPLUS Training"/)
  assert.doesNotMatch(pageSource, /admin-auth-signin-wordmark/)
  assert.match(pageSource, /Welcome back/)
  assert.match(pageSource, /placeholder="Email"/)
  assert.match(pageSource, /placeholder="Password"/)
  assert.match(pageSource, /className="admin-login-password-toggle"/)
  assert.match(pageSource, /Sign in/)
  assert.match(pageSource, /Forgot Password/)
  assert.doesNotMatch(pageSource, /Coach OS/)
  assert.doesNotMatch(pageSource, /coach dashboard scaffold/i)

  assert.match(cssSource, /--ui-font-family:/)
  assert.match(cssSource, /--ui-color-accent:\s*#3be0af;/i)
  assert.match(cssSource, /--ui-button-height-compact:\s*24px;/i)
  assert.match(cssSource, /--ui-button-height-default:\s*32px;/i)
  assert.match(cssSource, /--ui-button-height-prominent:\s*40px;/i)
  assert.match(cssSource, /--ui-button-height-auth:\s*68px;/i)
  assert.match(cssSource, /--ui-input-height-auth:\s*40px;/i)
  assert.match(cssSource, /:root\s*\{[\s\S]*--admin-bg:\s*var\(--ui-bg\);[\s\S]*--admin-text:\s*var\(--ui-fg\);[\s\S]*--admin-accent:\s*var\(--ui-color-accent\);[\s\S]*--admin-accent-surface:\s*var\(--ui-color-accent-strong\);[\s\S]*--admin-card-radius:\s*30px;[\s\S]*--admin-input-radius:\s*26px;[\s\S]*--admin-input-height:\s*var\(--ui-input-height-auth\);[\s\S]*--admin-button-height-compact:\s*var\(--ui-button-height-compact\);[\s\S]*--admin-button-height-default:\s*var\(--ui-button-height-default\);[\s\S]*--admin-button-height-prominent:\s*var\(--ui-button-height-prominent\);[\s\S]*--admin-button-height-auth:\s*var\(--ui-button-height-auth\);/i)
  assert.match(cssSource, /\.admin-page-shell\s*\{[\s\S]*min-height:\s*100vh;[\s\S]*display:\s*grid;/)
  assert.match(cssSource, /\.admin-page-shell\s*\{[\s\S]*background:\s*var\(--admin-bg\);/i)
  assert.match(cssSource, /\.admin-page-shell\s*\{[\s\S]*--auth-page-pattern-image:\s*url\('\/admin\/bg_pplus\.svg'\);/)
  assert.match(cssSource, /\.admin-page-shell:has\(#auth-theme-light:checked\)\s*\{[\s\S]*--auth-page-pattern-image:\s*url\('\/admin\/bg_pplus_light\.svg'\);/)
  assert.match(cssSource, /\.admin-login-pattern\s*\{[\s\S]*background-image:\s*var\(--auth-page-pattern-image\);[\s\S]*background-repeat:\s*no-repeat;[\s\S]*background-size:\s*cover;/)
  assert.match(cssSource, /\.admin-auth-frame\s*\{[\s\S]*display:\s*grid;/)
  assert.match(cssSource, /\.admin-auth-frame\s*\{[\s\S]*grid-template-columns:/)
  assert.match(cssSource, /\.admin-auth-frame\s*\{[\s\S]*--auth-toggle-width:\s*62px;/)
  assert.match(cssSource, /\.admin-auth-frame\s*\{[\s\S]*--auth-marketing-pattern-image:\s*url\('\/admin\/bg_pplus\.svg'\);/)
  assert.match(cssSource, /\.admin-auth-frame:has\(#auth-theme-light:checked\)\s*\{[\s\S]*--auth-toggle-width:\s*64px;/)
  assert.match(cssSource, /\.admin-auth-frame:has\(#auth-theme-light:checked\)\s*\{[\s\S]*--auth-marketing-pattern-image:\s*url\('\/admin\/bg_pplus_light\.svg'\);/)
  assert.match(cssSource, /\.admin-auth-frame:has\(#auth-theme-light:checked\)\s*\{[\s\S]*--auth-signin-surface:\s*#fff;/i)
  assert.match(cssSource, /\.admin-auth-frame:has\(#auth-theme-light:checked\)\s+\.admin-auth-marketing-headline h2:not\(\.admin-auth-marketing-headline-accent\)\s*\{[\s\S]*background:\s*linear-gradient\(119deg,/)
  assert.match(cssSource, /\.admin-auth-marketing\s*\{[\s\S]*justify-content:\s*center;/)
  assert.match(cssSource, /\.admin-auth-marketing\s*\{[\s\S]*background:\s*var\(--auth-marketing-surface\);/)
  assert.match(cssSource, /\.admin-auth-marketing::before\s*\{[\s\S]*background-image:\s*var\(--auth-marketing-pattern-image\);[\s\S]*display:\s*none;/)
  assert.match(cssSource, /\.admin-auth-frame:has\(#auth-theme-light:checked\)\s+\.admin-auth-marketing::before\s*\{[\s\S]*display:\s*block;/)
  assert.match(cssSource, /\.admin-auth-marketing-badge\s*\{[\s\S]*border-radius:\s*20px;/)
  assert.match(cssSource, /\.admin-auth-signin-shell\s*\{[\s\S]*width:\s*408px;/)
  assert.match(cssSource, /\.admin-auth-signin-shell\s*\{[\s\S]*justify-content:\s*flex-start;/)
  assert.match(cssSource, /\.admin-auth-theme-toggle-row\s*\{[\s\S]*display:\s*flex;[\s\S]*justify-content:\s*center;[\s\S]*padding-top:\s*16px;/)
  assert.match(cssSource, /\.admin-auth-theme-input\s*\{[\s\S]*display:\s*none;/)
  assert.match(cssSource, /\.admin-auth-theme-toggle\s*\{[\s\S]*width:\s*var\(--auth-toggle-width\);[\s\S]*height:\s*var\(--auth-toggle-height\);/)
  assert.match(cssSource, /\.admin-auth-theme-toggle-light\s*\{[\s\S]*position:\s*absolute;[\s\S]*opacity:\s*0;/)
  assert.match(cssSource, /\.admin-auth-frame:has\(#auth-theme-light:checked\)\s+\.admin-auth-theme-toggle-light\s*\{[\s\S]*opacity:\s*1;/)
  assert.match(cssSource, /\.admin-auth-theme-hit\s*\{[\s\S]*position:\s*absolute;[\s\S]*width:\s*calc\(var\(--auth-toggle-width\) \/ 2\);/)
  assert.match(cssSource, /\.admin-auth-signin-body\s*\{[\s\S]*flex:\s*1;[\s\S]*display:\s*flex;[\s\S]*flex-direction:\s*column;[\s\S]*justify-content:\s*center;/)
  assert.match(cssSource, /\.admin-auth-signin-logo-row\s*\{[\s\S]*justify-content:\s*center;/)
  assert.match(cssSource, /\.admin-auth-signin-logo-dark\s*\{[\s\S]*display:\s*block;/)
  assert.match(cssSource, /\.admin-auth-signin-logo-light\s*\{[\s\S]*display:\s*none;/)
  assert.match(cssSource, /\.admin-auth-frame:has\(#auth-theme-light:checked\)\s+\.admin-auth-signin-logo-light\s*\{[\s\S]*display:\s*block;/)
  assert.match(cssSource, /\.admin-auth-title\s*\{[\s\S]*font-size:/)
  assert.match(cssSource, /\.admin-auth-submit-button\s*\{[\s\S]*height:\s*40px;[\s\S]*border:\s*1px solid #06d6a0;[\s\S]*border-radius:\s*6px;[\s\S]*background:\s*#06d6a0;[\s\S]*color:\s*#000;/i)
  assert.match(cssSource, /\.admin-label\s*\{[\s\S]*font-size:\s*12px;[\s\S]*letter-spacing:\s*0\.12em;[\s\S]*text-transform:\s*uppercase;/)
  assert.match(cssSource, /\.admin-input\s*\{[\s\S]*height:\s*var\(--admin-input-height\);[\s\S]*border-radius:\s*var\(--admin-input-radius\);/)
  assert.match(cssSource, /\.admin-input\s*\{[\s\S]*border:\s*1px solid var\(--auth-input-border\);[\s\S]*background:\s*var\(--auth-input-bg\);[\s\S]*color:\s*var\(--auth-input-text\);/)
  assert.match(cssSource, /\.admin-input::placeholder\s*\{[\s\S]*color:\s*var\(--auth-input-placeholder\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*border-radius:\s*var\(--admin-input-radius\);/)
  assert.match(cssSource, /\.admin-button-compact\s*\{[\s\S]*height:\s*var\(--admin-button-height-compact\);/)
  assert.match(cssSource, /\.admin-button-default\s*\{[\s\S]*height:\s*var\(--admin-button-height-default\);/)
  assert.match(cssSource, /\.admin-button-prominent\s*\{[\s\S]*height:\s*var\(--admin-button-height-prominent\);/)
  assert.match(cssSource, /\.admin-button-auth\s*\{[\s\S]*height:\s*var\(--admin-button-height-auth\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*background:\s*var\(--admin-accent-surface\);/i)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*color:\s*var\(--admin-accent\);/i)
  assert.match(cssSource, /\.admin-button-secondary\s*\{[\s\S]*background:/)
  assert.match(cssSource, /\.admin-button-ghost\s*\{[\s\S]*background:\s*transparent;/)
  assert.match(cssSource, /\.admin-button-danger\s*\{[\s\S]*background:/)
  assert.match(cssSource, /\.admin-card-interactive\s*\{[\s\S]*cursor:\s*pointer;/)
  assert.match(cssSource, /\.admin-card-metric\s*\{[\s\S]*min-height:/)
  assert.match(cssSource, /\.admin-section-header\s*\{[\s\S]*display:\s*grid;/)
  assert.match(cssSource, /\.admin-select\s*\{[\s\S]*height:\s*40px;/)
  assert.match(cssSource, /\.admin-textarea\s*\{[\s\S]*min-height:/)
  assert.match(cssSource, /\.admin-login-forgot\s*\{[\s\S]*justify-self:\s*center;[\s\S]*color:\s*var\(--admin-accent\);/i)
  assert.match(cssSource, /\.admin-login-forgot\s*\{[\s\S]*font-size:\s*14px;/)
  assert.match(cssSource, /\.admin-login-forgot-row\s*\{[\s\S]*display:\s*flex;[\s\S]*justify-content:\s*center;[\s\S]*text-align:\s*center;/)
})
