import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pagePath = resolve(repoRoot, 'apps/web/app/page.jsx')
const cssPath = resolve(repoRoot, 'apps/web/app/globals.css')
const layoutPath = resolve(repoRoot, 'apps/web/app/layout.jsx')
const buttonPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-button.jsx')
const cardPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-card.jsx')
const inputPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-input.jsx')
const labelPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-label.jsx')
const pageShellPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-page-shell.jsx')
const sectionHeaderPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-section-header.jsx')
const selectPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-select.jsx')
const textareaPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-textarea.jsx')

test('admin login screen source matches the locked login mock seams', () => {
  const pageSource = readFileSync(pagePath, 'utf8')
  const cssSource = readFileSync(cssPath, 'utf8')
  const layoutSource = readFileSync(layoutPath, 'utf8')
  const buttonSource = readFileSync(buttonPath, 'utf8')
  const cardSource = readFileSync(cardPath, 'utf8')
  const inputSource = readFileSync(inputPath, 'utf8')
  const labelSource = readFileSync(labelPath, 'utf8')
  const pageShellSource = readFileSync(pageShellPath, 'utf8')
  const sectionHeaderSource = readFileSync(sectionHeaderPath, 'utf8')
  const selectSource = readFileSync(selectPath, 'utf8')
  const textareaSource = readFileSync(textareaPath, 'utf8')

  assert.match(layoutSource, /title:\s*'PPLUS Training'/)
  assert.match(layoutSource, /description:\s*'Coach dashboard and athlete management for PPLUS Training\.'/)

  assert.match(pageSource, /from '\.\.\/components\/admin\/ui\/admin-button'/)
  assert.match(pageSource, /from '\.\.\/components\/admin\/ui\/admin-card'/)
  assert.match(pageSource, /from '\.\.\/components\/admin\/ui\/admin-input'/)
  assert.match(pageSource, /from '\.\.\/components\/admin\/ui\/admin-label'/)
  assert.match(pageSource, /from '\.\.\/components\/admin\/ui\/admin-page-shell'/)
  assert.match(pageSource, /<AdminPageShell/)
  assert.match(pageSource, /<AdminCard/)
  assert.match(pageSource, /<AdminLabel[^>]*htmlFor="email"/)
  assert.match(pageSource, /<AdminInput[^>]*id="email"/)
  assert.match(pageSource, /<AdminLabel[^>]*htmlFor="password"/)
  assert.match(pageSource, /<AdminInput[^>]*id="password"/)
  assert.match(pageSource, /<AdminButton[^>]*type="submit"[^>]*size="auth"/)

  assert.match(buttonSource, /export default function AdminButton/)
  assert.match(buttonSource, /variant\s*=\s*'primary'/)
  assert.match(buttonSource, /size\s*=\s*'default'/)
  assert.match(buttonSource, /admin-button-secondary/)
  assert.match(buttonSource, /admin-button-ghost/)
  assert.match(buttonSource, /admin-button-danger/)
  assert.match(buttonSource, /admin-button-compact/)
  assert.match(buttonSource, /admin-button-default/)
  assert.match(buttonSource, /admin-button-prominent/)
  assert.match(buttonSource, /admin-button-auth/)
  assert.match(cardSource, /export default function AdminCard/)
  assert.match(cardSource, /layout\s*=\s*'default'/)
  assert.match(cardSource, /padding\s*=\s*'default'/)
  assert.match(cardSource, /variant\s*=\s*'default'/)
  assert.match(cardSource, /admin-card-auth/)
  assert.match(cardSource, /admin-card-padding-default/)
  assert.match(cardSource, /admin-card-padding-spacious/)
  assert.match(cardSource, /admin-card-padding-auth/)
  assert.match(cardSource, /admin-card-interactive/)
  assert.match(cardSource, /admin-card-metric/)
  assert.match(inputSource, /export default function AdminInput/)
  assert.match(inputSource, /admin-input/)
  assert.match(labelSource, /export default function AdminLabel/)
  assert.match(labelSource, /admin-label/)
  assert.match(pageShellSource, /export default function AdminPageShell/)
  assert.match(pageShellSource, /admin-page-shell/)
  assert.match(sectionHeaderSource, /export default function AdminSectionHeader/)
  assert.match(sectionHeaderSource, /admin-section-header/)
  assert.match(selectSource, /export default function AdminSelect/)
  assert.match(selectSource, /admin-select/)
  assert.match(textareaSource, /export default function AdminTextarea/)
  assert.match(textareaSource, /admin-textarea/)

  assert.match(pageSource, /className="admin-login-pattern"/)
  assert.match(pageSource, /defaultValue="admin@pplus\.app"/)
  assert.match(pageSource, /placeholder="Enter your password"/)
  assert.match(pageSource, /className="admin-login-password-toggle"/)
  assert.match(pageSource, /Sign in/)
  assert.match(pageSource, /className="admin-login-submit-icon"/)
  assert.match(pageSource, /Forgot password\?/)
  assert.doesNotMatch(pageSource, /Coach OS/)
  assert.doesNotMatch(pageSource, /coach dashboard scaffold/i)

  assert.match(cssSource, /--ui-font-family:/)
  assert.match(cssSource, /--ui-color-accent:\s*#3be0af;/i)
  assert.match(cssSource, /--ui-button-height-compact:\s*24px;/i)
  assert.match(cssSource, /--ui-button-height-default:\s*32px;/i)
  assert.match(cssSource, /--ui-button-height-prominent:\s*40px;/i)
  assert.match(cssSource, /--ui-button-height-auth:\s*68px;/i)
  assert.match(cssSource, /:root\s*\{[\s\S]*--admin-bg:\s*var\(--ui-bg\);[\s\S]*--admin-text:\s*var\(--ui-fg\);[\s\S]*--admin-accent:\s*var\(--ui-color-accent\);[\s\S]*--admin-accent-surface:\s*var\(--ui-color-accent-strong\);[\s\S]*--admin-card-radius:\s*30px;[\s\S]*--admin-input-radius:\s*26px;[\s\S]*--admin-input-height:\s*var\(--ui-input-height-auth\);[\s\S]*--admin-button-height-compact:\s*var\(--ui-button-height-compact\);[\s\S]*--admin-button-height-default:\s*var\(--ui-button-height-default\);[\s\S]*--admin-button-height-prominent:\s*var\(--ui-button-height-prominent\);[\s\S]*--admin-button-height-auth:\s*var\(--ui-button-height-auth\);/i)
  assert.match(cssSource, /\.admin-page-shell\s*\{[\s\S]*min-height:\s*100vh;[\s\S]*display:\s*grid;[\s\S]*place-items:\s*center;/)
  assert.match(cssSource, /\.admin-page-shell\s*\{[\s\S]*background:\s*var\(--admin-bg\);/i)
  assert.match(cssSource, /\.admin-login-pattern\s*\{[\s\S]*background-image:\s*url\('\/admin\/bg_pplus\.svg'\);[\s\S]*background-repeat:\s*no-repeat;[\s\S]*background-size:\s*cover;/)
  assert.match(cssSource, /\.admin-card\s*\{[\s\S]*width:\s*100%;[\s\S]*border-radius:\s*var\(--admin-card-radius\);/)
  assert.match(cssSource, /\.admin-card-auth\s*\{[\s\S]*width:\s*min\(100%, 490px\);/)
  assert.match(cssSource, /\.admin-card-padding-auth\s*\{[\s\S]*padding:\s*var\(--admin-card-padding-auth\);/)
  assert.match(cssSource, /\.admin-label\s*\{[\s\S]*font-size:\s*12px;[\s\S]*letter-spacing:\s*0\.12em;[\s\S]*text-transform:\s*uppercase;/)
  assert.match(cssSource, /\.admin-input\s*\{[\s\S]*height:\s*var\(--admin-input-height\);[\s\S]*border-radius:\s*var\(--admin-input-radius\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*border-radius:\s*var\(--admin-input-radius\);/)
  assert.match(cssSource, /\.admin-button-compact\s*\{[\s\S]*height:\s*var\(--admin-button-height-compact\);/)
  assert.match(cssSource, /\.admin-button-default\s*\{[\s\S]*height:\s*var\(--admin-button-height-default\);/)
  assert.match(cssSource, /\.admin-button-prominent\s*\{[\s\S]*height:\s*var\(--admin-button-height-prominent\);/)
  assert.match(cssSource, /\.admin-button-auth\s*\{[\s\S]*height:\s*var\(--admin-button-height-auth\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*background:\s*var\(--admin-accent-surface\);/i)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*color:\s*var\(--admin-accent\);/i)
  assert.match(cssSource, /\.admin-button-secondary\s*\{[\s\S]*background:/)
  assert.match(cssSource, /\.admin-button-ghost\s*\{[\s\S]*background:\s*transparent;/)
  assert.match(cssSource, /\.admin-button-danger\s*\{[\s\S]*background:/)
  assert.match(cssSource, /\.admin-card-interactive\s*\{[\s\S]*cursor:\s*pointer;/)
  assert.match(cssSource, /\.admin-card-metric\s*\{[\s\S]*min-height:/)
  assert.match(cssSource, /\.admin-section-header\s*\{[\s\S]*display:\s*grid;/)
  assert.match(cssSource, /\.admin-select\s*\{[\s\S]*height:\s*40px;/)
  assert.match(cssSource, /\.admin-textarea\s*\{[\s\S]*min-height:/)
  assert.match(cssSource, /\.admin-login-forgot\s*\{[\s\S]*justify-self:\s*center;[\s\S]*color:\s*var\(--admin-accent\);/i)
})
