import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const cssPath = resolve(repoRoot, 'apps/web/app/globals.css')
const adminIndexPath = resolve(repoRoot, 'apps/web/app/admin/page.jsx')
const adminUiPath = resolve(repoRoot, 'apps/web/app/admin/ui/page.jsx')
const adminSectionPath = resolve(repoRoot, 'apps/web/app/admin/[section]/page.jsx')
const adminSubsectionPath = resolve(repoRoot, 'apps/web/app/admin/[section]/[subsection]/page.jsx')
const adminShellPath = resolve(repoRoot, 'apps/web/components/admin/admin-shell.jsx')
const dashboardOverviewPath = resolve(repoRoot, 'apps/web/components/admin/dashboard-overview.jsx')
const athletesListViewPath = resolve(repoRoot, 'apps/web/components/admin/athletes-list-view.jsx')
const invitesListViewPath = resolve(repoRoot, 'apps/web/components/admin/invites-list-view.jsx')
const groupsListViewPath = resolve(repoRoot, 'apps/web/components/admin/groups-list-view.jsx')
const rankingsListViewPath = resolve(repoRoot, 'apps/web/components/admin/rankings-list-view.jsx')
const adminButtonPath = resolve(repoRoot, 'apps/web/components/admin/ui/admin-button.jsx')
const adminNavigationPath = resolve(repoRoot, 'apps/web/components/admin/admin-navigation.js')
const sidebarPath = resolve(repoRoot, 'apps/web/components/ui/sidebar.jsx')
const inviteAthleteIllustrationPath = resolve(repoRoot, 'apps/web/public/admin/invite_athlete_img.svg')
const rulesetPath = resolve(repoRoot, 'docs/admin-ui-ruleset.md')

test('admin navigation uses real nested routes driven by shared config', () => {
  for (const path of [
    adminIndexPath,
    adminUiPath,
    adminSectionPath,
    adminSubsectionPath,
    adminShellPath,
    dashboardOverviewPath,
    athletesListViewPath,
    invitesListViewPath,
    groupsListViewPath,
    rankingsListViewPath,
    adminButtonPath,
    adminNavigationPath,
    sidebarPath,
    inviteAthleteIllustrationPath,
  ]) {
    assert.ok(existsSync(path), `expected admin navigation file to exist: ${path}`)
  }

  const cssSource = readFileSync(cssPath, 'utf8')
  const adminIndexSource = readFileSync(adminIndexPath, 'utf8')
  const adminUiSource = readFileSync(adminUiPath, 'utf8')
  const adminSectionSource = readFileSync(adminSectionPath, 'utf8')
  const adminSubsectionSource = readFileSync(adminSubsectionPath, 'utf8')
  const adminShellSource = readFileSync(adminShellPath, 'utf8')
  const dashboardOverviewSource = readFileSync(dashboardOverviewPath, 'utf8')
  const athletesListViewSource = readFileSync(athletesListViewPath, 'utf8')
  const invitesListViewSource = readFileSync(invitesListViewPath, 'utf8')
  const groupsListViewSource = readFileSync(groupsListViewPath, 'utf8')
  const rankingsListViewSource = readFileSync(rankingsListViewPath, 'utf8')
  const adminButtonSource = readFileSync(adminButtonPath, 'utf8')
  const adminNavigationSource = readFileSync(adminNavigationPath, 'utf8')
  const sidebarSource = readFileSync(sidebarPath, 'utf8')
  const rulesetSource = readFileSync(rulesetPath, 'utf8')

  assert.match(adminIndexSource, /redirect\('\/admin\/dashboard'\)/)
  assert.match(adminUiSource, /redirect\('\/admin\/dashboard'\)/)

  assert.match(adminSectionSource, /AdminShell/)
  assert.match(adminSectionSource, /params/)
  assert.match(adminSectionSource, /section/)
  assert.match(adminSubsectionSource, /AdminShell/)
  assert.match(adminSubsectionSource, /subsection/)
  assert.match(adminSubsectionSource, /redirect\('\/admin\/dashboard'\)/)

  assert.match(adminShellSource, /from '\.\.\/ui\/sidebar-layout'/)
  assert.match(adminShellSource, /from '\.\.\/ui\/sidebar'/)
  assert.match(adminShellSource, /from '\.\/admin-navigation'/)
  assert.match(adminShellSource, /from '\.\/dashboard-overview'/)
  assert.match(adminShellSource, /from '\.\/athletes-list-view'/)
  assert.match(adminShellSource, /from '\.\/invites-list-view'/)
  assert.match(adminShellSource, /from '\.\/groups-list-view'/)
  assert.match(adminShellSource, /from '\.\/rankings-list-view'/)
  assert.match(adminShellSource, /brandLogoSrc="\/admin\/logo_pplus_training\.svg"/)
  assert.match(adminShellSource, /currentPath/)
  assert.match(adminShellSource, /pageTitle/)
  assert.match(adminShellSource, /DashboardOverview/)
  assert.match(adminShellSource, /AthletesListView/)
  assert.match(adminShellSource, /InvitesListView/)
  assert.match(adminShellSource, /GroupsListView/)
  assert.match(adminShellSource, /RankingsListView/)
  assert.match(adminShellSource, /group\.items\?\.map\(\(item\) => \(\{ \.\.\.item \}\)\) \?\? \[\]/)
  assert.match(adminShellSource, /!isDashboardOverview && !isAllAthletesView && !isAthleteInvitesView && !isAthleteGroupsView && !isAthleteRankingsView &&/)
  assert.match(adminShellSource, /currentPath === '\/admin\/athletes'/)
  assert.match(adminShellSource, /currentPath === '\/admin\/athletes\/invites'/)
  assert.match(adminShellSource, /currentPath === '\/admin\/athletes\/groups'/)
  assert.match(adminShellSource, /currentPath === '\/admin\/athletes\/rankings'/)
  assert.match(dashboardOverviewSource, /'use client'/)
  assert.match(dashboardOverviewSource, /useState/)
  assert.match(dashboardOverviewSource, /Users/)
  assert.match(dashboardOverviewSource, /CalendarRange/)
  assert.match(dashboardOverviewSource, /Activity/)
  assert.match(dashboardOverviewSource, /BadgeCheck/)
  assert.match(dashboardOverviewSource, /ArrowUp/)
  assert.match(dashboardOverviewSource, /ArrowDown/)
  assert.match(dashboardOverviewSource, /Send\b/)
  assert.match(dashboardOverviewSource, /icon:\s*Users/)
  assert.match(dashboardOverviewSource, /icon:\s*CalendarRange/)
  assert.match(dashboardOverviewSource, /icon:\s*Activity/)
  assert.match(dashboardOverviewSource, /icon:\s*BadgeCheck/)
  assert.match(dashboardOverviewSource, /icon:\s*Send/)
  assert.doesNotMatch(dashboardOverviewSource, /icon:\s*ClipboardList/)
  assert.doesNotMatch(dashboardOverviewSource, /icon:\s*SendHorizontal/)
  assert.match(dashboardOverviewSource, /Last month/)
  assert.match(dashboardOverviewSource, /Last 7 days/)
  assert.match(dashboardOverviewSource, /Last 3 months/)
  assert.match(dashboardOverviewSource, /Last year/)
  assert.match(dashboardOverviewSource, /overviewRangeOptions/)
  assert.match(dashboardOverviewSource, /overviewRangeCardData/)
  assert.match(dashboardOverviewSource, /activeRange/)
  assert.match(dashboardOverviewSource, /setActiveRange/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-toolbar/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-range-button/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-range-menu/)
  assert.match(dashboardOverviewSource, /Active athletes/)
  assert.match(dashboardOverviewSource, /Programs assigned/)
  assert.match(dashboardOverviewSource, /Sessions this week/)
  assert.match(dashboardOverviewSource, /Compliance/)
  assert.match(dashboardOverviewSource, /Pending invites/)
  assert.match(dashboardOverviewSource, /value: '8'/)
  assert.match(dashboardOverviewSource, /value: '4'/)
  assert.match(dashboardOverviewSource, /value: '12'/)
  assert.match(dashboardOverviewSource, /value: '3'/)
  assert.match(dashboardOverviewSource, /change: '28\.4%'/)
  assert.match(dashboardOverviewSource, /change: '12\.6%'/)
  assert.match(dashboardOverviewSource, /change: '31%'/)
  assert.match(dashboardOverviewSource, /change: '11\.3%'/)
  assert.match(dashboardOverviewSource, /overviewPerformanceData/)
  assert.match(dashboardOverviewSource, /overviewComplianceData/)
  assert.match(dashboardOverviewSource, /overviewSessionTimeData/)
  assert.match(dashboardOverviewSource, /Sessions/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-performance-kicker-row/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-performance-kicker-icon/)
  assert.match(dashboardOverviewSource, /<Activity className="admin-shell-overview-performance-kicker-icon"/)
  assert.match(dashboardOverviewSource, /Completed/)
  assert.match(dashboardOverviewSource, /Assigned/)
  assert.match(dashboardOverviewSource, /overviewCompletedGradient/)
  assert.match(dashboardOverviewSource, /stopColor="rgba\(59, 224, 175, 0\.28\)"/)
  assert.match(dashboardOverviewSource, /stopColor="rgba\(59, 224, 175, 0\.02\)"/)
  assert.match(dashboardOverviewSource, /stroke="#3be0af"/)
  assert.match(dashboardOverviewSource, /stroke="#58c6ff"/)
  assert.match(dashboardOverviewSource, /fill="#3be0af"/)
  assert.match(dashboardOverviewSource, /className=\{isActive \? 'admin-shell-overview-chart-point-active' : 'admin-shell-overview-chart-point'\}/)
  assert.match(dashboardOverviewSource, /Overall compliance/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-insight-label-row/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-insight-label-icon/)
  assert.match(dashboardOverviewSource, /<BadgeCheck className="admin-shell-overview-insight-label-icon"/)
  assert.match(dashboardOverviewSource, /Sessions by time of the day/)
  assert.match(dashboardOverviewSource, /<Activity className="admin-shell-overview-insight-label-icon"/)
  assert.match(dashboardOverviewSource, /View report/)
  assert.match(dashboardOverviewSource, /Apr 22 - May 21, 2026/)
  assert.match(dashboardOverviewSource, /May 21, 2026/)
  assert.match(dashboardOverviewSource, /footer: 'Last month'/)
  assert.match(dashboardOverviewSource, /footer: 'Last year'/)
  assert.match(dashboardOverviewSource, /admin-shell-overview-card-change-arrow-icon/)
  assert.match(dashboardOverviewSource, /function TrendArrowIcon/)
  assert.match(dashboardOverviewSource, /<ArrowDown className="admin-shell-overview-card-change-arrow-icon"/)
  assert.match(dashboardOverviewSource, /<ArrowUp className="admin-shell-overview-card-change-arrow-icon"/)
  assert.match(dashboardOverviewSource, /<TrendArrowIcon direction=\{card\.direction\} \/>/)
  assert.doesNotMatch(dashboardOverviewSource, /\{card\.direction === 'negative' \? '↓' : '↑'\}/)
  assert.doesNotMatch(dashboardOverviewSource, /\{data\.changeDirection === 'negative' \? '↓' : '↑'\}/)

  assert.match(athletesListViewSource, /'use client'/)
  assert.match(athletesListViewSource, /from 'lucide-react'/)
  assert.match(athletesListViewSource, /ArrowUpAZ/)
  assert.match(athletesListViewSource, /ArrowUpZA/)
  assert.match(athletesListViewSource, /X/)
  assert.match(athletesListViewSource, /Dialog/)
  assert.match(athletesListViewSource, /from '\.\.\/ui\/dialog'/)
  assert.doesNotMatch(athletesListViewSource, /ArrowUpDown/)
  assert.match(athletesListViewSource, /useState/)
  assert.match(athletesListViewSource, /sortDirection/)
  assert.match(athletesListViewSource, /setSortDirection/)
  assert.match(athletesListViewSource, /sortIconMap/)
  assert.match(athletesListViewSource, /ascending:\s*ArrowUpAZ/)
  assert.match(athletesListViewSource, /descending:\s*ArrowUpZA/)
  assert.match(athletesListViewSource, /from '\.\/ui\/admin-button'/)
  assert.match(athletesListViewSource, /<AdminButton/)
  assert.match(athletesListViewSource, /variant="primary"/)
  assert.match(athletesListViewSource, /size="default"/)
  assert.match(athletesListViewSource, /className="admin-shell-athletes-invite-button"/)
  assert.match(athletesListViewSource, /onClick=\{\(\) => setIsInviteDialogOpen\(true\)\}/)
  assert.match(athletesListViewSource, /isInviteDialogOpen/)
  assert.match(athletesListViewSource, /setIsInviteDialogOpen/)
  assert.match(athletesListViewSource, /title="Invite an athlete"/)
  assert.match(athletesListViewSource, /description="Fill out the information below\."/)
  assert.match(athletesListViewSource, /Fill out the information below\./)

  assert.match(athletesListViewSource, /eg: johndoe@email\.com/)
  assert.match(athletesListViewSource, /Invite athlete/)
  assert.match(athletesListViewSource, /Close invite athlete dialog/)
  assert.match(athletesListViewSource, /admin-shell-athletes-invite-dialog-illustration/)
  assert.match(athletesListViewSource, /src="\/admin\/invite_athlete_img\.svg"/)
  assert.match(athletesListViewSource, /alt="Invite athlete illustration"/)
  assert.match(athletesListViewSource, /aria-label=\{`Sort \$\{children\} \$\{sortDirection\}`\}/)
  assert.match(athletesListViewSource, /onClick=\{toggleSortDirection\}/)
  assert.match(athletesListViewSource, /admin-shell-athletes-sort-icon/)
  assert.match(athletesListViewSource, /Invite an athlete/)
  assert.match(athletesListViewSource, /Search for an athlete by name\.\.\./)
  assert.doesNotMatch(athletesListViewSource, /admin-shell-athletes-table-card-header/)
  assert.doesNotMatch(athletesListViewSource, /admin-shell-athletes-table-card-title/)
  assert.doesNotMatch(athletesListViewSource, /admin-shell-athletes-table-card-count/)
  assert.match(athletesListViewSource, /Athlete name/)
  assert.match(athletesListViewSource, /Training Program/)
  assert.match(athletesListViewSource, /Thomas Thibault/)
  assert.match(athletesListViewSource, /1\/01\/2011 \(15 year old\)/)
  assert.match(athletesListViewSource, /admin-shell-athletes-name-meta/)
  assert.match(athletesListViewSource, /12 \/ 40/)
  assert.match(athletesListViewSource, /5\/17\/2026/)
  assert.match(athletesListViewSource, /Rows per page:/)
  assert.match(athletesListViewSource, /admin-shell-athletes-toolbar/)
  assert.match(athletesListViewSource, /admin-shell-athletes-table-card/)
  assert.match(athletesListViewSource, /admin-shell-athletes-status-badge/)
  assert.match(athletesListViewSource, /admin-shell-athletes-progress-fill/)
  assert.match(athletesListViewSource, /admin-shell-athletes-pagination/)

  assert.match(invitesListViewSource, /'use client'/)
  assert.match(invitesListViewSource, /from 'lucide-react'/)
  assert.match(invitesListViewSource, /from '\.\.\/ui\/avatar'/)
  assert.match(invitesListViewSource, /ArrowUpAZ/)
  assert.match(invitesListViewSource, /ArrowUpZA/)
  assert.match(invitesListViewSource, /ChevronDown/)
  assert.match(invitesListViewSource, /MoreHorizontal/)
  assert.match(invitesListViewSource, /Search/)
  assert.match(invitesListViewSource, /Send/)
  assert.match(invitesListViewSource, /SortLabel/)
  assert.match(invitesListViewSource, /Invites/)
  assert.match(invitesListViewSource, /Search for an athlete by name\.\.\./)
  assert.match(invitesListViewSource, /Invite an athlete/)
  assert.match(invitesListViewSource, /Athlete name/)
  assert.match(invitesListViewSource, /Role/)
  assert.match(invitesListViewSource, /Join date/)
  assert.match(invitesListViewSource, /Status/)
  assert.match(invitesListViewSource, /Thomas Thibault/)
  assert.match(invitesListViewSource, /thomas@gmail\.com/)
  assert.match(invitesListViewSource, /Athlete/)
  assert.match(invitesListViewSource, /5\/17\/2026/)
  assert.match(invitesListViewSource, /Active/)
  assert.match(invitesListViewSource, /Pending/)
  assert.match(invitesListViewSource, /1 - 10 of 256/)
  assert.match(invitesListViewSource, /Rows per page:/)
  assert.match(invitesListViewSource, /aria-label=\{`Open actions for \$\{invite\.name\}`\}/)
  assert.match(invitesListViewSource, /admin-shell-invites-view/)
  assert.match(invitesListViewSource, /admin-shell-invites-table-card/)
  assert.match(invitesListViewSource, /admin-shell-invites-status-badge/)
  assert.match(invitesListViewSource, /admin-shell-invites-status-badge-pending/)
  assert.match(invitesListViewSource, /admin-shell-invites-role-chip/)
  assert.match(invitesListViewSource, /admin-shell-invites-pagination/)

  assert.match(groupsListViewSource, /'use client'/)
  assert.match(groupsListViewSource, /from 'lucide-react'/)
  assert.match(groupsListViewSource, /ArrowUpAZ/)
  assert.match(groupsListViewSource, /ArrowUpZA/)
  assert.match(groupsListViewSource, /ChevronDown/)
  assert.match(groupsListViewSource, /MoreHorizontal/)
  assert.match(groupsListViewSource, /Search/)
  assert.match(groupsListViewSource, /Plus/)
  assert.match(groupsListViewSource, /Groups/)
  assert.match(groupsListViewSource, /Search for a group by name\.\.\./)
  assert.match(groupsListViewSource, /Create a group/)
  assert.match(groupsListViewSource, /Group name/)
  assert.match(groupsListViewSource, /Access/)
  assert.match(groupsListViewSource, /Created date/)
  assert.match(groupsListViewSource, /Status/)
  assert.match(groupsListViewSource, /Group 1/)
  assert.match(groupsListViewSource, /Groupe 2/)
  assert.match(groupsListViewSource, /Groupe 10/)
  assert.match(groupsListViewSource, /7 athletes/)
  assert.match(groupsListViewSource, /Public/)
  assert.match(groupsListViewSource, /Private/)
  assert.match(groupsListViewSource, /5\/17\/2026/)
  assert.match(groupsListViewSource, /Active/)
  assert.match(groupsListViewSource, /1 - 10 of 256/)
  assert.match(groupsListViewSource, /Rows per page:/)
  assert.match(groupsListViewSource, /aria-label=\{`Open actions for \$\{group\.name\}`\}/)
  assert.match(groupsListViewSource, /admin-shell-groups-view/)
  assert.match(groupsListViewSource, /admin-shell-groups-table-card/)
  assert.match(groupsListViewSource, /admin-shell-groups-access-chip/)
  assert.match(groupsListViewSource, /admin-shell-groups-status-badge/)
  assert.match(groupsListViewSource, /admin-shell-groups-pagination/)

  assert.match(rankingsListViewSource, /'use client'/)
  assert.match(rankingsListViewSource, /from 'lucide-react'/)
  assert.match(rankingsListViewSource, /from '\.\.\/ui\/avatar'/)
  assert.match(rankingsListViewSource, /ArrowUpAZ/)
  assert.match(rankingsListViewSource, /ArrowUpZA/)
  assert.match(rankingsListViewSource, /Search/)
  assert.match(rankingsListViewSource, /gold_badge\.svg/)
  assert.match(rankingsListViewSource, /silver_badge\.svg/)
  assert.match(rankingsListViewSource, /bronze_badget\.svg/)
  assert.match(rankingsListViewSource, /Rankings/)
  assert.match(rankingsListViewSource, /Search for an athlete by name\.\.\./)
  assert.match(rankingsListViewSource, /Athlete name/)
  assert.match(rankingsListViewSource, /Program/)
  assert.match(rankingsListViewSource, /Workouts/)
  assert.match(rankingsListViewSource, /Last active/)
  assert.match(rankingsListViewSource, /Status/)
  assert.match(rankingsListViewSource, /Thomas Thibault/)
  assert.match(rankingsListViewSource, /1\/01\/2011 \(15 year old\)/)
  assert.match(rankingsListViewSource, /Training Program/)
  assert.match(rankingsListViewSource, /34 \/ 40/)
  assert.match(rankingsListViewSource, /29 \/ 40/)
  assert.match(rankingsListViewSource, /16 \/ 40/)
  assert.match(rankingsListViewSource, /5\/17\/2026/)
  assert.match(rankingsListViewSource, /Active/)
  assert.match(rankingsListViewSource, /1 - 10 of 256/)
  assert.match(rankingsListViewSource, /Rows per page:/)
  assert.match(rankingsListViewSource, /admin-shell-rankings-view/)
  assert.match(rankingsListViewSource, /admin-shell-rankings-table-card/)
  assert.match(rankingsListViewSource, /admin-shell-rankings-rank-badge-image/)
  assert.match(rankingsListViewSource, /admin-shell-rankings-progress-fill/)
  assert.match(rankingsListViewSource, /admin-shell-rankings-status-badge/)
  assert.match(rankingsListViewSource, /admin-shell-rankings-pagination/)

  assert.match(adminButtonSource, /export default function AdminButton/)
  assert.match(adminButtonSource, /children/)
  assert.match(adminButtonSource, /variant = 'primary'/)
  assert.match(adminButtonSource, /primary: ''/)
  assert.match(adminButtonSource, /secondary: 'admin-button-secondary'/)
  assert.match(adminButtonSource, /ghost: 'admin-button-ghost'/)
  assert.match(adminButtonSource, /danger: 'admin-button-danger'/)
  assert.match(adminButtonSource, /compact: 'admin-button-compact'/)
  assert.match(adminButtonSource, /default: 'admin-button-default'/)
  assert.match(adminButtonSource, /prominent: 'admin-button-prominent'/)
  assert.match(adminButtonSource, /className = ''/)
  assert.match(adminButtonSource, /\['admin-button', variantClass, sizeClass, className\]/)

  assert.match(adminNavigationSource, /href: '\/admin\/dashboard'/)
  assert.match(adminNavigationSource, /title: 'Overview'/)
  assert.match(adminNavigationSource, /description: 'Here is an overview of your platform\.'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/dashboard\/today'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/dashboard\/alerts'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/dashboard\/recent-activity'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Recent activity'/)
  assert.match(adminNavigationSource, /href: '\/admin\/athletes'/)
  assert.match(adminNavigationSource, /href: '\/admin\/programs'/)
  assert.match(adminNavigationSource, /href: '\/admin\/workouts'/)
  assert.match(adminNavigationSource, /href: '\/admin\/exercises'/)
  assert.match(adminNavigationSource, /href: '\/admin\/analytics'/)
  assert.match(adminNavigationSource, /href: '\/admin\/settings'/)
  assert.match(adminNavigationSource, /href: '\/admin\/athletes\/groups'/)
  assert.match(adminNavigationSource, /href: '\/admin\/athletes\/rankings'/)
  assert.match(adminNavigationSource, /label: 'Rankings'/)
  assert.match(adminNavigationSource, /title: 'Athlete rankings'/)
  assert.doesNotMatch(adminNavigationSource, /href: '\/admin\/athletes\/progress'/)
  assert.doesNotMatch(adminNavigationSource, /label: 'Progress'/)
  assert.doesNotMatch(adminNavigationSource, /title: 'Athlete progress'/)
  assert.match(adminNavigationSource, /href: '\/admin\/programs\/templates'/)
  assert.match(adminNavigationSource, /href: '\/admin\/workouts\/sessions'/)
  assert.match(adminNavigationSource, /href: '\/admin\/analytics\/compliance'/)
  assert.match(adminNavigationSource, /href: '\/admin\/settings\/team'/)
  assert.match(adminNavigationSource, /defaultHref/)

  assert.match(sidebarSource, /from 'next\/link'/)
  assert.match(sidebarSource, /currentPath\s*=\s*''/)
  assert.match(sidebarSource, /href\s*=\s*''/)
  assert.match(sidebarSource, /<Link/)
  assert.match(sidebarSource, /ui-sidebar-group-button-current/)
  assert.match(sidebarSource, /ui-sidebar-subitem-current/)
  assert.match(sidebarSource, /const isExpanded = isActive && Boolean\(group\.items\?\.length\)/)
  assert.match(sidebarSource, /const showChevron = Boolean\(group\.items\?\.length\)/)
  assert.match(sidebarSource, /showChevron \?/)
  assert.doesNotMatch(sidebarSource, /const isExpanded = isActive\n/)
  assert.match(sidebarSource, /startsWith\(/)

  assert.match(cssSource, /\.ui-sidebar\s*\{[\s\S]*max-width:\s*236px;/)
  assert.match(cssSource, /\.ui-sidebar\s*\{[\s\S]*border-radius:\s*0;/)
  assert.match(cssSource, /\.ui-sidebar\s*\{[\s\S]*box-shadow:\s*none;/)
  assert.match(cssSource, /\.ui-sidebar\s*\{[\s\S]*border-right:\s*1px solid/)
  assert.match(cssSource, /\.ui-sidebar-layout\s*\{[\s\S]*gap:\s*0;/)
  assert.match(cssSource, /\.ui-sidebar-layout\s*\{[\s\S]*padding:\s*0;/)
  assert.match(cssSource, /\.ui-sidebar-search\s*\{[\s\S]*min-height:\s*36px;/)
  assert.match(cssSource, /\.ui-sidebar-group-button\s*\{[\s\S]*grid-template-columns:\s*auto 1fr auto;/)
  assert.match(cssSource, /\.ui-sidebar-subitem-current::before\s*\{[\s\S]*width:\s*2px;/)
  assert.match(cssSource, /\.admin-shell-workspace\s*\{[\s\S]*min-height:\s*calc\(100vh - 16px\);/)
  assert.match(cssSource, /\.admin-shell-workspace-title\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-overview-range-button\s*\{[\s\S]*border-radius:\s*999px;/)
  assert.match(cssSource, /\.admin-shell-overview-range-menu\s*\{[\s\S]*position:\s*absolute;/)
  assert.match(cssSource, /\.admin-shell-overview-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(5, minmax\(0, 1fr\)\);/)
  assert.match(cssSource, /\.admin-shell-overview-card-header\s*\{[\s\S]*display:\s*flex;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value-row\s*\{[\s\S]*align-items:\s*center;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value-row\s*\{[\s\S]*justify-content:\s*flex-start;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-card-icon-shell\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-overview-card\s*\{[^}]*min-height:/)
  assert.match(cssSource, /\.admin-shell-overview-card\s*\{[\s\S]*align-content:\s*start;/)
  assert.match(cssSource, /\.admin-shell-overview-card\s*\{[\s\S]*gap:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-card\s*\{[\s\S]*border-radius:\s*24px;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value\s*\{[\s\S]*font-size:\s*2\.1rem;/)
  assert.match(cssSource, /\.admin-shell-overview-card-value\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-card-change-negative\s*\{[\s\S]*color:\s*#ff8d8d;/)
  assert.match(cssSource, /\.admin-shell-overview-card-change-arrow-icon\s*\{[\s\S]*width:\s*0\.82rem;/)
  assert.match(cssSource, /\.admin-shell-overview-analytics-layout\s*\{[\s\S]*grid-template-columns:\s*minmax\(0, 1\.75fr\) minmax\(280px, 0\.92fr\);/)
  assert.match(cssSource, /\.admin-shell-overview-performance-panel\s*\{[\s\S]*padding:\s*26px;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input\s*\{[\s\S]*appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input\s*\{[\s\S]*-webkit-appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input\s*\{[\s\S]*width:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input\s*\{[\s\S]*height:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input\s*\{[\s\S]*border-radius:\s*3px;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input\s*\{[\s\S]*border:\s*1px solid rgba\(72, 88, 116, 0\.95\);/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input\s*\{[\s\S]*background:\s*#111a2c;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input:checked\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input:checked\s*\{[\s\S]*background-image:\s*url\(/)
  assert.match(cssSource, /\.admin-shell-athletes-checkbox-cell input\s*\{[\s\S]*background-size:\s*8px 8px;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-label\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-button\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-button\s*\{[\s\S]*cursor:\s*pointer;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-button\s*\{[\s\S]*background:\s*transparent;/)
  assert.match(cssSource, /\.admin-shell-athletes-sort-icon\s*\{[\s\S]*width:\s*12px;/)
  assert.match(cssSource, /\.admin-shell-athletes-name-copy\s*\{[\s\S]*display:\s*grid;/)
  assert.match(cssSource, /\.admin-shell-athletes-name-copy\s*\{[\s\S]*gap:\s*2px;/)
  assert.match(cssSource, /\.admin-shell-athletes-name-meta\s*\{[\s\S]*color:\s*#8ea0bc;/)
  assert.match(cssSource, /\.admin-shell-athletes-name-meta\s*\{[\s\S]*font-size:\s*0\.72rem;/)

  assert.match(cssSource, /\.admin-shell-overview-performance-value\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-chart\s*\{[\s\S]*min-height:\s*320px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-meta\s*\{[\s\S]*display:\s*flex;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-meta\s*\{[\s\S]*justify-items:\s*flex-start;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-meta\s*\{[\s\S]*gap:\s*8px;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-legend\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-legend-dot-completed\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-legend-dot-assigned\s*\{[\s\S]*background:\s*#58c6ff;/)
  assert.match(cssSource, /\.admin-shell-overview-performance-tooltip\s*\{[\s\S]*position:\s*absolute;/)
  assert.match(cssSource, /\.admin-shell-overview-side-column\s*\{[\s\S]*grid-template-rows:\s*repeat\(2, minmax\(0, 1fr\)\);/)
  assert.match(cssSource, /\.admin-shell-overview-insight-card\s*\{[\s\S]*min-height:\s*198px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-row\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-row\s*\{[\s\S]*align-items:\s*center;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-icon\s*\{[\s\S]*width:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-label-icon\s*\{[\s\S]*height:\s*16px;/)
  assert.match(cssSource, /\.admin-shell-overview-insight-value\s*\{[\s\S]*font-weight:\s*900;/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bars\s*\{[\s\S]*align-items:\s*end;/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bar-completed\s*\{[\s\S]*rgba\(59, 224, 175, 0\.96\)[\s\S]*rgba\(31, 176, 135, 0\.72\)/)
  assert.match(cssSource, /\.admin-shell-overview-mini-bar-assigned\s*\{[\s\S]*rgba\(88, 198, 255, 0\.96\)[\s\S]*rgba\(58, 154, 232, 0\.72\)/)
  assert.match(cssSource, /\.admin-shell-overview-session-chart\s*\{[\s\S]*min-height:\s*132px;/)
  assert.match(cssSource, /\.admin-shell-overview-chart-point\s*\{[\s\S]*fill:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-overview-chart-point-active\s*\{[\s\S]*fill:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-overview-chart-point-active\s*\{[\s\S]*stroke:\s*#f5f8ff;/)
  assert.match(cssSource, /\.admin-shell-workspace-panel\s*\{[\s\S]*width:\s*min\(100%, 520px\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*gap:\s*8px;/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*border:\s*1px solid var\(--admin-accent-outline\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*background:\s*rgba\(8, 27, 24, 0\.9\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*color:\s*var\(--admin-accent\);/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*font-weight:\s*600;/)
  assert.match(cssSource, /\.admin-button\s*\{[\s\S]*box-shadow:\s*none;/)
  assert.match(cssSource, /\.admin-button-default\s*\{[\s\S]*min-height:\s*40px;/)
  assert.match(cssSource, /\.admin-button-default\s*\{[\s\S]*padding:\s*0 14px;/)
  assert.match(cssSource, /\.admin-button-default\s*\{[\s\S]*border-radius:\s*8px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-button\s*\{[\s\S]*justify-self:\s*end;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-button-icon\s*\{[\s\S]*width:\s*14px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-button-icon\s*\{[\s\S]*height:\s*14px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog\s*\{[\s\S]*width:\s*min\(100%, 800px\);/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog\s*\{[\s\S]*padding:\s*32px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-close\s*\{[\s\S]*position:\s*absolute;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-illustration\s*\{[\s\S]*margin:\s*0 auto;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-field input\s*\{[\s\S]*min-height:\s*46px;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-submit\s*\{[\s\S]*justify-self:\s*end;/)
  assert.match(cssSource, /\.admin-shell-athletes-invite-dialog-submit\s*\{[\s\S]*min-height:\s*40px;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-invite-dialog-submit\s*\{[^}]*background:\s*#3be0af;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-invite-button\s*\{[^}]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-athletes-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-athletes-top-search\s*\{[\s\S]*min-height:\s*40px;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-table-card-header\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-table-card-title\s*\{/)
  assert.doesNotMatch(cssSource, /\.admin-shell-athletes-table-card-count\s*\{/)
  assert.match(cssSource, /\.admin-shell-athletes-table-card\s*\{[\s\S]*border-radius:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-athletes-table\s*\{[\s\S]*border-collapse:\s*separate;/)
  assert.match(cssSource, /\.admin-shell-athletes-status-badge\s*\{[\s\S]*color:\s*#66efbf;/)
  assert.match(cssSource, /\.admin-shell-athletes-progress-fill\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-athletes-pagination\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-invites-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-invites-table-card\s*\{[\s\S]*border-radius:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-invites-table-card\s*\{[\s\S]*padding:\s*20px 28px 22px;/)
  assert.match(cssSource, /\.admin-shell-invites-table\s*\{[\s\S]*border-collapse:\s*separate;/)
  assert.match(cssSource, /\.admin-shell-invites-table-shell\s*\{[\s\S]*overflow:\s*hidden;/)
  assert.doesNotMatch(cssSource, /\.admin-shell-invites-table-shell\s*\{[\s\S]*padding-top:/)
  assert.match(cssSource, /\.admin-shell-invites-checkbox-cell input\s*\{[\s\S]*appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-invites-checkbox-cell input\s*\{[\s\S]*width:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-invites-checkbox-cell input:checked\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-invites-role-chip\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-invites-role-chip\s*\{[\s\S]*border:\s*1px solid rgba\(58, 73, 101, 0\.95\);/)
  assert.match(cssSource, /\.admin-shell-invites-avatar\s*\{[\s\S]*width:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-invites-status-badge\s*\{[\s\S]*color:\s*#66efbf;/)
  assert.match(cssSource, /\.admin-shell-invites-status-badge-pending\s*\{[\s\S]*color:\s*#f1c76a;/)
  assert.match(cssSource, /\.admin-shell-invites-status-dot-pending\s*\{[\s\S]*background:\s*#f1c76a;/)
  assert.match(cssSource, /\.admin-shell-invites-pagination\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-groups-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-groups-top-search\s*\{[\s\S]*min-height:\s*40px;/)
  assert.match(cssSource, /\.admin-shell-groups-create-button\s*\{[\s\S]*justify-self:\s*end;/)
  assert.match(cssSource, /\.admin-shell-groups-table-card\s*\{[\s\S]*border-radius:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-groups-table\s*\{[\s\S]*border-collapse:\s*separate;/)
  assert.match(cssSource, /\.admin-shell-groups-checkbox-cell input\s*\{[\s\S]*appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-groups-checkbox-cell input\s*\{[\s\S]*width:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-groups-checkbox-cell input:checked\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-groups-name-meta\s*\{[\s\S]*font-size:\s*0\.72rem;/)
  assert.match(cssSource, /\.admin-shell-groups-access-chip\s*\{[\s\S]*display:\s*inline-flex;/)
  assert.match(cssSource, /\.admin-shell-groups-access-chip\s*\{[\s\S]*border:\s*1px solid rgba\(58, 73, 101, 0\.95\);/)
  assert.match(cssSource, /\.admin-shell-groups-status-badge\s*\{[\s\S]*color:\s*#66efbf;/)
  assert.match(cssSource, /\.admin-shell-groups-pagination\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-rankings-toolbar\s*\{[\s\S]*justify-content:\s*space-between;/)
  assert.match(cssSource, /\.admin-shell-rankings-top-search\s*\{[\s\S]*min-height:\s*40px;/)
  assert.match(cssSource, /\.admin-shell-rankings-table-card\s*\{[\s\S]*border-radius:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-rankings-table\s*\{[\s\S]*border-collapse:\s*separate;/)
  assert.match(cssSource, /\.admin-shell-rankings-checkbox-cell input\s*\{[\s\S]*appearance:\s*none;/)
  assert.match(cssSource, /\.admin-shell-rankings-checkbox-cell input\s*\{[\s\S]*width:\s*20px;/)
  assert.match(cssSource, /\.admin-shell-rankings-checkbox-cell input:checked\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-rankings-rank-badge-image\s*\{[\s\S]*width:\s*28px;/)
  assert.match(cssSource, /\.admin-shell-rankings-rank-number\s*\{[\s\S]*font-weight:\s*700;/)
  assert.match(cssSource, /\.admin-shell-rankings-name-meta\s*\{[\s\S]*font-size:\s*0\.72rem;/)
  assert.match(cssSource, /\.admin-shell-rankings-progress-fill\s*\{[\s\S]*background:\s*#3be0af;/)
  assert.match(cssSource, /\.admin-shell-rankings-status-badge\s*\{[\s\S]*color:\s*#66efbf;/)
  assert.match(cssSource, /\.admin-shell-rankings-pagination\s*\{[\s\S]*justify-content:\s*space-between;/)

  assert.match(rulesetSource, /reference standard UI kit/i)
  assert.match(rulesetSource, /components\/ui/i)
})
