import test from 'node:test'
import assert from 'node:assert/strict'
import { existsSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const athletesDataTablePath = resolve(repoRoot, 'apps/web/components/admin/athletes-data-table.jsx')
const tabsPath = resolve(repoRoot, 'apps/web/components/ui/tabs.jsx')
const dialogPath = resolve(repoRoot, 'apps/web/components/ui/dialog.jsx')
const sheetPath = resolve(repoRoot, 'apps/web/components/ui/sheet.jsx')
const adminAthleteRepositoryPath = resolve(repoRoot, 'apps/web/lib/admin-athlete-repository.js')
const adminAthleteRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/athletes/route.js')
const adminInviteRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/invites/route.js')
const appLayoutPath = resolve(repoRoot, 'apps/web/app/layout.jsx')
const toastHookPath = resolve(repoRoot, 'apps/web/hooks/use-toast.js')
const baseToastPath = resolve(repoRoot, 'apps/web/components/ui/base-toast.jsx')

test('create athlete dialog uses the athlete profile form layout instead of invite copy', () => {
  assert.ok(existsSync(athletesDataTablePath), `expected athletes data table file to exist: ${athletesDataTablePath}`)
  assert.ok(existsSync(tabsPath), `expected shared tabs primitive to exist: ${tabsPath}`)
  assert.ok(existsSync(dialogPath), `expected shared dialog primitive to exist: ${dialogPath}`)
  assert.ok(existsSync(sheetPath), `expected shared sheet primitive to exist: ${sheetPath}`)
  assert.ok(existsSync(adminAthleteRepositoryPath), `expected admin athlete repository file to exist: ${adminAthleteRepositoryPath}`)
  assert.ok(existsSync(adminAthleteRoutePath), `expected admin athlete route file to exist: ${adminAthleteRoutePath}`)
  assert.ok(existsSync(adminInviteRoutePath), `expected admin invite route file to exist: ${adminInviteRoutePath}`)
  assert.ok(existsSync(appLayoutPath), `expected app layout file to exist: ${appLayoutPath}`)
  assert.ok(existsSync(toastHookPath), `expected toast hook file to exist: ${toastHookPath}`)
  assert.ok(existsSync(baseToastPath), `expected base toast file to exist: ${baseToastPath}`)

  const athletesDataTableSource = readFileSync(athletesDataTablePath, 'utf8')
  const tabsSource = readFileSync(tabsPath, 'utf8')
  const dialogSource = readFileSync(dialogPath, 'utf8')
  const adminAthleteRepositorySource = readFileSync(adminAthleteRepositoryPath, 'utf8')
  const adminAthleteRouteSource = readFileSync(adminAthleteRoutePath, 'utf8')
  const adminInviteRouteSource = readFileSync(adminInviteRoutePath, 'utf8')
  const appLayoutSource = readFileSync(appLayoutPath, 'utf8')
  const toastHookSource = readFileSync(toastHookPath, 'utf8')
  const baseToastSource = readFileSync(baseToastPath, 'utf8')

  assert.match(athletesDataTableSource, /from '@\/components\/ui\/input'/)
  assert.match(athletesDataTableSource, /import Checkbox from '@\/components\/ui\/checkbox'/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/select'/)
  assert.match(athletesDataTableSource, /import \{ Skeleton \} from '@\/components\/ui\/skeleton'/)
  assert.match(athletesDataTableSource, /athleteDialogMode === 'edit' \? 'Edit athlete profile' : 'Create athlete profile'/)
  assert.match(athletesDataTableSource, /athleteDialogMode === 'edit'[\s\S]*Update the information below\.[\s\S]*Fill out the information below\./)
  assert.doesNotMatch(athletesDataTableSource, /Add the athlete's personal details, profile photo, and preferred measurements\./)
  assert.doesNotMatch(athletesDataTableSource, /Update the athlete's personal details, profile photo, and preferred measurements\./)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-form/)
  assert.match(athletesDataTableSource, /from '@\/components\/ui\/sheet'/)
  assert.match(athletesDataTableSource, /<Sheet open=\{isCreateEditAthleteDialogOpen\} onOpenChange=\{\(open\) => \{[\s\S]*setIsCreateEditAthleteDialogOpen\(open\)[\s\S]*setAthleteDialogMode\('create'\)[\s\S]*setEditingAthleteId\(null\)[\s\S]*setSendAthleteInvite\(true\)[\s\S]*\}\}>/)
  assert.match(athletesDataTableSource, /<SheetContent side="right" className="admin-shell-athletes-create-sheet border-l !border-\[color:var\(--admin-dashboard-card-border\)\] bg-\[var\(--admin-dashboard-card-bg\)\] p-0 text-\[var\(--admin-dashboard-card-text\)\] !max-w-\[var\(--container-lg\)\]">/)
  assert.doesNotMatch(athletesDataTableSource, /admin-shell-athletes-create-sheet[^\"]*sm:max-w-\[720px\]/)
  assert.match(athletesDataTableSource, /<SheetHeader className="shrink-0 border-b !border-\[color:var\(--admin-dashboard-card-border\)\] px-6 py-5">/)
  assert.match(athletesDataTableSource, /<SheetTitle className="text-\[var\(--admin-dashboard-card-text\)\]">\{athleteDialogMode === 'edit' \? 'Edit athlete profile' : 'Create athlete profile'\}<\/SheetTitle>/)
  assert.match(athletesDataTableSource, /<SheetDescription className="text-\[var\(--admin-dashboard-card-muted\)\]">/)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-sheet-scroll min-h-0 flex-1 overflow-y-auto px-6 py-6 \[scrollbar-width:none\] \[-ms-overflow-style:none\] \[&::-webkit-scrollbar\]:hidden/)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-sheet-footer shrink-0 border-t !border-\[color:var\(--admin-dashboard-card-border\)\] px-6 py-5/)
  assert.doesNotMatch(athletesDataTableSource, /<Dialog open=\{isCreateEditAthleteDialogOpen\}/)
  assert.doesNotMatch(athletesDataTableSource, /<DialogContent[\s\S]*Edit athlete profile/)
  assert.doesNotMatch(athletesDataTableSource, /pageScrollable/)
  assert.match(athletesDataTableSource, /Upload avatar/)
  assert.match(athletesDataTableSource, /Avatar uploaded/)
  assert.match(athletesDataTableSource, /PNG, JPG up to 2MB/)
  assert.match(athletesDataTableSource, /type="file"/)
  assert.match(athletesDataTableSource, /value=\{createAthleteFirstName\}/)
  assert.match(athletesDataTableSource, /value=\{createAthleteLastName\}/)
  assert.match(athletesDataTableSource, /value=\{createAthleteDateOfBirth\}/)
  assert.match(athletesDataTableSource, /<button id="create-athlete-gender" type="button" className="admin-shell-athletes-example-columns-button admin-shell-athletes-create-select-trigger w-full" aria-label="Gender">/)
  assert.match(athletesDataTableSource, /<button id="create-athlete-position" type="button" className="admin-shell-athletes-example-columns-button admin-shell-athletes-create-select-trigger w-full" aria-label="Position">/)
  assert.match(athletesDataTableSource, /<DropdownMenuItem onSelect=\{\(\) => setCreateAthletePosition\('forward'\)\}>Forward<\/DropdownMenuItem>/)
  assert.match(athletesDataTableSource, /<DropdownMenuItem onSelect=\{\(\) => setCreateAthletePosition\('defense'\)\}>Defense<\/DropdownMenuItem>/)
  assert.match(athletesDataTableSource, /<DropdownMenuItem onSelect=\{\(\) => setCreateAthletePosition\('goalie'\)\}>Goalie<\/DropdownMenuItem>/)
  assert.match(athletesDataTableSource, /<DropdownMenuItem onSelect=\{\(\) => setCreateAthleteGender\('male'\)\}>Male<\/DropdownMenuItem>/)
  assert.match(athletesDataTableSource, /<DropdownMenuItem onSelect=\{\(\) => setCreateAthleteGender\('female'\)\}>Female<\/DropdownMenuItem>/)
  assert.match(athletesDataTableSource, /<DropdownMenuItem onSelect=\{\(\) => setCreateAthleteGender\('other'\)\}>Other<\/DropdownMenuItem>/)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-row admin-shell-athletes-create-row-two-up/)
  assert.match(athletesDataTableSource, /admin-shell-athletes-create-uploader relative flex w-full cursor-pointer flex-col items-center justify-center gap-4 px-6 py-2 text-center/)
  assert.match(athletesDataTableSource, /<div className="relative h-\[120px\] w-\[120px\] self-center">/)
  assert.match(athletesDataTableSource, /className="h-full w-full rounded-\[360px\] border !border-\[color:var\(--admin-dashboard-card-border\)\] bg-\[var\(--admin-dashboard-card-bg\)\] text-lg font-semibold text-\[var\(--admin-dashboard-card-text\)\] object-cover"/)
  assert.match(athletesDataTableSource, /className="absolute right-3 top-3 flex h-7 w-7 items-center justify-center rounded-full border !border-\[color:var\(--admin-dashboard-card-border\)\] bg-\[var\(--admin-dashboard-control-bg\)\] text-sm font-medium text-\[var\(--admin-shell-text-strong\)\]/)
  assert.match(athletesDataTableSource, /const athleteFilterRangeInputClassName = 'h-8 w-28 !border-0 bg-\[var\(--admin-dashboard-card-bg\)\] text-\[var\(--admin-dashboard-card-text\)\] shadow-none placeholder:text-\[var\(--admin-dashboard-card-muted\)\] focus-visible:!border-0 focus-visible:ring-0'/)
  assert.match(athletesDataTableSource, /className=\{athleteFilterRangeInputClassName\}/)
  assert.match(athletesDataTableSource, /const \[createAthleteDateOfBirth, setCreateAthleteDateOfBirth\] = useState\(''\)/)
  assert.match(athletesDataTableSource, /const \[createAthleteGender, setCreateAthleteGender\] = useState\('male'\)/)
  assert.match(athletesDataTableSource, /const \[createAthletePosition, setCreateAthletePosition\] = useState\('forward'\)/)
  assert.match(athletesDataTableSource, /const \[createAthleteHeightImperial, setCreateAthleteHeightImperial\] = useState\(''\)/)
  assert.match(athletesDataTableSource, /const \[createAthleteWeightImperial, setCreateAthleteWeightImperial\] = useState\(''\)/)
  assert.match(athletesDataTableSource, /const \[createAthleteHeightMetric, setCreateAthleteHeightMetric\] = useState\(''\)/)
  assert.match(athletesDataTableSource, /const \[createAthleteWeightMetric, setCreateAthleteWeightMetric\] = useState\(''\)/)
  assert.match(athletesDataTableSource, /const \[createAthleteInviteEmail, setCreateAthleteInviteEmail\] = useState\(''\)/)
  assert.match(athletesDataTableSource, /const \[inviteAthleteEmail, setInviteAthleteEmail\] = useState\(''\)/)
  assert.match(athletesDataTableSource, /const emptyStateMessage = error \|\| \(athleteFilters\.length > 0 \? 'No athletes match the current filters\.' : 'No results\.'\)/)
  assert.match(athletesDataTableSource, /const skeletonRows = Array\.from\(\{ length: pagination\.pageSize \}/)
  assert.match(athletesDataTableSource, /\{loading \? \([\s\S]*<TableRow key=\{`skeleton-\$\{rowIndex\}`\}/)
  assert.match(athletesDataTableSource, /<Skeleton className="h-4 w-4 rounded-\[4px\]" \/>/)
  assert.match(athletesDataTableSource, /<Skeleton className="h-10 w-10 rounded-full" \/>/)
  assert.match(athletesDataTableSource, /<Skeleton className="h-4 w-\[140px\]" \/>/)
  assert.match(athletesDataTableSource, /<Skeleton className="h-3 w-\[96px\]" \/>/)
  assert.match(athletesDataTableSource, /<Skeleton className="h-8 w-\[132px\] rounded-full" \/>/)
  assert.match(athletesDataTableSource, /function resetCreateAthleteForm\(\)/)
  assert.match(athletesDataTableSource, /function populateCreateAthleteFormFromAthlete\(athlete\)/)
  assert.match(athletesDataTableSource, /setCreateAthleteFirstName\(athlete\.firstName \?\? ''\)/)
  assert.match(athletesDataTableSource, /setCreateAthleteLastName\(athlete\.lastName \?\? ''\)/)
  assert.match(athletesDataTableSource, /setCreateAthleteDateOfBirth\(athlete\.dateOfBirth \?\? ''\)/)
  assert.match(athletesDataTableSource, /setCreateAthleteGender\(normalizeAthleteGender\(athlete\.gender\)\)/)
  assert.match(athletesDataTableSource, /setCreateAthletePosition\(normalizeAthletePosition\(athlete\.position\)\)/)
  assert.match(athletesDataTableSource, /function normalizeAthleteGender\(gender\)/)
  assert.match(athletesDataTableSource, /function normalizeAthletePosition\(position\)/)
  assert.match(athletesDataTableSource, /setCreateAthleteProfileImage\(athlete\.avatarUrl \?\? ''\)/)
  assert.match(athletesDataTableSource, /setCreateAthleteMeasurementUnit\('imperial'\)/)
  assert.match(athletesDataTableSource, /setCreateAthleteInviteEmail\(''\)/)
  assert.match(athletesDataTableSource, /setSendAthleteInvite\(true\)/)

  assert.match(athletesDataTableSource, /setCreateAthleteWeightImperial\(/)
  assert.match(athletesDataTableSource, /if \(athleteDialogMode === 'edit' && selectedAthlete\) \{[\s\S]*populateCreateAthleteFormFromAthlete\(selectedAthlete\)/)
  assert.match(athletesDataTableSource, /if \(athleteDialogMode === 'create'\) \{[\s\S]*resetCreateAthleteForm\(\)/)
  assert.match(athletesDataTableSource, /onEditAction=\{\(\) => setPendingRowAction\(\{ type: 'edit', athleteId: row\.original\.id \}\)\}/)
  assert.match(athletesDataTableSource, /const canSendInvite = row\.original\.status !== 'Active'/)
  assert.match(athletesDataTableSource, /const inviteActionLabel = row\.original\.hasInvite \? 'Resend invite' : 'Send invite'/)
  assert.match(athletesDataTableSource, /onSendInviteAction=\{canSendInvite \? \(\) => setPendingRowAction\(\{ type: 'sendInvite', athleteId: row\.original\.id \}\) : null\}/)
  assert.match(athletesDataTableSource, /inviteActionLabel=\{inviteActionLabel\}/)
  assert.match(athletesDataTableSource, /typeof onSendInviteAction === 'function' \? \(\s*<DropdownMenuItem/)
  assert.match(athletesDataTableSource, /\{inviteActionLabel\}/)
  assert.doesNotMatch(athletesDataTableSource, /onSendInviteAction=\{row\.original\.status !== 'Active' \? \(\) => setPendingRowAction\(\{ type: 'sendInvite', athleteId: row\.original\.id \}\) : null\}/)
  assert.match(athletesDataTableSource, /setAthleteDialogMode\('edit'\)/)
  assert.match(athletesDataTableSource, /setEditingAthleteId\(pendingRowAction\.athleteId\)/)
  assert.match(athletesDataTableSource, /setAthleteDialogMode\('create'\)/)
  assert.match(athletesDataTableSource, /setEditingAthleteId\(null\)/)
  assert.match(athletesDataTableSource, /setSendAthleteInvite\(true\)/)
  assert.match(athletesDataTableSource, /Send an invite to this athlete/)
  assert.match(athletesDataTableSource, /checked=\{sendAthleteInvite\}/)
  assert.match(athletesDataTableSource, /onChange=\{\(event\) => setSendAthleteInvite\(event\.target\.checked\)\}/)
  assert.match(athletesDataTableSource, /athleteDialogMode === 'create'[\s\S]*sendAthleteInvite \? /)
  assert.match(athletesDataTableSource, /sendAthleteInvite \? \(\s*<CreateAthleteDialogField htmlFor="create-athlete-invite-email" label="Email">/)
  assert.match(athletesDataTableSource, /<CreateAthleteDialogField htmlFor="create-athlete-invite-email" label="Email">/)
  assert.match(athletesDataTableSource, /id="create-athlete-invite-email"/)
  assert.match(athletesDataTableSource, /type="email"/)
  assert.match(athletesDataTableSource, /placeholder="athlete@email\.com"/)
  assert.match(athletesDataTableSource, /value=\{createAthleteInviteEmail\}/)
  assert.match(athletesDataTableSource, /onChange=\{\(event\) => setCreateAthleteInviteEmail\(event\.target\.value\)\}/)
  assert.match(athletesDataTableSource, /athleteDialogMode === 'edit' \? 'Save changes' : 'Create athlete'/)
  assert.match(athletesDataTableSource, /from '@\/hooks\/use-toast'/)
  assert.match(athletesDataTableSource, /const \{ toastManager \} = useToast\(\)/)
  assert.match(athletesDataTableSource, /async function handleCreateEditAthleteSubmit\(\)/)
  assert.match(athletesDataTableSource, /toastManager\.promise\(/)
  assert.match(athletesDataTableSource, /loading:\s*\{\s*title:\s*athleteDialogMode === 'edit' \? 'Saving athlete\.\.\.' : 'Creating athlete\.\.\.'/)
  assert.match(athletesDataTableSource, /success:\s*\(savedAthlete\) => \(\{\s*title:\s*athleteDialogMode === 'edit' \? 'Athlete updated' : savedAthlete\?\.requestBody\?\.sendInvite \? 'Invitation sent' : 'Athlete created'/)
  assert.match(athletesDataTableSource, /description:\s*athleteDialogMode === 'edit'[\s\S]*'Changes saved for '\s*\+[\s\S]*savedAthlete\?\.requestBody\?\.sendInvite[\s\S]*'Created a pending athlete account for '\s*\+[\s\S]*' and sent the invite\.'[\s\S]*'Created an inactive athlete account for '\s*\+[\s\S]*'\. You can send the invite later\.'/)
  assert.match(athletesDataTableSource, /error:\s*\(submitError\) => \(\{\s*title:\s*athleteDialogMode === 'edit' \? 'Failed to save athlete' : 'Failed to create athlete'/)
  assert.match(athletesDataTableSource, /description:\s*submitError\?\.message \|\| \(athleteDialogMode === 'edit' \? 'We could not save this athlete right now\.' : 'Creating an athlete from web admin requires a real email only when you send the invite now\.'/)
  assert.match(athletesDataTableSource, /return \{[\s\S]*athleteId: editingAthleteId,[\s\S]*avatarUrl:[\s\S]*avatarUpload:[\s\S]*inviteeEmail:[\s\S]*sendInvite:/)
  assert.doesNotMatch(athletesDataTableSource, /if \(athleteDialogMode === 'create' && !normalizedInviteEmail\) \{[\s\S]*Invite email is required to create an athlete account\./)
  assert.match(athletesDataTableSource, /if \(athleteDialogMode === 'create' && sendAthleteInvite && !normalizedInviteEmail\) \{[\s\S]*Invite email is required when sending an athlete invitation\./)
  assert.doesNotMatch(athletesDataTableSource, /Avatar uploads from this dialog are not wired yet\./)
  assert.match(athletesDataTableSource, /method:\s*athleteDialogMode === 'edit' \? 'PATCH' : 'POST'/)
  assert.match(athletesDataTableSource, /onClick=\{handleCreateEditAthleteSubmit\}/)
  assert.match(adminAthleteRouteSource, /import \{ createAdminAthleteRouteHandlers \} from '@\/lib\/admin-athlete-route-handlers'/)
  assert.match(adminAthleteRouteSource, /const handlers = createAdminAthleteRouteHandlers\(\)/)
  assert.match(adminAthleteRouteSource, /export const POST = handlers\.POST/)
  assert.match(adminAthleteRouteSource, /export const PATCH = handlers\.PATCH/)
  assert.match(adminInviteRouteSource, /import \{ createAdminInviteRouteHandlers \} from '@\/lib\/admin-invite-route-handlers'/)
  assert.match(adminInviteRouteSource, /const handlers = createAdminInviteRouteHandlers\(\)/)
  assert.match(adminInviteRouteSource, /export const GET = handlers\.GET/)
  assert.match(adminInviteRouteSource, /export const POST = handlers\.POST/)
  assert.match(adminAthleteRepositorySource, /import \{[\s\S]*createAthleteInvitationService[\s\S]*hashAthleteInvitationCode[\s\S]*normalizeAthleteInvitationEmail[\s\S]*\} from '\.\.\/\.\.\/\.\.\/packages\/data\/src\/invitations\/index\.js'/)
  assert.match(adminAthleteRepositorySource, /async createAthlete\(/)
  assert.match(adminAthleteRepositorySource, /async updateAthlete\(/)
  assert.match(adminAthleteRepositorySource, /async sendAthleteInvite\(/)
  assert.match(adminAthleteRepositorySource, /const createPlaceholderEmail = overrides\.createPlaceholderEmail \?\? createPlaceholderEmailDefault/)
  assert.match(adminAthleteRepositorySource, /uploadAthleteAvatar/)
  assert.match(adminAthleteRepositorySource, /authAdminRequest\(`\/auth\/v1\/admin\/users\/\$\{encodeURIComponent\(athleteRow\.user_id\)\}`,[\s\S]*method:\s*'PUT'/)
  assert.match(adminAthleteRepositorySource, /Invite email is required when sending an athlete invitation\./)
  assert.doesNotMatch(adminAthleteRepositorySource, /Invite email is required to create an athlete account\./)
  assert.match(appLayoutSource, /from '@\/components\/ui\/base-toast'/)
  assert.match(appLayoutSource, /<ToastProvider>/)
  assert.match(appLayoutSource, /<ToastViewport \/>/)
  assert.match(toastHookSource, /function useToast\(\)/)
  assert.match(toastHookSource, /toastManager:\s*\{[\s\S]*promise:/)
  assert.match(baseToastSource, /function ToastProvider\(/)
  assert.match(baseToastSource, /function ToastViewport\(/)
  assert.match(baseToastSource, /data-state=/)
  assert.match(adminAthleteRepositorySource, /requestTable\('athlete_profiles', '\?select=id,first_name,last_name,date_of_birth,gender,position,height_cm,weight_kg,avatar_url,status,created_at&order=created_at\.asc'\)/)
  assert.match(adminAthleteRepositorySource, /gender: row\.gender \?\? null/)
  assert.match(adminAthleteRepositorySource, /position: row\.position \?\? null/)
  assert.match(adminAthleteRepositorySource, /heightCm: row\.height_cm \?\? null/)
  assert.match(adminAthleteRepositorySource, /weightKg: row\.weight_kg \?\? null/)

  assert.match(tabsSource, /export \{ Tabs, TabsList, TabsTrigger, TabsContent \}/)
  assert.match(tabsSource, /TabsPrimitive\.Root/)
  assert.match(tabsSource, /TabsPrimitive\.Trigger/)
  assert.match(tabsSource, /TabsPrimitive\.List/)
  assert.doesNotMatch(tabsSource, /bg-\[#111D30\] p-1 text-\[#8EA0BC\]/)
  assert.doesNotMatch(tabsSource, /inline-flex h-11 w-full items-center/)
  assert.match(tabsSource, /inline-flex h-11 w-full rounded-\[14px\]/)
})
