import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const repoRoot = resolve(import.meta.dirname, '..')
const dashboardOverviewPath = resolve(repoRoot, 'apps/web/components/admin/dashboard-overview.jsx')
const calendarHeatmapPath = resolve(repoRoot, 'apps/web/components/ui/calendar-heatmap.jsx')

test('dashboard overview fetches real v2 coach overview API data instead of hardcoded KPI mocks', () => {
  const source = readFileSync(dashboardOverviewPath, 'utf8')
  const calendarHeatmapSource = readFileSync(calendarHeatmapPath, 'utf8')

  assert.match(source, /const defaultDashboardRange = 'last-month'/)
  assert.match(source, /fetch\(`\/api\/admin\/dashboard\/overview\?range=\$\{defaultDashboardRange\}`/)
  assert.match(source, /fetch\(`\/api\/admin\/dashboard\/overview\?range=\$\{trainingExecutionRange\}`/)
  assert.match(source, /setOverview\(payload\.overview/)
  assert.match(source, /trainingExecution:\s*payload\.overview\?\.trainingExecution \?\? previousOverview\.trainingExecution/)
  assert.doesNotMatch(source, /fetch\(`\/api\/admin\/dashboard\/overview\?range=\$\{activeRange\}`/)
  assert.match(source, /setLoading\(true\)/)
  assert.match(source, /setError\(/)
  assert.match(source, /Dashboard overview loading/)
  assert.match(source, /Dashboard overview error/)
  assert.match(source, /No dashboard data yet/)
  assert.match(source, /const cards = buildSummaryCards\(overview\?\.summary\)/)
  assert.match(source, /athletes/)
  assert.match(source, /programs/)
  assert.match(source, /workouts/)
  assert.match(source, /exercises/)
  assert.match(source, /invites/)
  assert.doesNotMatch(source, /dueWorkouts/)
  assert.doesNotMatch(source, /planAdherence/)
  assert.doesNotMatch(source, /needsAttention/)
  assert.match(source, /trainingExecution=\{overview\?\.trainingExecution\}/)
  assert.match(source, /workoutResults=\{overview\?\.workoutResults\}/)
  assert.match(source, /trainingConsistency=\{overview\?\.trainingConsistency\}/)
  assert.match(source, /CalendarHeatmap/)
  assert.match(source, /const heatmapDates = buildTrainingConsistencyWeightedDates\(trainingConsistency\?\.dailyActivity\)/)
  assert.match(source, /weightedDates=\{heatmapDates\}/)
  assert.match(source, /variantClassnames=\{trainingConsistencyHeatmapVariants\}/)
  assert.match(source, /numberOfMonths=\{1\}/)
  assert.match(source, /Monthly activity heatmap/)
  assert.match(source, /Use the arrows to review previous months\./)
  assert.match(source, /WorkoutResultsPanel/)
  assert.match(source, /BarChart/)
  assert.match(source, /<BarChart\s+accessibilityLayer\s+data=\{chartData\}/)
  assert.doesNotMatch(source, /layout="vertical"/)
  assert.match(source, /createWorkoutResultShortLabel/)
  assert.match(source, /workoutLabel:\s*createWorkoutResultShortLabel\(bucket\.workoutName, bucket\.category\)/)
  assert.match(source, /XAxis[\s\S]*dataKey="workoutLabel"[\s\S]*tickLine=\{false\}[\s\S]*tickMargin=\{10\}[\s\S]*axisLine=\{false\}[\s\S]*angle=\{-45\}[\s\S]*textAnchor="end"[\s\S]*height=\{72\}/)
  assert.match(source, /YAxis[\s\S]*tickLine=\{false\}[\s\S]*axisLine=\{false\}[\s\S]*tickMargin=\{8\}/)
  assert.match(source, /const workoutResultsChartHeight = 320/)
  assert.match(source, /const workoutResultsChartHeight = 320/)
  assert.match(source, /const workoutResultsChartWidth = Math\.max\(720, chartData\.length \* 96\)/)
  assert.match(source, /CardContent className="admin-shell-overview-workout-results-content overflow-x-auto"/)
  assert.match(source, /style=\{\{ height: workoutResultsChartHeight, minHeight: workoutResultsChartHeight, width: workoutResultsChartWidth, minWidth: workoutResultsChartWidth \}\}/)
  assert.match(source, /interval=\{0\}/)
  assert.doesNotMatch(source, /chartData\.slice/)
  assert.match(source, /Showing all \{selectedCategory\} workout results/)
  assert.match(source, /ChartTooltipContent indicator="dashed" labelFormatter=\{\(_, payload\) => payload\?\.\[0\]\?\.payload\?\.workoutName \?\? ''\}/)
  assert.match(source, /<Bar dataKey="assigned" fill="var\(--color-assigned\)" radius=\{4\} \/>/)
  assert.match(source, /<Bar dataKey="completed" fill="var\(--color-completed\)" radius=\{4\} \/>/)
  assert.match(source, /<Bar dataKey="missed" fill="var\(--color-missed\)" radius=\{4\} \/>/)
  assert.doesNotMatch(source, /Bar dataKey="value"/)
  assert.doesNotMatch(source, /workoutResultStatusOptions/)
  assert.match(source, /workoutResultCategoryOptions/)
  assert.match(source, /Category/)
  assert.doesNotMatch(source, /aria-label="Status"/)
  assert.match(source, /Assigned/)
  assert.match(source, /Completed/)
  assert.match(source, /Missed/)
  assert.match(source, /Warmup/)
  assert.match(source, /Speed Accelerator/)
  assert.match(source, /Edge Work/)
  assert.match(source, /Conditioning/)
  assert.match(source, /disabled=\{false\}/)
  assert.match(calendarHeatmapSource, /disabled:\s*'opacity-100'/)
  assert.match(calendarHeatmapSource, /day:\s*'relative block aspect-square w-full overflow-hidden rounded-\[7px\] p-0 text-center text-sm leading-none'/)
  assert.match(calendarHeatmapSource, /day_button:[\s\S]*absolute inset-0 flex h-full w-full items-center justify-center rounded-\[7px\][\s\S]*text-sm font-medium leading-none[\s\S]*text-\[var\(--admin-dashboard-card-text\)\]/)
  assert.doesNotMatch(source, /disabled\s*$/m)
  assert.match(source, /Training execution/)
  assert.match(source, /Training consistency/)
  assert.match(calendarHeatmapSource, /navLayout="around"/)
  assert.match(calendarHeatmapSource, /caption_label:\s*'text-base font-bold leading-none/)
  assert.match(source, /className="w-full"/)
  assert.match(calendarHeatmapSource, /months:\s*'flex w-full flex-col gap-4/)
  assert.match(calendarHeatmapSource, /month:\s*'relative w-full space-y-3/)
  assert.match(calendarHeatmapSource, /month_caption:\s*'flex items-center justify-center px-7 pb-4'/)
  assert.match(calendarHeatmapSource, /month_grid:\s*'w-full border-collapse'/)
  assert.match(calendarHeatmapSource, /weekdays:\s*'grid grid-cols-7'/)
  assert.match(calendarHeatmapSource, /weekday:\s*'w-full rounded-md text-center text-sm font-bold/)
  assert.match(calendarHeatmapSource, /week:\s*'mt-1 grid w-full grid-cols-7'/)
  assert.match(calendarHeatmapSource, /day:\s*'relative block aspect-square w-full overflow-hidden rounded-\[7px\] p-0 text-center text-sm leading-none'/)
  assert.match(calendarHeatmapSource, /'absolute inset-0 flex h-full w-full items-center justify-center rounded-\[7px\][^']*text-sm font-medium leading-none/)
  assert.doesNotMatch(calendarHeatmapSource, /day:\s*'relative h-7 w-full/)
  assert.doesNotMatch(calendarHeatmapSource, /'h-7 w-full rounded-\[7px\]/)
  assert.doesNotMatch(source, /className="min-w-max"/)
  assert.doesNotMatch(calendarHeatmapSource, /weekday:\s*'w-7/)
  assert.doesNotMatch(calendarHeatmapSource, /day:\s*'relative size-7/)
  assert.doesNotMatch(calendarHeatmapSource, /'size-7 rounded-\[7px\]/)
  assert.match(calendarHeatmapSource, /button_previous:[\s\S]*absolute left-3 top-3/)
  assert.match(calendarHeatmapSource, /button_next:[\s\S]*absolute right-3 top-3/)
  assert.doesNotMatch(calendarHeatmapSource, /nav:\s*'absolute inset-x-0 top-0 flex items-center justify-between'/)
  assert.doesNotMatch(source, /const overviewRangeCardData = \{/)
  assert.doesNotMatch(source, /value: '148'/)
  assert.doesNotMatch(source, /Daily adherence meets projections/)
  assert.doesNotMatch(source, /Sessions by time of the day/)
  assert.doesNotMatch(source, /RadarChart/)
})
