import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const workoutsDataTablePath = resolve(repoRoot, 'apps/web/components/admin/workouts-data-table.jsx')
const workoutsLibraryViewPath = resolve(repoRoot, 'apps/web/components/admin/workouts-library-view.jsx')
const workoutEditorDialogPath = resolve(repoRoot, 'apps/web/components/admin/workout-editor-dialog.jsx')
const workoutDeleteDialogPath = resolve(repoRoot, 'apps/web/components/admin/workout-delete-dialog.jsx')
const workoutTrainingBuilderPath = resolve(repoRoot, 'apps/web/components/admin/workout-training-builder.jsx')
const workoutTemplatesRoutePath = resolve(repoRoot, 'apps/web/app/api/admin/workout-templates/route.js')
const workoutTemplatesRouteHandlersPath = resolve(repoRoot, 'apps/web/lib/admin-workout-template-route-handlers.js')
const programWorkoutRepositoryPath = resolve(repoRoot, 'apps/web/lib/program-workout-repository.js')
const globalsCssPath = resolve(repoRoot, 'apps/web/app/globals.css')

test('workouts library uses real template data with admin light-mode controls and honest editor flows', () => {
  const tableSource = readFileSync(workoutsDataTablePath, 'utf8')
  const viewSource = readFileSync(workoutsLibraryViewPath, 'utf8')
  const editorSource = readFileSync(workoutEditorDialogPath, 'utf8')
  const workoutDeleteDialogSource = readFileSync(workoutDeleteDialogPath, 'utf8')
  const trainingBuilderSource = readFileSync(workoutTrainingBuilderPath, 'utf8')
  const routeSource = readFileSync(workoutTemplatesRoutePath, 'utf8')
  const routeHandlersSource = readFileSync(workoutTemplatesRouteHandlersPath, 'utf8')
  const repositorySource = readFileSync(programWorkoutRepositoryPath, 'utf8')
  const cssSource = readFileSync(globalsCssPath, 'utf8')

  assert.match(viewSource, /admin-shell-workouts-library-view/)
  assert.match(viewSource, /admin-shell-athletes-page-title/)
  assert.match(tableSource, /fetch\('\/api\/admin\/workout-templates'/)
  assert.match(routeSource, /import \{ cookies \} from 'next\/headers'/)
  assert.match(routeSource, /import \{ PPLUS_ADMIN_ACCESS_TOKEN_COOKIE \} from '@\/lib\/admin-auth-cookies'/)
  assert.match(routeSource, /async function requireAdminAccessToken\(\)/)
  assert.match(routeSource, /new Error\('Unauthorized admin request\.'\)/)
  assert.match(routeSource, /createAdminWorkoutTemplateRouteHandlers\(\{ requireAdminAccessToken \}\)/)
  assert.match(routeSource, /export async function GET\(\) \{[\s\S]*return handlers\.GET\(\)/)
  assert.match(routeSource, /export async function POST\(request\) \{[\s\S]*return handlers\.POST\(request\)/)
  assert.match(routeSource, /export async function PATCH\(request\) \{[\s\S]*return handlers\.PATCH\(request\)/)
  assert.match(routeSource, /export async function DELETE\(request\) \{[\s\S]*return handlers\.DELETE\(request\)/)
  assert.match(routeHandlersSource, /await requireAdmin\(\)/)
  assert.match(routeHandlersSource, /repository\.listWorkoutTemplates\(\)/)
  assert.match(repositorySource, /table:\s*'workout_templates'/)
  assert.match(repositorySource, /status:\s*'neq\.archived'/)
  assert.match(repositorySource, /workout_template_blocks/)
  assert.match(repositorySource, /workout_template_exercises/)
  assert.match(repositorySource, /workout_template_sets/)

  assert.match(tableSource, /admin-shell-athletes-filter-trigger/)
  assert.match(tableSource, /admin-shell-athletes-pagination-bar/)
  assert.match(tableSource, /admin-shell-athletes-page-size-select/)
  assert.match(tableSource, /admin-shell-athletes-empty-state/)
  assert.match(tableSource, /admin-shell-athletes-name-cell/)
  assert.match(tableSource, /admin-shell-athletes-name-text/)
  assert.match(tableSource, /admin-shell-athletes-name-meta/)
  assert.match(tableSource, /admin-shell-athletes-example-pagination-button-active/)

  assert.match(tableSource, /aria-label="Workout bulk actions"/)
  assert.match(tableSource, /const \[isBulkWorkoutMenuOpen, setIsBulkWorkoutMenuOpen\] = useState\(false\)/)
  assert.match(tableSource, /import \{[\s\S]*Dialog,[\s\S]*DialogContent,[\s\S]*DialogDescription,[\s\S]*DialogFooter,[\s\S]*DialogHeader,[\s\S]*DialogTitle,[\s\S]*\} from '@\/components\/ui\/dialog'/)
  assert.match(tableSource, /<Dialog open=\{isAiWorkoutImportDialogOpen\} onOpenChange=\{handleAiWorkoutImportDialogOpenChange\}>/)
  assert.match(tableSource, /useEffect\(\(\) => \{[\s\S]*if \(selectedWorkoutCount === 0\) \{[\s\S]*setIsBulkWorkoutMenuOpen\(false\)[\s\S]*\}\s*\}, \[selectedWorkoutCount\]\)/)
  assert.match(tableSource, /function handleBulkWorkoutMenuOpenChange\(isOpen\) \{[\s\S]*if \(isOpen && selectedWorkoutCount === 0\) \{[\s\S]*setIsBulkWorkoutMenuOpen\(false\)[\s\S]*return[\s\S]*\}[\s\S]*setIsBulkWorkoutMenuOpen\(isOpen\)/)
  assert.match(tableSource, /open=\{isBulkWorkoutMenuOpen && selectedWorkoutCount > 0\}/)
  assert.match(tableSource, /aria-label="Workout bulk actions"[\s\S]{0,260}disabled=\{selectedWorkoutCount === 0\}[\s\S]{0,120}aria-disabled=\{selectedWorkoutCount === 0\}/)
  assert.match(tableSource, /selectedWorkoutCount > 0 \? `Bulk actions \(\$\{selectedWorkoutCount\}\)` : 'Bulk actions'/)
  assert.match(tableSource, /DropdownMenuLabel>{selectedWorkoutCount > 0 \? 'Bulk actions' : 'Select workouts first'}/)
  assert.match(tableSource, /handleDuplicateSelectedWorkout/)
  assert.match(tableSource, /handleAssignSelectedWorkoutsToProgram/)
  assert.match(tableSource, /const \[isAssignWorkoutSheetOpen, setIsAssignWorkoutSheetOpen\] = useState\(false\)/)
  assert.match(tableSource, /const \[assignWorkoutProgramId, setAssignWorkoutProgramId\] = useState\(''\)/)
  assert.match(tableSource, /fetch\('\/api\/admin\/programs'/)
  assert.match(tableSource, /function handleOpenAssignSelectedWorkoutsSheet\(\) \{[\s\S]*setIsBulkWorkoutMenuOpen\(false\)[\s\S]*setIsAssignWorkoutSheetOpen\(true\)/)
  assert.match(tableSource, /<Sheet open=\{isAssignWorkoutSheetOpen\} onOpenChange=\{handleCloseAssignWorkoutSheet\}>[\s\S]*<SheetTitle>Assign to program<\/SheetTitle>/)
  assert.match(tableSource, /Selected workouts[\s\S]*\{selectedWorkoutCount\} workout\{selectedWorkoutCount === 1 \? '' : 's'\}/)
  assert.doesNotMatch(tableSource, /These templates will be prepared for insertion into the selected program\./)
  assert.match(tableSource, /Target program[\s\S]*Select a program[\s\S]*assignWorkoutProgramId/)
  assert.doesNotMatch(tableSource, /Assignment dates and exact placement will come from the planner handoff, not this design pass\./)
  assert.match(tableSource, /<label className="mb-2 block text-sm font-semibold text-\[var\(--admin-dashboard-card-text\)\]" htmlFor="assign-workout-program-trigger">[\s\S]*Target program/)
  assert.match(tableSource, /<SelectTrigger id="assign-workout-program-trigger" className="admin-shell-workouts-assign-program-select-trigger">/)
  assert.match(tableSource, /<SelectContent className="admin-dashboard-dropdown-content admin-shell-workouts-assign-program-select-content">/)
  assert.match(tableSource, /<SelectItem key=\{programOption\.id\} value=\{programOption\.id\} className="admin-shell-workouts-assign-program-select-item">/)
  assert.match(cssSource, /\.admin-shell-workouts-assign-program-select-trigger\s*\{[^}]*min-height:\s*44px;[^}]*border:\s*1px solid var\(--admin-dashboard-card-border\);[^}]*border-radius:\s*12px;[^}]*background:\s*var\(--admin-dashboard-control-bg\);[^}]*color:\s*var\(--admin-dashboard-card-text\);/)
  assert.match(cssSource, /\.admin-shell-workouts-assign-program-select-trigger\[data-state='open'\]\s*\{[^}]*box-shadow:\s*0 0 0 2px var\(--admin-input-focus\);/)
  assert.match(cssSource, /\.admin-shell-workouts-assign-program-select-content\s*\{[^}]*border-color:\s*var\(--admin-shell-control-border\) !important;[^}]*background:\s*var\(--admin-shell-control-bg\) !important;[^}]*color:\s*var\(--admin-shell-text\) !important;/)
  assert.match(cssSource, /\.admin-shell-workouts-assign-program-select-item\[data-highlighted\],[\s\S]*\.admin-shell-workouts-assign-program-select-item:hover,[\s\S]*\.admin-shell-workouts-assign-program-select-item:focus\s*\{[^}]*background:\s*var\(--admin-shell-nav-active-bg\) !important;[^}]*color:\s*var\(--admin-shell-nav-active-text\) !important;/)
  assert.match(tableSource, /Assignment preview[\s\S]*selectedWorkoutRows\.map\(\(workout\) =>/)
  assert.match(tableSource, /disabled=\{!assignWorkoutProgramId \|\| selectedWorkoutCount === 0 \|\| isAssigningWorkoutsToProgram\}/)
  assert.doesNotMatch(tableSource, /Program assignment persistence will be wired after the planner handoff is finalized\./)
  assert.match(tableSource, /from '@\/lib\/admin-workouts-export'/)
  assert.match(tableSource, /coachId: template\.coach_id \?\? ''/)
  assert.match(tableSource, /category: template\.category \?\? ''/)
  assert.match(tableSource, /focusAreaRaw: template\.focus_area \?\? ''/)
  assert.match(tableSource, /trainingType: template\.training_type \?\? ''/)
  assert.match(tableSource, /estimatedDurationMinutes: template\.estimated_duration_minutes \?\? ''/)
  assert.match(tableSource, /createdAt: template\.created_at \?\? ''/)
  assert.match(tableSource, /updatedAt: template\.updated_at \?\? ''/)
  assert.match(repositorySource, /select: 'id,coach_id,name,description,category,focus_area,training_type,bg_color,text_color,estimated_duration_minutes,thumbnail_url,status,created_at,updated_at'/)
  assert.match(tableSource, /const \[isExportWorkoutSheetOpen, setIsExportWorkoutSheetOpen\] = useState\(false\)/)
  assert.match(tableSource, /const \[selectedExportWorkoutIds, setSelectedExportWorkoutIds\] = useState\(\[\]\)/)
  assert.match(tableSource, /const \[isExportingWorkouts, setIsExportingWorkouts\] = useState\(false\)/)
  assert.match(tableSource, /const exportWorkoutsToReview = useMemo\([\s\S]*selectedExportWorkoutIds\.includes\(workout\.id\)/)
  assert.match(tableSource, /const exportWorkoutsFileName = getWorkoutsExportFileName\(\)/)
  assert.match(tableSource, /function handleOpenExportSelectedWorkoutsSheet\(\) \{[\s\S]*setSelectedExportWorkoutIds\(selectedWorkoutRows\.map\(\(workout\) => workout\.id\)\.filter\(Boolean\)\)[\s\S]*setIsExportWorkoutSheetOpen\(true\)/)
  assert.match(tableSource, /async function handleConfirmExportWorkouts\(\) \{[\s\S]*buildWorkoutsExportCsv\(exportWorkoutsToReview\)[\s\S]*downloadWorkoutsExportFile\(\{[\s\S]*fileName: exportWorkoutsFileName,[\s\S]*setIsExportWorkoutSheetOpen\(false\)[\s\S]*setSelectedExportWorkoutIds\(\[\]\)[\s\S]*table\.resetRowSelection\(\)/)
  assert.match(tableSource, /<Sheet open=\{isExportWorkoutSheetOpen\} onOpenChange=\{setIsExportWorkoutSheetOpen\}>[\s\S]*<SheetTitle>Export workouts<\/SheetTitle>[\s\S]*Review the selected workouts before downloading a CSV export\./)
  assert.match(tableSource, /admin-shell-workouts-export-sheet border-l border-\[color:var\(--admin-dashboard-card-border\)\] bg-\[var\(--admin-dashboard-card-bg\)\] p-0 text-\[var\(--admin-dashboard-card-text\)\] !max-w-\[var\(--container-lg\)\]/)
  assert.match(tableSource, /Selected workouts[\s\S]*\{exportWorkoutsToReview\.length\}[\s\S]*Format[\s\S]*CSV[\s\S]*Filename[\s\S]*\{exportWorkoutsFileName\}/)
  assert.match(tableSource, /Included columns[\s\S]*workoutExportColumns\.map\(\(column\) =>/)
  assert.match(tableSource, /Selected workout preview[\s\S]*exportWorkoutsToReview\.map\(\(workout\) =>/)
  assert.match(tableSource, /No workouts selected\./)
  assert.match(tableSource, /\{isExportingWorkouts \? 'Preparing CSV\.\.\.' : 'Download CSV'\}/)
  assert.match(tableSource, /handleOpenExportSelectedWorkoutsSheet/)
  assert.match(tableSource, /handleOpenArchiveSelectedWorkoutsDialog/)
  assert.match(tableSource, /handleOpenDeleteSelectedWorkoutsDialog/)
  assert.match(tableSource, /import WorkoutDeleteDialog from '@\/components\/admin\/workout-delete-dialog'/)
  assert.match(tableSource, /const deleteWorkoutsToReview = useMemo\([\s\S]*workoutsData\.filter\(\(workout\) => selectedDeleteWorkoutIds\.includes\(workout\.id\)\)/)
  assert.match(tableSource, /function handleOpenDeleteSelectedWorkoutsDialog\(\) \{[\s\S]*setIsBulkWorkoutMenuOpen\(false\)[\s\S]*setSelectedDeleteWorkoutIds\(selectedWorkoutRows\.map\(\(workout\) => workout\.id\)\.filter\(Boolean\)\)[\s\S]*setIsDeleteWorkoutDialogOpen\(true\)/)
  assert.match(tableSource, /<WorkoutDeleteDialog[\s\S]*open=\{isDeleteWorkoutDialogOpen\}[\s\S]*onOpenChange=\{setIsDeleteWorkoutDialogOpen\}[\s\S]*workouts=\{deleteWorkoutsToReview\}[\s\S]*isDeleting=\{isDeletingWorkoutTemplate\}[\s\S]*message=\{deleteWorkoutMessage\}[\s\S]*onConfirm=\{handleDeleteWorkoutTemplate\}/)
  assert.match(tableSource, /async function handleDeleteWorkoutTemplate\(\) \{[\s\S]*const workoutIds = selectedDeleteWorkoutIds\.length > 0 \? selectedDeleteWorkoutIds : \[selectedDeleteWorkoutId\]\.filter\(Boolean\)[\s\S]*method: 'DELETE'[\s\S]*body: JSON\.stringify\(\{ workoutTemplateIds: workoutIds \}\)[\s\S]*const deletedCount = Array\.isArray\(payload\.deletedWorkouts\) \? payload\.deletedWorkouts\.length : workoutIds\.length[\s\S]*setBulkWorkoutMessage\(`Deleted \$\{deletedCount\} workout\$\{deletedCount === 1 \? '' : 's'\}\.\`\)[\s\S]*setIsDeleteWorkoutDialogOpen\(false\)[\s\S]*setSelectedDeleteWorkoutId\(null\)[\s\S]*setSelectedDeleteWorkoutIds\(\[\]\)/)
  assert.doesNotMatch(tableSource, /Promise\.all\(workoutIds\.map/)
  assert.match(workoutDeleteDialogSource, /export default function WorkoutDeleteDialog\(\{[\s\S]*open,[\s\S]*onOpenChange,[\s\S]*workouts = \[\],[\s\S]*isDeleting = false,[\s\S]*message = '',[\s\S]*onConfirm,[\s\S]*\}\)/)
  assert.match(workoutDeleteDialogSource, /<DialogTitle>Delete workouts<\/DialogTitle>/)
  assert.match(workoutDeleteDialogSource, /Delete selected workouts permanently\. This cannot be undone\./)
  assert.match(workoutDeleteDialogSource, /const previewWorkouts = workouts\.slice\(0, 3\)/)
  assert.match(workoutDeleteDialogSource, /\+ \{hiddenWorkoutCount\} more/)
  assert.match(workoutDeleteDialogSource, /isDeleting \? 'Deleting\.\.\.' : 'Delete workouts'/)
  assert.match(tableSource, /Duplicate[\s\S]*Assign to program[\s\S]*Export[\s\S]*<DropdownMenuSeparator \/>[\s\S]*Archive[\s\S]*Delete/)
  assert.match(tableSource, /DropdownMenu[\s\S]*aria-label="Workout bulk actions"[\s\S]*DropdownMenu[\s\S]*Columns[\s\S]*Create workout/)

  assert.match(tableSource, /openCreateWorkoutDialog/)
  assert.match(tableSource, /openEditWorkoutDialog/)
  assert.match(tableSource, /openDuplicateWorkoutDialog/)
  assert.match(tableSource, /saveDisclaimer=/)
  assert.match(editorSource, /saveDisclaimer/)
  assert.match(routeSource, /export async function POST/)
  assert.match(routeHandlersSource, /repository\.createWorkoutTemplate/)
  assert.match(routeSource, /export async function PATCH/)
  assert.match(routeHandlersSource, /body\?\.action === 'assign-workout-templates-to-program'/)
  assert.match(routeHandlersSource, /repository\.assignWorkoutTemplatesToProgram\(\{[\s\S]*programId: body\?\.programId,[\s\S]*workoutTemplateIds: body\?\.workoutTemplateIds/)
  assert.match(routeHandlersSource, /repository\.updateWorkoutTemplate/)
  assert.match(tableSource, /const \[isAssigningWorkoutsToProgram, setIsAssigningWorkoutsToProgram\] = useState\(false\)/)
  assert.match(tableSource, /async function handleConfirmAssignSelectedWorkouts\(\) \{[\s\S]*method: 'PATCH'[\s\S]*body: JSON\.stringify\(\{[\s\S]*action: 'assign-workout-templates-to-program',[\s\S]*programId: assignWorkoutProgramId,[\s\S]*workoutTemplateIds: selectedWorkoutRows\.map\(\(workout\) => workout\.id\)\.filter\(Boolean\)/)
  assert.match(tableSource, /setBulkWorkoutMessage\(`Assigned \$\{assignedCount\} workout\$\{assignedCount === 1 \? '' : 's'\} to \$\{selectedAssignProgram\?\.name \?\? 'the selected program'\}\.\`\)/)
  assert.match(tableSource, /setRowSelection\(\{\}\)/)
  assert.match(tableSource, /disabled=\{!assignWorkoutProgramId \|\| selectedWorkoutCount === 0 \|\| isAssigningWorkoutsToProgram\}/)
  assert.match(tableSource, /\{isAssigningWorkoutsToProgram \? 'Assigning\.\.\.' : 'Confirm assignment'\}/)
  assert.match(tableSource, /disabled=\{isAssigningWorkoutsToProgram\}/)
  assert.match(tableSource, /setAssignWorkoutMessage/)
  assert.match(tableSource, /\{assignWorkoutMessage \? \(/)
  assert.match(repositorySource, /assignWorkoutTemplatesToProgram/)
  assert.match(repositorySource, /createProgramWorkoutFromTemplate\(\{[\s\S]*requireSchedule: false/)
  assert.match(repositorySource, /At least one workout template id is required\./)
  assert.match(tableSource, /setBulkWorkoutMessage\(''\)/)
  assert.match(routeHandlersSource, /body\?\.action === 'archive-workout-templates'/)
  assert.match(routeHandlersSource, /repository\.archiveWorkoutTemplates\(\{[\s\S]*workoutTemplateIds: body\?\.workoutTemplateIds/)
  assert.match(repositorySource, /async function archiveWorkoutTemplates\(\{ workoutTemplateIds = \[\] \} = \{\}\)/)
  assert.match(repositorySource, /const archiveEligibleTemplates = existingTemplates\.filter\(\(template\) => template\.status !== 'archived'\)/)
  assert.match(repositorySource, /skippedWorkouts: existingTemplates\.filter\(\(template\) => template\.status === 'archived'\)/)
  assert.match(tableSource, /async function handleArchiveWorkoutTemplates\(\) \{[\s\S]*method: 'PATCH'[\s\S]*action: 'archive-workout-templates',[\s\S]*workoutTemplateIds: selectedArchiveWorkoutIds/)
  assert.match(tableSource, /const archivedCount = Array\.isArray\(payload\.archivedWorkouts\) \? payload\.archivedWorkouts\.length : selectedArchiveWorkoutIds\.length/)
  assert.match(tableSource, /const skippedCount = Array\.isArray\(payload\.skippedWorkouts\) \? payload\.skippedWorkouts\.length : 0/)
  assert.match(tableSource, /setBulkWorkoutMessage\(`Archived \$\{archivedCount\} workout\$\{archivedCount === 1 \? '' : 's'\}\$\{skippedCount > 0 \? `; skipped \$\{skippedCount\} already archived` : ''\}\.\`\)/)
  assert.match(routeSource, /export async function DELETE/)
  assert.match(routeHandlersSource, /repository\.deleteWorkoutTemplates\(\{[\s\S]*workoutTemplateIds: body\?\.workoutTemplateIds \?\? \[body\?\.id\]\.filter\(Boolean\)/)
  assert.match(repositorySource, /async function deleteWorkoutTemplates\(\{ workoutTemplateIds = \[\] \} = \{\}\)/)
  assert.match(repositorySource, /method: 'DELETE',[\s\S]*table: 'workout_templates',[\s\S]*id: `in\.\$\{workoutTemplateFilter\}`,[\s\S]*prefer: 'return=representation'/)
  assert.match(repositorySource, /return \{[\s\S]*deletedWorkouts: Array\.isArray\(deletedRows\) \? deletedRows : \[\],[\s\S]*skippedWorkouts: \[\],[\s\S]*\}/)
  assert.doesNotMatch(routeHandlersSource, /repository\.archiveWorkoutTemplate\(body\?\.id\)/)
  assert.match(editorSource, /admin-shell-athletes-create-tabs/)
  assert.match(editorSource, /admin-shell-workout-editor-message/)
  assert.doesNotMatch(editorSource, /border-amber-300|bg-amber-50|text-amber-800/)
  assert.doesNotMatch(tableSource, /workout-\$\{Date\.now\(\)\}/)
  assert.doesNotMatch(tableSource, /Program 1|Program 2|Program 3|Thibault|Mason/)
  assert.doesNotMatch(editorSource, /Program 1|Program 2|Program 3|Thibault|Mason/)

  assert.doesNotMatch(tableSource, /className="rounded-\[12px\] min-h-\[40px\] !border !border-\[#24334A\] bg-transparent text-\[#DCE6F8\]/)
  assert.doesNotMatch(tableSource, /className="h-9 w-\[76px\] rounded-\[10px\] !border-\[#24334A\] bg-\[#111D30\]/)
  assert.doesNotMatch(tableSource, /className="h-24 text-center text-\[#8EA0BC\]"/)
  assert.doesNotMatch(tableSource, /text-\[#EEF4FF\]|text-\[#8EA0BC\]|text-\[#6F84A6\]|bg-\[#0F1728\]|bg-\[#111D30\]|border-\[#24334A\]/)
  assert.doesNotMatch(editorSource, /text-\[#DCE6F8\]|text-\[#EEF4FF\]|placeholder:text-\[#70809E\]|bg-\[#0F1728\]|bg-\[#111D30\]|border-\[#24334A\]/)
  assert.doesNotMatch(trainingBuilderSource, /text-\[#DCE6F8\]|text-\[#EEF4FF\]|text-\[#8EA0BC\]|text-\[#6F84A6\]|text-\[#60708F\]|placeholder:text-\[#70809E\]|bg-\[#0F1728\]|bg-\[#111827\]|bg-\[#111D30\]|bg-\[#15233A\]|border-\[#24334A\]|border-\[#1C2940\]|shadow-\[0_18px_40px_rgba\(0,0,0,0\.26\)\]/)
})
