export const statusStyles = {
  not_started: { backgroundColor: '#1d4ed8' },
  active: { backgroundColor: '#7c3aed' },
  completed: { backgroundColor: '#059669' },
  skipped: { backgroundColor: '#b45309' },
}

export const styles = {
  container: {
    flex: 1,
    backgroundColor: '#0b1220',
  },
  appShell: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    gap: 16,
    paddingBottom: 110,
  },
  previewBar: {
    backgroundColor: '#111827',
    borderRadius: 20,
    padding: 16,
    gap: 12,
  },
  previewBarLabel: {
    color: '#93c5fd',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  previewButtonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  previewButton: {
    backgroundColor: '#1f2937',
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  previewButtonActive: {
    backgroundColor: '#2563eb',
  },
  previewButtonText: {
    color: '#cbd5e1',
    fontWeight: '700',
  },
  previewButtonTextActive: {
    color: '#ffffff',
  },
  trainTabsRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  trainTabButton: {
    backgroundColor: '#111827',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
  },
  trainTabButtonActive: {
    backgroundColor: '#2563eb',
  },
  trainTabLabel: {
    color: '#94a3b8',
    fontWeight: '700',
  },
  trainTabLabelActive: {
    color: '#ffffff',
  },
  headerCard: {
    backgroundColor: '#111827',
    borderRadius: 20,
    padding: 20,
    gap: 8,
  },
  eyebrow: {
    color: '#93c5fd',
    fontSize: 14,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  title: {
    color: '#ffffff',
    fontSize: 32,
    fontWeight: '700',
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerActionsRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  finishButton: {
    backgroundColor: '#2563eb',
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  finishButtonDone: {
    backgroundColor: '#059669',
  },
  discardButton: {
    backgroundColor: '#7f1d1d',
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  discardButtonText: {
    color: '#fecaca',
    fontWeight: '700',
  },
  finishButtonText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  summary: {
    color: '#d1d5db',
    fontSize: 18,
    fontWeight: '600',
  },
  timer: {
    color: '#34d399',
    fontSize: 28,
    fontWeight: '700',
  },
  progressTrack: {
    height: 10,
    backgroundColor: '#1f2937',
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 4,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#3b82f6',
  },
  progressLabel: {
    color: '#9ca3af',
    fontSize: 13,
  },
  restCard: {
    backgroundColor: '#172554',
    borderRadius: 20,
    padding: 20,
    gap: 14,
  },
  restHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  restEyebrow: {
    color: '#93c5fd',
    textTransform: 'uppercase',
    fontSize: 12,
    letterSpacing: 1,
  },
  restTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  dismissText: {
    color: '#bfdbfe',
    fontWeight: '700',
  },
  restClock: {
    color: '#ffffff',
    fontSize: 42,
    fontWeight: '700',
  },
  restActions: {
    flexDirection: 'row',
    gap: 12,
  },
  restActionButton: {
    backgroundColor: '#2563eb',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  restActionText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  sectionCard: {
    backgroundColor: '#111827',
    borderRadius: 20,
    padding: 20,
    gap: 8,
  },
  todayCard: {
    backgroundColor: '#111827',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#243041',
    padding: 20,
    gap: 14,
  },
  todayCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  todayCardTitleBlock: {
    flex: 1,
    gap: 6,
  },
  todayCardLabel: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  todayCardWorkoutName: {
    color: '#ffffff',
    fontSize: 30,
    fontWeight: '800',
  },
  todayCardActionBadge: {
    backgroundColor: '#2563eb',
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 14,
    alignSelf: 'flex-start',
  },
  todayCardActionBadgeText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  todayCardScheduledLabel: {
    color: '#94a3b8',
    fontSize: 14,
    fontWeight: '600',
  },
  todayCardSummary: {
    color: '#e2e8f0',
    fontSize: 15,
    lineHeight: 22,
  },
  todayCardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingTop: 2,
  },
  todayCardFooterMeta: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '600',
  },
  todayCardFooterStatus: {
    color: '#60a5fa',
    fontSize: 13,
    fontWeight: '700',
  },
  programCard: {
    backgroundColor: '#111827',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#243041',
    padding: 18,
    flexDirection: 'row',
    gap: 14,
    alignItems: 'stretch',
  },
  programAccentRail: {
    width: 5,
    borderRadius: 999,
    backgroundColor: '#2563eb',
  },
  programCardContent: {
    flex: 1,
    gap: 12,
  },
  programCardLabel: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  programCardTitle: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '700',
  },
  programCardDateRange: {
    color: '#94a3b8',
    fontSize: 14,
  },
  programProgressRow: {
    flexDirection: 'row',
    gap: 6,
  },
  programProgressSegment: {
    flex: 1,
    height: 12,
    borderRadius: 999,
    backgroundColor: '#243041',
  },
  programProgressSegmentComplete: {
    backgroundColor: '#2563eb',
  },
  programProgressSegmentCurrent: {
    backgroundColor: '#60a5fa',
  },
  programMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  programMetaText: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '600',
  },
  sectionTitle: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '700',
  },
  sectionBody: {
    color: '#cbd5e1',
    fontSize: 15,
    lineHeight: 22,
  },
  primaryAction: {
    alignSelf: 'flex-start',
    backgroundColor: '#2563eb',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginTop: 4,
  },
  primaryActionText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  exerciseCard: {
    backgroundColor: '#1f2937',
    borderRadius: 18,
    padding: 14,
    gap: 12,
  },
  exerciseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  exerciseTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '700',
  },
  exerciseMeta: {
    color: '#9ca3af',
    fontSize: 14,
  },
  exerciseStatusBadge: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  exerciseStatusText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  setRow: {
    backgroundColor: '#111827',
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    gap: 12,
  },
  setRowCompleted: {
    backgroundColor: '#064e3b',
  },
  setRowCurrent: {
    borderWidth: 1,
    borderColor: '#f59e0b',
    backgroundColor: '#3b2a12',
  },
  setCopy: {
    flex: 1,
  },
  setControlsColumn: {
    minWidth: 120,
    gap: 8,
    alignItems: 'stretch',
  },
  setTitle: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
  },
  setMeta: {
    color: '#d1d5db',
    fontSize: 13,
    marginTop: 2,
  },
  actualControl: {
    gap: 4,
  },
  actualControlLabel: {
    color: '#bfdbfe',
    fontSize: 12,
    fontWeight: '700',
  },
  actualControlButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  stepButton: {
    backgroundColor: '#2563eb',
    borderRadius: 10,
    width: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepButtonText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  actualValue: {
    color: '#ffffff',
    fontWeight: '700',
    minWidth: 28,
    textAlign: 'center',
  },
  badge: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  badgeDone: {
    backgroundColor: '#10b981',
  },
  badgeReady: {
    backgroundColor: '#f59e0b',
  },
  badgeTodo: {
    backgroundColor: '#2563eb',
  },
  badgeText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  listRow: {
    backgroundColor: '#1f2937',
    borderRadius: 14,
    padding: 14,
    marginTop: 10,
  },
  listRowSelected: {
    borderWidth: 1,
    borderColor: '#60a5fa',
    backgroundColor: '#172554',
  },
  listRowTitle: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 16,
  },
  listRowBody: {
    color: '#cbd5e1',
    marginTop: 4,
  },
  metricsGrid: {
    gap: 12,
  },
  metricCard: {
    backgroundColor: '#111827',
    borderRadius: 18,
    padding: 18,
    gap: 6,
  },
  metricLabel: {
    color: '#93c5fd',
    fontWeight: '700',
  },
  metricValue: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '700',
  },
  metricDetail: {
    color: '#cbd5e1',
    lineHeight: 20,
  },
  tabBar: {
    position: 'absolute',
    left: -9999,
    width: 0,
    height: 0,
  },
  tabButton: {
    display: 'none',
  },
  tabButtonActive: {
    display: 'none',
  },
  tabLabel: {
    display: 'none',
  },
  tabLabelActive: {
    display: 'none',
  },
  bottomNavWrap: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  bottomNavMainPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#101827',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#243041',
    padding: 8,
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
  },
  bottomNavTab: {
    width: 74,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavTabActive: {
    backgroundColor: '#2563eb',
  },
  bottomNavUtilityButton: {
    width: 56,
    height: 56,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#101827',
    borderWidth: 1,
    borderColor: '#243041',
    shadowColor: '#000000',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
  },
  bottomNavUtilityButtonActive: {
    backgroundColor: '#2563eb',
  },
  bottomNavIcon: {
    fontSize: 18,
  },
  bottomNavIconActive: {
    opacity: 1,
  },
  bottomNavIconCanvas: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavIconStroke: {
    position: 'absolute',
    borderColor: '#f8fafc',
    backgroundColor: 'transparent',
  },
  bottomNavIconStrokeActive: {
    borderColor: '#ffffff',
  },
  bottomNavIconBarbell: {
    width: 16,
    borderTopWidth: 2,
  },
  bottomNavIconWeightLeft: {
    left: 2,
    width: 3,
    height: 10,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconWeightRight: {
    right: 2,
    width: 3,
    height: 10,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconChartBarShort: {
    left: 3,
    bottom: 3,
    width: 3,
    height: 7,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconChartBarMid: {
    left: 9,
    bottom: 3,
    width: 3,
    height: 11,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconChartBarTall: {
    left: 15,
    bottom: 3,
    width: 3,
    height: 15,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconHeadLeft: {
    left: 5,
    top: 3,
    width: 5,
    height: 5,
    borderWidth: 2,
    borderRadius: 999,
  },
  bottomNavIconHeadRight: {
    right: 5,
    top: 3,
    width: 5,
    height: 5,
    borderWidth: 2,
    borderRadius: 999,
  },
  bottomNavIconShoulders: {
    bottom: 3,
    width: 14,
    height: 7,
    borderWidth: 2,
    borderRadius: 999,
  },
  bottomNavIconChatBubble: {
    width: 14,
    height: 11,
    borderWidth: 2,
    borderRadius: 4,
    top: 4,
  },
  bottomNavIconChatTail: {
    width: 5,
    height: 5,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    transform: [{ rotate: '-35deg' }],
    bottom: 3,
    right: 5,
  },
}
