import { StyleSheet } from 'react-native'

const STATUS_COLOR_TOKENS = {
  notStarted: '#06D6A0',
  active: '#7c3aed',
  completed: '#059669',
  skipped: '#b45309',
}

export const statusStyles = {
  not_started: { backgroundColor: STATUS_COLOR_TOKENS.notStarted },
  active: { backgroundColor: STATUS_COLOR_TOKENS.active },
  completed: { backgroundColor: STATUS_COLOR_TOKENS.completed },
  skipped: { backgroundColor: STATUS_COLOR_TOKENS.skipped },
}

export function createAppStyles(theme) {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    appShell: {
      flex: 1,
    },
    shellScrollView: {
      flex: 1,
    },
    scrollContent: {
      padding: 24,
      gap: 24,
      paddingBottom: 24,
    },
    brandHeader: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 8,
      paddingBottom: 6,
    },
  brandHeaderSide: {
    width: 52,
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  brandHeaderSideRight: {
    alignItems: 'flex-end',
  },
  brandHeaderCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandLogoWrap: {
    width: 110,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandWordmark: {
    color: theme.logoText,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: 2,
  },
  brandIconButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  activeAthleteBanner: {
    marginHorizontal: -24,
    marginTop: -8,
    marginBottom: 4,
    backgroundColor: theme.accentSurface,
    borderRadius: 0,
    borderWidth: 0,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  activeAthleteBannerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  activeAthleteAvatar: {
    width: 34,
    height: 34,
    borderRadius: 999,
  },
  activeAthleteIdentity: {
    flexShrink: 1,
    minWidth: 0,
  },
  activeAthleteLabelWrap: {
    marginLeft: 'auto',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  activeAthleteEyebrow: {
    color: theme.accentText,
    fontSize: 14,
    fontWeight: '500',
  },
  activeAthleteName: {
    color: theme.accentText,
    fontSize: 16,
    fontWeight: '500',
  },
  brandIconCanvas: {
    width: 28,
    height: 28,
    justifyContent: 'center',
    alignItems: 'center',
  },
  brandProfileHead: {
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: 2,
    borderColor: theme.icon,
    marginBottom: 2,
  },
  brandProfileShoulders: {
    width: 20,
    height: 10,
    borderWidth: 2,
    borderColor: theme.icon,
    borderTopLeftRadius: 999,
    borderTopRightRadius: 999,
    borderBottomWidth: 0,
  },
  brandUtilityCard: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: theme.icon,
    paddingHorizontal: 4,
    paddingTop: 4,
    gap: 3,
  },
  brandUtilityCardTop: {
    height: 3,
    borderRadius: 999,
    backgroundColor: theme.icon,
    opacity: 0.95,
  },
  brandUtilityCardDotsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  brandUtilityCardDot: {
    width: 3,
    height: 3,
    borderRadius: 999,
    backgroundColor: theme.icon,
  },
  topHeader: {
    gap: 12,
  },
  previewBar: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 16,
    gap: 12,
  },
  previewHeaderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  previewBarLabel: {
    color: theme.accentText,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  previewHeaderActiveLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  previewButtonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  previewButton: {
    backgroundColor: theme.surfaceMuted,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  previewButtonActive: {
    backgroundColor: theme.accent,
  },
  previewButtonText: {
    color: theme.textMuted,
    fontWeight: '700',
  },
  previewButtonTextActive: {
    color: theme.text,
  },
  trainTabsRow: {
    flexDirection: 'row',
  },
  trainTabsPill: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    backgroundColor: theme.surface,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 6,
    alignSelf: 'flex-start',
  },
  trainTabButton: {
    backgroundColor: 'transparent',
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
  },
  trainTabButtonActive: {
    backgroundColor: theme.accent,
  },
  trainTabLabel: {
    color: theme.textSoft,
    fontWeight: '700',
  },
  trainTabLabelActive: {
    color: theme.text,
  },
  headerCard: {
    backgroundColor: theme.surface,
    borderRadius: 20,
    padding: 20,
    gap: 8,
  },
  eyebrow: {
    color: theme.accentText,
    fontSize: 14,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  title: {
    color: theme.text,
    fontSize: 32,
    fontWeight: '700',
  },
  headerTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerActionsRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  finishButton: {
    backgroundColor: theme.accent,
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  finishButtonDone: {
    backgroundColor: theme.accent,
  },
  discardButton: {
    backgroundColor: theme.dangerSurface,
    borderRadius: 999,
    paddingVertical: 10,
    paddingHorizontal: 16,
  },
  discardButtonText: {
    color: theme.dangerText,
    fontWeight: '700',
  },
  finishButtonText: {
    color: theme.text,
    fontWeight: '700',
  },
  summary: {
    color: theme.textMuted,
    fontSize: 18,
    fontWeight: '600',
  },
  timer: {
    color: theme.accentText,
    fontSize: 28,
    fontWeight: '700',
  },
  progressTrack: {
    height: 10,
    backgroundColor: theme.surfaceMuted,
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 4,
  },
  progressFill: {
    height: '100%',
    backgroundColor: theme.accent,
  },
  progressLabel: {
    color: theme.textSoft,
    fontSize: 13,
  },
  restCard: {
    backgroundColor: theme.accentSurface,
    borderRadius: 20,
    padding: 20,
    gap: 14,
  },
  restHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  restEyebrow: {
    color: theme.accentText,
    textTransform: 'uppercase',
    fontSize: 12,
    letterSpacing: 1,
  },
  restTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: '700',
  },
  dismissText: {
    color: theme.accentText,
    fontWeight: '700',
  },
  restClock: {
    color: theme.text,
    fontSize: 42,
    fontWeight: '700',
  },
  restActions: {
    flexDirection: 'row',
    gap: 12,
  },
  restActionButton: {
    backgroundColor: theme.accent,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 18,
  },
  restActionText: {
    color: theme.text,
    fontWeight: '700',
  },
  sectionCard: {
    backgroundColor: theme.surface,
    borderRadius: 20,
    padding: 20,
    gap: 8,
  },
  sectionHeadingWrap: {
    paddingTop: 4,
    paddingBottom: 0,
  },
  sectionHeading: {
    color: theme.text,
    fontSize: 22,
    fontWeight: '700',
  },
  sectionListOnly: {
    gap: 14,
  },
  calendarStripCard: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.border,
    paddingTop: 20,
    paddingBottom: 18,
    paddingHorizontal: 20,
  },
  calendarStripRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 2,
  },
  calendarDayColumn: {
    flex: 1,
    alignItems: 'center',
  },
  calendarDayWeekLabel: {
    color: theme.textSoft,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
  },
  calendarDayWeekLabelSelected: {
    color: theme.textMuted,
  },
  calendarDayButton: {
    minWidth: 40,
    minHeight: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 4,
    paddingBottom: 4,
    paddingHorizontal: 8,
  },
  calendarDaySelected: {
    borderWidth: 2,
    borderColor: theme.accent,
    backgroundColor: theme.backgroundMuted,
  },
  calendarDayNumber: {
    color: theme.text,
    fontSize: 16,
    fontWeight: '500',
  },
  calendarDayNumberSelected: {
    color: theme.accent,
    fontWeight: '700',
  },
  calendarIndicator: {
    width: 12,
    height: 4,
    borderRadius: 999,
  },
  calendarIndicatorActive: {
    backgroundColor: theme.accent,
  },
  calendarIndicatorMuted: {
    backgroundColor: theme.textSoft,
  },
  calendarIndicatorSpacer: {
    width: 12,
    height: 4,
  },
  todayCard: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 20,
    flexDirection: 'row',
    gap: 16,
    alignItems: 'stretch',
  },
  todayCardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  todayCardContent: {
    flex: 1,
    gap: 4,
    justifyContent: 'center',
  },
  todayCardTitleBlock: {
    flex: 1,
    gap: 2,
  },
  todayCardLabel: {
    color: theme.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  todayCardWorkoutName: {
    color: theme.text,
    fontSize: 16,
    fontWeight: '700',
  },
  todayCardCheckWrap: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: theme.textSoft,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.surface,
  },
  todayCardCheckWrapDone: {
    borderColor: theme.accent,
    backgroundColor: theme.accentSurface,
  },
  todayCardCheckIcon: {
    color: theme.textSoft,
    fontSize: 16,
    fontWeight: '700',
  },
  todayCardCheckIconDone: {
    color: theme.text,
  },
  todayCardScheduledLabel: {
    color: theme.textSoft,
    fontSize: 12,
    fontWeight: '600',
  },
  todayCardSummary: {
    color: theme.textMuted,
    fontSize: 12,
    lineHeight: 16,
  },
  todayCardFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    paddingTop: 0,
  },
  todayCardFooterMeta: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '600',
  },
  todayCardFooterStatus: {
    color: theme.accentText,
    fontSize: 12,
    fontWeight: '700',
  },
  programCard: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 20,
    flexDirection: 'row',
    gap: 16,
    alignItems: 'stretch',
  },
  programAccentRail: {
    width: 5,
    borderRadius: 999,
    backgroundColor: theme.accent,
  },
  programCardContent: {
    flex: 1,
    gap: 12,
  },
  programCardLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  programCardTitle: {
    color: theme.text,
    fontSize: 20,
    fontWeight: '700',
  },
  programCardDateRange: {
    color: theme.textSoft,
    fontSize: 15,
  },
  programProgressRow: {
    flexDirection: 'row',
    gap: 8,
  },
  programProgressSegment: {
    flex: 1,
    height: 12,
    borderRadius: 999,
    backgroundColor: theme.border,
  },
  programProgressSegmentComplete: {
    backgroundColor: theme.accent,
  },
  programProgressSegmentCurrent: {
    backgroundColor: theme.accentSoft,
  },
  programMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  programMetaText: {
    color: theme.textMuted,
    fontSize: 14,
    fontWeight: '600',
  },
  workoutListCard: {
    backgroundColor: theme.surface,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 16,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'stretch',
  },
  workoutListAccentRail: {
    width: 4,
    borderRadius: 999,
    backgroundColor: theme.accent,
  },
  workoutListCardContent: {
    flex: 1,
    gap: 4,
  },
  sectionTitle: {
    color: theme.text,
    fontSize: 20,
    fontWeight: '700',
  },
  sectionBody: {
    color: theme.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  primaryAction: {
    alignSelf: 'flex-start',
    backgroundColor: theme.accent,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginTop: 4,
  },
  primaryActionText: {
    color: theme.text,
    fontWeight: '700',
  },
  exerciseCard: {
    backgroundColor: theme.surfaceMuted,
    borderRadius: 18,
    padding: 14,
    gap: 12,
  },
  exerciseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  exerciseTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: '700',
  },
  exerciseMeta: {
    color: theme.textSoft,
    fontSize: 14,
  },
  exerciseStatusBadge: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  exerciseStatusText: {
    color: theme.text,
    fontSize: 12,
    fontWeight: '700',
  },
  setRow: {
    backgroundColor: theme.surface,
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'stretch',
    gap: 12,
  },
  setRowCompleted: {
    backgroundColor: theme.accentSurface,
  },
  setRowCurrent: {
    borderWidth: 1,
    borderColor: theme.dangerBorder,
    backgroundColor: theme.dangerSurface,
  },
  setCopy: {
    flex: 1,
  },
  setControlsColumn: {
    minWidth: 120,
    gap: 8,
    alignItems: 'stretch',
  },
  setTitle: {
    color: theme.text,
    fontSize: 16,
    fontWeight: '600',
  },
  setMeta: {
    color: theme.textMuted,
    fontSize: 13,
    marginTop: 2,
  },
  actualControl: {
    gap: 4,
  },
  actualControlLabel: {
    color: theme.accentText,
    fontSize: 12,
    fontWeight: '700',
  },
  actualControlButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  stepButton: {
    backgroundColor: theme.accent,
    borderRadius: 10,
    width: 26,
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepButtonText: {
    color: theme.text,
    fontWeight: '700',
  },
  actualValue: {
    color: theme.text,
    fontWeight: '700',
    minWidth: 28,
    textAlign: 'center',
  },
  badge: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  badgeDone: {
    backgroundColor: theme.accent,
  },
  badgeReady: {
    backgroundColor: theme.dangerBorder,
  },
  badgeTodo: {
    backgroundColor: theme.accent,
  },
  badgeText: {
    color: theme.text,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  listRow: {
    backgroundColor: theme.surfaceMuted,
    borderRadius: 14,
    padding: 14,
    marginTop: 10,
  },
  listRowSelected: {
    borderWidth: 1,
    borderColor: theme.accentText,
    backgroundColor: theme.accentSurface,
  },
  listRowTitle: {
    color: theme.text,
    fontWeight: '700',
    fontSize: 16,
  },
  listRowBody: {
    color: theme.textMuted,
    marginTop: 4,
  },
  metricsGrid: {
    gap: 12,
  },
  metricCard: {
    backgroundColor: theme.surface,
    borderRadius: 18,
    padding: 18,
    gap: 6,
  },
  metricLabel: {
    color: theme.accentText,
    fontWeight: '700',
  },
  metricValue: {
    color: theme.text,
    fontSize: 28,
    fontWeight: '700',
  },
  metricDetail: {
    color: theme.textMuted,
    lineHeight: 20,
  },
  tabBar: {
    position: 'absolute',
    left: -9999,
    width: 0,
    height: 0,
  },
  tabButton: {
    display: 'none',
  },
  tabButtonActive: {
    display: 'none',
  },
  tabLabel: {
    display: 'none',
  },
  tabLabelActive: {
    display: 'none',
  },
  bottomNavWrap: {
    backgroundColor: theme.background,
    paddingTop: 8,
    paddingHorizontal: 24,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 12,
  },
  bottomNavMainPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: theme.surface,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.border,
    padding: 10,
    shadowColor: theme.cardShadow,
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  bottomNavTab: {
    flex: 1,
    minHeight: 52,
    paddingVertical: 14,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavTabActive: {
    backgroundColor: theme.accent,
  },
  bottomNavIcon: {
    fontSize: 18,
  },
  bottomNavIconActive: {
    opacity: 1,
  },
  bottomNavIconCanvas: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomNavIconStroke: {
    position: 'absolute',
    borderColor: theme.icon,
    backgroundColor: 'transparent',
  },
  bottomNavIconStrokeActive: {
    borderColor: theme.icon,
  },
  bottomNavIconBarbell: {
    width: 16,
    borderTopWidth: 2,
  },
  bottomNavIconWeightLeft: {
    left: 2,
    width: 3,
    height: 10,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconWeightRight: {
    right: 2,
    width: 3,
    height: 10,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconChartBarShort: {
    left: 3,
    bottom: 3,
    width: 3,
    height: 7,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconChartBarMid: {
    left: 9,
    bottom: 3,
    width: 3,
    height: 11,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconChartBarTall: {
    left: 15,
    bottom: 3,
    width: 3,
    height: 15,
    borderWidth: 2,
    borderRadius: 2,
  },
  bottomNavIconHeadLeft: {
    left: 5,
    top: 3,
    width: 5,
    height: 5,
    borderWidth: 2,
    borderRadius: 999,
  },
  bottomNavIconHeadRight: {
    right: 5,
    top: 3,
    width: 5,
    height: 5,
    borderWidth: 2,
    borderRadius: 999,
  },
  bottomNavIconShoulders: {
    bottom: 3,
    width: 14,
    height: 7,
    borderWidth: 2,
    borderRadius: 999,
  },
  bottomNavIconChatBubble: {
    width: 14,
    height: 11,
    borderWidth: 2,
    borderRadius: 4,
    top: 4,
  },
  bottomNavIconChatTail: {
    width: 5,
    height: 5,
    borderLeftWidth: 2,
    borderBottomWidth: 2,
    transform: [{ rotate: '-35deg' }],
    bottom: 3,
    right: 5,
  },
  programSheetBackdrop: {
    flex: 1,
    backgroundColor: theme.overlay,
    justifyContent: 'flex-end',
  },
  programSheetBackdropPressable: {
    flex: 1,
  },
  programSheetPanel: {
    backgroundColor: theme.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingTop: 18,
    paddingBottom: 28,
    maxHeight: '88%',
  },
  programSheetScrollContent: {
    paddingBottom: 32,
    gap: 24,
  },
  programSheetHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  programSheetBackButton: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: theme.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  programSheetBackButtonText: {
    color: theme.text,
    fontSize: 28,
    lineHeight: 30,
    fontWeight: '500',
  },
  programSheetEditText: {
    color: theme.accentText,
    fontSize: 17,
    fontWeight: '600',
  },
  programSheetIntro: {
    gap: 8,
  },
  programSheetTitle: {
    color: theme.text,
    fontSize: 28,
    fontWeight: '700',
  },
  programSheetDateRange: {
    color: theme.textSoft,
    fontSize: 14,
  },
  programSheetProgressTrack: {
    gap: 16,
  },
  programSheetProgressRow: {
    flexDirection: 'row',
    gap: 6,
  },
  programSheetProgressSegment: {
    flex: 1,
    height: 12,
    borderRadius: 999,
    backgroundColor: theme.borderStrong,
  },
  programSheetProgressSegmentComplete: {
    backgroundColor: theme.accentBorder,
  },
  programSheetProgressSegmentCurrent: {
    backgroundColor: theme.accent,
  },
  programSheetStatsList: {
    gap: 10,
  },
  programSheetStatRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  programSheetStatText: {
    color: theme.textMuted,
    fontSize: 14,
    fontWeight: '600',
  },
  programSheetSection: {
    gap: 14,
  },
  programSheetSectionTitle: {
    color: theme.textMuted,
    fontSize: 18,
    fontWeight: '600',
  },
  programSheetRoutineGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  programSheetRoutineChip: {
    width: '48%',
    minHeight: 52,
    borderRadius: 18,
    backgroundColor: theme.surfaceMuted,
    borderWidth: 1,
    borderColor: theme.borderStrong,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  programSheetRoutineChipText: {
    color: theme.text,
    fontSize: 15,
    fontWeight: '600',
  },
  programSheetWeeksList: {
    gap: 16,
  },
  programSheetWeekCard: {
    backgroundColor: theme.surfaceMuted,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: theme.borderStrong,
    padding: 18,
    gap: 14,
  },
  programSheetWeekDateRange: {
    color: theme.textSoft,
    fontSize: 13,
    fontWeight: '600',
  },
  programSheetWeekTitle: {
    color: theme.text,
    fontSize: 24,
    fontWeight: '700',
  },
  programSheetDividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  programSheetDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: theme.borderStrong,
  },
  programSheetDividerText: {
    color: theme.textSoft,
    fontSize: 12,
    fontWeight: '600',
  },
  programSheetWorkoutList: {
    gap: 14,
  },
  programSheetWorkoutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  programSheetWorkoutDay: {
    width: 34,
    color: theme.text,
    fontSize: 15,
    fontWeight: '700',
  },
  programSheetWorkoutLabel: {
    flex: 1,
    color: theme.text,
    fontSize: 15,
    fontWeight: '600',
  },
  programSheetWorkoutDuration: {
    color: theme.textSoft,
    fontSize: 13,
    fontWeight: '600',
  },
  programSheetStatusBadge: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  programSheetStatusBadgeDone: {
    borderColor: theme.accentBorder,
    backgroundColor: theme.accentSurface,
  },
  programSheetStatusBadgeMissed: {
    borderColor: theme.dangerBorder,
    backgroundColor: theme.dangerSurface,
  },
  programSheetStatusBadgeMissedText: {
    color: theme.dangerText,
    fontSize: 15,
    fontWeight: '700',
    lineHeight: 16,
  },
  })

  return { ...styles, theme }
}
