name: Semgrep

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
      - semgrep.yml
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v6
      - name: Run Semgrep with repo rules
        run: semgrep scan --config semgrep.yml --error --exclude .github
